import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {resolve,dirname,extname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import {PGlite} from '@electric-sql/pglite';
const require=createRequire(import.meta.url);
function loader(overrides={}){const cache=new Map();function load(p){p=resolve(p);if(Object.hasOwn(overrides,p))return overrides[p];if(cache.has(p))return cache.get(p).exports;const target={exports:{}};cache.set(p,target);const js=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('require','module','exports',js)(n=>n.startsWith('.')?load(resolve(dirname(p),extname(n)?n:n+'.ts')):require(n),target,target.exports);return target.exports;}return load;}
const core=loader(),model=core('app/fire-inspections/model.ts');
const data=(v={})=>({...model.emptyInspection(),title:'test/inspection',test:true,...v});
const record=(d=data(),v=0)=>({id:'fictional-inspection',kind:'inspection',data:d,version:v,archived:false});
const completed=()=>data({status:'Completed',actualDate:'2026-09-23',inspector:'Fictional inspector',outcome:'No issues observed',inspectorAttested:true,checks:[{...model.emptyInspection().checks[0],result:'Acceptable'}],repeatMonths:6,nextDueDate:'2027-03-23'});
test('pilot is hidden from normal admins and denies lookalike emails',()=>{const a=core('app/fire-inspections/access.ts'),nav=core('app/portal-menu-items.ts'),p=core('app/permissions.ts');assert.equal(a.inspectionPilotAccess('BOBFF353@gmail.com '),true);for(const e of ['','another-admin@example.invalid','bobff353@gmail.com.evil',null])assert.equal(a.inspectionPilotAccess(e),false);assert.equal(nav.portalNavigationForPermissions(p.defaultPermissionsForRank('Chief',true)).includes('Fire Inspections'),false);assert.equal(p.permissionCatalog.some(p=>p.key==='inspections.pilot'),false);assert.ok(nav.portalNavigationForPermissions(['inspections.pilot']).includes('Fire Inspections'));});
test('date math clamps month ends and queue labels cross year boundaries',()=>{assert.equal(model.addMonths('2026-08-31',6),'2027-02-28');assert.equal(model.addMonths('2024-02-29',12),'2025-02-28');assert.equal(model.validDate('2026-02-29'),false);const d=data({status:'Scheduled',scheduledDate:'2027-01-02'});assert.equal(model.queueLabel(d,'2026-12-25'),'Due within 2 weeks');assert.equal(model.queueLabel(d,'2026-12-27'),'Due within 1 week');assert.equal(model.queueLabel(d,'2027-01-02'),'Due today');assert.equal(model.queueLabel(d,'2027-01-03'),'Past due');assert.equal(model.queueLabel({...d,status:'Completed'},'2027-01-03'),'Completed');});
test('unanswered and skipped checkpoints cannot produce a clean result',()=>{for(const result of ['Not checked','Not inspected','Needs attention'])assert.throws(()=>model.validateInspection('inspection',{...completed(),checks:[{...completed().checks[0],result}]}));model.validateInspection('inspection',completed());assert.throws(()=>model.validateInspection('inspection',{...completed(),checks:[]}));});
test('drafts are flexible but malformed dates, times and signatures are rejected',()=>{model.validateInspection('inspection',data());for(const v of [{scheduledTime:'25:99'},{actualDate:'2099-01-01'},{email:'invalid'},{status:'Scheduled',scheduledDate:''},{actualDate:'2026-02-29'}])assert.throws(()=>model.validateInspection('inspection',data(v)));assert.throws(()=>model.normalizeInspection(data({representative:{state:'Signed',strokes:[[[4,0]]],name:'bad'}})));assert.throws(()=>model.normalizeInspection(data({checks:[{...data().checks[0],result:'Pass automatically'}]})));assert.throws(()=>model.validateInspection('inspection',data({representative:{...model.blankSignature(),state:'Signed',name:'Name only'}})));});
test('follow-ups reset answers and signatures and preserve source and test classification',()=>{const r=record(completed(),1),child=model.followUpRecord(r,'routine','2027-03-23');assert.equal(child.data.status,'Needs scheduling');assert.equal(child.data.parentId,r.id);assert.equal(child.data.test,true);assert.ok(child.data.checks.every(c=>c.result==='Not checked'));assert.equal(child.data.inspectorAttested,false);assert.equal(child.data.representative.state,'Not requested');assert.equal(child.data.actualDate,'');assert.equal(model.followUpRecord(r,'reinspection','2026-10-01').data.repeatMonths,0);});
test('findings need observations and location; corrected findings need actual evidence',()=>{const d=completed();d.outcome='Corrections required';d.checks[0].result='Needs attention';assert.throws(()=>model.validateInspection('inspection',d));d.checks[0].observation='Fictional obstruction';d.checks[0].location='Test door';model.validateInspection('inspection',d);d.checks[0].result='Corrected on site';assert.throws(()=>model.validateInspection('inspection',d));d.checks[0].correction='Fictional obstruction removed';d.checks[0].correctedDate='2026-09-23';model.validateInspection('inspection',d);});
async function harness(){const pg=new PGlite();await pg.exec('CREATE SCHEMA firehouse;CREATE ROLE anon;CREATE ROLE authenticated;SET search_path=firehouse;CREATE TABLE field_preplans(id text primary key,business_name text,address text);');const ddl=fs.readFileSync('supabase/migrations/20260925032225_fire_inspections_private_pilot.sql','utf8').split('CREATE OR REPLACE FUNCTION')[0];await pg.exec(ddl);let failAt=-1;const base=loader({[resolve('app/supabase-server.ts')]:{}});const db=base('db/postgres-adapter.ts').createPostgresD1Adapter(async()=>({rpc:async(name,args)=>{try{const run=async(tx,s)=>{const r=await tx.query(s.sql);if(s.requiredChanges!=null&&r.affectedRows!==s.requiredChanges)throw Error('SAVE_CONFLICT');return s.mode==='first'?r.rows[0]??null:s.mode==='all'?r.rows:{success:true,meta:{changes:r.affectedRows}};};const result=name.endsWith('_batch')?await pg.transaction(async tx=>{const rows=[];for(const[i,s]of args.p_statements.entries()){if(i===failAt){failAt=-1;throw Error('Simulated transaction failure');}rows.push(await run(tx,s));}return rows;}):await run(pg,{sql:args.p_sql,mode:args.p_mode});return{data:result,error:null};}catch(e){return{data:null,error:{message:e.message}};}}}));const api=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:async()=>db}})('app/api/fire-inspections/route.ts');const request=(body,email='bobff353@gmail.com',department='fixture-department',origin='http://localhost')=>new Request('http://localhost/api/fire-inspections',{method:body?'POST':'GET',headers:{'content-type':'application/json','oai-authenticated-user-email':email,'x-department-id':department,origin},...(body?{body:JSON.stringify(body)}:{})});return{pg,api,request,fail(index){failAt=index;},close:()=>pg.close()};}
test('API denies non-owner and cross-origin writes before persisting anything',async()=>{const h=await harness();try{assert.equal((await h.api.GET(h.request(null,'other@example.invalid'))).status,403);assert.equal((await h.api.POST(h.request(record(),'bobff353@gmail.com','fixture-department','https://evil.invalid'))).status,403);assert.equal((await h.pg.query('select * from fire_inspection_pilot_records')).rows.length,0);}finally{await h.close();}});
test('completion and its follow-up commit atomically and retry without duplication',async()=>{const h=await harness();try{const body=record(completed());let r=await h.api.POST(h.request(body));assert.equal(r.status,201,await r.clone().text());const saved=await r.json();assert.equal(saved.followUps.length,1);r=await h.api.POST(h.request(body));assert.equal(r.status,200,await r.clone().text());assert.equal((await r.json()).followUps.length,1);assert.equal((await h.pg.query('select * from fire_inspection_pilot_records')).rows.length,2);assert.equal((await h.pg.query('select * from fire_inspection_pilot_audit')).rows.length,2);const other=await(await h.api.GET(h.request(null,'bobff353@gmail.com','other-dept'))).json();assert.equal(other.records.length,0);}finally{await h.close();}});
test('failure during follow-up creation rolls back report, history and child',async()=>{const h=await harness();try{h.fail(3);const body=record(completed());assert.equal((await h.api.POST(h.request(body))).status,503);assert.equal((await h.pg.query('select * from fire_inspection_pilot_records')).rows.length,0);assert.equal((await h.api.POST(h.request(body))).status,201);}finally{await h.close();}});
test('stale edits cannot overwrite a newer version',async()=>{const h=await harness();try{const b=record();const saved=await(await h.api.POST(h.request(b))).json();assert.equal((await h.api.POST(h.request({...saved.record,data:{...b.data,notes:'newer'}}))).status,200);assert.equal((await h.api.POST(h.request({...saved.record,data:{...b.data,notes:'stale'}}))).status,409);}finally{await h.close();}});
test('completed reports require a reason to reopen, invalidate acknowledgment, retain old version',async()=>{const h=await harness();try{const r=await(await h.api.POST(h.request(record(completed())))).json(),saved=r.record;assert.equal((await h.api.POST(h.request({...saved,data:{...saved.data,notes:'silent change'}}))).status,400);assert.equal((await h.api.POST(h.request({...saved,data:{...saved.data,status:'Draft'}}))).status,400);const reopened=await h.api.POST(h.request({...saved,data:{...saved.data,status:'Draft',changeReason:'Correct a typo'}}));assert.equal(reopened.status,200,await reopened.clone().text());const j=await reopened.json();assert.equal(j.record.data.inspectorAttested,false);assert.equal(j.record.data.representative.state,'Not requested');assert.equal((await h.pg.query("select count(*)::int n from fire_inspection_pilot_audit where record_id='fictional-inspection'")).rows[0].n,2);}finally{await h.close();}});
test('test records cannot become live and fabricated source property links are rejected',async()=>{const h=await harness();try{const j=await(await h.api.POST(h.request(record()))).json();assert.equal((await h.api.POST(h.request({...j.record,data:{...j.record.data,test:false}}))).status,400);assert.equal((await h.api.POST(h.request({...j.record,data:{...j.record.data,propertyId:'not-from-this-department'}}))).status,400);}finally{await h.close();}});
test('saved reports never claim email delivery or automatic code adoption',()=>{const text=model.reportText({...record(),updatedAt:'now',updatedBy:'fictional'});assert.match(text,/Not emailed/);assert.match(text,/Not verified/);});

test('attachment upload and download deny other accounts before database or storage use',async()=>{const never=async()=>{throw Error('must not reach backend');};const load=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:never},[resolve('app/supabase-server.ts')]:{getSupabaseServerClient:never}});const upload=load('app/api/fire-inspections/files/route.ts'),download=load('app/api/fire-inspections/files/[id]/route.ts');const headers={'oai-authenticated-user-email':'another-admin@example.invalid','x-department-id':'fixture-department'};assert.equal((await upload.POST(new Request('http://localhost/api/fire-inspections/files',{method:'POST',headers}))).status,403);assert.equal((await download.GET(new Request('http://localhost/api/fire-inspections/files/private-file',{headers}),{params:Promise.resolve({id:'private-file'})})).status,403);});

function attachmentHarness(){
  const files=new Map(),metadata=[],operations=[];
  let failMetadata=false,recordExists=true;
  const db={prepare(sql){return{bind(...args){return{
    async first(){operations.push('read');if(sql.includes('fire_inspection_pilot_records'))return recordExists?{id:'fixture-record'}:null;const row=metadata.find(r=>r.id===args[1]&&r.department===args[0]);return row?{objectKey:row.key,filename:row.filename,contentType:row.type}:null;},
    async run(){if(failMetadata)throw Error('Simulated metadata failure');const[id,department,recordId,key,filename,type,size]=args;metadata.push({id,department,recordId,key,filename,type,size});return{success:true};},
  };}};}};
  const storage={from(bucket){assert.equal(bucket,'stickney-fire-inspections-pilot');return{
    async upload(key,bytes,options){operations.push('upload');assert.equal(options.upsert,false);files.set(key,bytes);return{error:null};},
    async remove(keys){operations.push('remove');for(const key of keys)files.delete(key);return{error:null};},
    async download(key){operations.push('download');return files.has(key)?{data:new Blob([files.get(key)]),error:null}:{data:null,error:{message:'missing'}};},
  };}};
  const load=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:async()=>db},[resolve('app/supabase-server.ts')]:{getSupabaseServerClient:async()=>({storage})}});
  const headers={'oai-authenticated-user-email':'bobff353@gmail.com','x-department-id':'fixture-department',origin:'http://localhost'};
  return{upload:load('app/api/fire-inspections/files/route.ts'),download:load('app/api/fire-inspections/files/[id]/route.ts'),files,metadata,operations,
    request(content='%PDF-1.7\nPublic fictional PDF',type='application/pdf'){const body=new FormData();body.set('recordId','fixture-record');body.set('file',new File([content],'reference.pdf',{type}));return new Request('http://localhost/api/fire-inspections/files',{method:'POST',headers,body});},
    readRequest(department='fixture-department'){return new Request('http://localhost/api/fire-inspections/files/private-file',{headers:{...headers,'x-department-id':department}});},
    failMetadata(){failMetadata=true;},missingRecord(){recordExists=false;},
  };
}

test('private attachment round-trip preserves bytes and department isolation',async()=>{
  const h=attachmentHarness(),response=await h.upload.POST(h.request());
  assert.equal(response.status,201,await response.clone().text());
  const {attachment}=await response.json();assert.equal(h.metadata.length,1);assert.equal(h.files.size,1);
  assert.ok(h.metadata[0].key.startsWith('fixture-department/fixture-record/'));
  const downloaded=await h.download.GET(h.readRequest(),{params:Promise.resolve({id:attachment.id})});
  assert.equal(downloaded.status,200);assert.equal(await downloaded.text(),'%PDF-1.7\nPublic fictional PDF');
  assert.equal(downloaded.headers.get('cache-control'),'private, no-store');assert.equal(downloaded.headers.get('x-content-type-options'),'nosniff');
  assert.match(downloaded.headers.get('content-disposition'),/attachment/);
  assert.equal((await h.download.GET(h.readRequest('other-department'),{params:Promise.resolve({id:attachment.id})})).status,404);
});

test('attachments reject spoofed file content and missing records before storage upload',async()=>{
  const h=attachmentHarness();assert.equal((await h.upload.POST(h.request('<html>Not PDF</html>'))).status,400);assert.equal(h.operations.length,0);
  h.missingRecord();assert.equal((await h.upload.POST(h.request())).status,404);assert.equal(h.files.size,0);
});

test('failed attachment metadata removes the uploaded object and reports no success',async()=>{
  const h=attachmentHarness();h.failMetadata();assert.equal((await h.upload.POST(h.request())).status,503);
  assert.equal(h.files.size,0);assert.equal(h.metadata.length,0);assert.ok(h.operations.includes('remove'));
});


test('inspector review keeps the captured signature; changing inspection content invalidates it',()=>{const signed={...model.blankSignature(),state:'Signed',name:'Fictional signer',strokes:[[[0.1,0.2],[0.3,0.4]]]};const d=model.updateInspectionDetail(completed(),'representative',signed);assert.equal(d.inspectorAttested,false);const reviewed=model.updateInspectionDetail(d,'inspectorAttested',true);assert.deepEqual(reviewed.representative,signed);model.validateInspection('inspection',reviewed);const changed=model.updateInspectionDetail(reviewed,'notes','Changed observation');assert.equal(changed.representative.state,'Not requested');assert.equal(changed.inspectorAttested,false);});
