import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {resolve,dirname,extname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import {PGlite} from '@electric-sql/pglite';
const require=createRequire(import.meta.url);
test('private attachments round-trip, reject wrong contents and versions, and clean up failed metadata',async()=>{
 const h=await harness(),objects=new Map();
 const storage={from(bucket){assert.equal(bucket,'stickney-neris-pilot');return{async upload(key,bytes,options){objects.set(key,new Blob([bytes],{type:options.contentType}));return{error:null};},async download(key){return{data:objects.get(key),error:null};},async remove(keys){keys.forEach(k=>objects.delete(k));return{error:null};}};}};
 const load=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:async()=>h.db},[resolve('app/supabase-server.ts')]:{getSupabaseServerClient:async()=>({storage})}}),upload=load('app/api/neris/files/route.ts'),get=load('app/api/neris/files/[id]/route.ts');
 try{
  const saved=(await(await h.api.POST(h.request(report()))).json()).record;
  const send=(version=saved.version,contents='%PDF-1.4\nfictional attachment test',department='fixture-department')=>{const body=new FormData();body.set('recordId',saved.id);body.set('version',String(version));body.set('file',new File([contents],'test-evidence.pdf',{type:'application/pdf'}));return upload.POST(new Request('http://localhost/api/neris/files',{method:'POST',headers:{origin:'http://localhost','oai-authenticated-user-email':'bobff353@gmail.com','x-department-id':department},body}));};
  assert.equal((await send(saved.version,'wrong contents')).status,400);
  assert.equal((await send(0)).status,409);
  assert.equal((await send(saved.version,undefined,'other-department')).status,404);
  const response=await send();assert.equal(response.status,201,await response.clone().text());const file=(await response.json()).attachment;
  const download=await get.GET(h.request(null),{params:Promise.resolve({id:file.id})});assert.equal(download.status,200);assert.equal(await download.text(),'%PDF-1.4\nfictional attachment test');assert.equal(download.headers.get('X-Content-Type-Options'),'nosniff');assert.match(download.headers.get('Cache-Control'),/no-store/);
  assert.equal((await get.GET(h.request(null,'bobff353@gmail.com','other-department'),{params:Promise.resolve({id:file.id})})).status,404);
  h.fail(1);assert.equal((await send()).status,503);assert.equal(objects.size,1);assert.equal((await h.pg.query('select * from neris_pilot_files')).rows.length,1);
  const reviewed={...saved,data:valid()};reviewed.data.local.status='Reviewed';assert.equal((await h.api.POST(h.request(reviewed))).status,200);assert.equal((await send(2)).status,409);
 }finally{await h.close();}
});
function loader(overrides={}){const cache=new Map();function load(p){p=resolve(p);if(Object.hasOwn(overrides,p))return overrides[p];if(cache.has(p))return cache.get(p).exports;if(extname(p)==='.json')return JSON.parse(fs.readFileSync(p,'utf8'));const target={exports:{}};cache.set(p,target);const js=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText;new Function('require','module','exports',js)(n=>n.startsWith('.')?load(resolve(dirname(p),extname(n)?n:n+'.ts')):require(n),target,target.exports);return target.exports;}return load;}

const core=loader(),model=core('app/neris/model.ts'),access=core('app/neris/access.ts'),validation=core('app/neris/validation.ts');
const setupModel=core('app/neris/setup-model.ts');
test('department setup rejects invented states, malformed IDs and duplicate administrators',()=>{
 const data=model.newReport().data;data.setup=setupModel.emptySetup();assert.deepEqual(model.normalizeData(data).setup,data.setup);
 for(const patch of [{departmentId:'FD-made-up'},{departmentConfirmed:true},{reportingMethod:'Connected automatically'},{dispatchPlan:'Anything'},{leadId:'member-1',backupId:'member-1'},{tasks:{}},{notes:500}]){
  const changed=structuredClone(data);Object.assign(changed.setup,patch);assert.throws(()=>model.normalizeData(changed),JSON.stringify(patch));
 }
});
test('saved department choices are isolated, versioned and do not alter incident facts',async()=>{
 const h=await harness();try{
  const incident=report();assert.equal((await h.api.POST(h.request(incident))).status,201);
  const settings={...model.newReport(),id:'neris-setup-fixture-department',kind:'settings'};settings.data.payload={};settings.data.setup={...setupModel.emptySetup(),departmentId:'FD00000000',departmentConfirmed:true,reportingMethod:'NERIS portal'};
  const response=await h.api.POST(h.request(settings));assert.equal(response.status,201,await response.clone().text());const saved=(await response.json()).record;
  const all=await(await h.api.GET(h.request(null))).json();assert.deepEqual(all.records.find(r=>r.id===settings.id).data.setup,settings.data.setup);assert.deepEqual(all.records.find(r=>r.id===incident.id).data.payload,incident.data.payload);
  const competing=structuredClone(settings);competing.data.setup.reportingMethod='ESO';assert.equal((await h.api.POST(h.request(competing))).status,409);
  saved.data.setup.tasks.profile='Confirmed';assert.equal((await h.api.POST(h.request(saved))).status,200);
  assert.equal((await h.api.POST(h.request(saved,'other@example.invalid'))).status,403);
  const other=await(await h.api.GET(h.request(null,'bobff353@gmail.com','other-department'))).json();assert.equal(other.records.length,0);
 }finally{await h.close();}
});
test('draft shape rejects malformed local data before it can break a saved editor',()=>{const data=model.newReport().data;for(const key of ['title','writer','changeReason']){const changed=structuredClone(data);changed.local[key]={};assert.throws(()=>model.normalizeData(changed));}const changed=structuredClone(data);changed.local.personnel=[{id:'bad'}];assert.throws(()=>model.normalizeData(changed));});
const report=()=>{const r=model.newReport();r.data.local.title='test/NERIS verification';r.data.local.test=true;return r;};
const valid=()=>{const d=report().data;d.local.writer='Fictional writer';d.local.reviewed=true;d.payload={base:{department_neris_id:'FD00000000',incident_number:'TEST-001',location:{street:'Test Way',number:100}},incident_types:[{primary:true,type:'MEDICAL||ILLNESS'}],dispatch:{incident_number:'TEST-001',location:{},call_arrival:'2026-09-29T10:00:00-05:00',call_answered:'2026-09-29T10:00:05-05:00',call_create:'2026-09-29T10:00:10-05:00',unit_responses:[]}};return d;};
test('private reporting is not grantable to another administrator',()=>{assert.equal(access.nerisPilotAccess(' BOBFF353@gmail.com '),true);for(const e of ['',null,'admin@stickneyfire.com','bobff353@gmail.com.evil'])assert.equal(access.nerisPilotAccess(e),false);const nav=core('app/portal-menu-items.ts'),p=core('app/permissions.ts');assert.ok(!nav.portalNavigationForPermissions(p.defaultPermissionsForRank('Firefighter',true)).includes('NERIS Reporting'));assert.ok(nav.portalNavigationForPermissions(['neris.pilot']).includes('NERIS Reporting'));assert.ok(!p.permissionCatalog.some(x=>x.key==='neris.pilot'));});
test('all official incident and base fields have a form section; no default incident facts',()=>{const paths=model.sections.flatMap(s=>s.paths);for(const k of Object.keys(model.schemas.IncidentPayload.properties)){if(k==='base')continue;assert.ok(paths.includes(k),k);}for(const k of Object.keys(model.schemas.IncidentBasePayload.properties))assert.ok(paths.includes('base.'+k),k);assert.equal(Object.keys(model.schemas).length,149);const r=report();assert.equal(model.getAt(r.data.payload,'base.people_present'),undefined);assert.equal(model.getAt(r.data.payload,'base.animals_rescued'),undefined);assert.equal(model.getAt(r.data.payload,'dispatch.call_create'),undefined);assert.deepEqual(r.data.payload.incident_types,[]);});
test('official schema accepts a valid fictional minimum and rejects invented codes and missing offset',()=>{assert.deepEqual(validation.validateReport(valid()),[]);const d=valid();d.payload.incident_types[0].type='MADE_UP';assert.ok(validation.validateReport(d).length);d.payload.incident_types[0].type='MEDICAL||ILLNESS';d.payload.dispatch.call_create='2026-09-29T10:00:10';assert.ok(validation.validateReport(d).some(i=>i.path.includes('call_create')));});
test('cross-field rules enforce ordering, primary uniqueness, aid identity and module applicability',()=>{const d=valid();d.payload.dispatch.call_answered='2026-09-29T09:00:00-05:00';d.payload.incident_types.push({primary:true,type:'MEDICAL||ILLNESS'});d.payload.aids=[{department_neris_id:'FD00000000',aid_type:'SUPPORT_AID',aid_direction:'GIVEN'}];d.payload.fire_detail={};const issues=validation.validateReport(d);for(const text of ['primary','only once','cannot be after','itself','requires a FIRE'])assert.ok(issues.some(i=>i.message.includes(text)),text);});
test('structure fire requires alarm modules except support-only aid given',()=>{const d=valid();d.payload.incident_types=[{type:'FIRE||STRUCTURE_FIRE||CONFINED_COOKING_APPLIANCE_FIRE'}];const issues=validation.validateReport(d);for(const p of ['smoke_alarm','fire_alarm','other_alarm','fire_suppression','cooking_fire_suppression'])assert.ok(issues.some(i=>i.path==='/'+p));d.payload.aids=[{department_neris_id:'FD00000001',aid_type:'SUPPORT_AID',aid_direction:'GIVEN'}];assert.ok(!validation.validateReport(d).some(i=>i.message.includes('require')));});
test('NONE cannot mix with PPE, actions, fire investigation or suppression choices',()=>{const d=valid();d.payload.fire_detail={investigation_types:['NONE','OTHER'],suppression_appliances:['NONE','OTHER']};assert.equal(validation.validateReport(d).filter(i=>i.message==='None cannot be combined with another choice.').length,2);});
test('durations never guess missing or reversed timestamps; export never claims delivery',()=>{assert.equal(model.elapsedSeconds('2026-09-29T10:00:00-05:00','2026-09-29T10:00:23-05:00'),23);assert.equal(model.elapsedSeconds('',null),null);assert.equal(model.elapsedSeconds('2026-09-29T10:10:00Z','2026-09-29T10:00:00Z'),null);const packet=model.reviewPackage(report());assert.equal(packet.delivery.submitted,false);assert.equal(packet.delivery.receipt,null);assert.equal(packet.delivery.state,'not_connected');});
async function harness(){const pg=new PGlite();await pg.exec('CREATE SCHEMA firehouse;CREATE ROLE anon;CREATE ROLE authenticated;SET search_path=firehouse;CREATE TABLE employees(id text primary key,name text,active integer,pay_scale_id text);CREATE TABLE pay_scales(id text primary key,label text);');const ddl=fs.readFileSync('supabase/migrations/20260929182752_neris_private_reporting_pilot.sql','utf8').split('CREATE OR REPLACE FUNCTION')[0];await pg.exec(ddl);let failAt=-1;const base=loader({[resolve('app/supabase-server.ts')]:{}});const db=base('db/postgres-adapter.ts').createPostgresD1Adapter(async()=>({rpc:async(name,args)=>{try{const run=async(tx,s)=>{const r=await tx.query(s.sql);if(s.requiredChanges!=null&&r.affectedRows!==s.requiredChanges)throw Error('SAVE_CONFLICT');return s.mode==='first'?r.rows[0]??null:s.mode==='all'?r.rows:{success:true,meta:{changes:r.affectedRows}};};const result=name.endsWith('_batch')?await pg.transaction(async tx=>{const rows=[];for(const[i,s]of args.p_statements.entries()){if(i===failAt){failAt=-1;throw Error('Simulated transaction failure');}rows.push(await run(tx,s));}return rows;}):await run(pg,{sql:args.p_sql,mode:args.p_mode});return{data:result,error:null};}catch(e){return{data:null,error:{message:e.message}};}}}));const api=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:async()=>db}})('app/api/neris/route.ts');const request=(body,email='bobff353@gmail.com',department='fixture-department',origin='http://localhost')=>new Request('http://localhost/api/neris',{method:body?'POST':'GET',headers:{'content-type':'application/json','oai-authenticated-user-email':email,'x-department-id':department,origin},...(body?{body:JSON.stringify(body)}:{})});return{pg,db,api,request,fail(index){failAt=index;},close:()=>pg.close()};}
test('API denies other accounts, missing department and cross-origin writes',async()=>{const h=await harness();try{assert.equal((await h.api.GET(h.request(null,'other@example.invalid'))).status,403);assert.equal((await h.api.GET(h.request(null,'bobff353@gmail.com',''))).status,403);assert.equal((await h.api.POST(h.request(report(),'bobff353@gmail.com','fixture-department','https://evil.invalid'))).status,403);}finally{await h.close();}});
test('atomic save, identical retry, conflict protection, department isolation and archive history',async()=>{const h=await harness();try{const r=report();let response=await h.api.POST(h.request(r));assert.equal(response.status,201,await response.clone().text());const saved=(await response.json()).record;response=await h.api.POST(h.request(r));assert.equal((await response.json()).record.version,1);r.data.local.title='test/competing draft';assert.equal((await h.api.POST(h.request(r))).status,409);assert.equal((await h.api.POST(h.request({...saved,archived:true}))).status,200);assert.equal((await h.pg.query('select * from neris_pilot_audit')).rows.length,2);const other=await(await h.api.GET(h.request(null,'bobff353@gmail.com','other-department'))).json();assert.equal(other.records.length,0);}finally{await h.close();}});
test('failed audit rolls back report; reviewed records require correction and valid facts',async()=>{const h=await harness();try{h.fail(1);const r=report();assert.equal((await h.api.POST(h.request(r))).status,503);assert.equal((await h.pg.query('select * from neris_pilot_records')).rows.length,0);r.data=valid();r.data.local.status='Reviewed';let response=await h.api.POST(h.request(r));assert.equal(response.status,201,await response.clone().text());const saved=(await response.json()).record;saved.data.local.title='test/changed';assert.equal((await h.api.POST(h.request(saved))).status,400);saved.data.local.status='Draft';saved.data.local.changeReason='Correcting fictional test';assert.equal((await h.api.POST(h.request(saved))).status,200);}finally{await h.close();}});
test('attachment endpoints deny other accounts before touching storage',async()=>{const never=async()=>{throw Error('must not reach backend');};const load=loader({[resolve('db/bootstrap.ts')]:{ensureDatabase:never},[resolve('app/supabase-server.ts')]:{getSupabaseServerClient:never}}),headers={'oai-authenticated-user-email':'other@example.invalid','x-department-id':'fixture-department'};assert.equal((await load('app/api/neris/files/route.ts').POST(new Request('http://localhost/api/neris/files',{method:'POST',headers}))).status,403);assert.equal((await load('app/api/neris/files/[id]/route.ts').GET(new Request('http://localhost/api/neris/files/id',{headers}),{params:Promise.resolve({id:'id'})})).status,403);});
