import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("driver and ambulance openings follow department clearance rules", async () => {
  const source = await readFile(new URL("../app/schedule-eligibility.ts", import.meta.url), "utf8");
  assert.match(source, /driverStatus === "cleared"/);
  assert.match(source, /driverStatus === "cleared" \|\| driverStatus === "ambulance only"/);
  assert.match(source, /ambulance attendant/);
  assert.match(source, /isSingleRoleFirefighter/);
  assert.match(source, /chief\|captain\|lieutenant/);
  assert.match(source, /actingOfficerEligible/);
});

test("recurring shift patterns generate stable claimable openings", async () => {
  const source = await readFile(new URL("../app/api/scheduling/route.ts", import.meta.url), "utf8");
  assert.match(source, /generatedPatternOpenings/);
  assert.match(source, /pattern-open-/);
  assert.match(source, /source: `shift-pattern:\$\{gap\.patternId\}`/);
  assert.match(source, /resolveOpenAssignment/);
  assert.match(source, /Generated by \$\{gap\.patternName\} shift pattern/);
});

test("member open shifts are filtered by qualification and schedule conflicts", async () => {
  const source = await readFile(new URL("../app/api/scheduling/route.ts", import.meta.url), "utf8");
  assert.match(source, /employeeEligibleForAssignment\(selectedEmployee, assignment, "", tradeBusyAssignments\.results\)/);
  assert.match(source, /qualifiedForScheduleRole\(employee, role\)/);
  assert.match(source, /!busyAssignments\.some/);
  assert.match(source, /not cleared and available for this open position/);
});
