import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import { webcrypto } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
const source=fs.readFileSync(new URL('../app/staffing-eligibility.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {staffingRoles}=await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
test('employee qualifications form the approved hierarchy; old role flags cannot grant clearance',()=>{
 const all=['Officer/AO','Engine Driver','Ambulance Driver','FF/Attendant'];
 for(const rank of ['Chief','Deputy Chief','Captain','Lieutenant']) assert.deepEqual(staffingRoles({rank}),all);
 assert.deepEqual(staffingRoles({actingOfficerEligible:1}),all);
 assert.deepEqual(staffingRoles({driverStatus:'Cleared'}),all.slice(1));
 assert.deepEqual(staffingRoles({driverStatus:'Ambulance Only'}),all.slice(2));
 assert.deepEqual(staffingRoles({driverStatus:'Not Cleared',roles:all}),all.slice(3));
 assert.deepEqual(staffingRoles({}),all.slice(3));
 assert.deepEqual(staffingRoles({singleRole:1,rank:'Chief',actingOfficerEligible:1,driverStatus:'Cleared'}),[]);
 assert.deepEqual(staffingRoles({rank:'Single-Role Firefighter'}),[]);
});
const route=fs.readFileSync(new URL('../app/api/station-scheduler/route.ts',import.meta.url),'utf8');
const ast=ts.createSourceFile('route.ts',route,ts.ScriptTarget.Latest,true);
const names=['eligibleForRole','isSchedulableEmployee','isEligibleEmployeeForRole','addDaySlot','reviewClaim'];
const handlers=ast.statements.filter(s=>ts.isFunctionDeclaration(s)&&names.includes(s.name?.text)).map(s=>s.getText(ast)).join('\n');
test('saved profile controls assignment eligibility; arbitrary-day extras preserve minimum positions and reject conflicts',async()=>{
 const pg=new PGlite();
 try{
 await pg.exec(`CREATE SCHEMA firehouse; SET search_path=firehouse;
 CREATE TABLE employees(id text primary key,name text,active int,pay_scale_id text);
 CREATE TABLE pay_scales(id text primary key,label text);
 CREATE TABLE employee_profiles(employee_id text,end_date text,station_roles text,acting_officer_eligible int,driver_status text);
 CREATE TABLE station_shift_types(id text primary key,active int);
 CREATE TABLE station_schedule_entries(id text primary key,entry_date text,shift_type_id text,created_by text,UNIQUE(entry_date,shift_type_id));
 CREATE TABLE station_shift_slots(id text primary key,entry_id text,role text,employee_id text,status text,sort_order int,start_time text,end_time text,is_extra int);
 CREATE TABLE station_shift_claims(id text primary key,slot_id text,employee_id text,status text,reviewed_by text,reviewed_at timestamp);
 INSERT INTO employees VALUES('member','Test',1,'ff'); INSERT INTO pay_scales VALUES('ff','Firefighter');
 INSERT INTO employee_profiles VALUES('member','','["Officer/AO"]',0,'Cleared');
 INSERT INTO station_shift_types VALUES('day',1);`);
 await pg.exec(fs.readFileSync(new URL('../supabase/migrations/20260910011259_employee_eligibility_extra_staffing.sql',import.meta.url),'utf8'));
 const db={prepare(sql){let values=[],expected;const s={bind(...v){values=v;return s},expectChanges(n){expected=n;return s},async run(){let i=0;const q=sql.replaceAll('?',()=>`$${++i}`).replace(/\b(employeeId|entryDate|sortOrder|actingOfficerEligible|driverStatus|singleRole|slotId)\b/g,'"$1"');const result=await pg.query(q,values);if(expected!==undefined&&result.affectedRows!==expected)throw Error('conflict');return{...result,meta:{changes:result.affectedRows}}},async first(){return(await s.run()).rows[0]??null}};return s},async batch(writes){await pg.exec('BEGIN');try{for(const w of writes)await w.run();await pg.exec('COMMIT')}catch(e){await pg.exec('ROLLBACK');throw e}}};
 let conflict='';
 const sandbox={exports:{},crypto:webcrypto,staffingRoles,iso:/^\d{4}-\d{2}-\d{2}$/,normalizeScheduleTime:v=>/^\d{2}:\d{2}$/.test(v)?v:null,isGeneralOneDayPosition:r=>['Extra member','Firefighter','Training/Orientation'].includes(r),isOneDayPositionRole:r=>['Extra member','Engine Driver','FF/Attendant'].includes(r),staffingConflict:async()=>conflict,assignmentConflict:async()=>conflict,ok:(v={})=>({status:200,...v}),bad:(error,status=400)=>({status,error})};
 vm.runInNewContext(ts.transpileModule(handlers+'\nexports.h={isEligibleEmployeeForRole,addDaySlot,reviewClaim};',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,sandbox);
 const h=sandbox.exports.h;
 assert.equal(await h.isEligibleEmployeeForRole(db,'member','Engine Driver'),true);
 assert.equal(await h.isEligibleEmployeeForRole(db,'member','Officer/AO'),false);
 await pg.exec("UPDATE employee_profiles SET single_role=1");
 assert.equal(await h.isEligibleEmployeeForRole(db,'member','FF/Attendant'),false);
 assert.equal(await h.isEligibleEmployeeForRole(db,'member','Extra member'),true);
 const payload={date:'2099-12-25',shiftTypeId:'day',role:'Extra member',startTime:'10:00',endTime:'16:00',employeeId:'member',staffingReason:'Holiday coverage'};
 assert.equal((await h.addDaySlot(db,{name:'Admin'},payload,()=>{})).status,200);
 const rows=(await pg.query('SELECT * FROM station_shift_slots')).rows;
 assert.equal(rows.length,1);assert.equal(rows[0].is_extra,1);assert.equal(rows[0].staffing_reason,'Holiday coverage');
 conflict='Overlapping assignment';assert.equal((await h.addDaySlot(db,{name:'Admin'},{...payload,date:'2099-12-26'},()=>{})).status,409);
 assert.equal((await pg.query('SELECT * FROM station_schedule_entries')).rows.length,1,'failed save must not create a day');
 await assert.rejects(h.addDaySlot(db,{name:'Admin'},payload,()=>{throw Error('admin only')}),/admin only/);
 conflict='';
 assert.equal((await h.addDaySlot(db,{name:'Admin'},{...payload,date:'2099-02-31'},()=>{})).status,400);
 await pg.exec("INSERT INTO station_shift_slots(id,role,status) VALUES('requested','FF/Attendant','open'); INSERT INTO station_shift_claims(id,slot_id,employee_id,status) VALUES('claim','requested','member','pending')");
 assert.equal((await h.reviewClaim(db,{name:'Admin'},{id:'claim',decision:'approved'},()=>{})).status,409,'single-role cannot fill minimum seat');
 await pg.exec('UPDATE employee_profiles SET single_role=0');
 conflict='Already scheduled';
 assert.equal((await h.reviewClaim(db,{name:'Admin'},{id:'claim',decision:'approved'},()=>{})).status,409);
 conflict='';
 assert.equal((await h.reviewClaim(db,{name:'Admin'},{id:'claim',decision:'approved'},()=>{})).status,200);
 assert.equal((await pg.query("SELECT employee_id FROM station_shift_slots WHERE id='requested'")).rows[0].employee_id,'member');
 assert.equal((await pg.query("SELECT status FROM station_shift_claims WHERE id='claim'")).rows[0].status,'approved');
 }finally{await pg.close()}
});
