import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {trainingModules} from './helpers/training-modules.mjs';
import {documentHarness} from './helpers/document-workflow-harness.mjs';
const load=trainingModules(),model=load('app/training/model.ts'),phase=load('app/training/phase-four.ts');
const member={id:'fixture-a',name:'Local Fixture A',active:1,rank:'Firefighter'};
const record=(changes={})=>({id:'fixture-assignment',kind:'assignment',version:1,archived:false,createdAt:'2026-10-05',updatedAt:'2026-10-05',updatedBy:'fixture',data:{...model.emptyTrainingData(),title:'Local recurring assignment',status:'saved',date:'2026-10-01',dueDate:'2026-10-31',repeatEveryDays:30,hours:2,employeeIds:[member.id],attendance:{[member.id]:2},answers:{old:'completed'},...changes}});
test('recurrence shifts calendar dates across year boundaries and removes attendance and answers',()=>{const parent=record({date:'2026-12-01',dueDate:'2026-12-31',repeatEveryDays:1});const next=phase.nextAssignmentData(parent);assert.equal(next.dueDate,'2027-01-01');assert.equal(next.date,'2026-12-02');assert.deepEqual(next.attendance,{});assert.deepEqual(next.answers,{});assert.equal(next.seriesId,parent.id);assert.equal(model.creditedHours({...parent,data:next}),0);assert.equal(parent.data.attendance[member.id],2);});
test('invalid, archived and incomplete assignments cannot generate recurring records',()=>{for(const parent of [{...record(),archived:true},record({status:'draft'}),record({repeatEveryDays:null}),record({dueDate:'2026-02-29'})])assert.throws(()=>phase.nextAssignmentData(parent));});
test('old payloads get safe defaults; repeat and renewal intervals and dates are validated',()=>{const data=model.normalizeTrainingData({title:'Legacy'});assert.equal(data.documentType,'Other');assert.equal(data.repeatEveryDays,null);for(const changes of [{repeatEveryDays:0},{repeatEveryDays:367},{repeatEveryDays:1.5},{renewalMonths:121},{renewalMonths:0},{renewalMonths:true},{documentType:'invalid'}])assert.throws(()=>model.normalizeTrainingData({title:'x',...changes}));assert.throws(()=>model.validateTraining('assignment',record({date:'2026-11-01'}).data,[],[member]),/due date cannot/);assert.throws(()=>model.validateTraining('credential',record({issuedDate:'2026-11-01',dueDate:'2026-10-31',cycleStart:'2026-01-01',certificationId:'custom'}).data,[],[member]),/issue date/);});
test('renewal register uses recorded dates and excludes draft, archived and test records',()=>{const credential=(id,dueDate,changes={})=>({...record({dueDate,issuingAuthority:'Local issuer',repeatEveryDays:null,...changes}),id,kind:'credential'});const records=[credential('past','2026-10-04'),credential('edge','2027-01-03'),credential('later','2027-01-04'),credential('missing',''),credential('draft','2026-10-10',{status:'draft'}),credential('test','2026-10-10',{test:true}),{...credential('archive','2026-10-10'),archived:true}];const rows=phase.credentialRegister({records,members:[member],attachments:[{recordId:'edge'}]},'2026-10-05',90);assert.equal(rows.length,4);assert.equal(rows.find(r=>r.record.id==='edge').state,'Within reminder window');assert.equal(rows.find(r=>r.record.id==='edge').evidenceCount,1);assert.equal(rows.find(r=>r.record.id==='later').state,'Later');assert.equal(rows.find(r=>r.record.id==='past').state,'Past recorded renewal date');assert.equal(rows.find(r=>r.record.id==='missing').state,'Date needed');assert.equal(phase.credentialRegister({records,members:[member],attachments:[]},'2026-10-05',90,'issuer').length,4);});
async function harness(){const h=await documentHarness();await h.pg.exec('ALTER TABLE employees ADD COLUMN pay_scale_id text;CREATE TABLE pay_scales(id text PRIMARY KEY,label text);');await h.pg.exec(readFileSync('supabase/migrations/20260925014536_training_private_pilot.sql','utf8').split('CREATE OR REPLACE FUNCTION')[0]);const modules=trainingModules({[resolve('db/bootstrap.ts')]:{ensureDatabase:async()=>h.db},[resolve('app/department-portal.ts')]:h.context});const api=modules('app/api/training/route.ts');const request=(body,email='bobff353@gmail.com',department='fixture-department')=>new Request('http://localhost/api/training',{method:'POST',headers:{'Content-Type':'application/json','oai-authenticated-user-email':email,'x-department-id':department,origin:'http://localhost'},body:JSON.stringify(body)});const parent=record({attendance:{},answers:{}});const response=await api.POST(request({...parent,version:0}));assert.equal(response.status,201,await response.clone().text());return {...h,trainingApi:api,trainingRequest:request,parent:(await response.json()).record};}
const repeat=parent=>({action:'repeatAssignment',id:parent.id,version:parent.version});
test('actual SQL repeat creates one independent assignment and retry retains child edits',async()=>{const h=await harness();try{let response=await h.trainingApi.POST(h.trainingRequest(repeat(h.parent)));assert.equal(response.status,201,await response.clone().text());const child=(await response.json()).record;assert.notEqual(child.id,h.parent.id);assert.deepEqual(child.data.attendance,{});assert.equal(child.data.dueDate,'2026-11-30');assert.equal(model.creditedHours(child),0);response=await h.trainingApi.POST(h.trainingRequest({...child,id:'fixture-completion',kind:'completion',version:0,data:{...child.data,seriesId:'',repeatEveryDays:null,assignmentId:child.id,date:model.todayChicago(),hours:2,instructor:'Local instructor',attendance:{'fixture-a':2},status:'completed'}}));assert.equal(response.status,201,await response.clone().text());assert.equal(model.creditedHours((await response.json()).record),2);const olderClientData={...child.data,title:'Reviewed child'};delete olderClientData.seriesId;response=await h.trainingApi.POST(h.trainingRequest({...child,data:olderClientData,archived:true}));assert.equal(response.status,200);assert.equal((await response.json()).record.data.seriesId,h.parent.id);response=await h.trainingApi.POST(h.trainingRequest(repeat(h.parent)));assert.equal(response.status,200);const retry=(await response.json()).record;assert.equal(retry.data.title,'Reviewed child');assert.equal(retry.archived,true);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_records')).rows[0].n,3);}finally{await h.close();}});
test('concurrent repeat requests create only one occurrence and one child audit',async()=>{const h=await harness();try{const results=await Promise.all([h.trainingApi.POST(h.trainingRequest(repeat(h.parent))),h.trainingApi.POST(h.trainingRequest(repeat(h.parent)))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,201]);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_records')).rows[0].n,2);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_audit')).rows[0].n,2);}finally{await h.close();}});
test('failed repeat audit rolls back the new assignment and permits a single retry',async()=>{const h=await harness();try{h.state.failAt=2;assert.equal((await h.trainingApi.POST(h.trainingRequest(repeat(h.parent)))).status,503);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_records')).rows[0].n,1);assert.equal((await h.trainingApi.POST(h.trainingRequest(repeat(h.parent)))).status,201);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_audit')).rows[0].n,2);}finally{await h.close();}});
test('stale assignments, another pilot login and a different department cannot generate records',async()=>{const h=await harness();try{assert.equal((await h.trainingApi.POST(h.trainingRequest({...repeat(h.parent),version:9}))).status,409);assert.equal((await h.trainingApi.POST(h.trainingRequest(repeat(h.parent),'admin@stickneyfire.com'))).status,403);assert.equal((await h.trainingApi.POST(h.trainingRequest(repeat(h.parent),'bobff353@gmail.com','other-department'))).status,409);assert.equal((await h.pg.query('SELECT count(*) n FROM training_pilot_records')).rows[0].n,1);}finally{await h.close();}});
