"use client";

import { useEffect, useMemo, useState } from "react";
import { cachePublishedPreplan, getCachedPublishedPreplan } from "./offline-cache";
import { isOperationallyVisible, lifecycleState } from "./domain";

type Row = Record<string, unknown> & { id:string; archived?:number; levelId?:string; spaceId?:string };
type OperationalPayload = { plan?:Row;levels:Row[];spaces:Row[];alerts:Row[];hazmat:Row[];zones:Row[];annotations:Row[];assets:Row[];hoseLays:Row[];risks:Row[];reviews:Row[];revisions:Row[] };
const empty:OperationalPayload={levels:[],spaces:[],alerts:[],hazmat:[],zones:[],annotations:[],assets:[],hoseLays:[],risks:[],reviews:[],revisions:[]};

function label(value:unknown,fallback="Not entered"){const result=String(value??"").trim();return result||fallback;}
function date(value:unknown){const parsed=new Date(String(value??""));return Number.isFinite(parsed.getTime())?parsed.toLocaleString():"Not set";}

export default function OperationalPreplanPanel({preplanId,canEdit=false}:{preplanId:string;canEdit?:boolean}){
  const [data,setData]=useState<OperationalPayload>(empty);
  const [source,setSource]=useState<"loading"|"live"|"offline"|"unavailable">("loading");
  const [cachedAt,setCachedAt]=useState("");
  const [selectedLevel,setSelectedLevel]=useState("");
  const [reloadKey,setReloadKey]=useState(0),[editor,setEditor]=useState<""|"level"|"space"|"alert"|"hazmat"|"zone"|"asset"|"annotation"|"hoseLay"|"risk">(""),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
  const [assetFile,setAssetFile]=useState<File|null>(null);
  const blankForm={name:"",shortLabel:"",aliases:"",severity:"warning",title:"",message:"",effectiveAt:"",expiresAt:"",materialName:"",unNumber:"",ergGuideNumber:"",quantity:"",quantityUnit:"",storageType:"",hazmatId:"",zoneType:"isolation",radiusFeet:"100",annotationType:"road_closure",label:"",assetCategory:"reference",caption:"",totalDistanceFeet:"",hoseSizeInches:"4",sectionLengthFeet:"100",reserveFeet:"100",apparatusCapacityFeet:"",factor:"",score:"",explanation:"",source:"",targetHazardOverride:""};
  const [form,setForm]=useState<Record<string,string>>(blankForm);
  useEffect(()=>{
    let active=true;
    async function load(){
      try{
        const response=await fetch(`/api/field-preplans/operational?preplanId=${encodeURIComponent(preplanId)}`,{cache:"no-store"});
        if(!response.ok)throw new Error("Operational record unavailable");
        const payload=await response.json() as OperationalPayload;
        if(!active)return;
        setData(payload);setSource("live");
        const revision=Number(payload.revisions[0]?.revisionNumber??0);
        const now=new Date().toISOString();setCachedAt(now);
        if(payload.plan?.publicationStatus==="published")await cachePublishedPreplan({id:preplanId,revision,cachedAt:now,payload});
      }catch{
        try{
          const cached=await getCachedPublishedPreplan<OperationalPayload>(preplanId);
          if(!active)return;
          if(cached){setData(cached.payload);setCachedAt(cached.cachedAt);setSource("offline");}
          else setSource("unavailable");
        }catch{if(active)setSource("unavailable");}
      }
    }
    void load();return()=>{active=false};
  },[preplanId,reloadKey]);
  async function save(){
    setSaving(true);setSaveError("");
    try{
      if(!editor)return;
      if(editor==="asset"){
        if(!assetFile)throw new Error("Choose a JPG, PNG, WebP, or PDF attachment.");
        const upload=new FormData();upload.set("preplanId",preplanId);upload.set("category",form.assetCategory);upload.set("caption",form.caption);if(levelId)upload.set("levelId",levelId);upload.set("file",assetFile);
        const response=await fetch("/api/field-preplans/assets",{method:"POST",body:upload});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Unable to upload attachment.");
        setEditor("");setForm(blankForm);setAssetFile(null);setReloadKey((value)=>value+1);return;
      }
      const actions={level:"saveLevel",space:"saveSpace",alert:"saveAlert",hazmat:"saveHazmat",zone:"saveHazmatZone",annotation:"saveAnnotation",hoseLay:"saveHoseLay",risk:"saveRiskFactor"} as const;
      const payload:Record<string,unknown>={action:actions[editor],preplanId,levelId:levelId||undefined,...form,quantity:form.quantity?Number(form.quantity):undefined};
      if(editor==="space")payload.aliases=form.aliases.split(",").map((item)=>item.trim()).filter(Boolean);
      if(editor==="annotation")Object.assign(payload,{annotationType:form.annotationType,operationalSubtype:form.annotationType,label:form.label,coordinateSpace:"floor_plan",geometry:[]});
      if(editor==="zone")Object.assign(payload,{hazmatId:form.hazmatId,zoneType:form.zoneType,label:form.label,geometryType:"circle",geometry:{},radiusFeet:Number(form.radiusFeet)});
      if(editor==="hoseLay")Object.assign(payload,{totalDistanceFeet:Number(form.totalDistanceFeet),hoseSizeInches:Number(form.hoseSizeInches),sectionLengthFeet:Number(form.sectionLengthFeet),reserveFeet:Number(form.reserveFeet),apparatusCapacityFeet:form.apparatusCapacityFeet?Number(form.apparatusCapacityFeet):undefined,path:[],segmentDistances:[]});
      if(editor==="risk")Object.assign(payload,{factor:form.factor,score:Number(form.score),explanation:form.explanation,source:form.source,targetHazardOverride:form.targetHazardOverride?Number(form.targetHazardOverride):0});
      const response=await fetch("/api/field-preplans/operational",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});
      const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Unable to save operational record.");
      setEditor("");setForm(blankForm);setReloadKey((value)=>value+1);
    }catch(error){setSaveError(error instanceof Error?error.message:"Unable to save operational record.");}finally{setSaving(false);}
  }
  async function transition(action:"submitReview"|"returnDraft"|"publish"|"archive"){
    setSaving(true);setSaveError("");
    try{const response=await fetch("/api/field-preplans/operational",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,preplanId,comment:`${action} from Field Preplans`})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Unable to update publication status.");setReloadKey((value)=>value+1);}
    catch(error){setSaveError(error instanceof Error?error.message:"Unable to update publication status.");}finally{setSaving(false);}
  }
  async function restoreRevision(revisionNumber:number){
    if(!window.confirm(`Restore operational layers from revision ${revisionNumber}? A new published revision will be created. Current private attachments and legacy mapped systems will be preserved.`))return;
    setSaving(true);setSaveError("");
    try{const response=await fetch("/api/field-preplans/operational",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"restoreRevision",preplanId,revisionNumber,comment:`Restored operational layers from revision ${revisionNumber} in Field Preplans`})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Unable to restore revision.");setReloadKey((value)=>value+1);}
    catch(error){setSaveError(error instanceof Error?error.message:"Unable to restore revision.");}finally{setSaving(false);}
  }
  const levels=useMemo(()=>data.levels.filter((item)=>!item.archived),[data.levels]);
  const levelId=selectedLevel||String(levels.find((item)=>item.isDefault)?.id??levels[0]?.id??"");
  const spaces=data.spaces.filter((item)=>!item.archived&&(!levelId||item.levelId===levelId));
  const alerts=data.alerts.filter((item)=>!item.archived&&isOperationallyVisible({effectiveAt:item.effectiveAt as string,expiresAt:item.expiresAt as string,expirationAction:item.expirationAction as never})&&(!item.levelId||!levelId||item.levelId===levelId));
  const hazards=data.hazmat.filter((item)=>!item.archived&&isOperationallyVisible({effectiveAt:item.effectiveAt as string,expiresAt:item.expiresAt as string})&&(!item.levelId||!levelId||item.levelId===levelId));
  const hoseLays=data.hoseLays.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId));
  if(source==="loading")return <section className="operational-preplan-panel" aria-busy="true"><h3>Operational intelligence</h3><p>Loading published response details…</p></section>;
  if(source==="unavailable")return <section className="operational-preplan-panel"><h3>Operational intelligence</h3><p>The operational 2.0 record is not available yet. The approved legacy preplan above remains usable.</p></section>;
  return <section className="operational-preplan-panel" aria-label="Operational preplan intelligence">
    <header><div><span>PREPLAN 2.0 · {label(data.plan?.publicationStatus,"LEGACY").toUpperCase()}</span><h3>Operational intelligence</h3></div><div className={`operational-cache-state ${source}`}>{source==="offline"?"OFFLINE CACHED":data.plan?.publicationStatus==="published"?"LIVE PUBLISHED":"LIVE WORKING COPY"}<small>{cachedAt?date(cachedAt):""}</small></div></header>
    {canEdit&&<div className="operational-publication-actions"><strong>Publication workflow</strong><button disabled={saving} onClick={()=>void transition("returnDraft")}>Return to draft</button><button disabled={saving} onClick={()=>void transition("submitReview")}>Submit for review</button><button className="publish" disabled={saving} onClick={()=>void transition("publish")}>Publish revision</button><button disabled={saving} onClick={()=>void transition("archive")}>Archive</button></div>}
    {levels.length>0&&<nav aria-label="Building level"><label>Level<select value={levelId} onChange={(event)=>setSelectedLevel(event.target.value)}>{levels.map((level)=><option key={level.id} value={level.id}>{label(level.name)}</option>)}</select></label></nav>}
    {canEdit&&<div className="operational-editor-actions"><span>Add verified operational data</span>{([['level','Level'],['space','Room / area'],['alert','Response alert'],['hazmat','HazMat'],['zone','HazMat zone'],['asset','Attachment'],['annotation','Tactical annotation'],['hoseLay','Hose lay'],['risk','Risk factor']] as const).map(([key,name])=><button type="button" className={editor===key?"active":""} key={key} onClick={()=>{setEditor(editor===key?"":key);setSaveError("");}}>+ {name}</button>)}</div>}
    {editor&&<form className="operational-inline-editor" onSubmit={(event)=>{event.preventDefault();void save();}}><header><strong>{editor==="level"?"Add building level":editor==="space"?"Add room or operational area":editor==="alert"?"Add time-aware response alert":editor==="hazmat"?"Add HazMat inventory":editor==="zone"?"Add HazMat isolation or evacuation zone":editor==="asset"?"Upload secure operational attachment":editor==="annotation"?"Add named tactical annotation":editor==="hoseLay"?"Calculate and save hose lay":"Add transparent target-hazard factor"}</strong><button type="button" onClick={()=>setEditor("")} aria-label="Close editor">×</button></header>
      {editor==="level"&&<><label>Level name<input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Example: Basement 1"/></label><label>Short label<input value={form.shortLabel} onChange={(event)=>setForm({...form,shortLabel:event.target.value})} placeholder="Generated if blank"/></label></>}
      {editor==="space"&&<><label>Room / area name<input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Example: Electrical Room"/></label><label>CAD aliases<input value={form.aliases} onChange={(event)=>setForm({...form,aliases:event.target.value})} placeholder="Comma-separated dispatch names"/></label></>}
      {editor==="alert"&&<><label>Severity<select value={form.severity} onChange={(event)=>setForm({...form,severity:event.target.value})}><option value="informational">Informational</option><option value="caution">Caution</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><label>Alert title<input required value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label className="wide">Crew message<textarea required value={form.message} onChange={(event)=>setForm({...form,message:event.target.value})}/></label><label>Effective at<input type="datetime-local" value={form.effectiveAt} onChange={(event)=>setForm({...form,effectiveAt:event.target.value})}/></label><label>Expires at<input type="datetime-local" value={form.expiresAt} onChange={(event)=>setForm({...form,expiresAt:event.target.value})}/></label></>}
      {editor==="hazmat"&&<><label>Material name<input required value={form.materialName} onChange={(event)=>setForm({...form,materialName:event.target.value})}/></label><label>UN / NA number<input value={form.unNumber} onChange={(event)=>setForm({...form,unNumber:event.target.value})} inputMode="numeric"/></label><label>Verified ERG guide<input value={form.ergGuideNumber} onChange={(event)=>setForm({...form,ergGuideNumber:event.target.value})}/></label><label>Quantity<input value={form.quantity} onChange={(event)=>setForm({...form,quantity:event.target.value})} inputMode="decimal"/></label><label>Unit<input value={form.quantityUnit} onChange={(event)=>setForm({...form,quantityUnit:event.target.value})} placeholder="gal, lb, cylinders"/></label><label>Storage type<input value={form.storageType} onChange={(event)=>setForm({...form,storageType:event.target.value})}/></label><small className="wide">Only enter a guide number verified against the official PHMSA ERG 2024. Leaving it blank is safer than guessing.</small></>}
      {editor==="zone"&&<><label>HazMat record<select required value={form.hazmatId} onChange={(event)=>setForm({...form,hazmatId:event.target.value})}><option value="">Select verified material</option>{hazards.map((item)=><option key={item.id} value={item.id}>{label(item.materialName)}</option>)}</select></label><label>Zone type<select value={form.zoneType} onChange={(event)=>setForm({...form,zoneType:event.target.value})}><option value="isolation">Initial isolation</option><option value="evacuation">Evacuation</option><option value="hot">Hot zone</option><option value="warm">Warm zone</option><option value="cold">Cold zone</option><option value="custom">Custom</option></select></label><label>Firefighter-facing label<input required value={form.label} onChange={(event)=>setForm({...form,label:event.target.value})} placeholder="Example: 300 ft initial isolation"/></label><label>Radius (feet)<input required type="number" min="1" step="1" value={form.radiusFeet} onChange={(event)=>setForm({...form,radiusFeet:event.target.value})}/></label><small className="wide">This saves the verified zone and radius. Map placement remains pending until coordinates are added on the tactical drawing surface.</small></>}
      {editor==="asset"&&<><label>Category<select value={form.assetCategory} onChange={(event)=>setForm({...form,assetCategory:event.target.value})}><option value="reference">Reference</option><option value="floor_plan">Floor plan</option><option value="photo">Photo</option><option value="sds">Safety data sheet</option><option value="permit">Permit</option><option value="inspection">Inspection</option></select></label><label>Caption<input value={form.caption} onChange={(event)=>setForm({...form,caption:event.target.value})} placeholder="What responders should know"/></label><label className="wide">Private file<input required type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event)=>setAssetFile(event.target.files?.[0]??null)}/></label><small className="wide">Allowed: JPG, PNG, WebP, or PDF up to 25 MB. Files are served only through the authenticated preplan endpoint.</small></>}
      {editor==="annotation"&&<><label>Annotation name<input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Example: East alley road closure"/></label><label>Type<select value={form.annotationType} onChange={(event)=>setForm({...form,annotationType:event.target.value})}><option value="road_closure">Road closure</option><option value="collapse_zone">Collapse zone</option><option value="apparatus_placement">Apparatus placement</option><option value="ingress">Ingress</option><option value="egress">Egress</option><option value="staging">Staging</option><option value="command_post">Command post</option><option value="custom">Custom</option></select></label><label className="wide">Map label<input value={form.label} onChange={(event)=>setForm({...form,label:event.target.value})} placeholder="Short firefighter-facing label"/></label><small className="wide">The named record is saved now; geometry can be added from the tactical drawing surface when coordinates are available.</small></>}
      {editor==="hoseLay"&&<><label>Hose-lay name<input required value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} placeholder="Hydrant to Alpha side"/></label><label>Measured route<input required type="number" min="0" step="1" value={form.totalDistanceFeet} onChange={(event)=>setForm({...form,totalDistanceFeet:event.target.value})}/><small>feet</small></label><label>Hose size<input required type="number" min="0.5" step="0.5" value={form.hoseSizeInches} onChange={(event)=>setForm({...form,hoseSizeInches:event.target.value})}/><small>inches</small></label><label>Section length<input required type="number" min="1" step="1" value={form.sectionLengthFeet} onChange={(event)=>setForm({...form,sectionLengthFeet:event.target.value})}/><small>feet</small></label><label>Reserve<input required type="number" min="0" step="1" value={form.reserveFeet} onChange={(event)=>setForm({...form,reserveFeet:event.target.value})}/><small>feet</small></label><label>Verified apparatus capacity<input type="number" min="0" step="1" value={form.apparatusCapacityFeet} onChange={(event)=>setForm({...form,apparatusCapacityFeet:event.target.value})} placeholder="Leave blank if unverified"/><small>feet</small></label></>}
      {editor==="risk"&&<><label>Risk factor<input required value={form.factor} onChange={(event)=>setForm({...form,factor:event.target.value})} placeholder="Example: Bowstring truss"/></label><label>Score<input required type="number" min="-100" max="100" step="1" value={form.score} onChange={(event)=>setForm({...form,score:event.target.value})}/></label><label className="wide">Why this affects operations<textarea required value={form.explanation} onChange={(event)=>setForm({...form,explanation:event.target.value})}/></label><label className="wide">Verified source<input required value={form.source} onChange={(event)=>setForm({...form,source:event.target.value})} placeholder="Inspection, plan set, owner confirmation…"/></label><label>Authorized override<input type="number" min="-100" max="100" step="1" value={form.targetHazardOverride} onChange={(event)=>setForm({...form,targetHazardOverride:event.target.value})} placeholder="0"/></label></>}
      {saveError&&<p className="operational-save-error" role="alert">{saveError}</p>}<button className="primary-action" disabled={saving}>{saving?"Saving…":"Save operational record"}</button>
    </form>}
    <div className="operational-summary-grid">
      <article><span>LEVELS</span><strong>{levels.length}</strong><small>{levels.map((item)=>label(item.shortLabel)).join(" · ")||"Legacy arrival view"}</small></article>
      <article><span>ROOMS / AREAS</span><strong>{spaces.length}</strong><small>{spaces.slice(0,3).map((item)=>label(item.name)).join(" · ")||"None mapped"}</small></article>
      <article><span>REVISION</span><strong>{label(data.revisions[0]?.revisionNumber,"Legacy")}</strong><small>{label(data.revisions[0]?.publicationStatus,"Published record")}</small></article>
      <article><span>HOSE LAYS</span><strong>{hoseLays.length}</strong><small>{hoseLays[0]?`${label(hoseLays[0].recommendedHoseFeet)} ft recommended`:"None calculated"}</small></article>
    </div>
    <details className="revision-history operational-revision-history"><summary>Revision history <span>{data.revisions.length}</span></summary>{data.revisions.length?<ol>{data.revisions.map((revision)=><li key={revision.id}><div><strong>Revision {label(revision.revisionNumber)} · {label(revision.publicationStatus).replaceAll("_"," ")}</strong><span>{label(revision.summary,"No publication summary entered.")}</span><small>{label(revision.actor)} · {date(revision.createdAt)}{revision.restoredFromRevision?` · restored from revision ${revision.restoredFromRevision}`:""}</small></div>{canEdit&&Number(revision.revisionNumber)!==Number(data.plan?.revisionNumber)&&<button type="button" disabled={saving} onClick={()=>void restoreRevision(Number(revision.revisionNumber))}>Restore as new revision</button>}</li>)}</ol>:<p>No published operational revisions have been recorded yet.</p>}<p><small>Restore replaces revisioned operational layers. Current private attachments and legacy mapped systems are preserved.</small></p></details>
    <div className="operational-response-grid">
      <article className="operational-alerts"><h4>Response alerts</h4>{alerts.length?alerts.map((item)=>{const state=lifecycleState({effectiveAt:item.effectiveAt as string,expiresAt:item.expiresAt as string,expirationAction:item.expirationAction as never});return <section key={item.id} className={`operational-alert ${label(item.severity,"warning")} ${state}`}><div><strong>{label(item.title)}</strong><b>{label(item.severity).toUpperCase()} · {state.toUpperCase()}</b></div><p>{label(item.message)}</p>{item.expiresAt?<small>Expires {date(item.expiresAt)}</small>:null}</section>}):<p className="operational-empty">No active response alerts are recorded.</p>}</article>
      <article className="operational-hazmat"><h4>HazMat / ERG 2024</h4>{hazards.length?hazards.map((item)=><section key={item.id}><div><strong>{label(item.materialName)}</strong><b>{item.unNumber?`UN/NA ${label(item.unNumber)}`:"No UN/NA number"}</b></div><dl><div><dt>ERG guide</dt><dd>{label(item.ergGuideNumber,"Verify in official ERG")}</dd></div><div><dt>Quantity</dt><dd>{item.quantity?`${item.quantity} ${label(item.quantityUnit,"")}`:"Not entered"}</dd></div><div><dt>Storage</dt><dd>{label(item.storageType)}</dd></div></dl></section>):<p className="operational-empty">No HazMat inventory is recorded for this level.</p>}<a href="https://www.phmsa.dot.gov/training/hazmat/erg/emergency-response-guidebook-erg" target="_blank" rel="noreferrer">Open official PHMSA ERG 2024 ↗</a></article>
    </div>
    <div className="operational-response-grid">
      <article><h4>HazMat zones</h4>{data.zones.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).length?data.zones.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).map((item)=><section key={item.id}><div><strong>{label(item.label)}</strong><b>{label(item.zoneType).replaceAll("_"," ").toUpperCase()}</b></div><p>{item.radiusFeet?`${Number(item.radiusFeet).toLocaleString()} ft radius`:`${label(item.geometryType)} geometry`}</p><small>{label(hazards.find((hazard)=>hazard.id===item.hazmatId)?.materialName,"Linked HazMat record")}</small></section>):<p className="operational-empty">No HazMat isolation or evacuation zones are recorded for this level.</p>}</article>
      <article><h4>Secure attachments</h4>{data.assets.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).length?data.assets.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).map((item)=><section key={item.id}><div><strong>{label(item.caption,item.originalFilename as string)}</strong><b>{label(item.category).replaceAll("_"," ").toUpperCase()}</b></div><p>{label(item.originalFilename)}</p><a href={`/api/field-preplans/assets/${encodeURIComponent(item.id)}`} target="_blank" rel="noreferrer">Open private attachment ↗</a></section>):<p className="operational-empty">No secure attachments are available for this level.</p>}</article>
    </div>
    <div className="operational-response-grid">
      <article><h4>Tactical annotations</h4>{data.annotations.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).length?data.annotations.filter((item)=>!item.archived&&(!item.levelId||!levelId||item.levelId===levelId)).map((item)=><section key={item.id}><div><strong>{label(item.name)}</strong><b>{label(item.annotationType).replaceAll("_"," ").toUpperCase()}</b></div><p>{label(item.label,"Named annotation awaiting mapped geometry")}</p></section>):<p className="operational-empty">No tactical annotations are recorded for this level.</p>}</article>
      <article><h4>Target-hazard assessment</h4><strong>{label(data.plan?.targetHazardLevel,"low").toUpperCase()} TARGET HAZARD</strong>{data.risks.length?data.risks.map((item)=><section key={item.id}><div><strong>{label(item.factor)}</strong><b>{Number(item.score)>0?"+":""}{String(item.score??0)}</b></div><p>{label(item.explanation)}</p><small>Source: {label(item.source)}</small></section>):<p className="operational-empty">No scored risk factors are recorded.</p>}</article>
    </div>
    {hoseLays.length>0&&<article className="operational-hose-lays"><h4>Measured hose lays</h4>{hoseLays.map((item)=>{const recommended=Number(item.recommendedHoseFeet??0),capacity=item.apparatusCapacityFeet==null?null:Number(item.apparatusCapacityFeet);return <section key={item.id}><div><strong>{label(item.name)}</strong><b>{recommended.toLocaleString()} FT RECOMMENDED</b></div><p>{Number(item.totalDistanceFeet??0).toLocaleString()} ft route + {Number(item.reserveFeet??0).toLocaleString()} ft reserve · {label(item.hoseSizeInches)}-inch hose</p><small>{capacity==null?"Apparatus inventory unverified":recommended<=capacity?`Verified capacity ${capacity.toLocaleString()} ft · sufficient`:`DEFICIT: ${(recommended-capacity).toLocaleString()} ft beyond verified capacity`}</small></section>})}</article>}
  </section>;
}
