import { ensureDatabase } from "../../../db/bootstrap";

const ownerAdminEmails = ["bobff353@gmail.com"];
async function isAdmin(request: Request, db: Awaited<ReturnType<typeof ensureDatabase>>) { const email = request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase() ?? ""; if (ownerAdminEmails.includes(email)) return true; if (!email) return false; const row = await db.prepare("SELECT is_admin AS isAdmin FROM employee_profiles WHERE lower(email) = ? LIMIT 1").bind(email).first<{ isAdmin: number }>(); return Boolean(row?.isAdmin); }
const addDay = (iso: string) => { const date = new Date(`${iso}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + 1); return date.toISOString().slice(0, 10); };
const stamp = (date: string, time?: unknown, nextDay = false) => `${nextDay ? addDay(date) : date}T${String(time || "00:00").slice(0, 5)}:00`;
function equipment(raw: unknown) { try { return Object.entries(JSON.parse(String(raw || "{}")) as Record<string, { status?: string; detail?: string }>).filter(([, value]) => value.status && value.status !== "Present"); } catch { return []; } }

export async function GET(request: Request) {
  try {
    const db = await ensureDatabase();
    if (!await isAdmin(request, db)) return Response.json({ error: "Administrator privileges are required to view the complete activity timeline." }, { status: 403 });
    const days = Math.min(90, Math.max(1, Number(new URL(request.url).searchParams.get("days") || 14)));
    const [staffing, approvals, calls, logs, revisions] = await Promise.all([
      db.prepare("SELECT s.id, s.log_date AS logDate, s.shift_key AS shiftKey, s.time_in AS timeIn, s.time_out AS timeOut, s.acting_officer AS actingOfficer, e.name FROM daily_log_staffing s JOIN employees e ON e.id = s.employee_id WHERE s.log_date >= date('now', ?) AND s.employee_id IS NOT NULL").bind(`-${days} day`).all(),
      db.prepare("SELECT a.id, a.log_date AS logDate, a.shift_key AS shiftKey, a.sign_in_at AS signInAt, a.sign_out_at AS signOutAt, a.sign_in_equipment AS signInEquipment, a.sign_out_equipment AS signOutEquipment, a.sign_in_note AS signInNote, a.sign_out_note AS signOutNote, ein.name AS signInName, eout.name AS signOutName FROM daily_log_approvals a LEFT JOIN employees ein ON ein.id = a.sign_in_officer_id LEFT JOIN employees eout ON eout.id = a.sign_out_officer_id WHERE a.log_date >= date('now', ?)").bind(`-${days} day`).all(),
      db.prepare("SELECT id, log_date AS logDate, report_number AS reportNumber, time_out AS timeOut, time_in AS timeIn, responding_units AS respondingUnits, address, call_type AS callType FROM daily_log_calls WHERE log_date >= date('now', ?)").bind(`-${days} day`).all(),
      db.prepare("SELECT log_date AS logDate, shift_notes AS shiftNotes, updated_by AS updatedBy, updated_at AS updatedAt FROM daily_logs WHERE log_date >= date('now', ?) AND shift_notes <> ''").bind(`-${days} day`).all(),
      db.prepare("SELECT id, record_type AS recordType, record_id AS recordId, action, summary, actor, changed_at AS changedAt FROM record_revisions WHERE changed_at >= datetime('now', ?) AND ((record_type = 'payroll') OR (record_type = 'dailyLog' AND action = 'Unlocked'))").bind(`-${days} day`).all(),
    ]);
    const events: Array<{ id: string; timestamp: string; category: string; actor: string; title: string; detail: string; record: string }> = [];
    for (const row of staffing.results as Array<Record<string, unknown>>) { const overnight = String(row.timeOut) < String(row.timeIn); events.push({ id: `${row.id}-in`, timestamp: stamp(String(row.logDate), row.timeIn), category: "Staffing", actor: String(row.name), title: "Employee signed in", detail: `${row.shiftKey} shift${row.actingOfficer ? " · Acting Officer" : ""}`, record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); if (row.timeOut) events.push({ id: `${row.id}-out`, timestamp: stamp(String(row.logDate), row.timeOut, overnight), category: "Staffing", actor: String(row.name), title: "Employee signed out", detail: `${row.shiftKey} shift`, record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); }
    for (const row of approvals.results as Array<Record<string, unknown>>) { if (row.signInAt) events.push({ id: `${row.id}-approval-in`, timestamp: String(row.signInAt), category: "Approval", actor: String(row.signInName || "Officer"), title: "Officer approved shift start", detail: `${row.shiftKey} shift`, record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); if (row.signOutAt) events.push({ id: `${row.id}-approval-out`, timestamp: String(row.signOutAt), category: "Approval", actor: String(row.signOutName || "Officer"), title: "Officer approved shift close", detail: `${row.shiftKey} shift`, record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); for (const [mode, raw, at, actor] of [["start", row.signInEquipment, row.signInAt, row.signInName], ["close", row.signOutEquipment, row.signOutAt, row.signOutName]] as const) for (const [item, issue] of equipment(raw)) events.push({ id: `${row.id}-${mode}-${item}`, timestamp: String(at || stamp(String(row.logDate))), category: "Equipment", actor: String(actor || "Officer"), title: `${String(item)} · ${issue.status}`, detail: issue.detail || `${row.shiftKey} shift ${mode} check`, record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); for (const [mode, note, at, actor] of [["start", row.signInNote, row.signInAt, row.signInName], ["close", row.signOutNote, row.signOutAt, row.signOutName]] as const) if (note) events.push({ id: `${row.id}-note-${mode}`, timestamp: String(at || stamp(String(row.logDate))), category: "Note", actor: String(actor || "Officer"), title: `Officer ${mode} note`, detail: String(note), record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); }
    for (const row of calls.results as Array<Record<string, unknown>>) { if (row.timeOut) events.push({ id: `${row.id}-call-out`, timestamp: stamp(String(row.logDate), row.timeOut), category: "Call", actor: String(row.respondingUnits || "Responding units not entered"), title: `${row.callType} dispatched`, detail: [row.address, row.reportNumber ? `Report ${row.reportNumber}` : ""].filter(Boolean).join(" · "), record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); if (row.timeIn) events.push({ id: `${row.id}-call-in`, timestamp: stamp(String(row.logDate), row.timeIn, String(row.timeIn) < String(row.timeOut)), category: "Call", actor: String(row.respondingUnits || "Responding units not entered"), title: `${row.callType} cleared`, detail: [row.address, row.reportNumber ? `Report ${row.reportNumber}` : ""].filter(Boolean).join(" · "), record: `LOG-${String(row.logDate).replaceAll("-", "")}` }); }
    for (const row of logs.results as Array<Record<string, unknown>>) events.push({ id: `log-note-${row.logDate}`, timestamp: String(row.updatedAt), category: "Note", actor: String(row.updatedBy || "System"), title: "Daily Log note updated", detail: String(row.shiftNotes), record: `LOG-${String(row.logDate).replaceAll("-", "")}` });
    for (const row of revisions.results as Array<Record<string, unknown>>) events.push({ id: String(row.id), timestamp: String(row.changedAt), category: row.recordType === "payroll" ? "Payroll" : "Administration", actor: String(row.actor), title: String(row.action), detail: String(row.summary), record: row.recordType === "payroll" ? `PAY-${String(row.recordId).replaceAll("-", "")}` : `LOG-${String(row.recordId).replaceAll("-", "")}` });
    events.sort((a, b) => b.timestamp.localeCompare(a.timestamp));
    return Response.json({ events, days, generatedAt: new Date().toISOString() });
  } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to load activity timeline" }, { status: 500 }); }
}
