"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
type Event = { id: string; timestamp: string; category: string; actor: string; title: string; detail: string; record: string };
const categories = ["All", "Staffing", "Approval", "Call", "Equipment", "Note", "Payroll", "Administration"];
function eventDate(value: string) { const normalized = value.includes("T") ? value : value.replace(" ", "T") + "Z"; const date = new Date(normalized); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }); }
export default function ActivityTimeline() {
  const [events, setEvents] = useState<Event[]>([]), [category, setCategory] = useState("All"), [search, setSearch] = useState(""), [days, setDays] = useState(14), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch(`/api/activity?days=${days}`); const result = await response.json() as { events?: Event[]; error?: string }; if (response.ok) { setEvents(result.events ?? []); setError(""); } else setError(result.error || "Unable to load activity"); setLoading(false); }, [days]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => events.filter((event) => (category === "All" || event.category === category) && `${event.actor} ${event.title} ${event.detail} ${event.record}`.toLowerCase().includes(search.toLowerCase())), [category, events, search]);
  return <section className="activity-page"><header className="standard-page-header activity-header"><div><span className="page-icon">≡</span><div><p className="eyebrow">Administrator audit view</p><h1>Complete Activity Timeline</h1><p>Chronological department activity with the responsible employee, timestamp, and source record.</p></div></div><button className="quiet-button" onClick={() => void load()}>Refresh</button></header>
    <div className="activity-toolbar"><label className="resource-search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employee, action, note, or record…" /></label><label><span>Event type</span><select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>History</span><select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label></div>
    {error && <div className="error-banner"><span>{error}</span><button onClick={() => void load()}>Retry</button></div>}
    {loading ? <div className="activity-loading"><i/><i/><i/><i/></div> : filtered.length ? <div className="activity-feed">{filtered.map((event, index) => <article key={event.id} className={`activity-event ${event.category.toLowerCase()}`}><div className="activity-rail"><span>{event.category.slice(0,1)}</span>{index < filtered.length - 1 && <i/>}</div><div className="activity-card"><header><div><span className="activity-category">{event.category}</span><h2>{event.title}</h2></div><time>{eventDate(event.timestamp)}</time></header><p>{event.detail || "No additional details entered."}</p><footer><strong>{event.actor}</strong><span>{event.record}</span></footer></div></article>)}</div> : <div className="content-card action-empty-state"><span>≡</span><div><strong>No matching activity</strong><p>Try another event type, search, or history range.</p></div><button className="quiet-button" onClick={() => { setSearch(""); setCategory("All"); }}>Clear filters</button></div>}
  </section>;
}
