import type { PortalPage } from "./portal-navigation";
import type { PermissionKey } from "./permissions";

type AdminTask = { id: string; title: string; group: string; page: PortalPage; permissions: PermissionKey[]; steps: string; preview: string };

/** Navigation hints only. Editors and APIs independently verify current access. */
export const adminTasks: readonly AdminTask[] = [
  { id: "work-details", title: "Review work detail requests", group: "Schedule", page: "Work Details", permissions: ["scheduling.manage"], steps: "Find the request in the approval queue, review the member, dates, and hours, then approve or deny.", preview: "Review the saved request status and any approved hours in the appropriate period." },
  { id: "road-closures", title: "Add or resolve a road closure", group: "Operations", page: "Road Closures", permissions: ["incident_command.manage"], steps: "Trace the closed road, set a bypass point if needed, then review the details before activating. Resolve a closure when the road reopens.", preview: "Review the active closure list and map. These are operational updates, not a draft preview." },
  { id: "employees", title: "Edit a member or role eligibility", group: "People & access", page: "Employees", permissions: ["employees.manage"], steps: "Find the member, open their profile, change the needed fields, then Save. Cancel leaves the saved profile unchanged.", preview: "Reopen the saved profile. Login access is managed separately in Permissions." },
  { id: "rank-access", title: "Change default permissions by rank", group: "People & access", page: "Permissions", permissions: ["permissions.manage"], steps: "Choose a rank, find the permission, change it, then Save rank permissions. This changes the starting access for that rank.", preview: "Use Test as member for a read-only navigation preview; it does not test their actual login." },
  { id: "member-access", title: "Add or remove one member’s access", group: "People & access", page: "Permissions", permissions: ["permissions.manage"], steps: "Choose Member exceptions, select the member, then Add or Remove a permission. Save employee exceptions applies only to that person.", preview: "Review the saved access count. Test as member previews navigation, not authentication." },
  { id: "overview", title: "Schedule admin home", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Choose staffing, open positions, requests, or trades. Each action shows the affected dates and members before you submit.", preview: "Switch to My schedule to see the member layout. This does not impersonate another member." },
  { id: "roster", title: "Edit roster and standing assignments", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Find a member to review notification preferences, or add a recurring standing assignment. Daily staffing changes belong in Calendar.", preview: "Review the dated Calendar to confirm how recurring assignments affect staffing." },
  { id: "calendar", title: "Edit daily staffing and extra coverage", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Choose the date in Day staffing. Assign an eligible member or add extra coverage for a storm, holiday, or event, then save the affected shift.", preview: "Review the same day in Calendar and confirm the saved members and positions." },
  { id: "shiftTypes", title: "Build shifts and required positions", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Choose a shift template, check its times and positions, then save your changes. Review dated assignments separately.", preview: "Check Calendar and Open positions for the dates you are staffing." },
  { id: "distribution", title: "Auto-distribute a date range", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Set the start and end dates, review the distribution options, then build the assignments. Confirm the resulting roster.", preview: "Review the affected dates in Calendar; do not assume every position was filled." },
  { id: "reminders", title: "Set request deadlines and reminders", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Set the request due date and reminder rules. Check the delivery settings before saving.", preview: "Review the saved rules and request deadline; saving a rule is not proof a message was delivered." },
  { id: "requests", title: "Review shift requests", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Open a request, check dates and eligibility, then approve or deny. A request is not an assignment until approved.", preview: "Confirm the result in the dated roster." },
  { id: "trades", title: "Review offered and accepted trades", group: "Schedule", page: "Scheduling", permissions: ["scheduling.manage"], steps: "Review the members, roles, and dates before acting on a trade.", preview: "Check the resulting roster and trade status." },
  { id: "checks", title: "Edit apparatus checks and inventory templates", group: "Apparatus & equipment", page: "Inventory", permissions: ["inventory.setup.manage"], steps: "Choose the apparatus and check type, edit the checklist or due schedule, then Save & preview. Template changes do not rewrite completed reports.", preview: "Use Member preview to inspect the saved checklist without submitting a check." },
  { id: "apparatus", title: "Edit apparatus, locations, and photos", group: "Apparatus & equipment", page: "Inventory", permissions: ["inventory.setup.manage"], steps: "Choose the apparatus, edit its details or locations, and save that record. Keep existing linked equipment and history intact.", preview: "Return to Fleet and open the saved apparatus." },
  { id: "equipment", title: "Find equipment and change its details", group: "Apparatus & equipment", page: "Inventory", permissions: ["inventory.setup.manage"], steps: "Find the item by name, apparatus, or location. Open Edit, make the change, and save.", preview: "Use Save & preview in the checklist builder to review the member-facing result." },
  { id: "service", title: "Update repair work", group: "Apparatus & equipment", page: "Inventory", permissions: ["inventory.repairs.manage"], steps: "Find the repair, review the affected apparatus or item, then update its assignment or status.", preview: "Check the saved repair and apparatus readiness. Do not mark work complete until it is done." },
  { id: "payroll", title: "Review payroll and corrections", group: "Hours & pay", page: "Payroll", permissions: ["payroll.manage"], steps: "Choose the pay period, review member totals and correction requests, then use the existing approval controls. Finalized history is protected.", preview: "Review Timesheets for the same period before finalizing." },
  { id: "hours", title: "Correct employee hours", group: "Hours & pay", page: "Timesheets", permissions: ["payroll.manage"], steps: "Choose the period and employee. Hour cells save when you leave the field; wait for the save confirmation. Retry any highlighted failed save.", preview: "Review that employee’s saved totals and the matching Payroll period." },
  { id: "rates", title: "Edit pay rates and payroll rules", group: "Hours & pay", page: "Rates & Rules", permissions: ["payroll.manage"], steps: "Choose the rate or rule, check its effective date, then save. Verify the correct period and employee afterward.", preview: "Review the affected payroll totals. Past finalized records are not ordinary editable forms." },
  { id: "callbacks", title: "Review callback attendance and pay", group: "Hours & pay", page: "Callback Reviews", permissions: ["payroll.manage"], steps: "Open the submitted callback, review members and eligibility flags, then approve or return it for correction.", preview: "Confirm the review status and the related saved timesheet entries." },
  { id: "daily-log", title: "Edit or approve the Daily Log", group: "Operations", page: "Daily Log", permissions: ["daily_log.manage"], steps: "Choose the date, open the relevant call or entry, and use its save or approval control. Check the save status before leaving.", preview: "Reload the selected day and confirm the saved record." },
  { id: "board", title: "Change Live Operations board notes", group: "Operations", page: "Operations Board", permissions: ["settings.manage"], steps: "Use the board’s add or edit control for a note or event. Set its display-until date when needed, then save.", preview: "Close the editor to review the board. Calls, staffing, weather, and external feeds come from their own sources." },
  { id: "preplans", title: "Edit a building or preplan", group: "Operations", page: "Field Preplans", permissions: ["field_preplans.edit"], steps: "Find the building on the map or in search, open the record, then edit and save. Publishing and deleting require their own permissions.", preview: "Open the saved record in reader view. Unsaved changes are not operationally published." },
  { id: "inspections", title: "Change safety inspection checklists", group: "Operations", page: "Safety Inspections", permissions: ["safety_inspections.manage"], steps: "Open the checklist settings, choose the item to change, then save. Reopening a completed record is a separate action.", preview: "Open the inspection form to review the saved checklist without completing a report." },
  { id: "policies", title: "Add or edit a policy", group: "Shared information", page: "Policies", permissions: ["policies.manage"], steps: "Find and open the policy, choose Edit, then Save & view. Add a policy starts a new record.", preview: "Save & view opens the saved reader layout that members use." },
  { id: "box-cards", title: "Add or edit a box card", group: "Shared information", page: "Box Cards", permissions: ["box_cards.manage"], steps: "Choose the department and box card, open Edit, then Save & view. Check response rows and attached information.", preview: "Save & view opens the saved reader layout. Print remains available from the record." },
  { id: "duties", title: "Change recurring station duties", group: "Shared information", page: "Daily Duties", permissions: ["policies.manage"], steps: "Choose the day and duty, select Edit, then approve and save the instructions.", preview: "Close the editor and review the saved day/week duty list." },
  { id: "phones", title: "Update shared phone numbers", group: "Shared information", page: "Phone Numbers", permissions: ["settings.manage"], steps: "Search for a contact and choose Edit, or Add contact. Save the record; Remove requires a separate confirmation.", preview: "Use Preview directory to hide editing controls and review the shared directory layout." },
  { id: "devices", title: "Configure this Respond screen", group: "System", page: "Respond Device Modes", permissions: ["settings.manage"], steps: "Choose this screen’s mode and apparatus, then save. These settings apply to this browser/device.", preview: "Open Respond on this device and confirm its assigned apparatus. Do not send a test emergency call." },
  { id: "cad", title: "Review CAD integration settings", group: "System", page: "CAD Integration", permissions: ["settings.manage"], steps: "Review configuration and use the provided validation controls. Do not paste credentials into shared notes or messages.", preview: "Readiness checks do not prove end-to-end dispatch delivery." },
  { id: "health", title: "Check system health and backups", group: "System", page: "System Health", permissions: ["settings.manage"], steps: "Review current health and backup status. Unavailable checks are not confirmations of success.", preview: "This is a status screen, not an editor for operational records." },
  { id: "departments", title: "Review department workspaces", group: "System", page: "Departments", permissions: ["settings.manage"], steps: "Review existing department memberships. Create department adds a separate workspace; it does not rename or edit the current department.", preview: "A suggested address is not a deployed website. Existing workspace changes require the supported department provisioning process." },
];

export function availableAdminTasks(permissions: readonly string[], pages: readonly PortalPage[]) {
  return adminTasks.filter(task => pages.includes(task.page) && task.permissions.every(permission => permissions.includes(permission)));
}

export function schedulerAdminTask(value: string) {
  return adminTasks.some(task => task.page === "Scheduling" && task.id === value) ? value : "";
}

export function inventoryAdminDestination(value?: string) {
  if (value === "checks" || value === "apparatus") return `/inventory?adminTask=${value}`;
  if (value === "equipment" || value === "service") return `/inventory?adminTask=${value}`;
  return "/inventory";
}
