'use client';
import { useEffect,useState } from 'react';
import { locationAgeLabel,type ApparatusLocation } from './apparatus-location-domain';
import type { LocationView } from './apparatus-location-client';
import { respondingUnitsIncludeUnit } from './respond-device';
import './apparatus-locations.css';
export type LocationModel=LocationView&{refresh:()=>Promise<void>;sender:{status:string;active:boolean;start:(unit:string)=>void;stop:()=>void}};
export default function ApparatusLocationsPanel({model,onLocate,respondingUnits='',onFilter}:{model:LocationModel;onLocate?:(unit:ApparatusLocation)=>void;respondingUnits?:string;onFilter?:(onlyCall:boolean)=>void}){
 const [now,setNow]=useState(Date.now),[onlyCall,setOnlyCall]=useState(false),[all,setAll]=useState(false);
 const [apparatusId,setApparatusId]=useState(''),[deviceName,setDeviceName]=useState(''),[senderKind,setSenderKind]=useState<'browser'|'windows'>('browser');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[setup,setSetup]=useState(''),[savedPair,setSavedPair]=useState<{departmentId:string;deviceId:string;unit:string}|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),5000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const timer=setTimeout(()=>{try{setSavedPair(JSON.parse(localStorage.getItem('stickney-vehicle-pair')||'null'));}catch{setSavedPair(null);}},0);return()=>clearTimeout(timer);},[]);
 const paired=savedPair?.departmentId===model.departmentId&&model.units.some(unit=>unit.deviceId===savedPair.deviceId&&unit.enabled&&unit.senderKind==='browser')?savedPair.unit:'';
 async function manage(action:'pair'|'revoke',id=apparatusId){
  if(!id)return;
  if((action==='revoke'||model.units.some(unit=>unit.apparatusId===id&&unit.enabled))&&!window.confirm(action==='revoke'?'Disable location sharing for this apparatus? Its last position will be labeled last known.':'Replace the current sender? Only this newly paired device will be allowed to send.'))return;
  setBusy(true);setSetup('');setMessage('');
  try{
   const response=await fetch('/api/apparatus-locations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,apparatusId:id,deviceName,senderKind})});const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to save device setup.');
   if(action==='pair'&&senderKind==='browser'){const pair={departmentId:model.departmentId,deviceId:result.deviceId,unit:result.unit};localStorage.setItem('stickney-vehicle-pair',JSON.stringify(pair));setSavedPair(pair);model.sender.start(result.unit);setMessage(`This browser is paired to ${result.unit}.`);}
   else if(result.setup){setSetup(JSON.stringify(result.setup));setMessage('Pairing created. Copy the setup into the Windows companion on the vehicle. This secret is shown only now.');}
   else {model.sender.stop();setMessage('Location sender disabled.');}
   await model.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:'Setup failed.');}finally{setBusy(false);}
 }
 const filtered=model.units.filter(unit=>!onlyCall||respondingUnitsIncludeUnit(respondingUnits,unit.unit));
 const shown=all?filtered:filtered.filter(unit=>unit.deviceId);
 return <section className="apparatus-location-panel" aria-label="Apparatus locations">
  <header><div><h2>Apparatus locations</h2><p>One shared position per vehicle. Select a unit to find it on the map.</p></div><span className={model.connected?'location-connected':'location-disconnected'}>{model.connected?'Shared live connection':'Last known / connecting'}</span></header>
  {model.message&&<p className="location-message" role="status">{model.message}</p>}
  <div className="location-toolbar"><label>Show<select value={onlyCall?'call':'all'} onChange={event=>{const value=event.target.value==='call';setOnlyCall(value);onFilter?.(value);}}><option value="all">All department apparatus</option>{respondingUnits&&<option value="call">Units on this call</option>}</select></label><button type="button" onClick={()=>setAll(value=>!value)}>{all?'Show paired vehicles':`Include unpaired (${model.units.filter(unit=>!unit.deviceId).length})`}</button></div>
  <div className="location-unit-list">{shown.map(unit=><button type="button" key={unit.apparatusId} className={`location-unit ${locationAgeLabel(unit,now,model.connected).startsWith('Updated')?'fresh':'stale'}`} disabled={unit.latitude==null||!onLocate} onClick={()=>onLocate?.(unit)}><strong>{unit.unit}</strong><span>{unit.enabled?(unit.moving?'Moving':'Parked / stationary'):(unit.deviceId?'Tracking disabled':'Not paired')}</span><small>{locationAgeLabel(unit,now,model.connected)}{unit.accuracy!=null?` · ±${Math.round(unit.accuracy)} m`:''}</small></button>)}</div>
  {!shown.length&&<p className="location-empty">{model.units.length?'No paired vehicles in this view. An administrator can connect the mounted device below.':'No vehicle positions available. Incident updates continue separately.'}</p>}
  {paired&&<div className="location-browser-status"><strong>This browser: {paired}</strong><button type="button" onClick={()=>model.sender.active?model.sender.stop():model.sender.start(paired)}>{model.sender.active?'Stop sharing':'Start sharing this vehicle'}</button><p role="status">{model.sender.status}</p><small>Browser sharing requires this page visible. Use Windows tracking when other apps are open. Pair the mounted device—not a personal phone.</small></div>}
  {model.canManage&&<details className="location-setup" onToggle={event=>{if(!event.currentTarget.open)setSetup('');}}><summary>Set up / manage location tracking</summary><p>Choose the vehicle and one sender. Reserves can stay unpaired until needed. Changing a sender does not change call assignments.</p><div className="location-setup-fields"><label>Apparatus<select value={apparatusId} onChange={event=>setApparatusId(event.target.value)}><option value="">Choose apparatus</option>{model.units.map(unit=><option key={unit.apparatusId} value={unit.apparatusId}>{unit.unit} · {unit.name}</option>)}</select></label><label>Device name<input maxLength={60} value={deviceName} onChange={event=>setDeviceName(event.target.value)} placeholder="Engine mounted Surface"/></label><label>Tracking method<select value={senderKind} onChange={event=>setSenderKind(event.target.value as 'browser'|'windows')}><option value="browser">This browser · page must stay visible</option><option value="windows">Windows companion · other apps can stay open</option></select></label></div><div className="location-setup-actions"><button type="button" disabled={busy||!apparatusId||!deviceName.trim()} onClick={()=>void manage('pair')}>{busy?'Saving…':senderKind==='browser'?'Pair this browser and start':'Create Windows pairing'}</button><button type="button" disabled={busy||!apparatusId} onClick={()=>void manage('revoke')}>Disable selected sender</button></div><p role="status">{message}</p>{setup&&<div className="location-secret"><label>One-time Windows setup<textarea readOnly value={setup} spellCheck={false}/></label><button type="button" onClick={()=>void navigator.clipboard.writeText(setup).then(()=>setMessage('Setup copied. Paste it only into the vehicle tracker.')).catch(()=>setMessage('Select and copy the setup text manually.'))}>Copy Windows setup</button></div>}<p><a href="/downloads/StickneyVehicleTracker.cs" download>Windows tracker source</a> · <a href="/downloads/Start-StickneyVehicleTracker.ps1" download>Windows launcher</a></p><p>Save both files in one folder on the vehicle. Run the launcher in Windows PowerShell, paste the setup, then select Start sharing. No automatic installation or startup change is made.</p><small>Windows must stay awake and location access must be allowed. Hardware GPS is not yet verified. Pairings expire after 90 days; replace or disable them here.</small></details>}
 </section>;
}
