'use client';
import { useCallback,useEffect,useState } from 'react';
import type { DocumentState,DocumentVersion } from './document-workflow';
import './document-workflow.css';
type ReceiptReport=Array<{employeeId:string;name:string;acknowledgedAt:string|null}>;
type Workflow={state:DocumentState;versions:DocumentVersion[];acknowledgement:{acknowledgedAt:string}|null;canAcknowledge:boolean;canManage:boolean;acknowledgementReport:ReceiptReport;historicalReports?:Record<string,ReceiptReport>};
export function DocumentWorkflowPanel({id,revision,onChange}:{id:string;revision:string;onChange:()=>Promise<unknown>}) {
  const [data,setData]=useState<Workflow|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[attested,setAttested]=useState(false),[requireAck,setRequireAck]=useState(false),[notice,setNotice]=useState('');
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const response=await fetch('/api/document-workflow?id='+encodeURIComponent(id),{cache:'no-store',signal:signal??AbortSignal.timeout(20000)}),result=await response.json();if(!response.ok)throw Error(result.error||'History unavailable.');if(!signal?.aborted){setData(result);setError('');}}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Unable to read document history.');}finally{if(!signal?.aborted)setLoading(false);}},[id]);
  useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(()=>void load(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort();};},[load,revision]);
  async function act(action:string) {
    if(!data||busy||loading||error)return;
    if(action==='archive'&&!window.confirm('Archive this document? Published versions and acknowledgements will remain available to document managers.'))return;
    setBusy(true);setNotice('');
    try {const response=await fetch('/api/document-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,revision:data.state.revision,version:data.state.publishedVersion,attested,requiresAcknowledgement:requireAck}),signal:AbortSignal.timeout(20000)}),result=await response.json();if(!response.ok)throw Error(result.error||'Save not confirmed.');setAttested(false);await load();await onChange();setNotice(action==='acknowledge'?'Your acknowledgement is saved for this published version.':action==='publish'?'Reviewed draft published as a new version.':'Archive status saved. History is retained.');}
    catch(e){setError(e instanceof Error?e.message:'The save was not confirmed. Reload and retry.');}finally{setBusy(false);}
  }
  const current=data?.versions.find(version=>version.id===data.state.publishedVersion);
  return <section className="document-workflow" aria-label="Document versions and acknowledgements"><h3>Versions & acknowledgements</h3>
    {loading&&<p role="status">Loading saved version details…</p>}{error&&<p role="alert">{error} <button disabled={busy} onClick={()=>void load()}>Reload version details</button></p>}{notice&&<p role="status">{notice}</p>}
    {data&&<>
      <p>{data.state.archived?'Archived document':current?`Published version ${current.number} · ${current.content.documentType}`:data.state.draft&&!data.versions.length?'Unpublished document draft':'Legacy content · no publication receipt recorded'}{current?` · ${new Date(current.publishedAt).toLocaleString()}`:''}</p>
      {current?.content.sourceUrl&&<a href={current.content.sourceUrl} target="_blank" rel="noreferrer">Open published reference ↗</a>}
      {current?.requiresAcknowledgement&&<div className="document-ack"><p>{data.acknowledgement?`You acknowledged this version on ${new Date(data.acknowledgement.acknowledgedAt).toLocaleString()}.`:'This published version requires a separate acknowledgement. An earlier version’s receipt does not carry over.'}</p>{!data.acknowledgement&&data.canAcknowledge&&<><label><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)} disabled={busy||loading||Boolean(error)}/>I have read this published version and acknowledge receipt.</label><button disabled={!attested||busy||loading||Boolean(error)} onClick={()=>void act('acknowledge')}>Acknowledge version {current.number}</button></>}{!data.canAcknowledge&&!data.acknowledgement&&<p>Your verified member record is not assigned to acknowledge this version.</p>}</div>}
      {data.canManage&&<>
        {data.state.draft&&<details><summary>Review unpublished draft</summary><dl><dt>Name</dt><dd>{data.state.draft.title}</dd><dt>Type / effective date</dt><dd>{data.state.draft.documentType} · {data.state.draft.effectiveDate||'Date needed'}</dd></dl><pre>{data.state.draft.body||'Reference-only draft'}</pre>{data.state.draft.sourceUrl&&<a href={data.state.draft.sourceUrl} target="_blank" rel="noreferrer">Open draft reference ↗</a>}<label><input type="checkbox" checked={requireAck} onChange={e=>setRequireAck(e.target.checked)} disabled={busy||loading||Boolean(error)}/>Require acknowledgements from active members for this new version</label><p>Publishing preserves earlier versions and receipts. No employee email or push is sent.</p><button disabled={busy||loading||Boolean(error)||data.state.archived} onClick={()=>void act('publish')}>Publish reviewed draft</button></details>}
        <button disabled={busy||loading||Boolean(error)} onClick={()=>void act(data.state.archived?'restore':'archive')}>{data.state.archived?'Restore document':'Archive document'}</button>
        {current?.requiresAcknowledgement&&<details><summary>Acknowledgement report · {data.acknowledgementReport.filter(person=>person.acknowledgedAt).length}/{data.acknowledgementReport.length}</summary><p>Assigned active roster captured when this version was published. A receipt records acknowledgement, not competency or policy compliance.</p><ul>{data.acknowledgementReport.map(person=><li key={person.employeeId}><strong>{person.name}</strong><span>{person.acknowledgedAt?new Date(person.acknowledgedAt).toLocaleString():'Not acknowledged'}</span></li>)}</ul></details>}
      </>}
      <details><summary>Preserved version history · {data.versions.length}</summary>{!data.versions.length&&<p>Content snapshots begin with the first draft saved in this workflow. Older action-only audit entries cannot reconstruct earlier text.</p>}{data.versions.map(version=><details key={version.id}><summary>{version.legacy?'Legacy content snapshot':`Published version ${version.number}`} · {version.content.title}</summary><p>{version.content.documentType} · Effective {version.content.effectiveDate||'not recorded'}</p><pre>{version.content.body||'Reference-only document'}</pre>{version.content.sourceUrl&&<a href={version.content.sourceUrl} target="_blank" rel="noreferrer">Open saved reference ↗</a>}{data.canManage&&data.historicalReports?.[version.id]&&<><h4>Receipts for this version</h4><ul>{data.historicalReports[version.id].map(person=><li key={person.employeeId}><strong>{person.name}</strong><span>{person.acknowledgedAt?new Date(person.acknowledgedAt).toLocaleString():'Not acknowledged'}</span></li>)}</ul></>}</details>)}</details>
    </>}
  </section>;
}
