"use client";

import { departmentHolidays } from "./holidays";

export default function HolidayPolicy() {
  const year = new Date().getFullYear();
  const holidays = departmentHolidays(year);
  return <section className="holiday-policy-page">
    <div className="policy-hero"><div className="policy-title"><span className="page-icon" aria-hidden="true">★</span><div><p className="eyebrow">Stickney Fire Department</p><h2>Holiday Sign-Up Policy</h2><p>A clear working guide for holiday preferences, assignments, coverage, and payroll.</p></div></div><div className="policy-limit"><strong>3</strong><span>Maximum approved holiday shifts per member</span></div></div>
    <div className="policy-layout">
      <article className="content-card policy-main"><div className="policy-section"><span className="policy-step">1</span><div><h3>Submit holiday preferences</h3><p>Select the holiday shifts you want to work. Each holiday is divided into morning, afternoon, and night shifts when applicable.</p></div></div><div className="policy-section"><span className="policy-step">2</span><div><h3>Eligibility and order</h3><p>Officers and firefighters sign up during the eligibility window assigned to their service group. Sign-ups are timestamped and handled first-come, first-served while maintaining required officer coverage.</p></div></div><div className="policy-section"><span className="policy-step">3</span><div><h3>Assignment limit</h3><p>A member may be approved to work no more than three holiday shifts. A morning, afternoon, or night assignment counts as one shift.</p></div></div><div className="policy-section"><span className="policy-step">4</span><div><h3>Unfilled holiday shifts</h3><p>Two weeks before a holiday, remaining vacancies may be filled by random drawing from eligible members who have not fulfilled the holiday requirement.</p></div></div><div className="policy-section"><span className="policy-step">5</span><div><h3>Changes and credit</h3><p>Use the Shift Swap process when requesting relief from an assigned holiday. Holiday credit and holiday pay go only to the employee who actually works the shift.</p></div></div></article>
      <aside className="content-card policy-pay"><h3>Holiday payroll rules</h3><div className="pay-rule"><span>Holiday staffing</span><strong>Paid at the configured Holiday Rate</strong></div><div className="pay-rule"><span>Acting Officer</span><strong>Holiday rate plus eligible AO premium</strong></div><div className="pay-rule dpw"><span>DPW assignments</span><strong>Remain at 1.5× base pay</strong><p>No extra overtime or holiday pay is added. The Acting Officer premium still applies when the employee is designated AO.</p></div></aside>
    </div>
    <article className="content-card holiday-calendar"><div className="section-header"><div><h2>{year} Approved Holidays</h2><p>These dates automatically activate the holiday banner and payroll rule in the Daily Log.</p></div></div><div className="holiday-grid">{holidays.map((holiday) => <div className="holiday-item" key={holiday.date}><time dateTime={holiday.date}>{new Date(`${holiday.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</time><div><strong>{holiday.name}</strong>{holiday.note && <span>{holiday.note}</span>}</div></div>)}</div></article>
    <p className="policy-source-note">This page is a clean operational summary of the posted Holiday Sign-Up Procedure. The signed department policy controls if a conflict is discovered.</p>
  </section>;
}
