export const apparatus1204Compartments=["Cab","Pump / Booster Tank","SCBA","Compartment 1 (EMS)","Compartment 2","Engineer's Panel (Compartment 3)","Compartment 4","Compartment 5","Compartment 6","Compartment 7 (Rear)","Compartment 8 (Rear)","Compartment 9 (Rear)","Rear Hose","Compartment 10","Compartment 11","Compartment 12","Compartment 13"] as const;
type ImportedItem={compartment:string;name:string;quantity?:number;category?:string};
const items=(compartment:string,names:string[],category="Apparatus equipment"):ImportedItem[]=>names.map((name)=>{const match=name.match(/\((\d+)\)$/);return{compartment,name,quantity:match?Number(match[1]):1,category};});
export const apparatus1204Equipment:ImportedItem[]=[
 ...items("Cab",["Door opener","Nitrile / latex gloves","Knox Box keys","Cooler with water and ice","5-gas meter","Fuel card and PIN","Portable radio (4)","Box light (3)","Hi-vis safety vest (4)","Thermal imaging camera (TIC)","SCBA harness (4)","RIT bag with 4500 PSI cylinder","Officer's clipboard"]),
 ...items("SCBA",["Officer SCBA harness and cylinder","Engineer SCBA harness and cylinder","Rear SCBA harness and cylinder 1","Rear SCBA harness and cylinder 2","Rear SCBA harness and cylinder 3","Driver torpedo cylinder 1","Driver torpedo cylinder 2","Officer torpedo cylinder 1","Officer torpedo cylinder 2","Officer torpedo cylinder 3","Officer torpedo cylinder 4"],"SCBA"),
 ...items("Compartment 1 (EMS)",["Yellow scene tape","Red scene tape","Jump bag - oxygen","Jump bag - pediatric key","Jump bag - blood pressure cuff with stethoscope","Jump bag - pulse oximeter","Jump bag - adult BVM","Jump bag - non-rebreather mask","Jump bag - nasal cannulas","AED pads (2)","AED spare battery"],"EMS"),
 ...items("Compartment 2",["A-frame ladder with foot extension and tray attachment","Preconnected crosslay - 2.5-inch with nozzle","Preconnected crosslay - 1.75-inch fog","Preconnected crosslay - 1.75-inch smooth bore"]),
 ...items("Engineer's Panel (Compartment 3)",["Hydrant wrench","Spanners"]),
 ...items("Compartment 4",["Hydra-Shield hydrant wrench - silver","Custodian hydrant wrench - red","Electric PPV fan","Wheel chock (3)","50-foot 2.5-inch hose","Appliance - cellar nozzle","Appliance - foam eductor","Appliance - 2.5-inch to 1.5-inch Wye","Appliance - 4-inch female to Storz","Appliance - 5-inch female to Storz","Appliance - 5-inch female to 4-inch male","Blitz Force gun","Master fog nozzle","2.5-inch double female (2)","2.5-inch double male (2)","2.5-inch to 1.5-inch reducer (2)","2.5-inch female to Storz elbow","4-inch Storz to 2.5-inch male","Hydrant bag - hydrant wrench","Hydrant bag - spanner (2)","Hydrant bag - 2.5-inch to 1.5-inch reducer","Hydrant bag - gate valve"]),
 ...items("Compartment 5",["High-rise pack - 100-foot 2.5-inch hose","High-rise pack - 100-foot 1.75-inch hose","High-rise pack - 2.5-inch smooth bore","High-rise pack - orange strap (6)","High-rise bag - 2.5-inch to 1.5-inch reducer","High-rise bag - spanner wrench (2)","High-rise bag - in-line pressure gauge","High-rise bag - pipe wrench","High-rise bag - rope hose tool","High-rise bag - 2.5-inch gate valve","High-rise bag - 1.75-inch smooth bore","RIT bag - 60-minute cylinder","RIT bag - medium facepiece","RIT bag - webbing","RASP bag"]),
 ...items("Compartment 6",["50:1 fuel can (2)","Metal-blade Partner saw","Wood Warthog Partner saw","Stihl utility saw","Truckman vent saw","Saw tool box - spare belts","Saw tool box - wrench"],"Power tool"),
 ...items("Compartment 7 (Rear)",["16-foot roof ladder (2)","24-foot extension ladder","8-foot New York multi hook (2)"],"Ground ladder / long tool"),
 ...items("Compartment 8 (Rear)",["Rope rescue bag (2)","300-foot life-safety rope","Bag of webbing","Harness (2)"],"Rope rescue"),
 ...items("Compartment 9 (Rear)",["35-foot extension ladder","Attic / scuttle-hole ladder","10-foot pike pole","12-foot pike pole","7-foot pike pole","6-foot Eck hook"],"Ground ladder / long tool"),
 ...items("Rear Hose",["2.5-inch skid load with rope hose tools and playpipe","4-inch LDH"],"Hose load"),
 ...items("Compartment 10",["Three-bank Milwaukee battery charger with batteries","Grinder / cutter with spare battery","Bag with glass cutter and Sawzall with spare battery","Box of electrical whips / pigtails","Ratcheting strap (2)","Ram brace","Hardwire battery adapter for Genesis E-tools","Case of E-tool tips","Genesis E-tool spreader","Genesis E-tool cutter","Genesis E-tool ram"],"Rescue tool"),
 ...items("Compartment 11",["8-pound pick-head axe","Maul","Sledge hammer","Large bolt cutters","Small bolt cutters","Halligan bar","K-Tool bag - K-Tool","K-Tool bag - wedge","K-Tool bag - elevator key","K-Tool bag - needle-nose pliers","K-Tool bag - screwdriver","K-Tool bag - keys","K-Tool bag - electrical fuse puller"]),
 ...items("Compartment 12",["Dry chemical extinguisher","CO2 extinguisher","Class K extinguisher","Kodiak rescue struts","Rabbit Tool with rubber mallet","Ratchet straps"],"Rescue / extinguisher"),
 ...items("Compartment 13",["Wood cribbing","Wedges","Step chock (2)","Airbag control unit in case","Protective pad for airbags","Airbag (5)"],"Rescue tool"),
];
export const apparatus1204VehicleChecks=["Parking brake operational","Emergency lights operational","Transmission fluid in range - engine running","Fuel at least three-quarters","Engine oil in range","DEF level at least one-half","Wheel and tire condition acceptable","Air horn operational","Vehicle horn operational","Siren operational","Headlights, brake lights and turn signals operational","Outrigger stabilizers and aerial operational","Front-left tire pressure","Front-right tire pressure","Rear-left inner tire pressure","Rear-left outer tire pressure","Rear-right inner tire pressure","Rear-right outer tire pressure","Pump / booster tank water level","Pump hours","Exercise primer, pressure governor and circulate water","Vehicle enters pump and recirculates water","Run and operate all power tools / E-tools","Visually check all other hose, tools and equipment","Exercise all engineer-panel levers and drains","Exercise engineer-panel primer","Check chainsaw bar and chain oil","Check fuel level in all saws"] as const;
