export const apparatus1203Compartments = [
  "Cab", "Cab Cabinet", "Glove Box", "Pump / Booster Tank", "SCBA", "Driver Side Step",
  "Compartment 1 (Top)", "Compartment 1 (Bottom)", "Compartment 2", "Driver's Side Drawer",
  "Compartment 3", "Driver's Side", "Compartment 4", "Rear Compartment", "Compartment 5",
  "Compartment 6", "Officer's Side Drawer", "Compartment 7", "Officer's Side", "Officer's Side Step",
  "Top of Engine", "Hose",
] as const;

type ImportedItem={compartment:string;name:string;quantity?:number;category?:string};
const items=(compartment:string,names:string[],category="Apparatus equipment"):ImportedItem[]=>names.map((name)=>{
  const match=name.match(/\((\d+)\)$/); return {compartment,name,quantity:match?Number(match[1]):1,category};
});

export const apparatus1203Equipment:ImportedItem[]=[
 ...items("Cab",["Door opener","Box of N95 masks","5-gas meter","Thermal imaging camera (TIC)","Portable radio (4)","TIC SCBA mask","Yellow case - cell phone and GPS with cord","Fuel card and PIN","SCBA harness (4)","Knox Box keys","Hi-vis safety vest (5)","Cooler with water","Forest View / Lyons map","Gloves - various sizes","Box light (4)","LVAD papers","Officer's clipboard"]),
 ...items("Cab Cabinet",["Bag of surgical masks (5)","AED","EMS bag","EMS bag oxygen cylinder","Sensit meter","Puncture / leak kit","Rescue disc","PPE bag - N95, surgical mask and gown (12)","Camera and cable in case","Binoculars (2)","Barrier tape","Lockout/tagout kit","Geiger meter","Passport board","Dish soap","Duct tape","School maps","Pre-plan book","Box Card binder","Pet oxygen masks","Hand sanitizer","RIT bag - 60 minute SCBA bottle","RIT bag - UAC hose","RIT bag - spare SCBA mask","RIT bag - hose with regulator","RIT bag - 75 ft rope with pulley and carabiners (2)","RIT bag - male adapter","RIT bag - wire cutters","RIT bag - handcuff webbing with carabiner (2)","RIT bag - red lock with keys (2)","RIT bag - lock hasp (2)","RIT bag - 2 ft chain","RIT bag - lockout tags","RIT bag - markers (2)","RIT bag - shove knife","RIT bag - wedges (2)","Black Pelican case - TIFF meter","Black Pelican case - CO detector (2)","Black Pelican case - 9V battery (2)","Black Pelican case - RAD Alert","Black Pelican case - Smart M-8 nerve agent ID badge (4)","Black Pelican case - Smart M-8 chemical agent badge (4)"]),
 ...items("Glove Box",["ERG book","Knox key wrench","Accident envelope","Insurance card","Goggles (4)","Fuse puller","Haz-Mat Guide for First Responders","K-Tool bag - K-Tool","K-Tool bag - door chocks (2)","K-Tool bag - needle-nose pliers","K-Tool bag - lineman pliers","K-Tool bag - shove knife","K-Tool bag - putty knife","K-Tool bag - butter knife","K-Tool bag - mini crowbar","K-Tool bag - Allen wrench","K-Tool bag - elevator drop key","K-Tool bag - half-moon drop key (4)"]),
 ...items("SCBA",["Officer SCBA harness and cylinder","Engineer SCBA harness and cylinder","Rear SCBA harness and cylinder 1","Rear SCBA harness and cylinder 2","Rear SCBA harness and cylinder 3","Driver torpedo front 30-minute bottle","Driver torpedo rear 30-minute bottle","Officer torpedo front 60-minute bottle","Officer torpedo rear 60-minute bottle","Compartment 3 spare cylinder 1","Compartment 3 spare cylinder 2","Compartment 3 spare cylinder 3"],"SCBA"),
 ...items("Driver Side Step",["Roll of 5-inch hose","Hose roller","Hose clamp","Ice melt","BioSolve","Dish soap"]),
 ...items("Compartment 1 (Top)",["TFT nozzle with 2.5-inch adapter","2.5-inch foam nozzle","Master stream fog nozzle","2.5-inch MacNeal adapter (2)","2.5-inch to 1.5-inch reducer","Storz to 2.5-inch elbow","Storz to 2.5-inch male","Storz to 4.5-inch female (2)","Storz to 4.5-inch male","4-inch to 5-inch Storz","Storz to 4-inch female - Berwyn/Cicero","Double male","Double female","Wye","2.5-inch distributor nozzle","Towel","Foam eductor - handheld","Foam eductor - onboard","CST tool","Spanner (2)","Hard-suction spanner","Storz spanner (2)","Hydrant wrench (2)","Barrier tape","Hose chart","Hose jacket","Hose air fittings with caps","Siamese","Rubber mallet","1.75-inch fog nozzle","Hose edge roller","Bowling pin"]),
 ...items("Compartment 1 (Bottom)",["Chicago custodian and cross wrench","Tool box - sprinkler stops (4)","Tool box - claw hammer","Tool box - flat screwdriver (3)","Tool box - Phillips screwdriver (3)","Tool box - electrical tape (2)","Tool box - crescent wrench (2)","Tool box - pipe wrench (2)","Tool box - channel locks","Tool box - cable cutters","Tool box - cable ties","Tool box - tape measure","Tool box - electric meter lug","Tool box - hacksaw with blades","Tool box - 21-piece socket set","Tool box - box wrenches (7)","Tool box - Wonder Bar","Tool box - bag of nails","Tool box - box cutter with blades","Tool box - outlet tester","Tool box - butter knife (2)","Tool box - spare gaskets","Hydrant bag - rubber mallet","Hydrant bag - hydrant wrench","Hydrant bag - spanner (2)","Hydrant bag - Storz spanner","Hydrant bag - 2.5-inch gate valve","Hydrant bag - 4.5-inch female to Storz","Hydrant bag - double male","Hydrant bag - double female","Hydrant bag - 4.5-inch female to 4-inch male - Berwyn/Cicero"]),
 ...items("Compartment 2",["K extinguisher","Dry chemical extinguisher","CO2 extinguisher","Pressurized water extinguisher","Empty pump can"],"Extinguisher"),
 ...items("Driver's Side Drawer",["Hose chart","Cheater bar","Hose jacket","Towel","Flare","Rope hose tool","Roll of fire tape","Hard-suction spanner","CST tool","Foam eductor"]),
 ...items("Compartment 3",["Engineer SCBA pack","Flood light (2)","Cribbing","Post cover (4)","Plastic step chock (2)","Wooden step chock (2)","Kodiak struts","Vehicle lockout kit","Box of pigtails","Empty oil-dry bucket","Smoke ejector","Hanger bracket","Wheel chock"]),
 ...items("Driver's Side",["Spare 30-minute bottle (3)","Wheel chock","Oil-dry bin"]),
 ...items("Compartment 4",["Can of straight gas","Can of mixed fuel (2)","Funnel (2)","Rescue / vent saw","Stihl utility saw","Saw tool box"]),
 ...items("Rear Compartment",["24-foot extension ladder","14-foot roof ladder","10-foot attic ladder","6-foot pike pole","10-foot pike pole","6-foot New York hook (2)","Stokes basket"],"Ground ladder / long tool"),
 ...items("Compartment 5",["Hilti saw","Ram brace","Ram ammunition case of chains","Marrying straps (2)","Genesis E-tool spreader","Genesis E-tool cutter","Genesis E-tool ram","Genesis E-tool AC adapter","Genesis E-tool case with tips","Red Pelican case - glass cutter","Red Pelican case - spare battery (2)","Red Pelican case - handle","Glass Master with center punch","Airbag control unit","Hood release tool","Air bag (2)","Rubber air-bag pad (2)"],"Rescue tool"),
 ...items("Compartment 6",["Pick-head axe","Maul","Set of irons","A tool","Closet hook","Pinned Halligan"]),
 ...items("Officer's Side Drawer",["Bolt cutters","Sledge","Crow bar (2)","Hay hook (2)","Pry bar"]),
 ...items("Compartment 7",["Front intake manual-override wrench","RASP bag","Bag of water-rescue rope","150-foot life-safety rope","150-foot utility rope","100-foot 2.5-inch hose with stacked tip","100-foot 1.75-inch hose with 7/8-inch smooth bore","Hi-rise bag - spanner","Hi-rise bag - Storz spanner","Hi-rise bag - rope hose tool","Hi-rise bag - wheel wrench","Hi-rise bag - inline pressure gauge","Hi-rise bag - fog nozzle"]),
 ...items("Officer's Side",["Air bag (2)","Spare 60-minute bottle (2)","Spare 30-minute bottle (2)"]),
 ...items("Officer's Side Step",["Roll of 5-inch hose","Tarp (2)"]),
 ...items("Top of Engine",["Coal shovel","Spade shovel (2)","Flat shovel","Push broom (2)","Fire broom (3)","5-gallon bucket AFFF (6)","Traffic cone (6)","Ground monitor base"]),
 ...items("Hose",["1.75-inch fog preconnect","1.75-inch smooth-bore preconnect","2.5-inch preconnect","Hi-rise load","Front bumper supply","Front bumper preconnect","Lead line","Skid load","LDH supply - rear"],"Hose load"),
];

export const apparatus1203VehicleChecks=[
 "Emergency lights operational","Transmission fluid in range - engine running","Fuel at least three-quarters","Antifreeze / radiator level in range","Air horn operational","Engine oil in range","Vehicle horn operational","Body condition acceptable","Siren operational","Wheel and tire condition acceptable","Parking brake operational","Headlights, brake lights and turn signals operational","Generator fluid level over one-half","PTO generator, junction boxes and brow lights operational","Front-left tire pressure","Front-right tire pressure","Rear-left inner tire pressure","Rear-left outer tire pressure","Rear-right inner tire pressure","Rear-right outer tire pressure","Pump / booster tank water level","Exercise primer / circulate water","Vehicle enters pump and recirculates water",
] as const;
