"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { formatEmployeeName } from "./employee-names";
import { formatMilitaryTime } from "./military-time";
import ChiefBoardPanel from "./chief-board-panel";

type BoardData = { asOf: string; currentShift: string; onDuty: Array<{ employeeId: string; name: string; rank: string; timeIn: string; timeOut: string; actingOfficer: number }>; officerInCharge: string | null; staffing: { filled: number; required: number; complete: boolean }; equipmentIssues: Array<{ item: string; status: string; detail: string }>; activeCalls: Array<{ reportNumber: string; timeOut: string; respondingUnits: string; address: string; callType: string }>; apparatus: Array<{ unit: string; status: string }>; error?: string };
type CurrentDuty = { dayOfWeek: number; shiftKey: "morning" | "afternoon" | "night"; duty: string };
type CloseCallReport = { title: string; url: string; publishedAt: string; excerpt: string };
type Rotation = "equipment" | "duty" | "news";
const rotationOrder: Rotation[] = ["equipment", "duty", "news"];
const displayName = formatEmployeeName;
const shiftLabel = (value: string) => value === "morning" ? "6:00 AM – Noon" : value === "afternoon" ? "Noon – 6:00 PM" : "6:00 PM – 6:00 AM";
function nextShift(now: Date) { const local = new Date(now.toLocaleString("en-US", { timeZone: "America/Chicago" })); const minutes = local.getHours() * 60 + local.getMinutes(); const target = minutes < 360 ? 360 : minutes < 720 ? 720 : minutes < 1080 ? 1080 : 1800; const remaining = target - minutes; return { label: target === 360 ? "6:00 AM" : target === 720 ? "Noon" : "6:00 PM", remaining: `${Math.floor(remaining / 60)}h ${remaining % 60}m` }; }

export default function OperationsBoard() {
  const [data, setData] = useState<BoardData | null>(null), [currentDuty, setCurrentDuty] = useState<CurrentDuty | null>(null), [news, setNews] = useState<CloseCallReport[]>([]), [error, setError] = useState(""), [clock, setClock] = useState(new Date()), [rotation, setRotation] = useState<Rotation>("equipment");
  const load = useCallback(async () => { const [dashboardResponse, dutiesResponse, newsResponse] = await Promise.all([fetch("/api/dashboard"), fetch("/api/daily-duties"), fetch("/api/close-call-news")]); const result = await dashboardResponse.json() as BoardData; const duties = await dutiesResponse.json() as { currentDuty?: CurrentDuty | null }; const reports = await newsResponse.json() as { items?: CloseCallReport[] }; if (dashboardResponse.ok) { setData(result); setError(""); } else setError(result.error || "Unable to load live operations"); if (dutiesResponse.ok) setCurrentDuty(duties.currentDuty ?? null); if (newsResponse.ok) setNews(reports.items ?? []); }, []);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const refresh = window.setInterval(() => void load(), 30000); const ticker = window.setInterval(() => setClock(new Date()), 1000); const rotate = window.setInterval(() => setRotation((current) => rotationOrder[(rotationOrder.indexOf(current) + 1) % rotationOrder.length]), 12000); return () => { window.clearTimeout(initial); window.clearInterval(refresh); window.clearInterval(ticker); window.clearInterval(rotate); }; }, [load]);
  const next = useMemo(() => nextShift(clock), [clock]);
  const activeCall = data?.activeCalls[0];
  return <section className="operations-board">
    <header className="board-header"><div><p>Stickney Fire Department</p><h1>Live Operations Board</h1><span>{data ? shiftLabel(data.currentShift) : "Loading current shift…"}</span></div><div className="board-clock"><strong>{clock.toLocaleTimeString("en-US", { timeZone: "America/Chicago", hour: "numeric", minute: "2-digit", second: "2-digit" })}</strong><span>{clock.toLocaleDateString("en-US", { timeZone: "America/Chicago", weekday: "long", month: "long", day: "numeric" })}</span><small><i/> Live · refreshes every 30 seconds</small></div></header>
    {error && <div className="board-alert">{error}<button onClick={() => void load()}>Retry</button></div>}
    <div className="board-summary"><article className={data?.staffing.complete ? "clear" : "warning"}><span>Staffing</span><strong>{data?.staffing.filled ?? "—"} / {data?.staffing.required ?? 4}</strong><small>{data?.staffing.complete ? "Complete" : "Coverage needs attention"}</small></article><article className={data?.officerInCharge ? "clear" : "warning"}><span>Officer in charge</span><strong>{data?.officerInCharge ? displayName(data.officerInCharge) : "Not signed in"}</strong><small>Current shift command</small></article><article className={`active-call-summary ${activeCall ? "active" : "clear"}`}><span>{data?.activeCalls.length ? `Active call${data.activeCalls.length > 1 ? ` · ${data.activeCalls.length} total` : ""}` : "Active call"}</span>{activeCall ? <><strong>{activeCall.callType}</strong><b>{activeCall.address || "Address not entered"}</b><small>{activeCall.respondingUnits || "Units pending"} · {activeCall.timeOut ? formatMilitaryTime(activeCall.timeOut) : "Time pending"}</small></> : <><strong>None</strong><small>No open calls</small></>}</article><article><span>Next shift change</span><strong>{next.label}</strong><small>In {next.remaining}</small></article></div>
    <div className="board-grid redesigned"><ChiefBoardPanel />
      <section className="board-panel staffing"><header><h2>Current staffing</h2><span>{data?.onDuty.length ?? 0} members</span></header><div>{data?.onDuty.length ? data.onDuty.map((person) => <article key={person.employeeId}><b>{displayName(person.name)}</b><span>{person.rank}{person.actingOfficer ? " · Acting Officer" : ""}</span><time>{person.timeIn} – {person.timeOut}</time></article>) : <p className="board-empty">No staffing entered for this shift.</p>}</div></section>
      <section className={`board-panel equipment rotating-panel ${rotation}`} aria-live="polite"><header><h2>{rotation === "equipment" ? "Equipment issues" : rotation === "duty" ? "Current daily duty" : "Firefighter Close Calls"}</h2><span>{rotation === "equipment" ? `${data?.equipmentIssues.length ?? 0} reported` : rotation === "duty" ? `${clock.toLocaleDateString("en-US", { timeZone: "America/Chicago", weekday: "long" })} · ${shiftLabel(currentDuty?.shiftKey ?? data?.currentShift ?? "night")}` : "Latest 3 reports"}</span></header><div className="rotation-content">{rotation === "equipment" ? data?.equipmentIssues.length ? data.equipmentIssues.map((issue) => <article key={issue.item}><b>{issue.item}</b><strong>{issue.status}</strong><p>{issue.detail || "No details entered"}</p></article>) : <p className="board-empty clear">✓ No equipment issues reported</p> : rotation === "duty" ? currentDuty ? <article className="current-duty-card"><span>NOW</span><b>{currentDuty.shiftKey[0].toUpperCase() + currentDuty.shiftKey.slice(1)} duty</b><p>{currentDuty.duty}</p></article> : <p className="board-empty">No duty is entered for the current shift.</p> : news.length ? <div className="close-call-list">{news.map((report) => <a href={report.url} target="_blank" rel="noreferrer" key={report.url}><time>{new Date(report.publishedAt).toLocaleDateString("en-US", { timeZone: "America/Chicago", month: "short", day: "numeric" })}</time><strong>{report.title}</strong><span>Open report ↗</span></a>)}</div> : <p className="board-empty">Latest reports are temporarily unavailable.</p>}</div><footer className="rotation-indicator"><button className={rotation === "equipment" ? "active" : ""} aria-label="Show equipment issues" onClick={() => setRotation("equipment")}/><button className={rotation === "duty" ? "active" : ""} aria-label="Show current daily duty" onClick={() => setRotation("duty")}/><button className={rotation === "news" ? "active" : ""} aria-label="Show Firefighter Close Calls reports" onClick={() => setRotation("news")}/><span>Rotates every 12 seconds</span></footer></section></div>
    <section className="board-panel apparatus apparatus-wide"><header><h2>Apparatus status</h2><span>From active calls</span></header><div>{data?.apparatus.map((unit) => <article className={unit.status === "Committed to call" ? "committed" : "unknown"} key={unit.unit}><b>Unit {unit.unit}</b><span>{unit.status}</span></article>)}</div><p className="board-source-note">Availability is not assumed. Units only show “Committed” when listed on an active call.</p></section>
  </section>;
}
