export type ImportedBuildingSeed = { sourceRow: number; address: string; businessName: string };

export const importedBuildingSource = "coopy buildings.xlsx";

export const importedBuildingSeeds: ImportedBuildingSeed[] = [
  {sourceRow:5,address:"3501 Laramie",businessName:"HRT"},
  {sourceRow:6,address:"3502 Laramie",businessName:"Racino Temp"},
  {sourceRow:7,address:"3503 Laramie",businessName:"Stables"},
  {sourceRow:8,address:"3720 Cicero",businessName:"Esmaralda TruckinG (Unit 3)"},
  {sourceRow:9,address:"3738 Cicero",businessName:"Truck Quest"},
  {sourceRow:10,address:"3740 Cicero",businessName:"Casa Mateo"},
  {sourceRow:11,address:"3756 Cicero",businessName:"National Construction rental"},
  {sourceRow:12,address:"3800 Cicero",businessName:"Lennys Gas N wash"},
  {sourceRow:13,address:"3815 Laramie",businessName:"Waste managment"},
  {sourceRow:14,address:"3900 Cicero",businessName:"Motion industries"},
  {sourceRow:15,address:"3900 Laramie",businessName:"Koppers"},
  {sourceRow:16,address:"3901 Harlem",businessName:"Shell Gas station"},
  {sourceRow:17,address:"3903 Oak Park (A)",businessName:"Latino Services"},
  {sourceRow:18,address:"3903 Oak Park (B)",businessName:"Great Homes Real Estate"},
  {sourceRow:19,address:"3904 Gunderson",businessName:"Ante Debs"},
  {sourceRow:20,address:"3905 Oak Park",businessName:"Studio Gallery"},
  {sourceRow:21,address:"3906 Gunderson",businessName:"Unibrow Unstics"},
  {sourceRow:22,address:"3908 Gunderson",businessName:"Xelhua Beauty Spa"},
  {sourceRow:23,address:"4001 Harlem",businessName:"US Bank"},
  {sourceRow:24,address:"4100 Scoville",businessName:"Edison School"},
  {sourceRow:25,address:"4101 Oak Park",businessName:"Mt Auburn Cemetry"},
  {sourceRow:26,address:"4101A Oak Park",businessName:"Mt Auburn Funeral home"},
  {sourceRow:27,address:"4108 Oak Park",businessName:"Kindgom Hall"},
  {sourceRow:28,address:"4109 Harlem",businessName:"Oceeano Azul"},
  {sourceRow:29,address:"4119 Harlem",businessName:"4119 Harlem"},
  {sourceRow:30,address:"4121 Harlem",businessName:"4121 Harlem"},
  {sourceRow:31,address:"4127 Harlem",businessName:"4127 Harlem"},
  {sourceRow:32,address:"4133 Harlem",businessName:"4133 Harlem"},
  {sourceRow:33,address:"4139 Harlem",businessName:"4139 Harlem"},
  {sourceRow:34,address:"4143 Harlem",businessName:"4143 Harlem"},
  {sourceRow:35,address:"4201 Harlem",businessName:"4201 Harlem"},
  {sourceRow:36,address:"4205 Clinton",businessName:"Seguin Home"},
  {sourceRow:37,address:"4205 Harlem",businessName:"4205 Harlem"},
  {sourceRow:38,address:"4207 Harlem",businessName:"4207 Harlem"},
  {sourceRow:39,address:"4209 Harlem",businessName:"4209 Harlem"},
  {sourceRow:40,address:"4211 Harlem",businessName:"4211 Harlem"},
  {sourceRow:41,address:"4215 Harlem",businessName:"4215 Harlem"},
  {sourceRow:42,address:"4217 Harlem",businessName:"4217 Harlem"},
  {sourceRow:43,address:"4219 Harlem",businessName:"4219 Harlem"},
  {sourceRow:44,address:"4221 Harlem",businessName:"4221 Harlem"},
  {sourceRow:45,address:"4227 Harlem",businessName:"4227 Harlem"},
  {sourceRow:46,address:"4231 Harlem",businessName:"4231 Harlem"},
  {sourceRow:47,address:"4235 Elmwood",businessName:"Seguin Home"},
  {sourceRow:48,address:"4235 Harlem",businessName:"4235 Harlem"},
  {sourceRow:49,address:"4301 Harlem",businessName:"4301 Harlem"},
  {sourceRow:50,address:"4303 Harlem",businessName:"4303 Harlem"},
  {sourceRow:51,address:"4305 Harlem",businessName:"4305 Harlem"},
  {sourceRow:52,address:"4307 Harlem",businessName:"4307 Harlem"},
  {sourceRow:53,address:"4309 Harlem",businessName:"4309 Harlem"},
  {sourceRow:54,address:"4311 Harlem",businessName:"4311 Harlem"},
  {sourceRow:55,address:"4313 Harlem",businessName:"4313 Harlem"},
  {sourceRow:56,address:"4315 Harlem",businessName:"4315 Harlem"},
  {sourceRow:57,address:"4317 Harlem",businessName:"4317 Harlem"},
  {sourceRow:58,address:"4319 Harlem",businessName:"4319 Harlem"},
  {sourceRow:59,address:"4321 Harlem",businessName:"4321 Harlem"},
  {sourceRow:60,address:"4323 Harlem",businessName:"4325 Harlem"},
  {sourceRow:61,address:"4400 Home",businessName:"Home Elementary School"},
  {sourceRow:62,address:"4401 Harlem",businessName:"Chicago Eye Consultants"},
  {sourceRow:63,address:"4421 Harlem",businessName:"Hannah's Maintenance"},
  {sourceRow:64,address:"4425 Harlem",businessName:"Josph Field & ssociates (Suite 101)"},
  {sourceRow:65,address:"4433 Harlem",businessName:"Midcity Hand Car Wash"},
  {sourceRow:66,address:"4453 Harlem",businessName:"4453 Harlem"},
  {sourceRow:67,address:"4455 Harlem",businessName:"4455 Harlem"},
  {sourceRow:68,address:"4900 41st",businessName:"Asphalt Material Corp."},
  {sourceRow:69,address:"4950 Pershing Rd",businessName:"Galaxy Transport"},
  {sourceRow:70,address:"4950a Pershing Rd",businessName:"Lopez Tire"},
  {sourceRow:71,address:"4977 Pershing Rd",businessName:"Pitt Ohio"},
  {sourceRow:72,address:"4995 Pershing Rd",businessName:"El Malecho"},
  {sourceRow:73,address:"4997 Pershing Rd",businessName:"Monarka  Wholesale"},
  {sourceRow:74,address:"5000 41st",businessName:"Olympic Oil"},
  {sourceRow:75,address:"5000 Pershing Rd",businessName:"Delta Logistics"},
  {sourceRow:76,address:"5000a Pershing Rd",businessName:"PAR Trucking"},
  {sourceRow:77,address:"5001 40th ST",businessName:"Citywide Disposal"},
  {sourceRow:78,address:"5030 Pershing",businessName:"Waste Managment Repair Garage"},
  {sourceRow:79,address:"5041 Pershing Rd",businessName:"Safeway Transportation"},
  {sourceRow:80,address:"5050 Pershing Rd",businessName:"Waste Managment Admin "},
  {sourceRow:81,address:"5205 Pershing Rd",businessName:"Stickney Pumping Satation"},
  {sourceRow:82,address:"5600 Pershing Rd",businessName:"McCook Pumping Station"},
  {sourceRow:83,address:"5901 Pershing Rd",businessName:"Metro Water Rec District"},
  {sourceRow:84,address:"6001 Pershing  Rd",businessName:"MBM Veolia Water N.A."},
  {sourceRow:85,address:"6401 Pershing Rd",businessName:"Ridgewood Condminums"},
  {sourceRow:86,address:"6419 43rd St",businessName:"Village Of Stickney DPW"},
  {sourceRow:87,address:"6429 Pershing Rd",businessName:"Toby's Tap"},
  {sourceRow:88,address:"6431 Pershing Rd",businessName:"American Legion hall"},
  {sourceRow:89,address:"6433 43rd St",businessName:"Stickney FD"},
  {sourceRow:90,address:"6441 Pershing Rd",businessName:"Skyview Condminums"},
  {sourceRow:91,address:"6501 Pershing Rd",businessName:"Sign Edge"},
  {sourceRow:92,address:"6503 Pershing Rd",businessName:"Hard Headed Barber Shop"},
  {sourceRow:93,address:"6515B Pershing Rd",businessName:"Rising Stars Day Care"},
  {sourceRow:94,address:"6525 Pershing Rd",businessName:"Lynns Bar"},
  {sourceRow:95,address:"6533 Pershing Rd",businessName:"Stickney Village Hall"},
  {sourceRow:96,address:"6535 Pershing Rd",businessName:"Stickney Pd"},
  {sourceRow:97,address:"6601 Pershing Rd",businessName:"Chavez Carpentry"},
  {sourceRow:98,address:"6603 Pershing Rd",businessName:"El Papi Pollo"},
  {sourceRow:99,address:"6611 Pershing Rd",businessName:"McCraken's Watering  Hole"},
  {sourceRow:100,address:"6645 Pershing Rd",businessName:"The Ble Kangaroo"},
  {sourceRow:101,address:"6719 Pershing Rd",businessName:"Super Smokes"},
  {sourceRow:102,address:"6721 40th St",businessName:"Sticknet Township Clinic"},
  {sourceRow:103,address:"6721 Pershing Rd",businessName:"Ridgewood Condminums"},
  {sourceRow:104,address:"6725 Pershing Rd",businessName:"Alexanders Restaurant"},
  {sourceRow:105,address:"6727 Pershing Rd",businessName:"State Liquors"},
  {sourceRow:106,address:"6733 Pershing Rd",businessName:"Czech Kitchens"},
  {sourceRow:107,address:"6737 Pershing Rd",businessName:"Bonas Family hair care"},
  {sourceRow:108,address:"6739 Pershing Rd",businessName:"Tapia Sausage (Alley Entrance)"},
  {sourceRow:109,address:"6739 Pershing Rd",businessName:"Family Dentist"},
  {sourceRow:110,address:"6741 Pershing ",businessName:"Splash Grooming"},
  {sourceRow:111,address:"6743 Pershing Rd",businessName:"State Farm Insurance"},
  {sourceRow:112,address:"6800 43rd St",businessName:"Stickney-Forest View Library"},
  {sourceRow:113,address:"6801 43rd St",businessName:"The Childrens center of berwyn cicero"},
  {sourceRow:114,address:"6805 43rd St",businessName:"St.Pius X Catholic Church"},
  {sourceRow:115,address:"6807 Pershing Rd",businessName:"Wunderkind Academy"},
  {sourceRow:116,address:"6809 Pershing  Rd",businessName:"J&S Amigo Market"},
  {sourceRow:117,address:"6817 Pershing Rd",businessName:"Corned Beef Factory"},
  {sourceRow:118,address:"6821 Pershing Rd ",businessName:"Villa Nova Pizza"},
  {sourceRow:119,address:"6825 40th St",businessName:"Faith Community"},
  {sourceRow:120,address:"6827 Pershing Rd",businessName:"Spring Master"},
  {sourceRow:121,address:"7122 40th St",businessName:"Jewel-Osco"},
];
