"use client";

/* eslint-disable @next/next/no-img-element -- map tiles are third-party runtime imagery. */
import { useCallback, useEffect, useRef, useState } from "react";
import GoogleFieldMap from "./google-field-map";

type Point = { lat:number;lng:number };
type DrawingMode = "trace"|"detour"|"";
type Imagery = "street"|"aerial";
type RoadClosure = {
  id:string;roadName:string;reason:string;path:Point[];detourPoint:Point;
  status:"active"|"cleared";startedAt:string;expectedClearAt:string|null;
  createdBy:string;clearedBy:string|null;clearedAt:string|null;clearNote:string;
};

const stickney:Point={lat:41.8189,lng:-87.7734};
function world(point:Point,zoom:number){const scale=256*2**zoom;return{x:(point.lng+180)/360*scale,y:(1-Math.asinh(Math.tan(point.lat*Math.PI/180))/Math.PI)/2*scale};}
function project(point:Point,center:Point,zoom:number,width:number,height:number){const p=world(point,zoom),c=world(center,zoom);return{x:width/2+p.x-c.x,y:height/2+p.y-c.y};}
function unproject(x:number,y:number,center:Point,zoom:number,width:number,height:number):Point{const scale=256*2**zoom,c=world(center,zoom),wx=c.x+x-width/2,wy=c.y+y-height/2;return{lng:wx/scale*360-180,lat:Math.atan(Math.sinh(Math.PI*(1-2*wy/scale)))*180/Math.PI};}
function polyline(value:Point[],center:Point,zoom:number,width:number,height:number){return value.map((point)=>{const p=project(point,center,zoom,width,height);return`${p.x},${p.y}`;}).join(" ");}
function dateTime(value:string|null){return value?new Date(value).toLocaleString("en-US",{timeZone:"America/Chicago",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"Until reopened";}
function segmentFeet(a:Point,b:Point){const radius=20902231,lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 2*radius*Math.asin(Math.min(1,Math.sqrt(h)));}
function traceFeet(path:Point[]){return Math.round(path.slice(1).reduce((total,point,index)=>total+segmentFeet(path[index],point),0));}
function closureCenter(path:Point[]){return path.length?path.reduce((result,point)=>({lat:result.lat+point.lat/path.length,lng:result.lng+point.lng/path.length}),{lat:0,lng:0}):stickney;}
function roadNameFromAddress(value:string){return value.split(",")[0]?.trim()||value;}
export function roadClosureDetourUrl(closure:Pick<RoadClosure,"path"|"detourPoint">){const destination=closure.path.at(-1);if(!destination)return"https://www.google.com/maps";return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${destination.lat},${destination.lng}`)}&waypoints=${encodeURIComponent(`${closure.detourPoint.lat},${closure.detourPoint.lng}`)}&travelmode=driving`;}

function ClosureMap({apiKey,closures,draft,detourPoint,mode,center,zoom,imagery,onCenter,onZoom,onClick}:{apiKey:string;closures:RoadClosure[];draft:Point[];detourPoint:Point|null;mode:DrawingMode;center:Point;zoom:number;imagery:Imagery;onCenter:(point:Point)=>void;onZoom:(zoom:number)=>void;onClick:(point:Point)=>void}){
  const root=useRef<HTMLDivElement>(null),gesture=useRef<{x:number;y:number;center:Point;moved:boolean}|null>(null);
  const [size,setSize]=useState({width:1000,height:600}),[googleReady,setGoogleReady]=useState(false),[dragging,setDragging]=useState(false);
  useEffect(()=>{const element=root.current;if(!element)return;const update=()=>{const rect=element.getBoundingClientRect();if(rect.width&&rect.height)setSize({width:rect.width,height:rect.height});};update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect();},[]);
  const centerWorld=world(center,zoom),tileX=Math.floor(centerWorld.x/256),tileY=Math.floor(centerWorld.y/256),tileCount=2**zoom;
  const tiles=Array.from({length:25},(_,index)=>({x:tileX+index%5-2,y:tileY+Math.floor(index/5)-2})).filter((tile)=>tile.y>=0&&tile.y<tileCount);
  function mappedPoint(clientX:number,clientY:number){const rect=root.current!.getBoundingClientRect();return unproject(clientX-rect.left,clientY-rect.top,center,zoom,size.width,size.height);}
  return <div ref={root} className={`road-closure-map${mode?" capture":""}${dragging?" dragging":""}`}>
    <div className="road-map-tiles">{tiles.map((tile)=>{const wrappedX=((tile.x%tileCount)+tileCount)%tileCount,left=size.width/2+tile.x*256-centerWorld.x,top=size.height/2+tile.y*256-centerWorld.y;return <img key={`${tile.x}-${tile.y}`} alt="" draggable={false} style={{left,top,width:256,height:256}} src={imagery==="aerial"?`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${zoom}/${tile.y}/${wrappedX}`:`https://tile.openstreetmap.org/${zoom}/${wrappedX}/${tile.y}.png`}/>;})}</div>
    {apiKey?<GoogleFieldMap apiKey={apiKey} center={center} zoom={zoom} imagery={imagery} interactive={!mode} onReady={setGoogleReady} onViewChange={(next,nextZoom)=>{onCenter(next);onZoom(nextZoom);}}/>:null}
    <svg viewBox={`0 0 ${size.width} ${size.height}`} preserveAspectRatio="none" aria-label="Road closure map overlay">
      {closures.map((closure)=><g key={closure.id}><polyline className="active-road-closure" points={polyline(closure.path,center,zoom,size.width,size.height)}/>{closure.path.slice(0,1).map((point)=>{const p=project(point,center,zoom,size.width,size.height);return <text className="road-closure-label" x={p.x+12} y={p.y-13} key={closure.id}>{closure.roadName} · CLOSED</text>;})}</g>)}
      {draft.length?<polyline className="draft-road-closure" points={polyline(draft,center,zoom,size.width,size.height)}/>:null}
      {draft.map((point,index)=>{const p=project(point,center,zoom,size.width,size.height);return <g key={index}><circle className={`road-trace-point ${index===0?"start":index===draft.length-1?"end":""}`} cx={p.x} cy={p.y} r="10"/><text className="road-trace-number" x={p.x} y={p.y+4}>{index===0?"S":index===draft.length-1?"E":index+1}</text></g>;})}
      {detourPoint?(()=>{const p=project(detourPoint,center,zoom,size.width,size.height);return <g><circle className="road-detour-point" cx={p.x} cy={p.y} r="14"/><text className="road-detour-label" x={p.x+18} y={p.y+5}>BYPASS</text></g>;})():null}
    </svg>
    {mode?<div className="road-map-capture" role="application" aria-label={mode==="trace"?"Draw the closed road. Tap to add points or drag to move the map.":"Choose a preferred bypass point. Tap to place it or drag to move the map."}
      onPointerDown={(event)=>{if(event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);gesture.current={x:event.clientX,y:event.clientY,center,moved:false};setDragging(true);}}
      onPointerMove={(event)=>{const start=gesture.current;if(!start)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.hypot(dx,dy)>5)start.moved=true;if(start.moved)onCenter(unproject(size.width/2-dx,size.height/2-dy,start.center,zoom,size.width,size.height));}}
      onPointerUp={(event)=>{const start=gesture.current;gesture.current=null;setDragging(false);if(start&&!start.moved)onClick(mappedPoint(event.clientX,event.clientY));}}
      onPointerCancel={()=>{gesture.current=null;setDragging(false);}}
      onWheel={(event)=>{event.preventDefault();onZoom(Math.max(14,Math.min(21,zoom+(event.deltaY<0?1:-1))));}}/>:null}
    <div className="road-map-status"><i className={googleReady?"online":"fallback"}/>{mode==="trace"?"Tap along the closed road · drag to move":mode==="detour"?"Tap a safe bypass point · drag to move":googleReady?"Google street map":"Backup map active"}</div>
    <div className="road-map-legend"><span><i className="closed"/>Closed road</span><span><i className="bypass"/>Bypass point</span></div>
  </div>;
}

function WorkflowSteps({path,detourPoint,roadName}:{path:Point[];detourPoint:Point|null;roadName:string}){
  const steps=[{label:"Find the road",done:Boolean(roadName.trim())},{label:"Trace closure",done:path.length>=2},{label:"Set bypass",done:Boolean(detourPoint)},{label:"Review & activate",done:Boolean(roadName.trim()&&path.length>=2&&detourPoint)}];
  return <ol className="road-workflow-steps">{steps.map((step,index)=><li className={step.done?"done":""} key={step.label}><b>{step.done?"✓":index+1}</b><span>{step.label}</span></li>)}</ol>;
}

export default function RoadClosures(){
  const [closures,setClosures]=useState<RoadClosure[]>([]),[canManage,setCanManage]=useState(false),[mapsApiKey,setMapsApiKey]=useState("");
  const [center,setCenter]=useState<Point>(stickney),[zoom,setZoom]=useState(17),[imagery,setImagery]=useState<Imagery>("street"),[mode,setMode]=useState<DrawingMode>("");
  const [roadName,setRoadName]=useState(""),[reason,setReason]=useState(""),[expectedClearAt,setExpectedClearAt]=useState(""),[path,setPath]=useState<Point[]>([]),[detourPoint,setDetourPoint]=useState<Point|null>(null);
  const [search,setSearch]=useState(""),[searching,setSearching]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[showHistory,setShowHistory]=useState(false),[reopeningId,setReopeningId]=useState(""),[clearNote,setClearNote]=useState("Road reopened");
  const active=closures.filter((item)=>item.status==="active"),ready=Boolean(roadName.trim()&&path.length>=2&&detourPoint),distance=traceFeet(path);
  const load=useCallback(async()=>{const response=await fetch("/api/road-closures",{cache:"no-store"});const body=await response.json() as {closures?:RoadClosure[];canManage?:boolean;error?:string};if(!response.ok)throw new Error(body.error||"Unable to load road closures");setClosures(body.closures||[]);setCanManage(Boolean(body.canManage));},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void Promise.all([load(),fetch("/api/maps-config",{cache:"no-store"}).then((response)=>response.json()).then((body:{apiKey?:string})=>setMapsApiKey(body.apiKey||""))]).catch((error)=>setMessage(error instanceof Error?error.message:"Unable to load Road Closures"));},0);return()=>window.clearTimeout(timer);},[load]);
  function mapClick(point:Point){if(mode==="trace")setPath((current)=>[...current,point].slice(0,80));else if(mode==="detour"){setDetourPoint(point);setMode("");}}
  function resetDraft(){setRoadName("");setReason("");setExpectedClearAt("");setPath([]);setDetourPoint(null);setSearch("");setMode("");setMessage("");}
  async function locateRoad(){if(!search.trim())return;setSearching(true);setMessage("");try{const response=await fetch("/api/road-closures",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"locate",address:search})});const body=await response.json() as {location?:Point;formattedAddress?:string;error?:string};if(!response.ok||!body.location)throw new Error(body.error||"Road not found");setCenter(body.location);setZoom(19);setSearch(body.formattedAddress||search);if(!roadName.trim())setRoadName(roadNameFromAddress(body.formattedAddress||search));setMode("trace");setMessage("Road located. Tap points along the section that is closed.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to find that road");}finally{setSearching(false);}}
  function locateUser(){if(!navigator.geolocation){setMessage("Current location is unavailable on this device.");return;}navigator.geolocation.getCurrentPosition((position)=>{setCenter({lat:position.coords.latitude,lng:position.coords.longitude});setZoom(19);setMessage("Map centered on your current location.");},()=>setMessage("Location permission is unavailable. Search for the road instead."),{enableHighAccuracy:true,timeout:8000});}
  async function save(){setBusy(true);setMessage("");try{const response=await fetch("/api/road-closures",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",roadName,reason,expectedClearAt,path,detourPoint})});const body=await response.json() as {closures?:RoadClosure[];error?:string};if(!response.ok)throw new Error(body.error||"Unable to activate road closure");setClosures(body.closures||[]);resetDraft();setMessage("Road closure is active and now appears on Live Operations.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to activate road closure");}finally{setBusy(false);}}
  async function clearClosure(id:string){setBusy(true);setMessage("");try{const response=await fetch("/api/road-closures",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear",id,clearNote})});const body=await response.json() as {closures?:RoadClosure[];error?:string};if(!response.ok)throw new Error(body.error||"Unable to reopen road");setClosures(body.closures||[]);setReopeningId("");setClearNote("Road reopened");setMessage("Road reopened. Its Live Operations warning has cleared.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to reopen road");}finally{setBusy(false);}}
  function focusClosure(closure:RoadClosure){setCenter(closureCenter(closure.path));setZoom(19);setMode("");document.querySelector(".road-closure-map")?.scrollIntoView({behavior:"smooth",block:"center"});}
  return <section className="road-closures-page">
    <header className="road-closures-hero"><div><span>FIELD · OPERATIONAL ROUTING</span><h1>Road Closures</h1><p>Mark an unusable road section, give crews a preferred bypass, and keep the warning live until the road reopens.</p></div><strong className={active.length?"has-closures":"clear"}>{active.length?`${active.length} ACTIVE`:"ALL ROADS OPEN"}</strong></header>
    {message?<div className="road-closure-message" role="status"><span>{message}</span><button type="button" onClick={()=>setMessage("")}>Dismiss</button></div>:null}
    {canManage?<WorkflowSteps path={path} detourPoint={detourPoint} roadName={roadName}/>:null}
    <div className="road-location-search"><label><span>FIND ROAD OR INTERSECTION</span><div><input value={search} onChange={(event)=>setSearch(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"){event.preventDefault();void locateRoad();}}} placeholder="Example: 39th Street & Oak Park Avenue"/><button type="button" disabled={searching||!search.trim()} onClick={()=>void locateRoad()}>{searching?"Finding…":"Find on map"}</button></div></label><button type="button" className="locate-me" onClick={locateUser}>◎ Use current location</button></div>
    <div className="road-closure-layout">
      <div className="road-map-workspace">
        <div className="road-map-toolbar"><div><button type="button" className={imagery==="street"?"active":""} onClick={()=>setImagery("street")}>Streets</button><button type="button" className={imagery==="aerial"?"active":""} onClick={()=>setImagery("aerial")}>Aerial</button></div><div><button type="button" onClick={()=>setCenter(stickney)}>Center Stickney</button><button type="button" onClick={()=>setZoom(Math.max(14,zoom-1))} aria-label="Zoom out">−</button><b>Zoom {zoom}</b><button type="button" onClick={()=>setZoom(Math.min(21,zoom+1))} aria-label="Zoom in">+</button></div></div>
        <ClosureMap apiKey={mapsApiKey} closures={active} draft={path} detourPoint={detourPoint} mode={mode} center={center} zoom={zoom} imagery={imagery} onCenter={setCenter} onZoom={setZoom} onClick={mapClick}/>
        {canManage?<div className="road-drawing-dock"><div><strong>{mode==="trace"?"Drawing closed road":mode==="detour"?"Choosing bypass point":"Map ready"}</strong><span>{path.length>=2?`${path.length} points · about ${distance.toLocaleString()} ft traced`:"Trace the closed section from one end to the other."}</span></div><div>{mode==="trace"?<><button type="button" disabled={!path.length} onClick={()=>setPath((current)=>current.slice(0,-1))}>Undo</button><button type="button" disabled={path.length<2} className="primary" onClick={()=>setMode("detour")}>Finish trace → Set bypass</button></>:mode==="detour"?<><button type="button" onClick={()=>setMode("trace")}>Back to trace</button><button type="button" disabled={!detourPoint} className="primary" onClick={()=>setMode("")}>Use bypass point</button></>:<><button type="button" onClick={()=>setMode("trace")}>{path.length?"Edit road trace":"Start road trace"}</button><button type="button" disabled={path.length<2} onClick={()=>setMode("detour")}>{detourPoint?"Change bypass":"Set bypass point"}</button></>}</div></div>:null}
      </div>
      <aside>{canManage?<section className="road-closure-form"><span>CLOSURE DETAILS</span><h2>Review before activating</h2><label>Road name<input value={roadName} onChange={(event)=>setRoadName(event.target.value)} placeholder="Road or intersection"/></label><label>Why is it closed?<textarea value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Construction, flooding, wires down, fireground operations…"/></label><label>Expected reopening <em>Optional</em><input type="datetime-local" value={expectedClearAt} onChange={(event)=>setExpectedClearAt(event.target.value)}/></label><div className="road-draft-summary"><div className={path.length>=2?"complete":""}><span>ROAD TRACE</span><b>{path.length>=2?`${distance.toLocaleString()} ft mapped`:"Not finished"}</b></div><div className={detourPoint?"complete":""}><span>BYPASS</span><b>{detourPoint?"Selected":"Not selected"}</b></div></div>{ready?<a className="road-detour-preview" href={roadClosureDetourUrl({path,detourPoint:detourPoint!})} target="_blank" rel="noreferrer">Preview crew detour in Google Maps ↗</a>:null}<button type="button" className="activate-road-closure" disabled={busy||!ready} onClick={()=>void save()}>{busy?"Activating…":"Activate road closure"}</button><button type="button" className="reset-road-draft" disabled={busy||(!roadName&&!path.length&&!detourPoint)} onClick={resetDraft}>Start over</button><small>Google cannot accept a private exact-road exclusion. The crew link routes through the department bypass point you select.</small></section>:<section className="road-closure-form view-only"><span>VIEW ONLY</span><h2>Current road closures</h2><p>An officer or administrator with Incident Command permission can activate and clear closures.</p></section>}</aside>
    </div>
    <section className="active-road-list"><header><div><span>LIVE OPERATIONS</span><h2>Active road closures</h2></div><b>{active.length}</b></header>{active.length?active.map((closure)=><article key={closure.id}><div><span>ROAD OUT OF SERVICE</span><h3>{closure.roadName}</h3><p>{closure.reason||"No reason entered."}</p><small>Active since {dateTime(closure.startedAt)} · Expected clear: {dateTime(closure.expectedClearAt)} · {traceFeet(closure.path).toLocaleString()} ft marked</small></div><div className="road-closure-actions"><button type="button" onClick={()=>focusClosure(closure)}>Show on map</button><a href={roadClosureDetourUrl(closure)} target="_blank" rel="noreferrer">Open crew detour ↗</a>{canManage&&reopeningId!==closure.id?<button type="button" className="reopen" onClick={()=>setReopeningId(closure.id)}>Reopen road</button>:null}</div>{reopeningId===closure.id?<div className="road-reopen-confirm"><label>Reopening note<input value={clearNote} onChange={(event)=>setClearNote(event.target.value)}/></label><button type="button" onClick={()=>setReopeningId("")}>Cancel</button><button type="button" className="confirm" disabled={busy} onClick={()=>void clearClosure(closure.id)}>{busy?"Saving…":"Confirm road reopened"}</button></div>:null}</article>):<div className="road-closure-empty"><b>✓</b><div><strong>No active road closures</strong><span>New closures will appear here and on Live Operations.</span></div></div>}</section>
    <button type="button" className="road-history-toggle" onClick={()=>setShowHistory((value)=>!value)}>{showHistory?"Hide":"Show"} closure history ({closures.length-active.length})</button>{showHistory?<section className="road-closure-history">{closures.filter((item)=>item.status==="cleared").map((closure)=><article key={closure.id}><b>{closure.roadName}</b><span>Reopened {dateTime(closure.clearedAt)} by {closure.clearedBy||"Department"}</span><small>{closure.clearNote}</small></article>)}</section>:null}
  </section>;
}
