"use client";
import type { ReactNode } from "react";
import { useCallback, useEffect, useRef, useState } from "react";
type Alert = { id: string; severity: "critical" | "warning" | "info"; category: string; title: string; detail: string; page: string };
export default function SmartAlerts({ icon, onNavigate }: { icon: ReactNode; onNavigate: (page: string) => void }) {
  const [alerts, setAlerts] = useState<Alert[]>([]), [open, setOpen] = useState(false), [error, setError] = useState(""); const root = useRef<HTMLDivElement>(null);
  const load = useCallback(async () => { const response = await fetch("/api/alerts"); const result = await response.json() as { alerts?: Alert[]; error?: string }; if (response.ok) { setAlerts(result.alerts ?? []); setError(""); } else setError(result.error || "Alerts unavailable"); }, []);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0), timer = window.setInterval(() => void load(), 60000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [load]);
  useEffect(() => { const close = (event: MouseEvent) => { if (root.current && !root.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  return <div className="smart-alerts" ref={root}><button className="notification-button" aria-label={`${alerts.length} smart alerts`} aria-expanded={open} onClick={() => { setOpen((value) => !value); if (!open) void load(); }}>{icon}{alerts.length > 0 && <span>{alerts.length > 99 ? "99+" : alerts.length}</span>}</button>{open && <section className="alert-popover"><header><div><strong>Smart alerts</strong><small>Operational and administrative attention</small></div><button onClick={() => void load()}>Refresh</button></header>{error ? <p className="alert-error">{error}</p> : alerts.length ? <div className="alert-list">{alerts.map((alert) => <button key={alert.id} className={alert.severity} onClick={() => { onNavigate(alert.page); setOpen(false); }}><i>{alert.severity === "critical" ? "!" : alert.severity === "warning" ? "△" : "i"}</i><span><small>{alert.category}</small><strong>{alert.title}</strong><p>{alert.detail}</p></span><b>›</b></button>)}</div> : <div className="alerts-clear"><span>✓</span><strong>No active alerts</strong><p>Current records do not require attention.</p></div>}<footer>Automatically refreshed every minute</footer></section>}</div>;
}
