import { portalPageLabel, type PortalPage } from "./portal-navigation.ts";
import { portalWorkflows } from "./portal-workflows.ts";

type Help = { save: string; notify: string; related?: PortalPage[]; keywords?: string };
/** Describes existing behavior. These are instructions, never delivery receipts. */
export const workspaceHelp: Record<PortalPage, Help> = {
  "Fire Inspections": { save: "Follow Property, Plan, Checklist, Findings, and Finish. Save draft at any step. Completed reports require an explicit correction reason before reopening.", notify: "This owner-only pilot does not email contacts or send push notices. Its work queue shows upcoming and overdue visits. ESO is not connected.", keywords: "fire inspections eso business occupancy violation permit sprinkler hood follow up" },
  Training: { save: "Review the training and people, then save. Drafts do not earn training credit. History shows saved revisions.", notify: "This private pilot does not send assignments or reminders to members. Due items appear inside Training. OSFM is not connected.", keywords: "training vector targetsolutions osfm jpr task book credential certification recertification course attendance" },
  Dashboard: { save: "Home displays saved information. Open the source tool to change a record.", notify: "Open the bell for attention items and this device’s phone-alert settings.", related: ["Daily Log", "Scheduling", "Inventory"], keywords: "start home briefing" },
  Respond: { save: "Choose the correct incident before changing a response. Check the incident’s resulting status.", notify: "The bell controls this device’s phone alerts. Device Modes configures the display; CAD Integration shows delivery evidence.", related: ["Field Preplans", "Command Board", "Respond Device Modes", "CAD Integration"], keywords: "dispatch calls incident response" },
  "Operations Board": { save: "The board displays information from other tools. Save a note or event in its editor; edit staffing in Station Schedule.", notify: "Sound and screen settings affect this display. They do not confirm delivery to another person’s phone.", related: ["Daily Log", "Scheduling", "Daily Duties"], keywords: "tv monitor calendar events announcements" },
  "Command Board": { save: "Choose the incident, update the assignment, and check the result before changing incidents.", notify: "A board assignment is not a confirmed radio message. Use your department’s incident communications procedure.", related: ["Respond", "Field Preplans"], keywords: "accountability incident command" },
  "Field Preplans": { save: "Building details, mapped systems, photos, and advanced publication have separate save controls. Preview the saved preplan after editing.", notify: "Saving a preplan does not send an email or phone notice. Sharing and operational publication are separate actions.", related: ["Respond", "Road Closures", "Box Cards"], keywords: "building hydrant water fdc knox riser alarm photo footprint map flow" },
  "Road Closures": { save: "Review the road and dates before activating a closure. Resolve the saved closure when access reopens.", notify: "Check the active closure list and response map. Do not assume saving a closure has notified every responder.", related: ["Respond", "Field Preplans"], keywords: "street route access detour" },
  "Safety Inspections": { save: "Save draft lets you return later. Submit inspection completes the report. A manager can reopen it for correction.", notify: "Email report prepares an email in your mail app. Review recipients and send there; opening that email is not proof of delivery.", related: ["Inventory", "Daily Duties"], keywords: "inspection facility report deficiency extinguisher" },
  Scheduling: { save: "Submit a request or save the selected shift, then check its status and the dated calendar. A pending request is not an assignment.", notify: "Schedule administration → Reminders sets timing and audiences. Check delivery results and the member’s notification preferences; a saved rule is not a delivered message.", related: ["Daily Log", "Employees", "Work Details"], keywords: "calendar availability trade swap overtime mandatory shift vacation leave request" },
  "Daily Log": { save: "Review the date and staffing. Use Confirm & Save Staffing when shown, and wait for the server-save message after edits. Officer sign-out is a separate step.", notify: "Saving the log records the shift. It does not confirm someone has read the handoff. Use the bell for current attention items.", related: ["Scheduling", "Inventory", "Daily Duties", "Callback Reviews"], keywords: "logbook handoff officer staffing sign in sign out calls" },
  "Daily Duties": { save: "Open the linked apparatus check to record results. Duty wording changes use Approve & Save; Cancel keeps the saved wording.", notify: "Approved duty wording appears on the Live Operations Board. Updating wording is not proof of a phone or email notice.", related: ["Inventory", "Daily Log", "Operations Board"], keywords: "cleaning chores weekly station tasks" },
  Inventory: { save: "Choose a vehicle and check type. Resume an existing check where offered. Submit the check when complete; template edits use Save & preview.", notify: "Check schedules control due times and assigned recipients. Review notification settings and delivery status instead of assuming a failed check sent a notice.", related: ["Daily Duties", "Daily Log"], keywords: "vehicle apparatus equipment airpack scba bottle medication meds fuel mileage repair maintenance manual warranty checks daily weekly" },
  Payroll: { save: "Review hours and correction requests before Mark Reviewed. Finalize locks the period and asks for confirmation.", notify: "Review status and finalization are payroll actions. They are not a confirmation that a member received an email.", related: ["Timesheets", "Callback Reviews", "Work Details", "Rates & Rules"], keywords: "pay wages approval period" },
  Timesheets: { save: "Hours save when you leave a field. Wait for confirmation and retry highlighted failures. Finalized periods are read only.", notify: "A saved hour entry updates payroll. It does not send a correction notice by itself.", related: ["Payroll", "Daily Log"], keywords: "hours timecard pay correction" },
  "My Timesheet": { save: "This screen is read only. Submit a correction request if recorded hours are wrong, then check its status.", notify: "Submitting a correction creates a request for review. Check its status for the administrator’s decision.", related: ["Scheduling", "Daily Log"], keywords: "my hours timecard pay correction" },
  "Callback Reviews": { save: "Review attendance and flags, then use the approval or correction action. Confirm the resulting status and payroll entries.", notify: "A review decision is shown on the record. Do not assume a separate email was delivered.", related: ["Daily Log", "Payroll", "Timesheets"], keywords: "call back attendance approval" },
  "Work Details": { save: "Save or submit the work detail with the correct dates and hours. Approval is separate from entering a request.", notify: "Check the approval queue and request status. Confirm recipients before using any offered notification action.", related: ["Scheduling", "Payroll"], keywords: "special detail event coverage hours" },
  Employees: { save: "Edit the member, then Save Changes. Cancel returns to the roster. Contact details, qualifications, and login access are different settings.", notify: "An invitation requires the member’s login email. Sending an invitation is separate from saving a profile.", related: ["Employee Contacts", "Permissions", "Scheduling"], keywords: "personnel roster firefighter member qualification invite" },
  "Employee Contacts": { save: "This directory reads employee profiles. Authorized administrators correct the source in Employees.", notify: "Tapping a phone number opens your calling app; it does not place a call automatically.", related: ["Employees", "Phone Numbers"], keywords: "member phone directory contact" },
  "Phone Numbers": { save: "Use Add Contact or Edit, then Save Contact. Preview directory shows the reader layout. Cancel keeps the saved contact.", notify: "A saved contact does not send a message. Tap the number to use your device’s calling app.", related: ["Employee Contacts"], keywords: "hospital dispatch directory telephone vendor" },
  Policies: { save: "Find and open a policy. Authorized editors use Edit or Add Policy, then Save & view to review the result.", notify: "Saving a policy updates its reader view. It does not confirm acknowledgment or delivery to members.", related: ["Box Cards", "Holiday Policy", "EMS"], keywords: "policy sop sog procedure document manual" },
  "Box Cards": { save: "Choose a department and card. Authorized editors use Save & view. The original source remains available from the record.", notify: "Opening or editing a box card does not dispatch units or notify mutual-aid departments.", related: ["Respond", "Field Preplans"], keywords: "mabas mutual aid response alarm card" },
  "Holiday Policy": { save: "This is a reference screen. Use Station Schedule for requests and assignments.", notify: "Reading the policy does not submit a holiday shift request.", related: ["Scheduling", "Rates & Rules"], keywords: "holiday dates sign up" },
  EMS: { save: "Open the fillable PDF or download a copy. Work in the PDF is separate from saved portal records.", notify: "Opening or downloading a form does not email it. Use your approved document-sharing process.", related: ["Policies", "Phone Numbers"], keywords: "ambulance medical form document" },
  "Command Center": { save: "Charts summarize saved source records. Correct the original log, schedule, or payroll entry.", notify: "Viewing a chart does not send a report. Use the source record’s supported sharing controls.", related: ["Activity Timeline", "Daily Log", "Operations Board"], keywords: "analytics reports charts trends totals" },
  "Activity Timeline": { save: "History is read only. Open the original tool to make an authorized correction.", notify: "The timeline records activity; it is not a notification-delivery receipt.", related: ["System Health", "Daily Log"], keywords: "audit history who changed" },
  "Rates & Rules": { save: "Choose the effective date, edit rates, then Save Rates. Review the affected pay period.", notify: "Saving rates changes payroll settings. It is not a pay-change notice to employees.", related: ["Payroll", "Timesheets"], keywords: "pay rate salary effective date rule" },
  Departments: { save: "Add Department creates a separate workspace. It does not rename this department or copy its records.", notify: "Creating a workspace does not invite its members or publish a website.", related: ["Permissions", "System Health"], keywords: "workspace tenant department setup" },
  "System Health": { save: "This screen is read only. Refresh checks current status. Department handoff & support explains ownership, costs, recovery, access, and updates.", notify: "A healthy status is not a notification-delivery test. Check the relevant delivery results.", related: ["CAD Integration", "Respond Device Modes"], keywords: "backup health connection offline error ownership chief handoff price cost storage security maintenance updates support" },
  Permissions: { save: "Choose a rank or individual exception, then save that permission set. Test as member previews visibility without changing your identity.", notify: "Access changes do not send a login invitation. Invitations are handled from Employees.", related: ["Employees", "Test View"], keywords: "access roles rank security login" },
  "Test View": { save: "This is a read-only preview. Exit test view to return to your administrator tools.", notify: "Preview mode does not test someone’s actual sign-in or notification delivery.", related: ["Permissions"], keywords: "preview member access test" },
  "CAD Integration": { save: "Use the displayed configuration and validation controls. Sample validation does not create a live incident.", notify: "Verify actual delivery evidence before treating the connection as operational.", related: ["Respond", "System Health"], keywords: "dispatch integration delivery webhook" },
  "Respond Device Modes": { save: "Choose the device mode and apparatus, then Save device mode. It applies to this browser or installed app.", notify: "Phone-alert permission is managed through the bell. Saving a display mode does not prove alert delivery.", related: ["Respond", "CAD Integration"], keywords: "tv tablet screen monitor push phone notifications" },
};

export function matchesWorkspace(page: PortalPage, query: string) {
  const haystack = `${portalPageLabel(page)} ${portalWorkflows[page].purpose} ${portalWorkflows[page].group} ${workspaceHelp[page].keywords ?? ""}`.toLowerCase();
  return query.toLowerCase().trim().split(/\s+/).filter(Boolean).every(term => haystack.includes(term));
}
