'use client';
import { useEffect, useState } from 'react';
import type { DeskRow } from './reporting-desk';
import type { CadCall } from './cad-location';
import { parseSavedTime } from '../workflow-status';
type Desk = { rows: DeskRow[]; hasOlderCalls: boolean; generatedAt: string; scope: string };
async function readDesk(signal?: AbortSignal): Promise<Desk> { const response = await fetch('/api/neris/desk', { cache: 'no-store', signal }), result = await response.json(); if (!response.ok) throw Error(result.error || 'Coverage unavailable.'); return result; }
export function ReportingDesk({ onStart, onOpen }: { onStart: (call: CadCall) => void; onOpen: (id: string) => void }) {
  const [desk, setDesk] = useState<Desk | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(true), [query, setQuery] = useState(''), [filter, setFilter] = useState('All'), [page, setPage] = useState(0);
  async function load() { setBusy(true); setError(''); try { setDesk(await readDesk()); setPage(0); } catch (caught) { setDesk(null); setError(caught instanceof Error ? caught.message : 'Coverage unavailable.'); } finally { setBusy(false); } }
  useEffect(() => { const controller = new AbortController(); void readDesk(controller.signal).then(result => { if (!controller.signal.aborted) setDesk(result); }).catch(caught => { if (!controller.signal.aborted) setError(caught.message); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); return () => controller.abort(); }, []);
  const rows = desk?.rows.filter(row => (filter === 'All' || row.state === filter) && `${row.id} ${row.address} ${row.callType}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  return <section className="nr-panel reporting-desk"><h2>Reporting desk</h2><p>Find saved CAD calls without an active local report and review multiple report links. Nothing here submits or deletes a report.</p><div className="report-filters"><label>Find a CAD call<input value={query} onChange={event => { setQuery(event.target.value); setPage(0); }}/></label><label>Local report status<select value={filter} onChange={event => { setFilter(event.target.value); setPage(0); }}>{['All', 'No local report', 'Draft', 'Locally reviewed', 'Multiple local reports'].map(value => <option key={value}>{value}</option>)}</select></label><button type="button" disabled={busy} onClick={() => void load()}>{busy ? 'Loading…' : 'Refresh coverage'}</button></div>
    {error && <p role="alert">{error}</p>}{desk && <><p role="status">{rows.length} matching calls · {desk.rows.filter(row => row.state === 'No local report').length} without an active local report · {desk.rows.filter(row => row.state === 'Multiple local reports').length} with multiple reports</p><p className="report-note">{desk.scope}{desk.hasOlderCalls && ' Older calls exist outside this window.'} Refreshed {new Date(desk.generatedAt).toLocaleString()}.</p><div className="desk-rows">{rows.slice(page * 25, page * 25 + 25).map(row => <article key={row.id}><div><strong>{row.id} · {row.callType || 'Call type not recorded'}</strong><p>{row.address || 'Address not recorded'}{row.city && ` · ${row.city}`}</p><small>Dispatch time {parseSavedTime(row.dispatchedAt)?.toLocaleString('en-US', {timeZone:'America/Chicago'}) || 'Not recorded'} Central · {row.state}</small>{(row.archivedCount > 0 || row.testCount > 0) && <p>{row.archivedCount} archived / {row.testCount} test links excluded from active coverage. Review these before creating another report.</p>}</div><div className="desk-actions">{row.reports.map(report => <button type="button" key={report.id} onClick={() => onOpen(report.id)}>Open {report.title} · v{report.version}</button>)}{row.state === 'No local report' && <button type="button" onClick={() => onStart(row)}>Review CAD source →</button>}</div></article>)}</div>{!rows.length && <p>No matching saved CAD calls in this window. This does not prove no department activity.</p>}<div className="desk-actions"><button type="button" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous calls</button><span>Page {page + 1} of {Math.max(1, Math.ceil(rows.length / 25))}</span><button type="button" disabled={(page + 1) * 25 >= rows.length} onClick={() => setPage(page + 1)}>Next calls</button></div></>}
  </section>;
}
