'use client';
import {useId,useState} from 'react';
import {incidentCategories,incidentTypeGuides} from './guide';
import {resolveSchema,schemas,humanLabel,textDescription,type Schema,type Json,type Values} from './model';
type Props={schema:Schema;value:Json|undefined;onChange:(v:Json|undefined)=>void;label:string;required?:boolean;path:string;depth?:number};
const basicAddress=new Set(['number','street','street_postfix','unit_prefix','unit_value','postal_community','state','postal_code','country']);
function initial(s:Schema):Json{const node=resolveSchema(s);if(node.const!==undefined)return node.const;if(node.type==='object')return Object.fromEntries(Object.entries(node.properties||{}).filter(([,v])=>resolveSchema(v).const!==undefined).map(([k,v])=>[k,resolveSchema(v).const!]));if(node.type==='array')return[];return '';}
function Choice({options,value,onChange,label,multiple=false}:{options:Json[];value:Json|undefined;onChange:(v:Json|undefined)=>void;label:string;multiple?:boolean}){const[q,setQ]=useState(''),[category,setCategory]=useState(''),id=useId(),incident=options.includes('MEDICAL||ILLNESS||SICK_CASE');const selected=Array.isArray(value)?value:[];const shown=options.filter(v=>(!incident||!category||String(v).split('||')[0]===category)&&`${humanLabel(String(v))} ${String(v)}`.toLowerCase().includes(q.toLowerCase()));return <div className="nr-choice">{incident&&<><label>Incident category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{Object.entries(incidentCategories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{incidentTypeGuides[category]&&<a href={incidentTypeGuides[category]} target="_blank" rel="noreferrer">{incidentCategories[category]} selection guide ↗</a>}</>}{options.length>10&&<label htmlFor={id}>Find {label.toLowerCase()}<input id={id} type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Type a word or code…"/></label>}{multiple?<><div className="nr-choice-list">{shown.map(v=><label className="nr-check" key={String(v)}><input type="checkbox" checked={selected.includes(v)} onChange={e=>onChange(e.target.checked?[...selected,v]:selected.filter(x=>x!==v))}/>{humanLabel(String(v))}</label>)}</div>{!shown.length&&<p>No matching choices.</p>}<small>{selected.length} selected{selected.length>0&&` · ${selected.map(v=>humanLabel(String(v))).join('; ')}`}</small></>:<select aria-label={label} value={String(value??'')} onChange={e=>onChange(e.target.value||undefined)}><option value="">Choose…</option>{[...new Set([...shown,...options.filter(v=>v===value)])].map(v=><option key={String(v)} value={String(v)}>{humanLabel(String(v))}</option>)}</select>}</div>;}
function JsonEditor({value,onChange,label}:{value:Json|undefined;onChange:Props['onChange'];label:string}){const[text,setText]=useState(value===undefined?'':JSON.stringify(value,null,2)),[error,setError]=useState('');return <label>{label}<textarea value={text} rows={6} onChange={e=>{setText(e.target.value);try{onChange(e.target.value?JSON.parse(e.target.value):undefined);setError('');e.target.setCustomValidity('');}catch{setError('Complete valid JSON before leaving this field.');e.target.setCustomValidity('Complete valid JSON before leaving this field.');}}}/>{error&&<strong role="alert">{error}</strong>}<small>Advanced structured data. Use verified GeoJSON / address attributes only.</small></label>;}
function Timestamp({value,onChange,label}:{value:Json|undefined;onChange:Props['onChange'];label:string}){const raw=String(value||''),match=raw.match(/^(.*?)(Z|[+-]\d\d:\d\d)$/),local=match?match[1]:raw,[chosenOffset,setChosenOffset]=useState(''),offset=match?.[2]||chosenOffset;const withSeconds=(v:string)=>v.length===16?`${v}:00`:v;return <div className="nr-time"><label>Date and time<input aria-label={label} type="datetime-local" step="1" value={local} onBlur={e=>onChange(e.target.value?`${withSeconds(e.target.value)}${offset}`:undefined)} onChange={e=>onChange(e.target.value?`${withSeconds(e.target.value)}${offset}`:undefined)}/></label><label>Time zone<select aria-label={`${label} time zone`} value={offset} onChange={e=>{setChosenOffset(e.target.value);if(local)onChange(`${withSeconds(local)}${e.target.value}`);}}><option value="">Choose offset</option><option value="-05:00">Central daylight · UTC−05</option><option value="-06:00">Central standard · UTC−06</option><option value="Z">UTC</option>{offset&&!['-05:00','-06:00','Z'].includes(offset)&&<option>{offset}</option>}</select></label><small>Choose the offset in effect at this incident. No times are filled automatically.</small></div>;}
export function SchemaField({schema,value,onChange,label,required=false,path,depth=0}:Props){
 const s=resolveSchema(schema),id=useId();
 if(depth>20)return <JsonEditor value={value} onChange={onChange} label={label}/>;
 const variants=s.oneOf||s.anyOf?.filter(v=>v.type!=='null');
 if(variants?.length){
  // Some official unions are scalar alternatives (for example domestic/foreign aid IDs).
  // Keep those editable as a value; only object unions use a discriminator selector.
  if(variants.every(v=>['string','integer','number'].includes(resolveSchema(v).type||'')))return <SchemaField schema={{...s,oneOf:undefined,anyOf:undefined,type:'string'}} value={value} onChange={onChange} label={label} required={required} path={path} depth={depth+1}/>;
  // Incident type has an RMS array and CAD-only array. RMS is the documented reporting form.
  if(variants.every(v=>resolveSchema(v).type==='array'))return <SchemaField schema={variants[0]} value={value} onChange={onChange} label={label} required={required} path={path} depth={depth+1}/>;
  const mapping=s.discriminator?.mapping;
  const choices=mapping?Object.entries(mapping).map(([key,r])=>({key,schema:schemas[r.split('/').pop()!]})):variants.map((v,i)=>({key:String(i),schema:resolveSchema(v)}));
  const discriminator=s.discriminator?.propertyName||'type',selected=value&&typeof value==='object'&&!Array.isArray(value)?String(value[discriminator]??''):'';
  const choice=mapping?choices.find(c=>c.key===selected):choices.find(c=>JSON.stringify(resolveSchema(c.schema).properties?.[discriminator]?.const)===JSON.stringify(selected));
  return <fieldset className="nr-group" id={path}><legend>{label}{required?' *':''}</legend><select aria-label={label} value={choice?.key||''} onChange={e=>{const c=choices.find(c=>c.key===e.target.value);if(c)onChange({...initial(c.schema) as Values,[discriminator]:c.key});else onChange(undefined);}}><option value="">Choose…</option>{choices.map(c=><option key={c.key} value={c.key}>{humanLabel(mapping?c.key:c.schema.title||c.key)}</option>)}</select>{choice&&<SchemaField schema={choice.schema} value={value} onChange={onChange} label="Details" required path={`${path}.details`} depth={depth+1}/>}</fieldset>;
 }
 if(s.const!==undefined)return <div className="nr-constant"><small>{label}</small><span>{humanLabel(String(s.const))}</span></div>;
 if(s.enum)return <div className="nr-field" id={path}><label>{label}{required?' *':''}</label><Choice options={s.enum} value={value} onChange={onChange} label={label}/>{textDescription(s)&&<small>{textDescription(s)}</small>}</div>;
 if(s.type==='object'||s.properties){const obj=value&&typeof value==='object'&&!Array.isArray(value)?value as Values:{};const enabled=value!==undefined&&value!==null;
  if(!required&&!enabled)return <div className="nr-optional" id={path}><div><strong>{label}</strong><small>Not recorded</small></div><button type="button" onClick={()=>onChange(initial(s))}>Add {label.toLowerCase()}</button></div>;
  if(!s.properties)return <JsonEditor key={path} value={value} onChange={onChange} label={label}/>;
  const isAddress=s.title==='LocationPayload',addressOrder=[...basicAddress],entries=Object.entries(s.properties);if(isAddress)entries.sort(([a],[b])=>(addressOrder.includes(a)?addressOrder.indexOf(a):100)-(addressOrder.includes(b)?addressOrder.indexOf(b):100));
  const fields=(rows:[string,Schema][])=>rows.map(([k,child])=><SchemaField key={k} schema={child} value={obj[k]} onChange={v=>{const next={...obj};if(v===undefined)delete next[k];else next[k]=v;onChange(next);}} label={humanLabel(k)} required={s.required?.includes(k)} path={`${path}.${k}`} depth={depth+1}/>);
  return <fieldset className="nr-group" id={path}><legend>{label}{required?' *':''}</legend>{!required&&<button className="nr-remove" type="button" onClick={()=>{if(window.confirm(`Remove ${label.toLowerCase()} from this draft? Earlier saved versions remain in history.`))onChange(undefined);}}>Remove section</button>}<div className="nr-fields">{fields(isAddress?entries.filter(([k])=>basicAddress.has(k)):entries)}</div>{isAddress&&<details><summary>Detailed address, cross streets, aliases & additional attributes</summary><div className="nr-fields">{fields(entries.filter(([k])=>!basicAddress.has(k)))}</div></details>}{s.description?.includes('Validation Rules')&&<details><summary>Official field rules</summary><p className="nr-rule-text">{textDescription(s)}</p></details>}</fieldset>;
 }
 if(s.type==='array'){const list=Array.isArray(value)?value:[],item=resolveSchema(s.items||{});
  if(item.enum)return <fieldset className="nr-group" id={path}><legend>{label}{required?' *':''}</legend><Choice multiple options={item.enum} value={list} onChange={onChange} label={label}/></fieldset>;
  if(path.includes('polygon')||path.includes('coordinates'))return <JsonEditor key={path} value={value} onChange={onChange} label={label}/>;
  return <fieldset className="nr-group nr-array" id={path}><legend>{label}{required?' *':''} · {list.length}</legend>{!list.length&&<p className="nr-muted">None recorded. Add an entry only when it applies.</p>}{list.map((v,i)=><details open key={`${path}-${i}`}><summary>{label} {i+1}{v&&typeof v==='object'&&!Array.isArray(v)&&v.reported_unit_id?` · ${v.reported_unit_id}`:''}</summary><SchemaField schema={s.items||{}} value={v} onChange={next=>onChange(list.map((x,j)=>j===i?next??initial(s.items||{}):x))} label={`${label} ${i+1}`} required path={`${path}.${i}`} depth={depth+1}/><button className="nr-remove" type="button" onClick={()=>{if(window.confirm('Remove this entry from the draft? Saved history is preserved.'))onChange(list.filter((_,j)=>i!==j));}}>Remove entry {i+1}</button></details>)}<button type="button" disabled={s.maxItems!==undefined&&list.length>=s.maxItems} onClick={()=>onChange([...list,initial(s.items||{})])}>+ Add {label.toLowerCase()}</button>{s.maxItems&&<small>Up to {s.maxItems} entries</small>}</fieldset>;
 }
 return <div className="nr-field" id={path}><label htmlFor={id}>{label}{required?' *':''}</label>{s.type==='boolean'?<select id={id} value={value===true?'yes':value===false?'no':''} onChange={e=>onChange(e.target.value===''?undefined:e.target.value==='yes')}><option value="">Not answered</option><option value="yes">Yes</option><option value="no">No</option></select>:s.format==='date-time'?<Timestamp value={value} onChange={onChange} label={label}/>:s.maxLength&&s.maxLength>2000?<textarea id={id} value={String(value??'')} rows={7} maxLength={s.maxLength} onChange={e=>onChange(e.target.value||undefined)}/>:<input id={id} type={s.type==='number'||s.type==='integer'?'number':'text'} step={s.type==='integer'?1:'any'} min={s.minimum} max={s.maximum} maxLength={s.maxLength} value={typeof value==='string'||typeof value==='number'?value:''} onChange={e=>onChange(e.target.value===''?undefined:s.type==='number'||s.type==='integer'?Number(e.target.value):e.target.value)}/>}<small>{textDescription(s)}</small></div>;
}
