'use client';
import {useState} from 'react';
import {codeLabel, codeTypes, emptyCode, normalizeCode, searchCodes, selectCode, type CodeData, type CodeEntry, type CodeSelection} from './codes';
import type {InspectionFile} from './model';
import {useUnsavedWork} from '../use-unsaved-work';

export function CodePicker({entries,selected,onChange,label='Select verified code references'}:{entries:CodeEntry[];selected:CodeSelection[];onChange:(value:CodeSelection[])=>void;label?:string}) {
 const [query,setQuery]=useState(''),[type,setType]=useState(''),[edition,setEdition]=useState(''),[jurisdiction,setJurisdiction]=useState('');
 const matches=searchCodes(entries,query,type,edition,jurisdiction);
 return <details className="fi-panel"><summary>{label} · {selected.length} selected</summary>
  <p>Choose the edition that applies to this property. Selections retain the exact saved wording and version.</p>
  <div className="fi-code-selected">{selected.map(c=><div key={c.id+':'+c.version}><strong>{codeLabel(c)}</strong><small>Library version {c.version}</small><button type="button" onClick={()=>onChange(selected.filter(s=>s.id!==c.id||s.version!==c.version))}>Remove {c.title}</button></div>)}</div>
  <CodeFilters entries={entries} query={query} setQuery={setQuery} type={type} setType={setType} edition={edition} setEdition={setEdition} jurisdiction={jurisdiction} setJurisdiction={setJurisdiction}/>
  <div className="fi-code-results">{matches.slice(0,60).map(c=>{const chosen=selected.some(s=>s.id===c.id&&s.version===c.version);return <article className="fi-panel" key={c.id}><strong>{codeLabel(c.data)}</strong><p>{c.data.applicability}</p><details><summary>Read section / source</summary><p className="fi-prewrap">{c.data.text||'No section text stored.'}</p>{c.data.sourceUrl&&<a href={c.data.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a>}</details><button type="button" disabled={chosen||selected.length>=30} onClick={()=>onChange([...selected,selectCode(c)])}>{chosen?'Selected':'+ Select this edition / section'}</button></article>;})}</div>
  {!matches.length&&<p>No matching codes. Add your verified ordinance or code section in the Code library tab, then return here. You can save this inspection as a draft first.</p>}{matches.length>60&&<small>Showing 60 matches. Narrow the search.</small>}
 </details>;
}
type FilterProps={entries:CodeEntry[];query:string;setQuery:(s:string)=>void;type:string;setType:(s:string)=>void;edition:string;setEdition:(s:string)=>void;jurisdiction:string;setJurisdiction:(s:string)=>void};
function CodeFilters(p:FilterProps){return <div className="fi-grid"><label className="fi-field">Search codes<input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Section, exit, local ordinance…"/></label>{([{key:'type',label:'Code type',values:codeTypes,value:p.type,set:p.setType},{key:'edition',label:'Edition / year',values:[...new Set(p.entries.map(c=>c.data.edition))].sort(),value:p.edition,set:p.setEdition},{key:'jurisdiction',label:'Jurisdiction',values:[...new Set(p.entries.map(c=>c.data.jurisdiction).filter(Boolean))].sort(),value:p.jurisdiction,set:p.setJurisdiction}]).map(f=><label className="fi-field" key={f.key}>{f.label}<select value={f.value} onChange={e=>f.set(e.target.value)}><option value="">All {f.label.toLowerCase()}s</option>{f.values.map(v=><option key={v}>{v}</option>)}</select></label>)}</div>;}

export default function CodeLibrary({entries,files,onSaved,onUpload,onEditingChange}:{entries:CodeEntry[];files:InspectionFile[];onSaved:(c:CodeEntry)=>void;onEditingChange:(editing:boolean)=>void;onUpload:(file:File,target:{codeId:string})=>Promise<void>}) {
 const [query,setQuery]=useState(''),[type,setType]=useState(''),[edition,setEdition]=useState(''),[jurisdiction,setJurisdiction]=useState(''),[archived,setArchived]=useState(false),[editing,setEditing]=useState<CodeEntry|null>(null),[data,setData]=useState(emptyCode),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=!!editing&&JSON.stringify(data)!==JSON.stringify(editing.data);useUnsavedWork(dirty,busy);
 function edit(c:CodeEntry){onEditingChange(true);setEditing(c);setData(c.data);setError('');}
 async function save(c:CodeEntry){setBusy(true);setError('');try{const r=await fetch('/api/fire-inspections/codes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...c,data:normalizeCode(c.data)})}),j=await r.json();if(!r.ok)throw Error(j.error||'Code was not saved.');onSaved(j.entry);setEditing(null);onEditingChange(false);}catch(e){setError(e instanceof Error?e.message:'Save not confirmed. Keep your draft and retry.');}finally{setBusy(false);}}
 const fields: [keyof CodeData,string][]=[['edition','Edition / year *'],['jurisdiction','Jurisdiction / adopting authority'],['section','Section / ordinance number'],['title','Section or document title *'],['effectiveDate','Effective date, if verified'],['sourceUrl','Official source link']];
 return <section><div className="fi-heading"><div><h2>Code library</h2><p>Keep local ordinances and multiple code editions together. Search, read, then select the exact section for a finding.</p></div>{!editing&&<button className="fi-primary" onClick={()=>edit({id:crypto.randomUUID(),version:0,archived:false,updatedAt:'',updatedBy:'',data:emptyCode()})}>+ Add code / ordinance</button>}</div>
 <p className="fi-note">You decide which adopted edition applies. An older building does not automatically qualify for an older code. Record the verified applicability or local approval; the app does not infer it.</p>
 {error&&<p role="alert" className="fi-error">{error}</p>}
 {editing?<form className="fi-panel" onSubmit={e=>{e.preventDefault();void save({...editing,data});}}><fieldset disabled={busy} className="fi-form-body"><div className="fi-grid"><label className="fi-field">Code type *<select value={data.type} onChange={e=>setData({...data,type:e.target.value})}>{codeTypes.map(t=><option key={t}>{t}</option>)}</select></label>{fields.map(([k,label])=><label className="fi-field" key={k}>{label}<input type={k==='effectiveDate'?'date':k==='sourceUrl'?'url':'text'} value={data[k]} onChange={e=>setData({...data,[k]:e.target.value})}/></label>)}</div><label className="fi-field">Section text you are permitted to store<textarea rows={8} value={data.text} onChange={e=>setData({...data,text:e.target.value})}/></label><label className="fi-field">Where / when it applies and verified adoption notes<textarea value={data.applicability} onChange={e=>setData({...data,applicability:e.target.value})} placeholder="Adoption ordinance, building use, scope, exceptions, approval reference…"/></label><p>Save first to attach a PDF or photo of your permitted reference. PDF contents are not automatically searched; enter searchable section text or notes above.</p><div className="fi-actions"><button type="button" onClick={()=>{if(!dirty||window.confirm('Discard unsaved code changes?')){setEditing(null);onEditingChange(false);}}}>← Back to code library</button><button className="fi-primary" type="submit">{busy?'Saving…':'Save code reference'}</button></div></fieldset></form>:<>
 <CodeFilters entries={entries} query={query} setQuery={setQuery} type={type} setType={setType} edition={edition} setEdition={setEdition} jurisdiction={jurisdiction} setJurisdiction={setJurisdiction}/><label className="fi-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Show archived references</label>
 {searchCodes(entries.filter(c=>c.archived===archived).map(c=>({...c,archived:false})),query,type,edition,jurisdiction).map(c=><article className="fi-panel" key={c.id}><h3>{codeLabel(c.data)}</h3><small>Version {c.version} · {archived?'Archived':'Available to select'}</small><p>{c.data.applicability}</p><details><summary>Read saved text and source</summary><p className="fi-prewrap">{c.data.text||'No section text stored.'}</p>{c.data.sourceUrl&&<a href={c.data.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a>}</details><div className="fi-actions"><button disabled={busy} onClick={()=>edit({...c,archived})}>Edit reference</button><button disabled={busy} onClick={()=>{if(window.confirm(`${archived?'Restore':'Archive'} this reference? Past reports keep their saved selection.`))void save({...c,archived:!archived});}}>{archived?'Restore':'Archive'}</button></div>{files.filter(f=>f.codeId===c.id).map(f=><p key={f.id}><a href={`/api/fire-inspections/files/${encodeURIComponent(f.id)}`}>{f.filename}</a></p>)}{!archived&&<label className="fi-field">Attach source document (PDF / photo, up to 4 MB)<input type="file" disabled={busy} accept="application/pdf,image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{await onUpload(file,{codeId:c.id});}catch(err){setError(err instanceof Error?err.message:'Upload failed.');}finally{setBusy(false);}}}/></label>}</article>)}{!entries.length&&<div className="fi-panel"><h3>Add your first verified reference</h3><p>No code requirements have been invented or preselected. Add IBC 2018 and IBC 2021 as separate entries, for example, only if those are editions you actually use.</p></div>}
 </>}
 </section>;
}
