'use client';
import { useEffect, useRef, useState, type PointerEvent } from 'react';
import { inspectionChecks, inspectionSections, inspectionTypes } from './catalog';
import { addMonths, updateInspectionDetail, blankSignature, emptyInspection, findings, freshCheck, normalizeInspection, resultOptions, todayChicago, validateInspection, type InspectionData, type InspectionRecord, type InspectionSnapshot, type Signature } from './model';
import {inspectionDraftKey} from './draft-backup';
import {CodePicker} from './code-library';
import {EvidencePhotos} from './evidence';
import { useUnsavedWork } from '../use-unsaved-work';
export function newInspection(kind:InspectionRecord['kind']='inspection',seed:Partial<InspectionData>={}):InspectionRecord{return{id:crypto.randomUUID(),kind,data:{...emptyInspection(),...seed},version:0,archived:false,createdAt:'',updatedAt:'',updatedBy:''};}
export function SignaturePad({value,onChange,label="Representative"}:{value:Signature;onChange:(s:Signature)=>void;label?:string}){
 const drawing=useRef(false),points=useRef<number[][][]>(value.strokes);
 function point(e:PointerEvent<SVGSVGElement>){const r=e.currentTarget.getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
 function finish(){if(!drawing.current)return;drawing.current=false;onChange({...value,strokes:points.current,signedAt:''});}
 return <div className="fi-signature"><p>{label === "Representative" ? "Have the representative sign below to acknowledge receipt of the observations. This does not change a finding." : "Sign below after reviewing the observations and report."}</p><svg viewBox="0 0 600 160" preserveAspectRatio="none" role="img" aria-label={`${label} signature drawing area`} onPointerDown={e=>{if(e.button!==0)return;drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);points.current=[...value.strokes,[point(e)]];onChange({...value,strokes:points.current,signedAt:''});}} onPointerMove={e=>{if(!drawing.current)return;if(points.current.reduce((n,s)=>n+s.length,0)>=7900)return;points.current=[...points.current.slice(0,-1),[...points.current[points.current.length-1],point(e)]];onChange({...value,strokes:points.current,signedAt:''});}} onPointerUp={finish} onPointerCancel={finish}>{value.strokes.map((stroke,i)=><polyline key={i} points={stroke.map(p=>`${p[0]*600},${p[1]*160}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/>)}</svg><button type="button" onClick={()=>onChange({...value,strokes:[],signedAt:''})}>Clear signature</button><small>A typed name alone is not a captured signature. Use the signature status above if no drawing is provided.</small></div>;
}
type Props={initial:InspectionRecord;snapshot:InspectionSnapshot;initialStep?:number;recovered?:boolean;onSave:(record:InspectionRecord,keepEditing?:boolean)=>Promise<InspectionRecord>;onUpload:(file:File,target:{recordId:string;checkId?:string;caption?:string})=>Promise<void>;onCancel:()=>void};
export default function InspectionEditor({initial,snapshot,initialStep=0,recovered=false,onSave,onUpload,onCancel}:Props){
 const [base,setBase]=useState(initial),[data,setData]=useState(initial.data),[step,setStep]=useState(initialStep),[busy,setBusy]=useState(false),[error,setError]=useState(''),[section,setSection]=useState(initial.data.sections[0]||'Access'),[search,setSearch]=useState(''),[custom,setCustom]=useState('');
 const template=initial.kind==='template',steps=template?['Name','Choose checks']:['Property','Plan','Checklist','Findings','Finish'];
 const [recoveredDirty,setRecoveredDirty]=useState(recovered);
 const dirty=recoveredDirty||JSON.stringify(data)!==JSON.stringify(base.data);useUnsavedWork(dirty,busy);
 useEffect(()=>{if(!dirty)return;try{sessionStorage.setItem(inspectionDraftKey(snapshot.departmentId||'local-fixture'),JSON.stringify({record:{...base,data},step,time:Date.now()}));}catch{/* Manual Save and Download my draft remain available if browser storage is full. */}},[base,data,dirty,step,snapshot.departmentId]);
 const set=<K extends keyof InspectionData>(key:K,value:InspectionData[K])=>setData(d=>updateInspectionDetail(d,key,value));
 // Editing observations after signing clears the prior acknowledgment.
 const field=(key:keyof InspectionData,label:string,type='text',hint='')=><label className="fi-field" key={key}>{label}<input type={type} value={String(data[key]??'')} onChange={e=>set(key,e.target.value as never)} onInput={type==='date'?e=>set(key,e.currentTarget.value as never):undefined}/>{hint&&<small>{hint}</small>}</label>;
 const select=(key:keyof InspectionData,label:string,options:string[])=><label className="fi-field">{label}<select value={String(data[key])} onChange={e=>set(key,e.target.value as never)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
 function next(index:number){if(index===2&&!data.sections.includes(section))setSection(data.sections[0]||'');setStep(index);setError('');setSearch('');document.getElementById('fi-editor-top')?.scrollIntoView({block:'start'});}
 function changeSection(name:string,checked:boolean){setData(d=>({...d,sections:checked?[...d.sections,name]:d.sections.filter(s=>s!==name),checks:checked?[...d.checks,...inspectionChecks.filter(c=>c.section===name&&!d.checks.some(x=>x.id===c.id)).map(freshCheck)]:d.checks.filter(c=>c.section!==name),representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}));}
 function updateCheck(id:string,patch:Partial<InspectionData['checks'][number]>){setData(d=>({...d,checks:d.checks.map(c=>c.id===id?{...c,...patch}:c),representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}));}
 async function save(status:InspectionData['status']){setError('');try{const d=normalizeInspection({...data,status:template?'Draft':status});validateInspection(initial.kind,d);setBusy(true);await onSave({...base,data:d});}catch(e){setError(e instanceof Error?e.message:'Save was not confirmed. Your entries remain here.');}finally{setBusy(false);}}
 function downloadDraft(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({...base,data},null,2)],{type:'application/json'}));a.href=url;a.download='inspection-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function addPhoto(file:File,checkId:string,caption:string){setError('');setBusy(true);try{const d=normalizeInspection({...data,representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false});validateInspection(initial.kind,d);const saved=await onSave({...base,data:d},true);setRecoveredDirty(false);setBase(saved);setData(saved.data);await onUpload(file,{recordId:saved.id,checkId,caption});}catch(e){setError(e instanceof Error?e.message:'Photo upload was not confirmed. Your saved progress remains available.');}finally{setBusy(false);}}
 const visibleChecks=data.checks.filter(c=>(!section||c.section===section)&&`${c.label} ${c.observation}`.toLowerCase().includes(search.toLowerCase()));
 const errors=findings(data),unanswered=data.checks.filter(c=>c.result==='Not checked').length;
 const propertyChoices=snapshot.properties.filter(p=>`${p.name} ${p.address}`.toLowerCase().includes(search.toLowerCase())).slice(0,40);
 const plan=<><h3>Choose what applies</h3><p>Only selected topics appear during this visit. You can change them anytime before finishing.</p><div className="fi-topic-grid">{inspectionSections.map(s=><label key={s}><input type="checkbox" checked={data.sections.includes(s)} onChange={e=>changeSection(s,e.target.checked)}/>{s}</label>)}</div><label className="fi-field">Add your own checkpoint<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="For example: equipment unique to this property"/></label><button type="button" disabled={!custom.trim()} onClick={()=>{const label=custom.trim();setData(d=>({...d,sections:[...new Set([...d.sections,'Custom'])],checks:[...d.checks,freshCheck({id:crypto.randomUUID(),label,section:'Custom',source:'Department-created observation prompt'})],representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}));setCustom('');}}>+ Add checkpoint</button></>;
 return <form className="fi-editor" onSubmit={e=>e.preventDefault()}>
  <div className="fi-heading" id="fi-editor-top"><div><span className="fi-eyebrow">{template?'CHECKLIST BUILDER':`STEP ${step+1} OF 5`}</span><h2>{template?'Build a reusable checklist':data.title||'New inspection'}</h2><p>{['Choose a property or type a new one.','Set the visit and select the checks that apply.','Tap a result for each checkpoint.','Describe issues and the action needed.','Review the report, acknowledgment, and next visit.'][step]}</p></div><span className="fi-badge">{busy?'Saving…':dirty?'Changes not saved':base.version?`Saved · version ${base.version}`:'Not saved yet'}</span></div>
  <nav className="fi-steps" aria-label="Inspection steps">{steps.map((s,i)=><button type="button" key={s} disabled={busy} aria-current={step===i?'step':undefined} onClick={()=>next(i)}><span>{i+1}</span>{s}</button>)}</nav>
  <fieldset disabled={busy} className="fi-form-body">
  {step===0&&<><h3>{template?'Name your checklist':'Which property?'}</h3>{!template&&<details className="fi-panel"><summary>Find an existing property ({snapshot.properties.length})</summary><label className="fi-field">Search saved properties<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Business or street address"/></label><div className="fi-picker">{propertyChoices.map(p=><button type="button" key={p.id} onClick={()=>{setData(d=>({...d,title:p.name,address:p.address,propertyId:p.id}));setSearch('');}}><strong>{p.name}</strong><span>{p.address}</span></button>)}{!propertyChoices.length&&<p>No match. Enter the property below.</p>}</div></details>}
   <div className="fi-grid">{field('title',template?'Checklist name *':'Business / property name *')}{!template&&<>{field('address','Street address')}{select('type','Inspection type',inspectionTypes)}{field('occupancy','Occupancy / actual use')}{field('contact','On-site contact')}{field('email','Contact email','email')}{field('phone','Phone number','tel')}{field('owner','Property / business owner')}</>}</div>
   {!base.version&&<label className="fi-check"><input type="checkbox" checked={data.test} onChange={e=>set('test',e.target.checked)}/>Test record — excluded from the regular work queue</label>}
   {!template&&<details className="fi-panel"><summary>Use a saved checklist</summary><select aria-label="Saved checklist" defaultValue="" onChange={e=>{const t=snapshot.records.find(r=>r.id===e.target.value);if(t)setData(d=>({...d,sections:t.data.sections,checks:t.data.checks.map(freshCheck),representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}));}}><option value="">Choose a checklist…</option>{snapshot.records.filter(r=>r.kind==='template'&&!r.archived).map(t=><option key={t.id} value={t.id}>{t.data.title}</option>)}</select><small>Using a checklist resets its answers for this visit.</small></details>}
  </>}
  {template&&step===1&&<>{plan}<h3>{data.checks.length} checkpoints</h3>{data.checks.map(c=><div className="fi-checkpoint" key={c.id}><span>{c.section} · {c.label}</span><button type="button" onClick={()=>set('checks',data.checks.filter(x=>x.id!==c.id))}>Remove {c.label}</button></div>)}</>}
  {!template&&step===1&&<><div className="fi-grid">{field('scheduledDate','Scheduled date','date')}{field('scheduledTime','Scheduled time (24-hour)','text','Enter HH:MM, for example 14:30.')}{field('inspector','Lead inspector')}{field('others','Additional inspectors')}{field('codeEdition','Applicable code and edition','text','Enter the code adopted for this property; no edition is assumed.')}{field('localAmendments','Local amendments / approval reference')}</div><label className="fi-field">Reason / preparation notes<textarea value={data.reason} onChange={e=>set('reason',e.target.value)} placeholder="Complaint, plan review, access arrangements, records to bring…"/></label><CodePicker entries={snapshot.codes||[]} selected={data.codeBasis||[]} onChange={v=>set('codeBasis',v)} label="Codes / editions that apply to this property"/>{plan}<details className="fi-panel"><summary>Optional recurring visit</summary><label className="fi-field">Repeat after completion<select value={data.repeatMonths} onChange={e=>setData(d=>({...d,repeatMonths:Number(e.target.value),nextDueDate:d.actualDate&&Number(e.target.value)?addMonths(d.actualDate,Number(e.target.value)):'',representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}))}><option value={0}>No automatic follow-up</option><option value={6}>Every 6 months</option><option value={12}>Every year</option>{![0,6,12].includes(data.repeatMonths)&&<option value={data.repeatMonths}>Every {data.repeatMonths} months</option>}</select></label><label className="fi-field">Custom interval in months<input type="number" min={0} max={120} value={data.repeatMonths} onChange={e=>{const n=Number(e.target.value);setData(d=>({...d,repeatMonths:n,nextDueDate:d.actualDate&&n?addMonths(d.actualDate,n):'',representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}));}}/></label><small>This is your visit schedule. Verify separate system service intervals against the applicable requirements.</small></details></>}
  {!template&&step===2&&<><div className="fi-progress"><strong>{data.checks.length-unanswered} of {data.checks.length} answered</strong><span>{data.checks.filter(c=>c.result==='Needs attention').length} need attention</span></div><div className="fi-grid"><label className="fi-field">Topic<select value={section} onChange={e=>setSection(e.target.value)}><option value="">All selected topics</option>{data.sections.map(s=><option key={s}>{s}</option>)}</select></label><label className="fi-field">Find a checkpoint<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Exit, alarm, FDC…"/></label></div>{!visibleChecks.length&&<p>No checkpoints here. Choose another topic or add one in Plan.</p>}{visibleChecks.map(c=><article className={`fi-checkpoint ${c.result==='Needs attention'?'fi-needs':''}`} key={c.id}><div className="fi-heading"><h3>{c.label}</h3><small>{c.section}</small></div><div className="fi-result-buttons" role="group" aria-label={`${c.label} result`}>{resultOptions.filter(r=>r!=='Not checked').map(r=><button type="button" key={r} aria-pressed={c.result===r} onClick={()=>updateCheck(c.id,{result:r,...(r==='Corrected on site'?{correctedDate:data.actualDate||todayChicago()}:{} )})}>{r}</button>)}<button type="button" className="fi-link" onClick={()=>updateCheck(c.id,{result:'Not checked'})}>Clear result</button></div>{['Needs attention','Corrected on site','Not inspected'].includes(c.result)&&<label className="fi-field">What did you observe?<textarea value={c.observation} onChange={e=>updateCheck(c.id,{observation:e.target.value})} placeholder="Describe the condition. Add location and action in Findings."/></label>}<details><summary>Reference / location / notes</summary><p className="fi-muted">{c.source}. Observation prompt only; verify the applicable code.</p><label className="fi-field">Location<input value={c.location} onChange={e=>updateCheck(c.id,{location:e.target.value})}/></label>{!['Needs attention','Corrected on site','Not inspected'].includes(c.result)&&<label className="fi-field">Observation<textarea value={c.observation} onChange={e=>updateCheck(c.id,{observation:e.target.value})}/></label>}</details></article>)}</>}
  {!template&&step===3&&<><h3>{errors.length} findings to review</h3><p>Code citations stay blank until you verify them. These observations are not automatically issued violation notices.</p>{errors.length===0&&<p className="fi-note">No findings recorded. Return to Checklist to add any issues.</p>}{errors.map(c=><article className="fi-panel" key={c.id}><h3>{c.label} · {c.result}</h3><div className="fi-grid">{(['location','observation','correction','code','dueDate','correctedDate'] as const).map(k=><label className="fi-field" key={k}>{{location:'Exact location',observation:'Observed condition',correction:'Correction / requested action',code:'Verified code section and title',dueDate:'Correction due',correctedDate:'Corrected date'}[k]}{['observation','correction'].includes(k)?<textarea value={c[k]} onChange={e=>updateCheck(c.id,{[k]:e.target.value})}/>:<input type={k.endsWith('Date')?'date':'text'} value={c[k]} onChange={e=>updateCheck(c.id,{[k]:e.target.value})}/>}</label>)}<label className="fi-field">Priority<select value={c.priority} onChange={e=>updateCheck(c.id,{priority:e.target.value})}>{['Routine','Urgent','Immediate action'].map(x=><option key={x}>{x}</option>)}</select></label></div><CodePicker entries={snapshot.codes||[]} selected={c.citations||[]} onChange={v=>updateCheck(c.id,{citations:v})} label="Find and cite a saved code section"/><EvidencePhotos files={snapshot.attachments.filter(f=>f.recordId===base.id&&f.checkId===c.id)} label={c.label} onAdd={(file,caption)=>addPhoto(file,c.id,caption)}/>{c.priority==='Immediate action'&&<p className="fi-note">Record the action taken under your department’s procedure. Saving this form does not dispatch help or notify anyone.</p>}</article>)}<label className="fi-field">Additional notes / questions to research<textarea value={data.notes} onChange={e=>set('notes',e.target.value)}/></label><p className="fi-muted">Adding a deficiency photo saves your progress first. Each photo stays linked to its finding. Attach general plans or PDFs from the saved inspection.</p></>}
  {!template&&step===4&&<><div className="fi-note"><strong>{unanswered?`${unanswered} checkpoints still need a result`:'All selected checkpoints have an answer'}</strong><p>{data.checks.filter(c=>c.result==='Needs attention').length} open issues · {data.checks.filter(c=>c.result==='Not inspected').length} explicitly not inspected.</p><button type="button" onClick={()=>next(2)}>Back to checklist</button></div><div className="fi-grid">{field('actualDate','Actual inspection date','date')}{field('inspector','Inspector')}{field('startTime','Visit start (24-hour)')}{field('endTime','Visit end (24-hour)')}{select('outcome','Inspection outcome',['','No issues observed','Corrections required','Incomplete / no access'])}</div>
    {data.repeatMonths>0&&<div className="fi-panel"><h3>Next routine inspection</h3><p>Every {data.repeatMonths} months. Finishing creates one private follow-up in Needs scheduling.</p>{field('nextDueDate','Next routine due date','date')}<button type="button" disabled={!data.actualDate} onClick={()=>set('nextDueDate',addMonths(data.actualDate,data.repeatMonths))}>Calculate from actual inspection date</button></div>}
    <section className="fi-panel"><h3>Reinspection / failed items</h3><p>{data.checks.some(c=>c.result==='Needs attention')?'Choose what happens next for the open issues before finishing.':'Optionally arrange a follow-up visit.'}</p>{select('reinspectionDecision','Next step',['','Schedule','Needs scheduling','Not needed'])}{data.reinspectionDecision==='Schedule'&&<div className="fi-grid">{field('followUpDate','Reinspection date *','date')}{field('reinspectionTime','Appointment time * (24-hour)','text','For example 09:30')}</div>}{data.reinspectionDecision==='Needs scheduling'&&<>{field('followUpDate','Target due date (optional)','date')}<p>Finishing creates a linked reinspection in Needs scheduling, even if no date is set.</p></>}{data.reinspectionDecision==='Not needed'&&<label className="fi-field">Why is no reinspection needed?<textarea value={data.reinspectionReason} onChange={e=>set('reinspectionReason',e.target.value)}/></label>}</section>
    {(['representative','inspectorSignature'] as const).map(key=>{const signature=data[key]||blankSignature(),label=key==='representative'?'Representative':'Inspector';return <section className="fi-panel" key={key}><h3>{label} signature</h3><div className="fi-grid"><label className="fi-field">{label} signature status<select value={signature.state} onChange={e=>set(key,{...blankSignature(),name:signature.name,role:signature.role,state:e.target.value as Signature['state']})}>{(key==='representative'?['Not requested','Signed','Declined','Not present']:['Not requested','Signed']).map(v=><option key={v}>{v}</option>)}</select></label><label className="fi-field">{label} name<input value={signature.name} onChange={e=>set(key,{...signature,name:e.target.value,strokes:[],signedAt:''})}/></label><label className="fi-field">{label} role<input value={signature.role} onChange={e=>set(key,{...signature,role:e.target.value,strokes:[],signedAt:''})}/></label></div>{signature.state==='Signed'&&<SignaturePad value={signature} label={label} onChange={v=>set(key,v)}/>}</section>;})}
    <label className="fi-check"><input type="checkbox" checked={data.inspectorAttested} onChange={e=>setData(d=>({...d,inspectorAttested:e.target.checked}))}/>I reviewed this inspection for accuracy. My account and this report version will be recorded.</label>
    <p className="fi-note"><strong>Delivery: not sent.</strong> After finishing, choose Email report to review the recipient and send the saved PDF. Finishing alone does not email anyone or submit to ESO.</p>
   </>}
  </fieldset>
  {error&&<div className="fi-error" role="alert"><strong>{error}</strong><div className="fi-actions"><button type="button" onClick={downloadDraft}>Download my draft</button><button type="button" disabled={busy} onClick={()=>{if(window.confirm("Leave and discard the unsaved draft? Download a copy first if you need it."))onCancel();}}>Return to saved records</button></div></div>}
  <footer className="fi-editor-footer"><button type="button" disabled={busy} onClick={()=>{if(step)next(step-1);else if(!dirty||window.confirm('Leave this editor and discard unsaved changes?'))onCancel();}}>← {step?'Back':template?'Checklist library':'All inspections'}</button><button type="button" disabled={busy} onClick={()=>save(template?'Draft':data.status)}>{busy?'Saving…':template?'Save checklist':data.status==='Draft'?'Save draft':'Save progress'}</button>{!template&&step===1&&<button type="button" disabled={busy} onClick={()=>save(data.scheduledDate?'Scheduled':'Needs scheduling')}>{data.scheduledDate?'Save schedule':'Save for scheduling'}</button>}{step<steps.length-1?<button type="button" disabled={busy} className="fi-primary" onClick={()=>next(step+1)}>Next: {steps[step+1]} →</button>:!template&&<button type="button" className="fi-primary" disabled={busy} onClick={()=>save('Completed')}>Finish & save report</button>}</footer>
 </form>;
}
