'use client';
import { useState } from 'react';
import { nearbyHydrants, observationFields, openFindings, propertyVisits, type FieldObservations } from './field-workflow';
import { type InspectionRecord, type Property } from './model';

export function ObservationEditor({value,onChange}:{value:FieldObservations;onChange:(value:FieldObservations)=>void}) {
  return <details className="fi-panel"><summary>Update preplan? Capture field observations</summary><p>Record what you find here. Save the inspection, then review the current preplan before applying selected fields. Photos remain attached to this inspection.</p>
    {Object.entries(observationFields).map(([key,label])=><label className="fi-field" key={key}>{label}<textarea value={value[key as keyof FieldObservations]||''} maxLength={2000} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>)}
  </details>;
}
export function PropertyHistory({property,records,includeTests,onOpen,onStart}:{property:Property;records:InspectionRecord[];includeTests:boolean;onOpen:(id:string)=>void;onStart:()=>void}) {
  const visits=propertyVisits(records,property.id,includeTests);
  const [hydrants,setHydrants]=useState<{id:string;hydrantNumber:string;address:string;serviceStatus:string;latitude:number;longitude:number;distanceFeet:number}[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function loadHydrants(){setBusy(true);setError('');try{const response=await fetch('/api/field-hydrants',{cache:'no-store'}),j=await response.json();if(!response.ok)throw Error(j.error||'Hydrants are unavailable.');setHydrants(nearbyHydrants(property,j.hydrants||[]));}catch(e){setError(e instanceof Error?e.message:'Hydrants are unavailable.');}finally{setBusy(false);}}
  return <section className="fi-panel" aria-label={`Property history: ${property.name}`}><h3>{property.name}</h3><p>{property.address}</p>
    <div className="fi-actions"><a className="fi-button" href={`?page=field-preplans&display=portal&preplan=${encodeURIComponent(property.id)}`}>Open visual preplan</a><button onClick={onStart}>Schedule a visit →</button><button disabled={busy} onClick={loadHydrants}>{busy?'Checking hydrants…':'Nearby hydrant references'}</button></div>
    {hydrants&&<div><p>Straight-line distance from saved coordinates. Confirm access, location, service status and flow on site.</p>{hydrants.map(h=><p key={h.id}><a href={`?page=field-preplans&display=portal&hydrant=${encodeURIComponent(h.id)}`}>Hydrant {h.hydrantNumber||'Number not recorded'}</a> · about {h.distanceFeet} ft · {h.serviceStatus||'Status unknown'} · {h.address}</p>)}{!hydrants.length&&<p>No saved coordinates or accessible hydrant references are available for this property.</p>}</div>}{error&&<p role="alert" className="fi-error">{error}</p>}
    <h4>Inspection history</h4>{visits.map(r=><article className="fi-row" key={r.id}><button className="fi-row-title" onClick={()=>onOpen(r.id)}><strong>{r.data.test?'TEST · ':''}{r.data.type}</strong><span>{r.data.actualDate||r.data.scheduledDate||'Visit date not set'} · {r.archived?'Archived · ':''}{r.data.status} · version {r.version}</span></button><span>{openFindings(r).length} unresolved observations in this report</span></article>)}{!visits.length&&<p>No linked inspection history recorded. Legacy unlinked visits remain in the work queue.</p>}
  </section>;
}
export function PreplanReview({record,property,onRefresh}:{record:InspectionRecord;property?:Property;onRefresh:()=>Promise<void>}) {
  const [checked,setChecked]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState(false);
  const observations=Object.entries(record.data.preplanObservations||{}).filter(([,value])=>value.trim());
  if(!observations.length)return null;
  async function apply(){setBusy(true);setSaved(false);setMessage('');try{const r=await fetch('/api/fire-inspections/preplan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recordId:record.id,version:record.version,fields:checked,expectedUpdatedAt:property?.updatedAt,expectedValues:Object.fromEntries(checked.map(key=>[key,property?.[key as keyof FieldObservations]||'']))})}),j=await r.json();if(!r.ok||!j.saved)throw Error(j.error||'Preplan update was not confirmed.');setSaved(true);setMessage((j.replayed?'Previously applied · no duplicate update · ':'Preplan update confirmed · ')+j.receipt.appliedAt);try{await onRefresh();}catch{setMessage('Preplan update confirmed, but current values could not reload. Refresh before another update.');}}catch(e){setMessage(e instanceof Error?e.message:'Preplan update was not confirmed.');}finally{setBusy(false);}}
  return <section className="fi-panel" aria-label="Preplan field review"><h3>Review preplan observations</h3><p>Choose the fields to replace after comparing the current preplan. Building summary changes may be visible immediately; advanced preplan publication is separate. The saved inspection report remains unchanged. Blank observations never erase fields.</p>
    {observations.map(([key,value])=><div className="fi-panel" key={key}><label className="fi-check"><input type="checkbox" checked={checked.includes(key)} disabled={busy} onChange={e=>setChecked(keys=>e.target.checked?[...keys,key]:keys.filter(k=>k!==key))}/>{observationFields[key as keyof FieldObservations]}</label><p>Current preplan: <span className="fi-prewrap">{property?.[key as keyof FieldObservations]||'Not recorded'}</span></p><p>Inspection observation: <span className="fi-prewrap">{value}</span></p></div>)}
    <div className="fi-actions"><button disabled={busy} onClick={()=>void onRefresh().then(()=>{setMessage('Current preplan refreshed. Compare the values before applying.');setSaved(false);}).catch(()=>{setMessage('Refresh failed. Keep these observations and retry.');setSaved(false);})}>Refresh current property</button><button className="fi-primary" disabled={busy||!checked.length||!property?.updatedAt||record.archived||record.data.test} onClick={apply}>{busy?'Applying…':'Apply selected observations'}</button></div>{record.data.test&&<p>Test inspections cannot change operational preplans.</p>}{!property&&<p>Link an available department property before applying.</p>}{message&&<p className={saved?'fi-success':'fi-note'} role="status">{message}</p>}
  </section>;
}
