'use client';
import {useEffect,useState} from 'react';
import type {InspectionRecord} from './model';
type Delivery={id:string;recordVersion:number;recipient:string;sender:string;status:string;error:string;createdAt:string;updatedAt:string};
export default function ReportDelivery({record}:{record:InspectionRecord}) {
 const [opened,setOpened]=useState(false),[recipient,setRecipient]=useState(record.data.test?'bobff353@gmail.com':record.data.email),[deliveries,setDeliveries]=useState<Delivery[]>([]),[loaded,setLoaded]=useState(false),[setup,setSetup]=useState<{configured:boolean;sender:string;domainStatus:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function history(){const r=await fetch(`/api/fire-inspections/email?recordId=${encodeURIComponent(record.id)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setDeliveries(j.deliveries);setLoaded(true);}
 useEffect(()=>{const c=new AbortController();void fetch(`/api/fire-inspections/email?recordId=${encodeURIComponent(record.id)}`,{cache:'no-store',signal:c.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);if(!c.signal.aborted){setDeliveries(j.deliveries);setLoaded(true);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[record.id]);
 async function open(){setOpened(true);setError('');try{const r=await fetch('/api/fire-inspections/email?setup=1',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setSetup(j);}catch(e){setError(e instanceof Error?e.message:'Email setup could not be checked.');}}
 async function action(body:object){setBusy(true);setError('');try{const r=await fetch('/api/fire-inspections/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error);setDeliveries(d=>[j.delivery,...d.filter(x=>x.id!==j.delivery.id)]);setLoaded(true);if(j.delivery.error)setError(j.delivery.error);}catch(e){setError(e instanceof Error?e.message:'Delivery was not confirmed. Check history before retrying.');}finally{setBusy(false);}}
 const canSend=!record.archived&&(record.data.status==='Completed'||record.data.test);
 return <section className="fi-panel"><div className="fi-heading"><div><h3>Email report</h3><p>Send the saved PDF, including signatures and deficiency photos.</p></div><button disabled={!canSend||busy} className="fi-primary" onClick={open}>Review & email report</button></div>{!canSend&&<p>Finish and save the inspection before emailing its report.</p>}
 {opened&&<form className="fi-panel" onSubmit={e=>{e.preventDefault();void action({action:'send',confirmed:true,recordId:record.id,version:record.version,recipient});}}><h4>Review before sending · version {record.version}</h4><p><a href={`/api/fire-inspections/report?recordId=${encodeURIComponent(record.id)}&version=${record.version}`} target="_blank" rel="noreferrer">Preview / download the exact report PDF ↗</a></p><p>From: {setup?.sender||'Checking email setup…'}</p>{setup&&<p>Email provider: {setup.configured?'Configured':'Not configured'} · Sender domain: {setup.domainStatus}</p>}<label className="fi-field">Recipient email<input type="email" required value={recipient} disabled={busy||record.data.test} onChange={e=>setRecipient(e.target.value)}/></label>{record.data.test&&<p className="fi-note">TEST report. Delivery is restricted to bobff353@gmail.com.</p>}<p>Send report emails this saved version. Repeating the same send safely reuses its delivery record.</p><div className="fi-actions"><button type="button" disabled={busy} onClick={()=>setOpened(false)}>Back · close email review</button><button type="submit" disabled={busy||!setup?.configured} className="fi-primary">{busy?'Sending…':'Send report email'}</button></div></form>}
 {error&&<p className="fi-error" role="alert">{error}</p>}{!loaded?<button disabled={busy} onClick={()=>void history().catch(e=>setError(e.message))}>Load email history</button>:!deliveries.length?<p><strong>Not emailed.</strong> No delivery requests are recorded for this inspection.</p>:<div aria-live="polite">{deliveries.map(d=><article className="fi-delivery" key={d.id}><strong>{d.status} · report version {d.recordVersion}</strong><p>To {d.recipient} · {new Date(d.createdAt).toLocaleString()}</p><p>{d.status==='Accepted'?'The email provider accepted the message. Delivery has not been confirmed.':d.status==='Delivered'?'The provider confirmed delivery. This does not mean the recipient read it.':d.error}</p><small>Last checked / changed {new Date(d.updatedAt).toLocaleString()}</small><div className="fi-actions"><button disabled={busy} onClick={()=>action({action:'refresh',id:d.id})}>Check delivery status</button>{canSend&&['Prepared','Unconfirmed','Failed'].includes(d.status)&&d.recordVersion===record.version&&<button disabled={busy} onClick={()=>action({action:'send',confirmed:true,recordId:record.id,version:d.recordVersion,recipient:d.recipient})}>Retry safely to {d.recipient}</button>}</div></article>)}</div>}
 </section>;
}
