'use client';
import { useCallback, useEffect, useState } from 'react';
import InspectionEditor,{newInspection} from './editor';
import { blankSignature, findings, queueLabel, reportText, todayChicago, type InspectionRecord, type InspectionSnapshot } from './model';
import { IFSTA_URL, quickReferences } from './catalog';
import CodeLibrary from './code-library';
import {codeLabel} from './codes';
import {EvidencePhotos} from './evidence';
import {inspectionDraftKey,readInspectionDraft} from './draft-backup';
import ReportDelivery from './report-delivery';
import './inspections.css';
const tabs=['Work queue','Calendar','Properties','Checklists','Code library','Quick reference'] as const;
type Tab=typeof tabs[number];
const blank:InspectionSnapshot={records:[],properties:[],attachments:[]};
function printReport(){const closed=[...document.querySelectorAll<HTMLDetailsElement>('.fi-workspace details:not([open])')];closed.forEach(d=>d.open=true);window.addEventListener('afterprint',()=>closed.forEach(d=>d.open=false),{once:true});window.print();}
function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function fetchInspections(signal?:AbortSignal):Promise<InspectionSnapshot>{const r=await fetch('/api/fire-inspections',{cache:'no-store',signal}),j=await r.json();if(!r.ok)throw Error(j.error||'Inspections could not load.');return j;}
export default function FireInspectionsWorkspace(){
 const [snapshot,setSnapshot]=useState(blank),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<Tab>('Work queue');
 const [editing,setEditing]=useState<InspectionRecord|null>(null),[editStep,setEditStep]=useState(0),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('Active'),[showTests,setShowTests]=useState(false),[showArchived,setShowArchived]=useState(false),[busy,setBusy]=useState(false),[month,setMonth]=useState(todayChicago().slice(0,7));
 const [recoveredEditing,setRecoveredEditing]=useState(false);
 const [recovery,setRecovery]=useState<ReturnType<typeof readInspectionDraft>>(null);
 const [codeEditing,setCodeEditing]=useState(false);
 const [history,setHistory]=useState<{version:number;payload:string;actor:string;createdAt:string;archived:number}[]|null>(null);
 const receive=useCallback((j:InspectionSnapshot)=>{setSnapshot(j);setLoaded(true);setError('');try{setRecovery(readInspectionDraft(sessionStorage.getItem(inspectionDraftKey(j.departmentId||'local-fixture'))));}catch{}},[]);
 const load=useCallback(()=>fetchInspections().then(receive).catch(e=>setError(e.message)),[receive]);
 useEffect(()=>{const c=new AbortController();void fetchInspections(c.signal).then(j=>{if(!c.signal.aborted){receive(j);const p=new URLSearchParams(window.location.search),view=p.get('inspectionTab');if(tabs.includes(view as Tab))setTab(view as Tab);setSelected(p.get('inspectionRecord')||'');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[receive]);
 function route(t:Tab,id=''){setTab(t);setSelected(id);setEditing(null);setQuery('');setError('');setNotice('');setHistory(null);const u=new URL(location.href);u.searchParams.set('inspectionTab',t);if(id)u.searchParams.set('inspectionRecord',id);else u.searchParams.delete('inspectionRecord');window.history.replaceState(window.history.state,'',u);}
 function clearBackup(){try{sessionStorage.removeItem(inspectionDraftKey(snapshot.departmentId||'local-fixture'));}catch{}setRecovery(null);}
 function edit(r:InspectionRecord,step=0,recovered=false){setRecoveredEditing(recovered);setEditing(r);setEditStep(step);setNotice('');setError('');}
 async function save(r:InspectionRecord,keepEditing=false):Promise<InspectionRecord>{const response=await fetch('/api/fire-inspections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)}),j=await response.json();if(!response.ok||!j.saved||!j.record)throw Error(j.error||'The server did not confirm the save. Retry with your draft still here.');const saved=[j.record,...(j.followUps||[])];setSnapshot(s=>({...s,records:[...saved,...s.records.filter(old=>!saved.some(n=>n.id===old.id))]}));clearBackup();if(keepEditing)return j.record;setEditing(null);route(r.kind==='template'?'Checklists':'Work queue',r.id);setNotice(`Saved · version ${j.record.version}${j.followUps?.length?` · ${j.followUps.length} follow-up(s) available below`:''}.`);return j.record;}
 async function mutate(r:InspectionRecord){setBusy(true);setError('');try{await save(r);}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 const records=snapshot.records.filter(r=>r.archived===showArchived&&(showTests||!r.data.test));
 const inspections=records.filter(r=>r.kind==='inspection');
 const visible=inspections.filter(r=>`${r.data.title} ${r.data.address} ${r.data.inspector} ${r.data.type}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='Active'?!['Completed','Canceled'].includes(r.data.status)||filter==='All':filter==='Completed'?r.data.status==='Completed':filter==='Needs scheduling'?r.data.status==='Needs scheduling'||(!r.data.scheduledDate&&r.data.status==='Draft'):queueLabel(r.data)===filter));
 const record=snapshot.records.find(r=>r.id===selected);
 const count=(f:(r:InspectionRecord)=>boolean)=>inspections.filter(f).length;
 const row=(r:InspectionRecord)=><article className="fi-row" key={r.id}><button className="fi-row-title" onClick={()=>route(r.kind==='template'?'Checklists':'Work queue',r.id)}><strong>{r.data.test?'TEST · ':''}{r.data.title}</strong><span>{r.data.type} · {r.data.address||'Address not recorded'}</span></button><div><span className={`fi-badge ${queueLabel(r.data)==='Past due'?'fi-overdue':''}`}>{queueLabel(r.data)}</span><small>{r.data.scheduledDate?`${r.data.scheduledDate} ${r.data.scheduledTime||'Time not set'}`:r.data.nextDueDate?`Due ${r.data.nextDueDate} · appointment needed`:'Date not set'}</small></div><div className="fi-actions">{r.data.status!=='Completed'&&r.data.status!=='Canceled'&&!r.archived&&<><button className="fi-primary" onClick={()=>edit({...r,data:{...r.data,status:'In progress',actualDate:r.data.actualDate||todayChicago()}},2)}>Start / continue</button><button onClick={()=>edit(r,1)}>{r.data.scheduledDate?'Reschedule':'Schedule'}</button></>}</div></article>;
 async function uploadTarget(file:File,target:{recordId?:string;codeId?:string;checkId?:string;caption?:string}){const body=new FormData();for(const[k,v]of Object.entries(target))if(v)body.append(k,v);body.append('file',file);const r=await fetch('/api/fire-inspections/files',{method:'POST',body}),j=await r.json();if(!r.ok)throw Error(j.error||'Upload was not confirmed.');setSnapshot(s=>({...s,attachments:[j.attachment,...s.attachments]}));}
 async function upload(file:File){if(!record)return;setBusy(true);setError('');try{await uploadTarget(file,{recordId:record.id});setNotice('Attachment saved privately.');}catch(e){setError(e instanceof Error?e.message:'Upload was not confirmed.');}finally{setBusy(false);}}
 async function showHistory(){setBusy(true);try{const r=await fetch(`/api/fire-inspections?history=${encodeURIComponent(selected)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setHistory(j.history);}catch(e){setError(String(e));}finally{setBusy(false);}}
 if(!loaded)return <section className="fi-workspace"><h2>Fire Inspections</h2><p>{error||'Loading your private inspection workspace…'}</p>{error&&<button onClick={load}>Retry loading</button>}</section>;
 return <section className="fi-workspace" aria-label="Private fire inspections">
  <header className="fi-heading fi-top"><div><span className="fi-eyebrow">FIRE PREVENTION · PRIVATE PILOT</span><h1>Fire Inspections</h1><p>Schedule a visit. Record what you find. Know what happens next.</p></div><span className="fi-badge">Only bobff353@gmail.com</span></header>
  {editing?<InspectionEditor key={editing.id+':'+editing.version} initial={editing} snapshot={snapshot} initialStep={editStep} recovered={recoveredEditing} onSave={save} onUpload={uploadTarget} onCancel={()=>{clearBackup();setEditing(null);}}/>:<>
  {recovery&&<div className="fi-note"><strong>Unsaved inspection available on this tab</strong><p>{recovery.record.data.title||'Untitled inspection'}. Continue the draft to review and save it. A newer saved version will still be protected from overwriting.</p><div className="fi-actions"><button onClick={()=>{edit(recovery.record,recovery.step,true);setRecovery(null);}}>Continue recovered draft</button><button onClick={()=>{if(window.confirm('Discard this browser draft? Saved inspections stay unchanged.'))clearBackup();}}>Discard browser draft</button></div></div>}
  <nav className="fi-tabs" aria-label="Fire inspection workspaces">{tabs.map(t=><button key={t} disabled={codeEditing} aria-current={t===tab?'page':undefined} onClick={()=>route(t)}>{t}</button>)}</nav>
  {error&&<div role="alert" className="fi-error">{error} <button onClick={load}>Refresh saved records</button></div>}{notice&&<div role="status" className="fi-success">{notice}</div>}
  {selected&&!record&&<p className="fi-note">This inspection is not available. <button onClick={()=>route('Work queue')}>Back to inspections</button></p>}
  {record?<>
   <button className="fi-link" onClick={()=>route(tab)}>← Back to {tab.toLowerCase()}</button>
   <div className="fi-heading"><div><h2>{record.data.test?'TEST · ':''}{record.data.title}</h2><p>{record.data.address} · {record.data.type}</p><small>Saved {new Date(record.updatedAt).toLocaleString()} · version {record.version}</small></div><span className="fi-badge">{record.data.status}</span></div>
   <div className="fi-actions fi-panel">{!record.archived&&record.data.status!=='Completed'&&<button className="fi-primary" onClick={()=>edit(record,record.kind==='template'?0:record.data.status==='In progress'?2:0)}>Edit {record.kind==='template'?'checklist':'inspection'}</button>}{!record.archived&&record.data.status==='Completed'&&<button onClick={()=>{const reason=window.prompt('Why does this completed report need a correction?');if(reason?.trim())void mutate({...record,data:{...record.data,status:'Draft',changeReason:reason.trim(),representative:blankSignature(),inspectorSignature:blankSignature(),inspectorAttested:false}});}}>Reopen for correction</button>}{record.kind==='inspection'&&<><a className="fi-button" href={`/api/fire-inspections/report?recordId=${encodeURIComponent(record.id)}&version=${record.version}`} target="_blank" rel="noreferrer">Download PDF report</a><button onClick={()=>download(`inspection-${record.id}.txt`,reportText(record))}>Text copy</button><button onClick={printReport}>Print / save PDF</button></>}<button disabled={busy} onClick={showHistory}>Version history</button><button disabled={busy} onClick={()=>{if(window.confirm(`${record.archived?'Restore':'Archive'} this private record? Its history will remain saved.`))void mutate({...record,archived:!record.archived});}}>{record.archived?'Restore':'Archive'}</button></div>
   {record.kind==='template'?<><p>{record.data.checks.length} checkpoints · {record.data.sections.join(', ')}</p><button className="fi-primary" onClick={()=>edit(newInspection('inspection',{checks:record.data.checks.map(c=>({...c,result:'Not checked',observation:'',correction:'',location:'',dueDate:'',correctedDate:''})),sections:record.data.sections}))}>Use this checklist for a visit</button></>:<>
    <div className="fi-summary fi-panel"><div><small>Visit</small><strong>{record.data.actualDate||record.data.scheduledDate||'Needs scheduling'}</strong><p>{record.data.inspector||'Inspector not recorded'}{record.data.others?` · With ${record.data.others}`:''}</p><p>{record.data.startTime||'Start time not recorded'} – {record.data.endTime||'End time not recorded'}</p></div><div><small>Outcome</small><strong>{record.data.outcome||'Not completed'}</strong><p>{findings(record.data).length} findings · {record.data.checks.filter(c=>c.result==='Not checked').length} unanswered</p></div><div><small>Next step</small><strong>{record.data.status==='Completed'?'Review follow-ups':record.data.scheduledDate?'Continue inspection':'Schedule the visit'}</strong><p>{record.data.nextDueDate?`Routine due ${record.data.nextDueDate}`:record.data.repeatMonths?`Every ${record.data.repeatMonths} months · calculate next date when finishing`:'No routine recurrence set'}</p></div></div>
    <section className="fi-panel"><h3>Contacts & code basis</h3><p>Owner: {record.data.owner||'Not recorded'}</p><p>{record.data.contact||'Contact not recorded'} · {record.data.email||'Email not recorded'} · {record.data.phone||'Phone not recorded'}</p><p>Occupancy: {record.data.occupancy||'Not recorded'} · Code: {record.data.codeEdition||'Not verified'}</p><ul>{(record.data.codeBasis||[]).map(c=><li key={c.id+":"+c.version}>{codeLabel(c)} · library version {c.version}</li>)}</ul><p>Local amendments: {record.data.localAmendments||'Not recorded'}</p><p>Visit reason: {record.data.reason||'Not recorded'}</p>{record.data.propertyId&&<a href={`?page=field-preplans&display=portal&preplan=${encodeURIComponent(record.data.propertyId)}`}>Open linked property / preplan →</a>}</section>
    <section className="fi-panel"><h3>Follow-up visits</h3>{snapshot.records.filter(r=>r.data.parentId===record.id).map(row)}{!snapshot.records.some(r=>r.data.parentId===record.id)&&<p>No follow-ups created. Set recurrence or a reinspection date before finishing.</p>}{record.data.parentId&&<button onClick={()=>route('Work queue',record.data.parentId)}>Open original inspection and findings →</button>}</section>
    <section className="fi-panel"><h3>Report & findings</h3>{record.data.checks.map(c=><details key={c.id} className="fi-saved-check"><summary><span>{c.label}</span><strong>{c.result}</strong></summary><p>Location: {c.location||'Not recorded'}</p><p>{c.observation||'No observation note'}</p><p>Priority: {c.priority}</p><p>Action: {c.correction||'Not recorded'}</p><p>Citation: {c.code||'Not verified'} · Due: {c.dueDate||'Not set'} · Corrected: {c.correctedDate||'Not recorded'}</p><ul>{(c.citations||[]).map(code=><li key={code.id+":"+code.version}>{codeLabel(code)} · library version {code.version}</li>)}</ul><EvidencePhotos label={c.label} files={snapshot.attachments.filter(f=>f.recordId===record.id&&f.checkId===c.id)}/><small>{c.source}</small></details>)}<p>{record.data.notes}</p></section>
    <section className="fi-panel"><h3>Acknowledgments & delivery</h3><p>Representative: {record.data.representative.name||'Not recorded'} · {record.data.representative.role||'Role not recorded'} · {record.data.representative.state}</p>{record.data.representative.state==='Signed'&&<><svg className="fi-saved-signature" viewBox="0 0 600 160" preserveAspectRatio="none" aria-label="Saved representative signature">{record.data.representative.strokes.map((stroke,i)=><polyline key={i} points={stroke.map(p=>`${p[0]*600},${p[1]*160}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5"/>)}</svg><small>Captured {record.data.representative.signedAt}</small></>}<p>Inspector review: {record.data.inspectorAttested?`Acknowledged in version ${record.version} saved by ${record.updatedBy}`:'Not acknowledged'}</p>{record.data.inspectorSignature?.state==='Signed'&&<><h4>Inspector signature · {record.data.inspectorSignature.name}</h4><svg className="fi-saved-signature" viewBox="0 0 600 160" preserveAspectRatio="none" aria-label="Saved inspector signature">{record.data.inspectorSignature.strokes.map((stroke,i)=><polyline key={i} points={stroke.map(p=>`${p[0]*600},${p[1]*160}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5"/>)}</svg></>}<p>Reinspection: {record.data.reinspectionDecision||'Not recorded'} {record.data.followUpDate} {record.data.reinspectionTime} {record.data.reinspectionReason}</p><p>Push reminders: not enabled for this private pilot. Saved records appear in your work queue with due-in-2-weeks, due-in-1-week, and past-due labels.</p></section><ReportDelivery key={record.id+":"+record.version} record={record}/>
   </>}
   <section className="fi-panel"><h3>Photos, plans & reports</h3><p>Private PDF, JPG, PNG, or WebP · up to 4 MB each.</p>{!record.archived&&record.data.status!=="Completed"&&<label className="fi-field">Attach a file<input type="file" disabled={busy} accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label>}{snapshot.attachments.filter(a=>a.recordId===record.id).map(a=><p key={a.id}><a href={`/api/fire-inspections/files/${encodeURIComponent(a.id)}`}>{a.filename}</a> · {Math.ceil(a.size/1024)} KB</p>)}</section>
   {history&&<section className="fi-panel"><h3>Saved version history</h3>{history.map(h=><details key={h.version}><summary>Version {h.version} · {new Date(h.createdAt).toLocaleString()} · {h.actor}</summary><p>{h.archived?'Archived':'Active'} · {JSON.parse(h.payload).status} · {JSON.parse(h.payload).changeReason||'No correction reason'}</p><button onClick={()=>download(`inspection-${record.id}-version-${h.version}.json`,h.payload,'application/json')}>Download this saved version</button></details>)}</section>}
  </>:<>
  {tab==='Work queue'&&<>
   <div className="fi-launch"><button className="fi-primary" onClick={()=>edit(newInspection(),0)}><strong>+ Schedule inspection</strong><span>Choose property, date, and checklist</span></button><button onClick={()=>edit(newInspection('inspection',{status:'In progress',actualDate:todayChicago()}),0)}><strong>Start a visit now</strong><span>Record findings as you walk</span></button><button onClick={()=>{setFilter('Needs scheduling');}}><strong>Review follow-ups</strong><span>Find visits that need a date</span></button></div>
   <div className="fi-metrics">{[['Past due',count(r=>queueLabel(r.data)==='Past due')],['Due today',count(r=>queueLabel(r.data)==='Due today')],['Needs scheduling',count(r=>r.data.status==='Needs scheduling')],['Completed',count(r=>r.data.status==='Completed')]].map(([label,n])=><button key={label} onClick={()=>setFilter(String(label))}><strong>{n}</strong><span>{label}</span></button>)}</div>
   <div className="fi-toolbar"><label className="fi-field">Find an inspection<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business, address, inspector…"/></label><label className="fi-field">Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Active','All','Draft','Needs scheduling','Due today','Due within 1 week','Due within 2 weeks','Past due','Completed'].map(f=><option key={f}>{f}</option>)}</select></label><label className="fi-check"><input type="checkbox" checked={showTests} onChange={e=>setShowTests(e.target.checked)}/>Include tests</label><label className="fi-check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Archived</label></div>
   <div className="fi-panel">{visible.map(row)}{visible.length===0&&<div className="fi-empty"><h3>{inspections.length?'No matching inspections':'Your inspection workspace is ready'}</h3><p>{inspections.length?'Change the filter or search to find another record.':'Choose Schedule inspection or Start a visit now. Existing preplan properties are available to select.'}</p></div>}</div>
  </>}
  {tab==='Calendar'&&<><div className="fi-heading"><div><h2>Inspection calendar</h2><p>Appointments and follow-up due dates. Times use the department’s local clock.</p></div><label className="fi-field">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>{inspections.filter(r=>(r.data.scheduledDate||r.data.nextDueDate).startsWith(month)&&r.data.status!=='Canceled').sort((a,b)=>(a.data.scheduledDate||a.data.nextDueDate).localeCompare(b.data.scheduledDate||b.data.nextDueDate)).map(row)}{!inspections.some(r=>(r.data.scheduledDate||r.data.nextDueDate).startsWith(month))&&<p className="fi-panel">No visits scheduled or due in this month.</p>}<button onClick={()=>edit(newInspection())}>+ Schedule inspection</button></>}
  {tab==='Properties'&&<><h2>Choose a property</h2><label className="fi-field">Search properties<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business or address"/></label><div className="fi-picker fi-property-list">{snapshot.properties.filter(p=>`${p.name} ${p.address}`.toLowerCase().includes(query.toLowerCase())).slice(0,100).map(p=><article className="fi-row" key={p.id}><div><strong>{p.name}</strong><p>{p.address}</p></div><button onClick={()=>edit(newInspection('inspection',{title:p.name,address:p.address,propertyId:p.id}),1)}>Schedule a visit →</button></article>)}</div><p>Showing up to 100 matching preplan properties. Selecting a property does not edit its preplan.</p><button onClick={()=>edit(newInspection())}>Inspect a property not listed</button></>}
  {tab==='Checklists'&&<><div className="fi-heading"><div><h2>Your reusable checklists</h2><p>Choose topics and add your own checkpoints. Each new visit starts unanswered.</p></div><button className="fi-primary" onClick={()=>edit(newInspection('template'))}>+ Build checklist</button></div>{snapshot.records.filter(r=>r.kind==='template'&&!r.archived).map(r=><article className="fi-row" key={r.id}><button className="fi-row-title" onClick={()=>route('Checklists',r.id)}><strong>{r.data.title}</strong><span>{r.data.checks.length} checkpoints</span></button><button onClick={()=>edit(r)}>Edit checklist</button></article>)}{!snapshot.records.some(r=>r.kind==='template'&&!r.archived)&&<div className="fi-panel"><h3>Start with the included inspection topics</h3><p>Access, occupancy, egress, building systems, water systems, alarms, extinguishers, cooking suppression, hazardous materials, plans, and follow-up. Save your selections as a checklist.</p><button onClick={()=>edit(newInspection('template',{title:'General fire / life safety'}),1)}>Customize general checklist →</button></div>}</>}
  {tab==='Code library'&&<CodeLibrary onEditingChange={setCodeEditing} entries={snapshot.codes||[]} files={snapshot.attachments} onSaved={entry=>setSnapshot(s=>({...s,codes:[entry,...(s.codes||[]).filter(c=>c.id!==entry.id)]}))} onUpload={uploadTarget}/>}
  {tab==='Quick reference'&&<><h2>Find the next step</h2><p>Procedure prompts based on your supplied slides and IFSTA reference. Verify adopted code, edition, amendments, and property conditions before citing a requirement.</p><label className="fi-field">Search inspection guidance<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hood, citation, change of use, follow-up…"/></label>{quickReferences.filter(r=>`${r.title} ${r.tags} ${r.text}`.toLowerCase().includes(query.toLowerCase())).map(r=><article className="fi-panel" key={r.title}><h3>{r.title}</h3><p>{r.text}</p><small>{r.source}</small></article>)}<section className="fi-panel"><h3>Reference library</h3><p>IFSTA: Fire Inspection and Code Enforcement, 9th edition. Procedure and report workflow reviewed from Chapter 16, including pages 561–562. Jones & Bartlett: the 14 chapter slide decks you supplied; the local files were read without loading large slide decks in Chrome.</p><p><a href={IFSTA_URL} target="_blank" rel="noreferrer">Open your IFSTA library ↗</a></p><p><a href="https://sfm.illinois.gov/about/divisions/fire-prevention-and-building-safety.html" target="_blank" rel="noreferrer">Illinois OSFM Fire Prevention ↗</a> · <a href="https://www.nfpa.org/for-professionals/codes-and-standards" target="_blank" rel="noreferrer">NFPA codes and standards ↗</a> · <a href="https://codes.iccsafe.org/" target="_blank" rel="noreferrer">ICC code library ↗</a></p><p>Teaching materials guide the workflow. They are not a verified local code adoption list. This pilot does not copy the books, issue enforcement orders, or communicate with ESO.</p></section></>}
  </>}
  </>}
 </section>;
}
