export type SafetyInspectionTemplateSeed = {
  id: string;
  slug: string;
  title: string;
  description: string;
  cadence: "weekly" | "monthly";
  category: string;
  locationOptions: string[];
};

export type SafetyInspectionItemSeed = {
  id: string;
  templateId: string;
  section: string;
  label: string;
  detail: string;
  required: number;
  sortOrder: number;
};

export const safetyInspectionTemplates: SafetyInspectionTemplateSeed[] = [
  {
    id: "monthly-public-works-extinguishers",
    slug: "public-works-monthly-fire-extinguishers",
    title: "Public Works Monthly Fire Extinguisher Inspection",
    description: "Monthly inspection of the extinguishers assigned to the Public Works garage, spare storage, vehicles, and gas pump.",
    cadence: "monthly",
    category: "Fire extinguishers",
    locationOptions: [],
  },
  {
    id: "monthly-pump-station-extinguishers",
    slug: "pump-station-monthly-fire-extinguishers",
    title: "Pump Station Monthly Fire Extinguisher Inspection",
    description: "Monthly inspection of the extinguishers at the Pump Station first floor, basement, and generator building.",
    cadence: "monthly",
    category: "Fire extinguishers",
    locationOptions: [],
  },
  {
    id: "monthly-village-hall-police-extinguishers",
    slug: "village-hall-police-monthly-fire-extinguishers",
    title: "Village Hall and Police Department Fire Extinguisher Inspection",
    description: "Monthly extinguisher and AED readiness inspection for the Police Department, basement, and Village Hall.",
    cadence: "monthly",
    category: "Fire extinguishers",
    locationOptions: [],
  },
  {
    id: "weekly-eyewash-inspection",
    slug: "weekly-eye-wash-inspection",
    title: "Weekly Eye Wash Inspection",
    description: "Weekly operational check of the five department eyewash locations.",
    cadence: "weekly",
    category: "Safety equipment",
    locationOptions: [],
  },
  {
    id: "monthly-general-safety-inspection",
    slug: "monthly-safety-inspection",
    title: "Monthly Safety Inspection",
    description: "Comprehensive monthly safety inspection covering work practices, postings, fire control, housekeeping, electrical, sanitation, equipment, and building systems.",
    cadence: "monthly",
    category: "Facility safety",
    locationOptions: ["Fire Department", "Village Hall", "Police station"],
  },
];

const rows = (
  templateId: string,
  prefix: string,
  values: Array<[section: string, label: string, detail?: string, required?: number]>,
): SafetyInspectionItemSeed[] => values.map(([section, label, detail = "", required = 1], index) => ({
  id: `${prefix}-${String(index + 1).padStart(3, "0")}`,
  templateId,
  section,
  label,
  detail,
  required,
  sortOrder: (index + 1) * 10,
}));

export const safetyInspectionItems: SafetyInspectionItemSeed[] = [
  ...rows("monthly-public-works-extinguishers", "pw-ext", [
    ["Garage", "Hall by men's room", "10 lb dry chemical"],
    ["Garage", "Garage Door #1 — northeast", "2.5 lb dry chemical"],
    ["Garage", "Garage Door #2 — west", "20 lb dry chemical"],
    ["Garage", "Garage Door #3 — west", "10 lb dry chemical"],
    ["Garage", "Garage Door #4 — southeast", "10 lb dry chemical"],
    ["Garage", "Garage Door #5 — east by bench", "5 lb dry chemical"],
    ["Spare extinguishers under stairs", "Spare 10 lb dry chemical #1", "10 lb dry chemical", 0],
    ["Spare extinguishers under stairs", "Spare 5 lb dry chemical #1", "5 lb dry chemical", 0],
    ["Spare extinguishers under stairs", "Spare 10 lb dry chemical #2", "10 lb dry chemical", 0],
    ["Spare extinguishers under stairs", "Spare 5 lb dry chemical #2", "5 lb dry chemical", 0],
    ["Spare extinguishers under stairs", "Spare cartridge unit", "20 lb dry chemical cartridge", 0],
    ["Vehicles", "Bobcat", "5 lb dry chemical"],
    ["Vehicles", "Truck 8 — black pickup", "5 lb dry chemical", 0],
    ["Vehicles", "T-7 — large dump truck", "5 lb dry chemical", 0],
    ["Vehicles", "T-13 — white dump truck", "5 lb dry chemical", 0],
    ["Vehicles", "Komatsu", "2.5 lb dry chemical"],
    ["Vehicles", "T-3 — water SUV", "5 lb dry chemical", 0],
    ["Vehicles", "T-12 — black dump truck", "5 lb dry chemical", 0],
    ["Vehicles", "T-5 — red pickup", "Size not entered", 0],
    ["Vehicles", "Truck 1 — garbage truck", "5 lb dry chemical"],
    ["Vehicles", "Kubota", "2.5 lb dry chemical", 0],
    ["Vehicles", "T-4 — Dodge pickup", "5 lb dry chemical", 0],
    ["Vehicles", "Sweeper", "2.5 lb dry chemical", 0],
    ["Gas pump", "Gas pump extinguisher", "10 lb dry chemical", 0],
  ]),
  ...rows("monthly-pump-station-extinguishers", "pump-ext", [
    ["1st Floor", "By front door", "10 lb dry chemical"],
    ["Basement", "By stairs", "10 lb CO₂"],
    ["Generator Building", "By door", "10 lb dry chemical"],
  ]),
  ...rows("monthly-village-hall-police-extinguishers", "vhpd-ext", [
    ["1st Floor PD", "Hall by Dispatch", "10 lb dry chemical"],
    ["1st Floor PD", "Lock up", "10 lb dry chemical"],
    ["1st Floor PD", "PD Garage", "10 lb dry chemical"],
    ["1st Floor PD", "Hall by Detective's office", "10 lb dry chemical"],
    ["1st Floor PD", "Men's room", "10 lb dry chemical"],
    ["1st Floor PD", "By back door", "10 lb dry chemical"],
    ["1st Floor PD", "Zoll AED monitor", "AED"],
    ["Basement", "Electrical room", "10 lb dry chemical"],
    ["Basement", "Gun Range", "10 lb dry chemical"],
    ["Basement", "Maintenance room — front", "10 lb dry chemical"],
    ["Basement", "Maintenance room — back", "10 lb CO₂"],
    ["Village Hall", "Hall by storage rooms", "10 lb dry chemical"],
    ["Village Hall", "Outside clerk's office", "10 lb dry chemical"],
    ["Village Hall", "Clerk office closet", "10 lb dry chemical"],
    ["Village Hall", "Outside break room", "5 lb dry chemical"],
    ["Village Hall", "Outside trustee's office", "5 lb dry chemical"],
  ]),
  ...rows("weekly-eyewash-inspection", "eyewash", [
    ["Location", "Fire Department", "Apparatus floor"],
    ["Location", "Police Department", "Hall by bathrooms"],
    ["Location", "Public Works", "Under stairs"],
    ["Location", "Police Department", "Gun Range basement"],
    ["Location", "Pump Station", "Main room"],
  ]),
  ...rows("monthly-general-safety-inspection", "monthly-safe", [
    ["Safe Work Practice", "Employees in good health and dressed in uniform"],
    ["Safe Work Practice", "Proper protective equipment used as required"],
    ["Safe Work Practice", "Employee workplace clean and orderly; free of spills and oil"],
    ["Safe Work Practice", "Safe operating procedures followed when moving vehicles"],
    ["Safe Work Practice", "Ventilating devices used when engines run inside"],
    ["Safe Work Practice", "Compressed gas cylinders stored upright and properly secured"],
    ["Safe Work Practice", "Public access restricted"],
    ["Safe Work Practice", "Equipment and machine guards in place"],
    ["Safe Work Practice", "Tools and machines used properly"],
    ["Safe Work Practice", "Tools and machines properly maintained"],
    ["Safe Work Practice", "Flame- or spark-producing operations isolated from flammable liquids"],
    ["Safe Work Practice", "Flammables kept in proper containers and stored properly"],
    ["Safe Work Practice", "Flammable liquid spills cleaned up immediately"],
    ["Bulletin Board & Records", "OSHA labor poster posted"],
    ["Bulletin Board & Records", "State labor poster posted"],
    ["Bulletin Board & Records", "State Department of Unemployment poster posted"],
    ["Bulletin Board & Records", "Equal Employment Opportunity poster posted"],
    ["Bulletin Board & Records", "State sexual harassment notice poster posted"],
    ["Bulletin Board & Records", "Family Medical Leave Act poster posted"],
    ["Bulletin Board & Records", "Minimum wage poster posted"],
    ["Bulletin Board & Records", "Medical network and work-related injury processing procedure poster posted"],
    ["Bulletin Board & Records", "Discrimination in employment poster posted"],
    ["Office / Administration Area", "Employees in good health and dressed properly"],
    ["Office / Administration Area", "Equipment used properly"],
    ["Office / Administration Area", "Housekeeping kept up"],
    ["Office / Administration Area", "Unattended files and desk drawers closed"],
    ["Office / Administration Area", "Only one file drawer open at a time"],
    ["Fire Control", "Fire doors closed and free of obstacles"],
    ["Fire Control", "Exits clearly marked and non-exits marked"],
    ["Fire Control", "Fire instructions posted"],
    ["Fire Control", "Emergency evacuation plan posted"],
    ["Fire Control", "Fire extinguishers in good condition, at proper height, and inspected monthly"],
    ["Fire Control", "Hazardous materials located away from heat, flame, water, and damage"],
    ["Fire Control", "Hazardous operations isolated, including welding, grinding, and cutting"],
    ["Housekeeping — All Areas", "Floors clean, free of defects, grease, and oil spills"],
    ["Housekeeping — All Areas", "Trash containers sufficient in number and not overflowing"],
    ["Housekeeping — All Areas", "Permanent ladders firmly attached and in good condition"],
    ["Housekeeping — All Areas", "Ladders stored properly and free of defects"],
    ["Housekeeping — All Areas", "Stairs clear and in good condition"],
    ["Housekeeping — All Areas", "Storage areas neatly kept"],
    ["Housekeeping — All Areas", "Cleaning supplies readily available"],
    ["Exterior and Parking Areas", "Parking surface free of holes and debris"],
    ["Exterior and Parking Areas", "Sidewalks free of trip hazards"],
    ["Exterior and Parking Areas", "Fuel island clean and posted No Smoking"],
    ["Exterior and Parking Areas", "Fire extinguisher available at fuel island"],
    ["Electrical", "Permanent wiring boxes, switches, outlets, and lights secure"],
    ["Electrical", "36-inch clearance maintained around electrical panel"],
    ["Electrical", "Breakers and fuse panels properly maintained and closed"],
    ["Electrical", "Extension cords, portable lights, and tool wiring free of cuts or damage"],
    ["Electrical", "Protective devices for equipment in use"],
    ["Electrical", "Electrical outlet covers in place"],
    ["Electrical", "GFCI outlets tested and operational"],
    ["Electrical", "Extension cords used only temporarily"],
    ["Electrical", "Lighting sufficient and free from glare"],
    ["Health & Sanitation", "Food area clean and maintained"],
    ["Health & Sanitation", "Bathrooms clean and properly maintained"],
    ["Health & Sanitation", "Noise protection present and used properly"],
    ["Health & Sanitation", "Ventilation adequate, including special venting as needed"],
    ["Health & Sanitation", "Protective equipment adequate, neatly stored, accessible, and used"],
    ["Health & Sanitation", "Eyewash station present and in good working condition"],
    ["Machines, Equipment & Tools", "Electrical equipment and tools protected by grounding or insulation"],
    ["Machines, Equipment & Tools", "Moving parts within seven feet of floor enclosed"],
    ["Machines, Equipment & Tools", "Machines guarded at point of operation"],
    ["Machines, Equipment & Tools", "Hand tools in good working condition"],
    ["Machines, Equipment & Tools", "Hoists and jacks marked for weight rating"],
    ["Machines, Equipment & Tools", "Pre-use inspections conducted for all hoists and jacks"],
    ["Machines, Equipment & Tools", "Hoists, ropes, slings, jacks, and hooks in good working condition"],
    ["Miscellaneous Items", "Exit lighting checked and operational"],
    ["Miscellaneous Items", "Emergency lighting tested and operational"],
    ["Miscellaneous Items", "Hood and duct system inspected and operational"],
    ["Miscellaneous Items", "Sprinkler control valve open"],
    ["Miscellaneous Items", "Riser clear of obstructions"],
    ["Miscellaneous Items", "Sprinkler heads unobstructed and free of debris"],
    ["Miscellaneous Items", "Fire Department connection unobstructed and in good condition"],
    ["Miscellaneous Items", "Hydrant accessible and operating properly"],
    ["Miscellaneous Items", "Door bells operate"],
    ["Miscellaneous Items", "Bay door reverse sensor operational"],
    ["Miscellaneous Items", "Ceiling tiles intact and in place"],
    ["Miscellaneous Items", "Eyewash station bottles intact and not expired"],
    ["Miscellaneous Items", "Hot water tank relief valve operational"],
  ]),
];
