do $$
declare
  stickney_id uuid;
  engine_1201_id uuid;
begin
  select id into stickney_id
  from public.departments
  where name = 'Stickney Fire Department'
  limit 1;

  select id into engine_1201_id
  from public.inventory_apparatus_profiles
  where department_id = stickney_id and name = '1201'
  limit 1;

  if stickney_id is null or engine_1201_id is null then
    raise exception 'Stickney Fire Department apparatus 1201 must exist before loading form 248';
  end if;

  insert into public.inventory_compartments
    (department_id, apparatus_id, label, side, sort_order)
  values
    (stickney_id, engine_1201_id, 'Vehicle', 'cab', 100),
    (stickney_id, engine_1201_id, 'Front Tires', 'front', 110),
    (stickney_id, engine_1201_id, 'Rear Tires', 'rear', 120),
    (stickney_id, engine_1201_id, 'Cab', 'cab', 130),
    (stickney_id, engine_1201_id, 'Cab - Cabinet', 'cab', 140),
    (stickney_id, engine_1201_id, 'Glove box', 'cab', 150),
    (stickney_id, engine_1201_id, 'Pump / Booster & Foam Tank', 'pump', 160),
    (stickney_id, engine_1201_id, 'SCBA', 'cab', 170),
    (stickney_id, engine_1201_id, 'Compartment 1 (Top)', 'driver', 200),
    (stickney_id, engine_1201_id, 'Compartment 1 (Bottom)', 'driver', 210),
    (stickney_id, engine_1201_id, 'Driver Side Fold-Up Step', 'driver', 220),
    (stickney_id, engine_1201_id, 'Compartment 2', 'driver', 230),
    (stickney_id, engine_1201_id, 'Compartment 3 (Top)', 'driver', 240),
    (stickney_id, engine_1201_id, 'Compartment 3 (Bottom)', 'driver', 250),
    (stickney_id, engine_1201_id, 'Compartment 4', 'driver', 260),
    (stickney_id, engine_1201_id, 'Rear (Driver Side)', 'rear', 270),
    (stickney_id, engine_1201_id, 'Rear (Officer Side)', 'rear', 280),
    (stickney_id, engine_1201_id, 'Compartment 5', 'officer', 290),
    (stickney_id, engine_1201_id, 'Compartment 6', 'officer', 300),
    (stickney_id, engine_1201_id, 'Compartment 7 (Top)', 'officer', 310),
    (stickney_id, engine_1201_id, 'Compartment 7 (Bottom)', 'officer', 320),
    (stickney_id, engine_1201_id, 'Top of Engine', 'roof', 330),
    (stickney_id, engine_1201_id, 'Hose', 'rear', 340)
  on conflict (apparatus_id, label) do update
  set side = excluded.side,
      sort_order = excluded.sort_order;

  with source_items(section_label, item_name, quantity_required, equipment_category, check_types, item_order) as (
    values
      ('Vehicle','Record mileage',1,'vehicle',array['weekly'],1),
      ('Vehicle','Fuel (must be 3/4)',1,'vehicle',array['weekly'],2),
      ('Vehicle','Airhorn operational',1,'vehicle',array['weekly'],3),
      ('Vehicle','Vehicle horn operational',1,'vehicle',array['weekly'],4),
      ('Vehicle','Siren operational',1,'vehicle',array['weekly'],5),
      ('Vehicle','Parking brake operational',1,'vehicle',array['weekly'],6),
      ('Vehicle','Head lights / brake lights / turn signals operational',1,'vehicle',array['weekly'],7),
      ('Vehicle','Emergency lights operational',1,'vehicle',array['weekly'],8),
      ('Vehicle','Transmission fluid (engine must be running)',1,'vehicle',array['weekly'],9),
      ('Vehicle','Antifreeze / radiator level',1,'vehicle',array['weekly'],10),
      ('Vehicle','Engine oil',1,'vehicle',array['weekly'],11),
      ('Vehicle','Body condition',1,'vehicle',array['weekly'],12),
      ('Vehicle','Wheel and tire condition',1,'vehicle',array['weekly'],13),
      ('Front Tires','Left PSI',1,'vehicle',array['weekly'],1),
      ('Front Tires','Right PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Left inner PSI',1,'vehicle',array['weekly'],1),
      ('Rear Tires','Left outer PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Right inner PSI',1,'vehicle',array['weekly'],3),
      ('Rear Tires','Right outer PSI',1,'vehicle',array['weekly'],4),
      ('Cab','Door opener',1,'equipment',array['weekly'],1),
      ('Cab','5 gas meter (fully charged)',1,'equipment',array['weekly'],2),
      ('Cab','Portable radios (charged and on channel 1)',4,'equipment',array['weekly'],3),
      ('Cab','Fuel card and PIN',1,'equipment',array['weekly'],4),
      ('Cab','Hi-vis safety vests',5,'equipment',array['weekly'],5),
      ('Cab','F.V. / Lyons map',1,'equipment',array['weekly'],6),
      ('Cab','Box lights',4,'equipment',array['weekly'],7),
      ('Cab','Haz-Mat Guide for First Responders',1,'equipment',array['weekly'],8),
      ('Cab','Thermal imaging camera (TIC), charged',1,'equipment',array['weekly'],9),
      ('Cab','Knox Box keys',1,'equipment',array['weekly'],10),
      ('Cab','Gloves (various sizes)',1,'equipment',array['weekly'],11),
      ('Cab','LVAD papers',1,'equipment',array['weekly'],12),
      ('Cab','SCBA harness',4,'air_pack',array['air_pack'],1),
      ('Cab - Cabinet','Bag of surgical masks',5,'equipment',array['weekly'],1),
      ('Cab - Cabinet','AED',1,'equipment',array['weekly'],2),
      ('Cab - Cabinet','EMS bag',1,'equipment',array['weekly'],3),
      ('Cab - Cabinet','EMS bag O2 level',1,'equipment',array['weekly'],4),
      ('Cab - Cabinet','Officer''s clipboard (stocked)',1,'equipment',array['weekly'],5),
      ('Cab - Cabinet','Rescue disc',1,'equipment',array['weekly'],6),
      ('Cab - Cabinet','PPE bags with N95, surgical mask and gown',12,'equipment',array['weekly'],7),
      ('Cab - Cabinet','TIFF meter',1,'equipment',array['weekly'],8),
      ('Cab - Cabinet','Binoculars',2,'equipment',array['weekly'],9),
      ('Cab - Cabinet','Barrier tape',1,'equipment',array['weekly'],10),
      ('Cab - Cabinet','Passport board',1,'equipment',array['weekly'],11),
      ('Cab - Cabinet','Dish soap',1,'equipment',array['weekly'],12),
      ('Cab - Cabinet','Duct tape',1,'equipment',array['weekly'],13),
      ('Cab - Cabinet','School maps',1,'equipment',array['weekly'],14),
      ('Cab - Cabinet','Pre-plan book',1,'equipment',array['weekly'],15),
      ('Cab - Cabinet','Box card binder',1,'equipment',array['weekly'],16),
      ('Glove box','ERG book',1,'equipment',array['weekly'],1),
      ('Glove box','Knox key wrench',1,'equipment',array['weekly'],2),
      ('Glove box','Accident envelope',1,'equipment',array['weekly'],3),
      ('Glove box','Hand sanitizer',1,'equipment',array['weekly'],4),
      ('Glove box','Insurance card',1,'equipment',array['weekly'],5),
      ('Glove box','EMS cabinet keys',1,'equipment',array['weekly'],6),
      ('Glove box','Goggles',2,'equipment',array['weekly'],7),
      ('Glove box','Fuse puller',1,'equipment',array['weekly'],8),
      ('Glove box','Terrorism book',1,'equipment',array['weekly'],9),
      ('Pump / Booster & Foam Tank','Water level',1,'vehicle',array['weekly'],1),
      ('Pump / Booster & Foam Tank','Foam level',1,'vehicle',array['weekly'],2),
      ('Pump / Booster & Foam Tank','Vehicle goes into pump and recirculates water',1,'vehicle',array['weekly'],3),
      ('SCBA','Officer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['air_pack'],1),
      ('SCBA','Engineer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['air_pack'],2),
      ('SCBA','Rear 1 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['air_pack'],3),
      ('SCBA','Rear 2 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['air_pack'],4),
      ('SCBA','Rear 3 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['air_pack'],5),
      ('SCBA','Driver side torpedo front 30 minute bottle at 4500 PSI',1,'air_pack',array['air_pack'],6),
      ('SCBA','Driver side torpedo rear 30 minute bottle at 4500 PSI',1,'air_pack',array['air_pack'],7),
      ('SCBA','Officer side torpedo front 60 minute bottle at 4500 PSI',1,'air_pack',array['air_pack'],8),
      ('SCBA','Officer side torpedo rear 60 minute bottle at 4500 PSI',1,'air_pack',array['air_pack'],9),
      ('SCBA','Compartment 3 spare cylinder 1 at 4500 PSI',1,'air_pack',array['air_pack'],10),
      ('SCBA','Compartment 3 spare cylinder 2 at 4500 PSI',1,'air_pack',array['air_pack'],11),
      ('SCBA','Compartment 3 spare cylinder 3 at 4500 PSI',1,'air_pack',array['air_pack'],12),
      ('Compartment 1 (Top)','TFT nozzle with 2.5 inch adapter',1,'equipment',array['inventory'],1),
      ('Compartment 1 (Top)','2.5 inch foam nozzle',1,'equipment',array['inventory'],2),
      ('Compartment 1 (Top)','Master stream fog',1,'equipment',array['inventory'],3),
      ('Compartment 1 (Top)','2.5 inch MacNeal adapters',2,'equipment',array['inventory'],4),
      ('Compartment 1 (Top)','2.5 inch to 1.5 inch reducer',1,'equipment',array['inventory'],5),
      ('Compartment 1 (Top)','Storz to 2.5 inch elbow',1,'equipment',array['inventory'],6),
      ('Compartment 1 (Top)','Storz to 4.5 inch female',1,'equipment',array['inventory'],7),
      ('Compartment 1 (Top)','Storz to 4.5 inch male',1,'equipment',array['inventory'],8),
      ('Compartment 1 (Top)','4 inch to 5 inch Storz',1,'equipment',array['inventory'],9),
      ('Compartment 1 (Top)','4.5 inch female to 4 inch male (Berwyn / Cicero)',1,'equipment',array['inventory'],10),
      ('Compartment 1 (Top)','Double male',1,'equipment',array['inventory'],11),
      ('Compartment 1 (Top)','Double female',1,'equipment',array['inventory'],12),
      ('Compartment 1 (Top)','Wye',1,'equipment',array['inventory'],13),
      ('Compartment 1 (Top)','2.5 inch distributor nozzle',1,'equipment',array['inventory'],14),
      ('Compartment 1 (Top)','Towel',1,'equipment',array['inventory'],15),
      ('Compartment 1 (Top)','Foam eductor (handheld)',1,'equipment',array['inventory'],16),
      ('Compartment 1 (Top)','Foam eductor (on-board)',1,'equipment',array['inventory'],17),
      ('Compartment 1 (Top)','CST tool',1,'equipment',array['inventory'],18),
      ('Compartment 1 (Top)','Spanners',2,'equipment',array['inventory'],19),
      ('Compartment 1 (Top)','Hard suction spanner',1,'equipment',array['inventory'],20),
      ('Compartment 1 (Top)','Storz spanners',4,'equipment',array['inventory'],21),
      ('Compartment 1 (Top)','Hydrant wrench',1,'equipment',array['inventory'],22),
      ('Compartment 1 (Top)','Barrier tape',1,'equipment',array['inventory'],23),
      ('Compartment 1 (Top)','Hose chart',1,'equipment',array['inventory'],24),
      ('Compartment 1 (Top)','Hose jacket',1,'equipment',array['inventory'],25),
      ('Compartment 1 (Bottom)','Hose clamp',1,'equipment',array['inventory'],1),
      ('Compartment 1 (Bottom)','Cheater bar',1,'equipment',array['inventory'],2),
      ('Compartment 1 (Bottom)','Hose roller',1,'equipment',array['inventory'],3),
      ('Compartment 1 (Bottom)','PPV fan',1,'equipment',array['inventory'],4),
      ('Compartment 1 (Bottom)','Roll of 4 inch hose',1,'equipment',array['inventory'],5),
      ('Compartment 1 (Bottom)','Tool box - sprinkler stops',4,'equipment',array['inventory'],6),
      ('Compartment 1 (Bottom)','Tool box - duct tape',1,'equipment',array['inventory'],7),
      ('Compartment 1 (Bottom)','Tool box - claw hammer',1,'equipment',array['inventory'],8),
      ('Compartment 1 (Bottom)','Tool box - flat screwdrivers',3,'equipment',array['inventory'],9),
      ('Compartment 1 (Bottom)','Tool box - Phillips screwdrivers',3,'equipment',array['inventory'],10),
      ('Compartment 1 (Bottom)','Tool box - electrical tape',2,'equipment',array['inventory'],11),
      ('Compartment 1 (Bottom)','Tool box - crescent wrenches',2,'equipment',array['inventory'],12),
      ('Compartment 1 (Bottom)','Tool box - pipe wrenches',2,'equipment',array['inventory'],13),
      ('Compartment 1 (Bottom)','Tool box - channel locks',1,'equipment',array['inventory'],14),
      ('Compartment 1 (Bottom)','Tool box - vice grips',1,'equipment',array['inventory'],15),
      ('Compartment 1 (Bottom)','Tool box - cable cutters',1,'equipment',array['inventory'],16),
      ('Compartment 1 (Bottom)','Tool box - cable ties',1,'equipment',array['inventory'],17),
      ('Compartment 1 (Bottom)','Tool box - tape measure',1,'equipment',array['inventory'],18),
      ('Compartment 1 (Bottom)','Tool box - electric meter lug',1,'equipment',array['inventory'],19),
      ('Compartment 1 (Bottom)','Tool box - hacksaw with blades',1,'equipment',array['inventory'],20),
      ('Compartment 1 (Bottom)','Tool box - 21 piece socket set',1,'equipment',array['inventory'],21),
      ('Compartment 1 (Bottom)','Tool box - box wrenches',7,'equipment',array['inventory'],22),
      ('Compartment 1 (Bottom)','Tool box - wonder bar',1,'equipment',array['inventory'],23),
      ('Compartment 1 (Bottom)','Tool box - bag of nails',1,'equipment',array['inventory'],24),
      ('Compartment 1 (Bottom)','Tool box - box cutter with blades',1,'equipment',array['inventory'],25),
      ('Compartment 1 (Bottom)','Tool box - outlet tester',1,'equipment',array['inventory'],26),
      ('Compartment 1 (Bottom)','Tool box - butter knives',2,'equipment',array['inventory'],27),
      ('Compartment 1 (Bottom)','Tool box - spare gaskets',1,'equipment',array['inventory'],28),
      ('Compartment 1 (Bottom)','Hydrant bag - rubber mallet',1,'equipment',array['inventory'],29),
      ('Compartment 1 (Bottom)','Hydrant bag - hydrant wrench',1,'equipment',array['inventory'],30),
      ('Compartment 1 (Bottom)','Hydrant bag - spanners',2,'equipment',array['inventory'],31),
      ('Compartment 1 (Bottom)','Hydrant bag - Storz spanners',2,'equipment',array['inventory'],32),
      ('Compartment 1 (Bottom)','Hydrant bag - 2.5 inch gate valve',1,'equipment',array['inventory'],33),
      ('Compartment 1 (Bottom)','Hydrant bag - 4.5 inch female to Storz',1,'equipment',array['inventory'],34),
      ('Compartment 1 (Bottom)','Hydrant bag - double male',1,'equipment',array['inventory'],35),
      ('Compartment 1 (Bottom)','Hydrant bag - double female',1,'equipment',array['inventory'],36),
      ('Compartment 1 (Bottom)','Hydrant bag - 4.5 inch female to 4 inch male (Berwyn / Cicero)',1,'equipment',array['inventory'],37),
      ('Driver Side Fold-Up Step','Bag of oil dry',1,'equipment',array['inventory'],1),
      ('Compartment 2','Class K extinguisher',1,'equipment',array['inventory'],1),
      ('Compartment 2','Dry chemical extinguisher',1,'equipment',array['inventory'],2),
      ('Compartment 2','CO2 extinguisher',1,'equipment',array['inventory'],3),
      ('Compartment 2','Pressurized water extinguishers',2,'equipment',array['inventory'],4),
      ('Compartment 3 (Top)','Engineer''s SCBA',1,'air_pack',array['air_pack'],1),
      ('Compartment 3 (Top)','30 minute SCBA spare cylinders',3,'air_pack',array['air_pack'],2),
      ('Compartment 3 (Top)','Bottle of dish soap',1,'equipment',array['inventory'],1),
      ('Compartment 3 (Top)','Pressurized water extinguisher',1,'equipment',array['inventory'],2),
      ('Compartment 3 (Bottom)','Cribbing',1,'equipment',array['inventory'],1),
      ('Compartment 3 (Bottom)','Jug of salt',1,'equipment',array['inventory'],2),
      ('Compartment 3 (Bottom)','Plastic step chocks',2,'equipment',array['inventory'],3),
      ('Compartment 4','Can of straight gasoline',1,'equipment',array['inventory'],1),
      ('Compartment 4','Cans of mixed fuel',2,'equipment',array['inventory'],2),
      ('Compartment 4','Milk crate of chains',1,'equipment',array['inventory'],3),
      ('Rear (Driver Side)','10 foot hard suction',2,'equipment',array['inventory'],1),
      ('Rear (Driver Side)','Piercing nozzle',1,'equipment',array['inventory'],2),
      ('Rear (Driver Side)','6 foot pike poles',2,'equipment',array['inventory'],3),
      ('Rear (Driver Side)','8 foot pike pole',1,'equipment',array['inventory'],4),
      ('Rear (Driver Side)','12 foot pike pole',1,'equipment',array['inventory'],5),
      ('Rear (Driver Side)','6 foot New York hook',1,'equipment',array['inventory'],6),
      ('Rear (Driver Side)','8 foot New York hook',1,'equipment',array['inventory'],7),
      ('Rear (Officer Side)','24 foot extension ladder',1,'equipment',array['inventory'],1),
      ('Rear (Officer Side)','14 foot roof ladder',1,'equipment',array['inventory'],2),
      ('Rear (Officer Side)','10 foot attic ladder',1,'equipment',array['inventory'],3),
      ('Rear (Officer Side)','6 foot New York hook',1,'equipment',array['inventory'],4),
      ('Rear (Officer Side)','8 foot pike pole',1,'equipment',array['inventory'],5),
      ('Compartment 5','Marrying straps',2,'equipment',array['inventory'],1),
      ('Compartment 5','Old Hurst power unit',1,'equipment',array['inventory'],2),
      ('Compartment 5','Long ram',1,'equipment',array['inventory'],3),
      ('Compartment 5','Short ram',1,'equipment',array['inventory'],4),
      ('Compartment 5','Cutters with hose',1,'equipment',array['inventory'],5),
      ('Compartment 5','Spreaders with hose',1,'equipment',array['inventory'],6),
      ('Compartment 6','150 foot life rope',1,'equipment',array['inventory'],1),
      ('Compartment 6','150 foot utility rope',1,'equipment',array['inventory'],2),
      ('Compartment 6','Tarps',2,'equipment',array['inventory'],3),
      ('Compartment 6','RASP bag',1,'equipment',array['inventory'],4),
      ('Compartment 7 (Top)','Pick head axes',2,'equipment',array['inventory'],1),
      ('Compartment 7 (Top)','Mauls',2,'equipment',array['inventory'],2),
      ('Compartment 7 (Top)','Sets of irons',2,'equipment',array['inventory'],3),
      ('Compartment 7 (Top)','Sledges',2,'equipment',array['inventory'],4),
      ('Compartment 7 (Top)','Pry bar',1,'equipment',array['inventory'],5),
      ('Compartment 7 (Top)','A Tool',1,'equipment',array['inventory'],6),
      ('Compartment 7 (Top)','Spanners',2,'equipment',array['inventory'],7),
      ('Compartment 7 (Top)','Storz spanners',2,'equipment',array['inventory'],8),
      ('Compartment 7 (Top)','Hydrant wrench',1,'equipment',array['inventory'],9),
      ('Compartment 7 (Top)','Bolt cutters',1,'equipment',array['inventory'],10),
      ('Compartment 7 (Top)','Hay hook',1,'equipment',array['inventory'],11),
      ('Compartment 7 (Bottom)','100 foot 2.5 inch hose with stacked tip',1,'equipment',array['inventory'],1),
      ('Compartment 7 (Bottom)','100 foot 1.75 inch hose with 7/8 inch smooth bore nozzle',1,'equipment',array['inventory'],2),
      ('Compartment 7 (Bottom)','Hi-rise bag - spanner',1,'equipment',array['inventory'],3),
      ('Compartment 7 (Bottom)','Hi-rise bag - rope hose tool',1,'equipment',array['inventory'],4),
      ('Compartment 7 (Bottom)','Hi-rise bag - wheel wrench',1,'equipment',array['inventory'],5),
      ('Compartment 7 (Bottom)','Hi-rise bag - inline pressure gauge',1,'equipment',array['inventory'],6),
      ('Compartment 7 (Bottom)','Hi-rise bag - 1.75 inch fog nozzle with 2.5 inch reducer',1,'equipment',array['inventory'],7),
      ('Top of Engine','Coal shovel',1,'equipment',array['inventory'],1),
      ('Top of Engine','Spade shovel',1,'equipment',array['inventory'],2),
      ('Top of Engine','Flat shovels',2,'equipment',array['inventory'],3),
      ('Top of Engine','Push brooms',2,'equipment',array['inventory'],4),
      ('Top of Engine','Fire brooms',3,'equipment',array['inventory'],5),
      ('Top of Engine','5 gallon buckets of AFFF',4,'equipment',array['inventory'],6),
      ('Top of Engine','Traffic cones',19,'equipment',array['inventory'],7),
      ('Top of Engine','Bucket of oil dry',1,'equipment',array['inventory'],8),
      ('Hose','1.75 inch fog preconnect',1,'equipment',array['inventory'],1),
      ('Hose','1.75 inch smooth bore preconnect',1,'equipment',array['inventory'],2),
      ('Hose','2.5 inch preconnect',1,'equipment',array['inventory'],3),
      ('Hose','Hi-rise load',1,'equipment',array['inventory'],4),
      ('Hose','Front bumper preconnect',1,'equipment',array['inventory'],5),
      ('Hose','Lead line',1,'equipment',array['inventory'],6),
      ('Hose','Skid load',1,'equipment',array['inventory'],7),
      ('Hose','L.D.H. Storz supply',1,'equipment',array['inventory'],8)
  ), ranked_items as (
    select
      source_items.*,
      c.id as compartment_id,
      'form-248-' || lpad(row_number() over (
        order by c.sort_order, source_items.item_order, source_items.item_name
      )::text, 3, '0') as source_key
    from source_items
    join public.inventory_compartments c
      on c.department_id = stickney_id
     and c.apparatus_id = engine_1201_id
     and c.label = source_items.section_label
  )
  insert into public.inventory_equipment
    (department_id, apparatus_id, compartment_id, name, quantity_required,
     equipment_category, check_types, source_key, source_form, item_order)
  select
    stickney_id,
    engine_1201_id,
    ranked_items.compartment_id,
    ranked_items.item_name,
    ranked_items.quantity_required,
    ranked_items.equipment_category,
    ranked_items.check_types,
    ranked_items.source_key,
    '1201 Weekly Check (RESERVE) form 248',
    ranked_items.item_order
  from ranked_items
  on conflict (department_id, apparatus_id, source_key) where source_key is not null
  do update set
    compartment_id = excluded.compartment_id,
    name = excluded.name,
    quantity_required = excluded.quantity_required,
    equipment_category = excluded.equipment_category,
    check_types = excluded.check_types,
    source_form = excluded.source_form,
    item_order = excluded.item_order,
    retired_at = null;
end $$;
