alter table public.inventory_equipment
  add column if not exists source_key text,
  add column if not exists source_form text,
  add column if not exists item_order integer not null default 0,
  add column if not exists retired_at timestamptz;

create unique index if not exists inventory_equipment_source_key_idx
  on public.inventory_equipment (department_id, apparatus_id, source_key)
  where source_key is not null;

create index if not exists inventory_equipment_active_checklist_idx
  on public.inventory_equipment (department_id, apparatus_id, compartment_id, item_order)
  where retired_at is null;

do $$
declare
  stickney_id uuid;
  engine_1203_id uuid;
begin
  select id into stickney_id
  from public.departments
  where name = 'Stickney Fire Department'
  limit 1;

  select id into engine_1203_id
  from public.inventory_apparatus_profiles
  where department_id = stickney_id and name = '1203'
  limit 1;

  if stickney_id is null or engine_1203_id is null then
    raise exception 'Stickney Fire Department apparatus 1203 must exist before loading its FRONTLINE checklist';
  end if;

  insert into public.inventory_compartments
    (department_id, apparatus_id, label, side, sort_order)
  values
    (stickney_id, engine_1203_id, 'Vehicle', 'cab', 100),
    (stickney_id, engine_1203_id, 'Front Tires', 'front', 110),
    (stickney_id, engine_1203_id, 'Rear Tires', 'rear', 120),
    (stickney_id, engine_1203_id, 'Cab', 'cab', 130),
    (stickney_id, engine_1203_id, 'Cab - Cabinet', 'cab', 140),
    (stickney_id, engine_1203_id, 'Glove Box', 'cab', 150),
    (stickney_id, engine_1203_id, 'Pump / Booster Tank', 'pump', 160),
    (stickney_id, engine_1203_id, 'SCBA', 'cab', 170),
    (stickney_id, engine_1203_id, 'Driver Side Step', 'driver', 180),
    (stickney_id, engine_1203_id, 'Compartment 1 (Top)', 'driver', 190),
    (stickney_id, engine_1203_id, 'Compartment 1 (Bottom)', 'driver', 200),
    (stickney_id, engine_1203_id, 'Compartment 2', 'driver', 210),
    (stickney_id, engine_1203_id, 'Driver''s Side Drawer', 'driver', 220),
    (stickney_id, engine_1203_id, 'Compartment 3', 'driver', 230),
    (stickney_id, engine_1203_id, 'Driver''s Side', 'driver', 240),
    (stickney_id, engine_1203_id, 'Compartment 4', 'rear', 250),
    (stickney_id, engine_1203_id, 'Rear Compartment', 'rear', 260),
    (stickney_id, engine_1203_id, 'Compartment 5', 'officer', 270),
    (stickney_id, engine_1203_id, 'Compartment 6', 'officer', 280),
    (stickney_id, engine_1203_id, 'Officer''s Side Drawer', 'officer', 290),
    (stickney_id, engine_1203_id, 'Compartment 7', 'officer', 300),
    (stickney_id, engine_1203_id, 'Officer''s Side', 'officer', 310),
    (stickney_id, engine_1203_id, 'Officer''s Side Step', 'officer', 320),
    (stickney_id, engine_1203_id, 'Top of Engine', 'roof', 330),
    (stickney_id, engine_1203_id, 'Hose', 'rear', 340)
  on conflict (apparatus_id, label) do update
  set side = excluded.side,
      sort_order = excluded.sort_order;

  with source_items(section_label, item_name, quantity_required, equipment_category, check_types, source_key, item_order) as (
    values
      ('Vehicle','Record mileage',1,'vehicle',array['weekly'],'frontline-251-001',1),
      ('Vehicle','Fuel (must be 3/4)',1,'vehicle',array['weekly'],'frontline-251-002',2),
      ('Vehicle','Airhorn operational',1,'vehicle',array['weekly'],'frontline-251-003',3),
      ('Vehicle','Vehicle horn operational',1,'vehicle',array['weekly'],'frontline-251-004',4),
      ('Vehicle','Siren operational',1,'vehicle',array['weekly'],'frontline-251-005',5),
      ('Vehicle','Parking brake operational',1,'vehicle',array['weekly'],'frontline-251-006',6),
      ('Vehicle','Head lights / brake lights / turn signals operational',1,'vehicle',array['weekly'],'frontline-251-007',7),
      ('Vehicle','Check generator fluid level sight glass (must be over 1/2)',1,'vehicle',array['weekly'],'frontline-251-008',8),
      ('Vehicle','Run PTO generator; check junction boxes and brow lights',1,'vehicle',array['weekly'],'frontline-251-009',9),
      ('Vehicle','Emergency lights operational',1,'vehicle',array['weekly'],'frontline-251-010',10),
      ('Vehicle','Transmission fluid (engine must be running)',1,'vehicle',array['weekly'],'frontline-251-011',11),
      ('Vehicle','Antifreeze / radiator level',1,'vehicle',array['weekly'],'frontline-251-012',12),
      ('Vehicle','Engine oil',1,'vehicle',array['weekly'],'frontline-251-013',13),
      ('Vehicle','Body condition',1,'vehicle',array['weekly'],'frontline-251-014',14),
      ('Vehicle','Wheel and tire condition',1,'vehicle',array['weekly'],'frontline-251-015',15),
      ('Front Tires','Left PSI',1,'vehicle',array['weekly'],'frontline-251-016',1),
      ('Front Tires','Right PSI',1,'vehicle',array['weekly'],'frontline-251-017',2),
      ('Rear Tires','Left inner PSI',1,'vehicle',array['weekly'],'frontline-251-018',1),
      ('Rear Tires','Left outer PSI',1,'vehicle',array['weekly'],'frontline-251-019',2),
      ('Rear Tires','Right inner PSI',1,'vehicle',array['weekly'],'frontline-251-020',3),
      ('Rear Tires','Right outer PSI',1,'vehicle',array['weekly'],'frontline-251-021',4),
      ('Cab','Door opener',1,'equipment',array['weekly','inventory'],'frontline-251-022',1),
      ('Cab','5 gas meter (fully charged)',1,'equipment',array['weekly','inventory'],'frontline-251-023',2),
      ('Cab','Portable radios (charged and on channel 1)',4,'equipment',array['weekly','inventory'],'frontline-251-024',3),
      ('Cab','Fuel card and PIN',1,'equipment',array['weekly','inventory'],'frontline-251-025',4),
      ('Cab','SCBA harness',4,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-026',5),
      ('Cab','Hi-vis safety vests',5,'equipment',array['weekly','inventory'],'frontline-251-027',6),
      ('Cab','F.V. / Lyons map',1,'equipment',array['weekly','inventory'],'frontline-251-028',7),
      ('Cab','Box lights',4,'equipment',array['weekly','inventory'],'frontline-251-029',8),
      ('Cab','Box of N95 masks',1,'equipment',array['weekly','inventory'],'frontline-251-030',9),
      ('Cab','Thermal imaging camera (TIC), charged',1,'equipment',array['weekly','inventory'],'frontline-251-031',10),
      ('Cab','T.I.C. SCBA mask',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-032',11),
      ('Cab','Yellow case (cell phone and GPS with cord)',1,'equipment',array['weekly','inventory'],'frontline-251-033',12),
      ('Cab','Knox Box keys',1,'equipment',array['weekly','inventory'],'frontline-251-034',13),
      ('Cab','Cooler with water',1,'equipment',array['weekly','inventory'],'frontline-251-035',14),
      ('Cab','Gloves (various sizes)',1,'equipment',array['weekly','inventory'],'frontline-251-036',15),
      ('Cab','LVAD papers',1,'equipment',array['weekly','inventory'],'frontline-251-037',16),
      ('Cab','Officer''s clipboard (stocked)',1,'equipment',array['weekly','inventory'],'frontline-251-038',17),
      ('Cab - Cabinet','Bag of surgical masks',5,'equipment',array['weekly','inventory'],'frontline-251-039',1),
      ('Cab - Cabinet','AED',1,'equipment',array['weekly','inventory'],'frontline-251-040',2),
      ('Cab - Cabinet','EMS bag',1,'equipment',array['weekly','inventory'],'frontline-251-041',3),
      ('Cab - Cabinet','EMS bag O2 level',1,'equipment',array['weekly'],'frontline-251-042',4),
      ('Cab - Cabinet','Sensit meter',1,'equipment',array['weekly','inventory'],'frontline-251-043',5),
      ('Cab - Cabinet','Puncture / leak kit',1,'equipment',array['weekly','inventory'],'frontline-251-044',6),
      ('Cab - Cabinet','Rescue Disc',1,'equipment',array['weekly','inventory'],'frontline-251-045',7),
      ('Cab - Cabinet','PPE bags with N95, surgical mask and gown',12,'equipment',array['weekly','inventory'],'frontline-251-046',8),
      ('Cab - Cabinet','Camera and cable in case',1,'equipment',array['weekly','inventory'],'frontline-251-047',9),
      ('Cab - Cabinet','Binoculars',2,'equipment',array['weekly','inventory'],'frontline-251-048',10),
      ('Cab - Cabinet','Barrier tape',1,'equipment',array['weekly','inventory'],'frontline-251-049',11),
      ('Cab - Cabinet','Lock out tag out kit (LOTO)',1,'equipment',array['weekly','inventory'],'frontline-251-050',12),
      ('Cab - Cabinet','Geiger meter',1,'equipment',array['weekly','inventory'],'frontline-251-051',13),
      ('Cab - Cabinet','Passport board',1,'equipment',array['weekly','inventory'],'frontline-251-052',14),
      ('Cab - Cabinet','Dish soap',1,'equipment',array['weekly','inventory'],'frontline-251-053',15),
      ('Cab - Cabinet','Duct tape',1,'equipment',array['weekly','inventory'],'frontline-251-054',16),
      ('Cab - Cabinet','School maps',1,'equipment',array['weekly','inventory'],'frontline-251-055',17),
      ('Cab - Cabinet','Pre-plan book',1,'equipment',array['weekly','inventory'],'frontline-251-056',18),
      ('Cab - Cabinet','Box card binder',1,'equipment',array['weekly','inventory'],'frontline-251-057',19),
      ('Cab - Cabinet','Pet O2 masks',1,'equipment',array['weekly','inventory'],'frontline-251-058',20),
      ('Cab - Cabinet','Hand sanitizer',1,'equipment',array['weekly','inventory'],'frontline-251-059',21),
      ('Cab - Cabinet','R.I.T. bag - 60 minute SCBA bottle',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-060',22),
      ('Cab - Cabinet','R.I.T. bag - hose with universal connection (UAC)',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-061',23),
      ('Cab - Cabinet','R.I.T. bag - spare SCBA mask',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-062',24),
      ('Cab - Cabinet','R.I.T. bag - hose with regulator',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-063',25),
      ('Cab - Cabinet','R.I.T. bag - 75 foot rope with pulley and carabiners',1,'equipment',array['weekly','inventory'],'frontline-251-064',26),
      ('Cab - Cabinet','R.I.T. bag - male adapter',1,'equipment',array['weekly','inventory'],'frontline-251-065',27),
      ('Cab - Cabinet','R.I.T. bag - wire cutters',1,'equipment',array['weekly','inventory'],'frontline-251-066',28),
      ('Cab - Cabinet','R.I.T. bag - handcuff webbing with carabiner',2,'equipment',array['weekly','inventory'],'frontline-251-067',29),
      ('Cab - Cabinet','LOTO - red lock with keys',2,'equipment',array['weekly','inventory'],'frontline-251-068',30),
      ('Cab - Cabinet','LOTO - lock hasp',2,'equipment',array['weekly','inventory'],'frontline-251-069',31),
      ('Cab - Cabinet','LOTO - 2 foot chain',1,'equipment',array['weekly','inventory'],'frontline-251-070',32),
      ('Cab - Cabinet','LOTO - lockout tags',1,'equipment',array['weekly','inventory'],'frontline-251-071',33),
      ('Cab - Cabinet','LOTO - marker',2,'equipment',array['weekly','inventory'],'frontline-251-072',34),
      ('Cab - Cabinet','LOTO - shove knife',1,'equipment',array['weekly','inventory'],'frontline-251-073',35),
      ('Cab - Cabinet','LOTO - wedge',2,'equipment',array['weekly','inventory'],'frontline-251-074',36),
      ('Cab - Cabinet','Black Pelican case - TIFF meter',1,'equipment',array['weekly','inventory'],'frontline-251-075',37),
      ('Cab - Cabinet','Black Pelican case - CO detector',2,'equipment',array['weekly','inventory'],'frontline-251-076',38),
      ('Cab - Cabinet','Black Pelican case - 9V battery',2,'equipment',array['weekly','inventory'],'frontline-251-077',39),
      ('Cab - Cabinet','Black Pelican case - RAD Alert',1,'equipment',array['weekly','inventory'],'frontline-251-078',40),
      ('Cab - Cabinet','Black Pelican case - Smart M-8 nerve agent ID badge',4,'equipment',array['weekly','inventory'],'frontline-251-079',41),
      ('Cab - Cabinet','Black Pelican case - Smart M-8 chemical agent badge',4,'equipment',array['weekly','inventory'],'frontline-251-080',42),
      ('Glove Box','ERG book',1,'equipment',array['weekly','inventory'],'frontline-251-081',1),
      ('Glove Box','Knox key wrench',1,'equipment',array['weekly','inventory'],'frontline-251-082',2),
      ('Glove Box','Accident envelope',1,'equipment',array['weekly','inventory'],'frontline-251-083',3),
      ('Glove Box','Insurance card',1,'equipment',array['weekly','inventory'],'frontline-251-084',4),
      ('Glove Box','Goggles',4,'equipment',array['weekly','inventory'],'frontline-251-085',5),
      ('Glove Box','Fuse puller',1,'equipment',array['weekly','inventory'],'frontline-251-086',6),
      ('Glove Box','Haz-Mat guide for first responders',1,'equipment',array['weekly','inventory'],'frontline-251-087',7),
      ('Glove Box','K-Tool bag - K-Tool',1,'equipment',array['weekly','inventory'],'frontline-251-088',8),
      ('Glove Box','K-Tool bag - door chocks',2,'equipment',array['weekly','inventory'],'frontline-251-089',9),
      ('Glove Box','K-Tool bag - needle nose pliers',1,'equipment',array['weekly','inventory'],'frontline-251-090',10),
      ('Glove Box','K-Tool bag - lineman pliers',1,'equipment',array['weekly','inventory'],'frontline-251-091',11),
      ('Glove Box','K-Tool bag - shove knife',1,'equipment',array['weekly','inventory'],'frontline-251-092',12),
      ('Glove Box','K-Tool bag - putty knife',1,'equipment',array['weekly','inventory'],'frontline-251-093',13),
      ('Glove Box','K-Tool bag - butter knife',1,'equipment',array['weekly','inventory'],'frontline-251-094',14),
      ('Glove Box','K-Tool bag - mini crowbar',1,'equipment',array['weekly','inventory'],'frontline-251-095',15),
      ('Glove Box','K-Tool bag - Allen wrench',1,'equipment',array['weekly','inventory'],'frontline-251-096',16),
      ('Glove Box','K-Tool bag - elevator drop key',1,'equipment',array['weekly','inventory'],'frontline-251-097',17),
      ('Glove Box','K-Tool bag - half moon drop key',4,'equipment',array['weekly','inventory'],'frontline-251-098',18),
      ('Pump / Booster Tank','Water level full',1,'vehicle',array['weekly'],'frontline-251-099',1),
      ('Pump / Booster Tank','Exercise primer / circulate water',1,'vehicle',array['weekly'],'frontline-251-100',2),
      ('Pump / Booster Tank','Vehicle goes into pump and recirculates water',1,'vehicle',array['weekly'],'frontline-251-101',3),
      ('SCBA','Officer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-102',1),
      ('SCBA','Engineer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-103',2),
      ('SCBA','Rear 1 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-104',3),
      ('SCBA','Rear 2 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-105',4),
      ('SCBA','Rear 3 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-106',5),
      ('SCBA','Driver side torpedo - front 30 minute bottle at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-107',6),
      ('SCBA','Driver side torpedo - rear 30 minute bottle at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-108',7),
      ('SCBA','Officer side torpedo - front 60 minute bottle at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-109',8),
      ('SCBA','Officer side torpedo - rear 60 minute bottle at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-110',9),
      ('SCBA','Compartment 3 spare cylinder 1 at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-111',10),
      ('SCBA','Compartment 3 spare cylinder 2 at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-112',11),
      ('SCBA','Compartment 3 spare cylinder 3 at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-113',12),
      ('Driver Side Step','Roll of 5 inch hose',1,'equipment',array['weekly','inventory'],'frontline-251-114',1),
      ('Driver Side Step','Hose roller',1,'equipment',array['weekly','inventory'],'frontline-251-115',2),
      ('Driver Side Step','Hose clamp',1,'equipment',array['weekly','inventory'],'frontline-251-116',3),
      ('Driver Side Step','Ice melt',1,'equipment',array['weekly','inventory'],'frontline-251-117',4),
      ('Driver Side Step','BioSolve',1,'equipment',array['weekly','inventory'],'frontline-251-118',5),
      ('Driver Side Step','Dish soap',1,'equipment',array['weekly','inventory'],'frontline-251-119',6),
      ('Compartment 1 (Top)','TFT nozzle with 2.5 inch adapter',1,'equipment',array['weekly','inventory'],'frontline-251-120',1),
      ('Compartment 1 (Top)','2.5 inch foam nozzle',1,'equipment',array['weekly','inventory'],'frontline-251-121',2),
      ('Compartment 1 (Top)','Master stream fog',1,'equipment',array['weekly','inventory'],'frontline-251-122',3),
      ('Compartment 1 (Top)','2.5 inch MacNeal adapter',2,'equipment',array['weekly','inventory'],'frontline-251-123',4),
      ('Compartment 1 (Top)','2.5 inch to 1.5 inch reducer',1,'equipment',array['weekly','inventory'],'frontline-251-124',5),
      ('Compartment 1 (Top)','Storz to 2.5 inch elbow',1,'equipment',array['weekly','inventory'],'frontline-251-125',6),
      ('Compartment 1 (Top)','Storz to 2.5 inch male',1,'equipment',array['weekly','inventory'],'frontline-251-126',7),
      ('Compartment 1 (Top)','Storz to 4.5 inch female',2,'equipment',array['weekly','inventory'],'frontline-251-127',8),
      ('Compartment 1 (Top)','Storz to 4.5 inch male',1,'equipment',array['weekly','inventory'],'frontline-251-128',9),
      ('Compartment 1 (Top)','4 inch to 5 inch Storz',1,'equipment',array['weekly','inventory'],'frontline-251-129',10),
      ('Compartment 1 (Top)','Storz to 4 inch female (Berwyn/Cicero)',1,'equipment',array['weekly','inventory'],'frontline-251-130',11),
      ('Compartment 1 (Top)','Double male',1,'equipment',array['weekly','inventory'],'frontline-251-131',12),
      ('Compartment 1 (Top)','Double female',1,'equipment',array['weekly','inventory'],'frontline-251-132',13),
      ('Compartment 1 (Top)','Wye',1,'equipment',array['weekly','inventory'],'frontline-251-133',14),
      ('Compartment 1 (Top)','2.5 inch distributor nozzle',1,'equipment',array['weekly','inventory'],'frontline-251-134',15),
      ('Compartment 1 (Top)','Towel',1,'equipment',array['weekly','inventory'],'frontline-251-135',16),
      ('Compartment 1 (Top)','Foam eductor (handheld)',1,'equipment',array['weekly','inventory'],'frontline-251-136',17),
      ('Compartment 1 (Top)','Foam eductor (on-board)',1,'equipment',array['weekly','inventory'],'frontline-251-137',18),
      ('Compartment 1 (Top)','CST tool',1,'equipment',array['weekly','inventory'],'frontline-251-138',19),
      ('Compartment 1 (Top)','Spanners',2,'equipment',array['weekly','inventory'],'frontline-251-139',20),
      ('Compartment 1 (Top)','Hard suction spanner',1,'equipment',array['weekly','inventory'],'frontline-251-140',21),
      ('Compartment 1 (Top)','Storz spanner',2,'equipment',array['weekly','inventory'],'frontline-251-141',22),
      ('Compartment 1 (Top)','Hydrant wrench',2,'equipment',array['weekly','inventory'],'frontline-251-142',23),
      ('Compartment 1 (Top)','Barrier tape',1,'equipment',array['weekly','inventory'],'frontline-251-143',24),
      ('Compartment 1 (Top)','Hose chart',1,'equipment',array['weekly','inventory'],'frontline-251-144',25),
      ('Compartment 1 (Top)','Hose jacket',1,'equipment',array['weekly','inventory'],'frontline-251-145',26),
      ('Compartment 1 (Top)','Hose air fittings with caps',1,'equipment',array['weekly','inventory'],'frontline-251-146',27),
      ('Compartment 1 (Top)','Siamese',1,'equipment',array['weekly','inventory'],'frontline-251-147',28),
      ('Compartment 1 (Top)','Rubber mallet',1,'equipment',array['weekly','inventory'],'frontline-251-148',29),
      ('Compartment 1 (Top)','1.75 inch fog nozzle',1,'equipment',array['weekly','inventory'],'frontline-251-149',30),
      ('Compartment 1 (Top)','Hose edge roller',1,'equipment',array['weekly','inventory'],'frontline-251-150',31),
      ('Compartment 1 (Top)','Bowling pin',1,'equipment',array['weekly','inventory'],'frontline-251-151',32),
      ('Compartment 1 (Bottom)','Chicago custodian and cross wrench',1,'equipment',array['weekly','inventory'],'frontline-251-152',1),
      ('Compartment 1 (Bottom)','Tool box - sprinkler stops',4,'equipment',array['weekly','inventory'],'frontline-251-153',2),
      ('Compartment 1 (Bottom)','Tool box - claw hammer',1,'equipment',array['weekly','inventory'],'frontline-251-154',3),
      ('Compartment 1 (Bottom)','Tool box - flat screwdriver',3,'equipment',array['weekly','inventory'],'frontline-251-155',4),
      ('Compartment 1 (Bottom)','Tool box - Phillips screwdriver',3,'equipment',array['weekly','inventory'],'frontline-251-156',5),
      ('Compartment 1 (Bottom)','Tool box - electrical tape',2,'equipment',array['weekly','inventory'],'frontline-251-157',6),
      ('Compartment 1 (Bottom)','Tool box - crescent wrench',2,'equipment',array['weekly','inventory'],'frontline-251-158',7),
      ('Compartment 1 (Bottom)','Tool box - pipe wrench',2,'equipment',array['weekly','inventory'],'frontline-251-159',8),
      ('Compartment 1 (Bottom)','Tool box - channel locks',1,'equipment',array['weekly','inventory'],'frontline-251-160',9),
      ('Compartment 1 (Bottom)','Tool box - cable cutters',1,'equipment',array['weekly','inventory'],'frontline-251-161',10),
      ('Compartment 1 (Bottom)','Tool box - cable ties',1,'equipment',array['weekly','inventory'],'frontline-251-162',11),
      ('Compartment 1 (Bottom)','Tool box - tape measure',1,'equipment',array['weekly','inventory'],'frontline-251-163',12),
      ('Compartment 1 (Bottom)','Tool box - electric meter lug',1,'equipment',array['weekly','inventory'],'frontline-251-164',13),
      ('Compartment 1 (Bottom)','Tool box - hacksaw with blades',1,'equipment',array['weekly','inventory'],'frontline-251-165',14),
      ('Compartment 1 (Bottom)','Tool box - 21 piece socket set',1,'equipment',array['weekly','inventory'],'frontline-251-166',15),
      ('Compartment 1 (Bottom)','Tool box - box wrenches',7,'equipment',array['weekly','inventory'],'frontline-251-167',16),
      ('Compartment 1 (Bottom)','Tool box - Wonder Bar',1,'equipment',array['weekly','inventory'],'frontline-251-168',17),
      ('Compartment 1 (Bottom)','Tool box - bag of nails',1,'equipment',array['weekly','inventory'],'frontline-251-169',18),
      ('Compartment 1 (Bottom)','Tool box - box cutter with blades',1,'equipment',array['weekly','inventory'],'frontline-251-170',19),
      ('Compartment 1 (Bottom)','Tool box - outlet tester',1,'equipment',array['weekly','inventory'],'frontline-251-171',20),
      ('Compartment 1 (Bottom)','Tool box - butter knife',2,'equipment',array['weekly','inventory'],'frontline-251-172',21),
      ('Compartment 1 (Bottom)','Tool box - spare gaskets',1,'equipment',array['weekly','inventory'],'frontline-251-173',22),
      ('Compartment 1 (Bottom)','Hydrant bag - rubber mallet',1,'equipment',array['weekly','inventory'],'frontline-251-174',23),
      ('Compartment 1 (Bottom)','Hydrant bag - hydrant wrench',1,'equipment',array['weekly','inventory'],'frontline-251-175',24),
      ('Compartment 1 (Bottom)','Hydrant bag - spanner',2,'equipment',array['weekly','inventory'],'frontline-251-176',25),
      ('Compartment 1 (Bottom)','Hydrant bag - Storz spanner',1,'equipment',array['weekly','inventory'],'frontline-251-177',26),
      ('Compartment 1 (Bottom)','Hydrant bag - 2.5 inch gate valve',1,'equipment',array['weekly','inventory'],'frontline-251-178',27),
      ('Compartment 1 (Bottom)','Hydrant bag - 4.5 inch female to Storz',1,'equipment',array['weekly','inventory'],'frontline-251-179',28),
      ('Compartment 1 (Bottom)','Hydrant bag - double male',1,'equipment',array['weekly','inventory'],'frontline-251-180',29),
      ('Compartment 1 (Bottom)','Hydrant bag - double female',1,'equipment',array['weekly','inventory'],'frontline-251-181',30),
      ('Compartment 1 (Bottom)','Hydrant bag - 4.5 inch female to 4 inch male (Berwyn/Cicero)',1,'equipment',array['weekly','inventory'],'frontline-251-182',31),
      ('Compartment 2','K extinguisher',1,'equipment',array['weekly','inventory'],'frontline-251-183',1),
      ('Compartment 2','Dry chemical extinguisher',1,'equipment',array['weekly','inventory'],'frontline-251-184',2),
      ('Compartment 2','CO2 extinguisher',1,'equipment',array['weekly','inventory'],'frontline-251-185',3),
      ('Compartment 2','Pressurized water extinguisher',1,'equipment',array['weekly','inventory'],'frontline-251-186',4),
      ('Compartment 2','Empty pump can',1,'equipment',array['weekly','inventory'],'frontline-251-187',5),
      ('Driver''s Side Drawer','Hose chart',1,'equipment',array['weekly','inventory'],'frontline-251-188',1),
      ('Driver''s Side Drawer','Cheater bar',1,'equipment',array['weekly','inventory'],'frontline-251-189',2),
      ('Driver''s Side Drawer','Hose jacket',1,'equipment',array['weekly','inventory'],'frontline-251-190',3),
      ('Driver''s Side Drawer','Towel',1,'equipment',array['weekly','inventory'],'frontline-251-191',4),
      ('Driver''s Side Drawer','Flare',1,'equipment',array['weekly','inventory'],'frontline-251-192',5),
      ('Driver''s Side Drawer','Rope hose tool',1,'equipment',array['weekly','inventory'],'frontline-251-193',6),
      ('Driver''s Side Drawer','Roll(s) fire tape',1,'equipment',array['weekly','inventory'],'frontline-251-194',7),
      ('Driver''s Side Drawer','Hard suction spanner',1,'equipment',array['weekly','inventory'],'frontline-251-195',8),
      ('Driver''s Side Drawer','CST tool',1,'equipment',array['weekly','inventory'],'frontline-251-196',9),
      ('Driver''s Side Drawer','Foam eductor',1,'equipment',array['weekly','inventory'],'frontline-251-197',10),
      ('Compartment 3','Engineer SCBA pack',1,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-198',1),
      ('Compartment 3','Flood light',2,'equipment',array['weekly','inventory'],'frontline-251-199',2),
      ('Compartment 3','Cribbing',1,'equipment',array['weekly','inventory'],'frontline-251-200',3),
      ('Compartment 3','Post cover',4,'equipment',array['weekly','inventory'],'frontline-251-201',4),
      ('Compartment 3','Plastic step chocks',2,'equipment',array['weekly','inventory'],'frontline-251-202',5),
      ('Compartment 3','Wooden step chocks',2,'equipment',array['weekly','inventory'],'frontline-251-203',6),
      ('Compartment 3','Kodiak struts',1,'equipment',array['weekly','inventory'],'frontline-251-204',7),
      ('Compartment 3','Vehicle lockout kit',1,'equipment',array['weekly','inventory'],'frontline-251-205',8),
      ('Compartment 3','Box of pig tails',1,'equipment',array['weekly','inventory'],'frontline-251-206',9),
      ('Compartment 3','Bucket for oil dry (empty)',1,'equipment',array['weekly','inventory'],'frontline-251-207',10),
      ('Compartment 3','Smoke ejector',1,'equipment',array['weekly','inventory'],'frontline-251-208',11),
      ('Compartment 3','Hanger bracket',1,'equipment',array['weekly','inventory'],'frontline-251-209',12),
      ('Compartment 3','Wheel chock',1,'equipment',array['weekly','inventory'],'frontline-251-210',13),
      ('Driver''s Side','Spare 30 minute bottles',3,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-211',1),
      ('Driver''s Side','Wheel chock',1,'equipment',array['weekly','inventory'],'frontline-251-212',2),
      ('Driver''s Side','Oil dry bin (full)',1,'equipment',array['weekly','inventory'],'frontline-251-213',3),
      ('Compartment 4','Can of straight gas',1,'equipment',array['weekly','inventory'],'frontline-251-214',1),
      ('Compartment 4','Can of mixed fuel',2,'equipment',array['weekly','inventory'],'frontline-251-215',2),
      ('Compartment 4','Funnel',2,'equipment',array['weekly','inventory'],'frontline-251-216',3),
      ('Compartment 4','Rescue / vent saw',1,'equipment',array['weekly','inventory'],'frontline-251-217',4),
      ('Compartment 4','Stihl saw (utility)',1,'equipment',array['weekly','inventory'],'frontline-251-218',5),
      ('Compartment 4','Saw tool box',1,'equipment',array['weekly','inventory'],'frontline-251-219',6),
      ('Rear Compartment','24 foot extension ladder',1,'equipment',array['weekly','inventory'],'frontline-251-220',1),
      ('Rear Compartment','14 foot roof ladder',1,'equipment',array['weekly','inventory'],'frontline-251-221',2),
      ('Rear Compartment','10 foot attic ladder',1,'equipment',array['weekly','inventory'],'frontline-251-222',3),
      ('Rear Compartment','6 foot pike pole',1,'equipment',array['weekly','inventory'],'frontline-251-223',4),
      ('Rear Compartment','10 foot pike pole',1,'equipment',array['weekly','inventory'],'frontline-251-224',5),
      ('Rear Compartment','6 foot New York hook',2,'equipment',array['weekly','inventory'],'frontline-251-225',6),
      ('Rear Compartment','Stokes basket',1,'equipment',array['weekly','inventory'],'frontline-251-226',7),
      ('Compartment 5','Hilti saw',1,'equipment',array['weekly','inventory'],'frontline-251-227',1),
      ('Compartment 5','Ram brace',1,'equipment',array['weekly','inventory'],'frontline-251-228',2),
      ('Compartment 5','Ram ammo case of chains',1,'equipment',array['weekly','inventory'],'frontline-251-229',3),
      ('Compartment 5','Marrying straps',2,'equipment',array['weekly','inventory'],'frontline-251-230',4),
      ('Compartment 5','Case with various E-Tool tips',1,'equipment',array['weekly','inventory'],'frontline-251-231',5),
      ('Compartment 5','Glass Master with center punch',1,'equipment',array['weekly','inventory'],'frontline-251-232',6),
      ('Compartment 5','Airbag control unit',1,'equipment',array['weekly','inventory'],'frontline-251-233',7),
      ('Compartment 5','Hood release tool',1,'equipment',array['weekly','inventory'],'frontline-251-234',8),
      ('Compartment 5','Air bags',2,'equipment',array['weekly','inventory'],'frontline-251-235',9),
      ('Compartment 5','Rubber air bag pads',2,'equipment',array['weekly','inventory'],'frontline-251-236',10),
      ('Compartment 5','Genesis E-Tools - spreaders',1,'equipment',array['weekly','inventory'],'frontline-251-237',11),
      ('Compartment 5','Genesis E-Tools - cutters',1,'equipment',array['weekly','inventory'],'frontline-251-238',12),
      ('Compartment 5','Genesis E-Tools - ram',1,'equipment',array['weekly','inventory'],'frontline-251-239',13),
      ('Compartment 5','Genesis E-Tools - AC adapter (3-prong to battery)',1,'equipment',array['weekly','inventory'],'frontline-251-240',14),
      ('Compartment 5','Red Pelican case - glass cutter',1,'equipment',array['weekly','inventory'],'frontline-251-241',15),
      ('Compartment 5','Red Pelican case - spare batteries',2,'equipment',array['weekly','inventory'],'frontline-251-242',16),
      ('Compartment 5','Red Pelican case - handle',1,'equipment',array['weekly','inventory'],'frontline-251-243',17),
      ('Compartment 6','Pick head axe',1,'equipment',array['weekly','inventory'],'frontline-251-244',1),
      ('Compartment 6','Maul',1,'equipment',array['weekly','inventory'],'frontline-251-245',2),
      ('Compartment 6','Set of irons',1,'equipment',array['weekly','inventory'],'frontline-251-246',3),
      ('Compartment 6','A Tool',1,'equipment',array['weekly','inventory'],'frontline-251-247',4),
      ('Compartment 6','Closet hook',1,'equipment',array['weekly','inventory'],'frontline-251-248',5),
      ('Compartment 6','Pinned Halligan',1,'equipment',array['weekly','inventory'],'frontline-251-249',6),
      ('Officer''s Side Drawer','Bolt cutters',1,'equipment',array['weekly','inventory'],'frontline-251-250',1),
      ('Officer''s Side Drawer','Sledge',1,'equipment',array['weekly','inventory'],'frontline-251-251',2),
      ('Officer''s Side Drawer','Crow bar',2,'equipment',array['weekly','inventory'],'frontline-251-252',3),
      ('Officer''s Side Drawer','Hay hook',2,'equipment',array['weekly','inventory'],'frontline-251-253',4),
      ('Officer''s Side Drawer','Pry bar',1,'equipment',array['weekly','inventory'],'frontline-251-254',5),
      ('Compartment 7','Front intake manual override wrench',1,'equipment',array['weekly','inventory'],'frontline-251-255',1),
      ('Compartment 7','RASP bag',1,'equipment',array['weekly','inventory'],'frontline-251-256',2),
      ('Compartment 7','Bag of water rescue rope',1,'equipment',array['weekly','inventory'],'frontline-251-257',3),
      ('Compartment 7','150 foot life safety rope',1,'equipment',array['weekly','inventory'],'frontline-251-258',4),
      ('Compartment 7','150 foot utility rope',1,'equipment',array['weekly','inventory'],'frontline-251-259',5),
      ('Compartment 7','100 foot 2.5 inch hose with stacked tip',1,'equipment',array['weekly','inventory'],'frontline-251-260',6),
      ('Compartment 7','100 foot 1.75 inch hose with 7/8 inch smooth bore',1,'equipment',array['weekly','inventory'],'frontline-251-261',7),
      ('Compartment 7','Hi-Rise bag - spanner',1,'equipment',array['weekly','inventory'],'frontline-251-262',8),
      ('Compartment 7','Hi-Rise bag - Storz spanner',1,'equipment',array['weekly','inventory'],'frontline-251-263',9),
      ('Compartment 7','Hi-Rise bag - rope hose tool',1,'equipment',array['weekly','inventory'],'frontline-251-264',10),
      ('Compartment 7','Hi-Rise bag - wheel wrench',1,'equipment',array['weekly','inventory'],'frontline-251-265',11),
      ('Compartment 7','Hi-Rise bag - inline pressure gauge',1,'equipment',array['weekly','inventory'],'frontline-251-266',12),
      ('Compartment 7','Hi-Rise bag - fog nozzle',1,'equipment',array['weekly','inventory'],'frontline-251-267',13),
      ('Officer''s Side','Air bags',2,'equipment',array['weekly','inventory'],'frontline-251-268',1),
      ('Officer''s Side','Spare 60 minute bottles',2,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-269',2),
      ('Officer''s Side','Spare 30 minute bottles',2,'air_pack',array['weekly','inventory','air_pack'],'frontline-251-270',3),
      ('Officer''s Side Step','Roll of 5 inch hose',1,'equipment',array['weekly','inventory'],'frontline-251-271',1),
      ('Officer''s Side Step','Tarps',2,'equipment',array['weekly','inventory'],'frontline-251-272',2),
      ('Top of Engine','Coal shovel',1,'equipment',array['weekly','inventory'],'frontline-251-273',1),
      ('Top of Engine','Spade shovel',2,'equipment',array['weekly','inventory'],'frontline-251-274',2),
      ('Top of Engine','Flat shovel',1,'equipment',array['weekly','inventory'],'frontline-251-275',3),
      ('Top of Engine','Push broom',2,'equipment',array['weekly','inventory'],'frontline-251-276',4),
      ('Top of Engine','Fire broom',3,'equipment',array['weekly','inventory'],'frontline-251-277',5),
      ('Top of Engine','5 gallon bucket AFFF',6,'equipment',array['weekly','inventory'],'frontline-251-278',6),
      ('Top of Engine','Traffic cones',6,'equipment',array['weekly','inventory'],'frontline-251-279',7),
      ('Top of Engine','Ground monitor base',1,'equipment',array['weekly','inventory'],'frontline-251-280',8),
      ('Hose','1.75 inch fog preconnect',1,'equipment',array['weekly','inventory'],'frontline-251-281',1),
      ('Hose','1.75 inch smooth bore preconnect',1,'equipment',array['weekly','inventory'],'frontline-251-282',2),
      ('Hose','2.5 inch preconnect',1,'equipment',array['weekly','inventory'],'frontline-251-283',3),
      ('Hose','Hi-Rise load',1,'equipment',array['weekly','inventory'],'frontline-251-284',4),
      ('Hose','Front bumper supply',1,'equipment',array['weekly','inventory'],'frontline-251-285',5),
      ('Hose','Front bumper preconnect',1,'equipment',array['weekly','inventory'],'frontline-251-286',6),
      ('Hose','Lead line',1,'equipment',array['weekly','inventory'],'frontline-251-287',7),
      ('Hose','Skid load',1,'equipment',array['weekly','inventory'],'frontline-251-288',8),
      ('Hose','L.D.H. supply (rear)',1,'equipment',array['weekly','inventory'],'frontline-251-289',9)
  )
  insert into public.inventory_equipment
    (department_id, apparatus_id, compartment_id, name, quantity_required,
     equipment_category, check_types, source_key, source_form, item_order)
  select
    stickney_id,
    engine_1203_id,
    c.id,
    source_items.item_name,
    source_items.quantity_required,
    source_items.equipment_category,
    source_items.check_types,
    source_items.source_key,
    '1203 Weekly Check (FRONTLINE) form 251',
    source_items.item_order
  from source_items
  join public.inventory_compartments c
    on c.department_id = stickney_id
   and c.apparatus_id = engine_1203_id
   and c.label = source_items.section_label
  on conflict (department_id, apparatus_id, source_key) where source_key is not null
  do update set
    compartment_id = excluded.compartment_id,
    name = excluded.name,
    quantity_required = excluded.quantity_required,
    equipment_category = excluded.equipment_category,
    check_types = excluded.check_types,
    source_form = excluded.source_form,
    item_order = excluded.item_order,
    retired_at = null;
end $$;
