do $$
declare
  stickney_id uuid;
  ambulance_1205_id uuid;
begin
  select id into stickney_id
  from public.departments
  where name = 'Stickney Fire Department'
  limit 1;

  select id into ambulance_1205_id
  from public.inventory_apparatus_profiles
  where department_id = stickney_id and name = '1205'
  limit 1;

  if stickney_id is null or ambulance_1205_id is null then
    raise exception 'Stickney Fire Department apparatus 1205 must exist before loading form 272';
  end if;

  insert into public.inventory_compartments
    (department_id, apparatus_id, label, side, sort_order)
  values
    (stickney_id, ambulance_1205_id, 'Vehicle', 'cab', 100),
    (stickney_id, ambulance_1205_id, 'Disinfection / Cleaning', 'interior', 110),
    (stickney_id, ambulance_1205_id, 'Front Tires', 'front', 120),
    (stickney_id, ambulance_1205_id, 'Rear Tires', 'rear', 130),
    (stickney_id, ambulance_1205_id, 'Cab', 'cab', 200),
    (stickney_id, ambulance_1205_id, 'Driver''s Side Front', 'driver', 210),
    (stickney_id, ambulance_1205_id, 'Driver''s Side Middle', 'driver', 220),
    (stickney_id, ambulance_1205_id, 'Driver''s Side Rear', 'driver', 230),
    (stickney_id, ambulance_1205_id, 'Passenger Side Rear', 'officer', 240),
    (stickney_id, ambulance_1205_id, 'Jump Bag - Main Compartment', 'interior', 250),
    (stickney_id, ambulance_1205_id, 'Jump Bag - Top Mesh Pouch', 'interior', 260),
    (stickney_id, ambulance_1205_id, 'Jump Bag - Large Side Pouch 1', 'interior', 270),
    (stickney_id, ambulance_1205_id, 'Jump Bag - Large Side Pouch 2', 'interior', 280),
    (stickney_id, ambulance_1205_id, 'Jump Bag - Small Side Pouch', 'interior', 290),
    (stickney_id, ambulance_1205_id, 'Medication Boxes', 'interior', 300),
    (stickney_id, ambulance_1205_id, 'Oxygen Bag', 'interior', 310),
    (stickney_id, ambulance_1205_id, 'Action Area', 'interior', 320),
    (stickney_id, ambulance_1205_id, 'Cabinet 1 - Above Action Area', 'interior', 330),
    (stickney_id, ambulance_1205_id, 'Cabinet 2', 'interior', 340),
    (stickney_id, ambulance_1205_id, 'Cabinet 3 - Beneath Action Area', 'interior', 350),
    (stickney_id, ambulance_1205_id, 'Cabinet 4 - Corner Shelf', 'interior', 360),
    (stickney_id, ambulance_1205_id, 'Cabinet 5', 'interior', 370),
    (stickney_id, ambulance_1205_id, 'Cabinet 6', 'interior', 380),
    (stickney_id, ambulance_1205_id, 'Cabinet 7 - Overhead Bench Seat', 'interior', 390),
    (stickney_id, ambulance_1205_id, 'Under Bench Seat', 'interior', 400),
    (stickney_id, ambulance_1205_id, 'Roll-up Cabinet Top Shelf', 'interior', 410),
    (stickney_id, ambulance_1205_id, 'Roll-up Cabinet Second Shelf', 'interior', 420),
    (stickney_id, ambulance_1205_id, 'Roll-up Cabinet Third Shelf', 'interior', 430),
    (stickney_id, ambulance_1205_id, 'Pediatric Jump Bag', 'interior', 440),
    (stickney_id, ambulance_1205_id, 'Drawer', 'interior', 450),
    (stickney_id, ambulance_1205_id, 'Fourth Shelf', 'interior', 460),
    (stickney_id, ambulance_1205_id, 'Bottom Shelf', 'interior', 470),
    (stickney_id, ambulance_1205_id, 'Linen Cabinet', 'interior', 480),
    (stickney_id, ambulance_1205_id, 'Misc. Interior', 'interior', 490)
  on conflict (apparatus_id, label) do update
  set side = excluded.side,
      sort_order = excluded.sort_order;

  with source_items(section_label, item_name, quantity_required, equipment_category, check_types, item_order) as (
    values
      ('Vehicle','Fuel - fill at or below 3/4',1,'vehicle',array['weekly'],1),
      ('Vehicle','Record mileage',1,'vehicle',array['weekly'],2),
      ('Vehicle','Engine oil',1,'vehicle',array['weekly'],3),
      ('Vehicle','Transmission fluid (vehicle must be on and in neutral)',1,'vehicle',array['weekly'],4),
      ('Vehicle','Coolant / radiator level',1,'vehicle',array['weekly'],5),
      ('Vehicle','Power steering fluid',1,'vehicle',array['weekly'],6),
      ('Vehicle','Battery terminals tight and free of corrosion',1,'vehicle',array['weekly'],7),
      ('Vehicle','Belts tight and in good condition',1,'vehicle',array['weekly'],8),
      ('Vehicle','Dash gauges and electronics functioning properly',1,'vehicle',array['weekly'],9),
      ('Vehicle','Head lights and brake lights functioning properly',1,'vehicle',array['weekly'],10),
      ('Vehicle','Running lights functioning properly',1,'vehicle',array['weekly'],11),
      ('Vehicle','Turn signals and hazards functioning properly',1,'vehicle',array['weekly'],12),
      ('Vehicle','Compartment lights functioning properly',1,'vehicle',array['weekly'],13),
      ('Vehicle','All interior lights functioning properly',1,'vehicle',array['weekly'],14),
      ('Vehicle','Siren and horn functioning properly',1,'vehicle',array['weekly'],15),
      ('Vehicle','Emergency lights functioning properly',1,'vehicle',array['weekly'],16),
      ('Vehicle','Backup lights and alarm functioning properly',1,'vehicle',array['weekly'],17),
      ('Vehicle','Overall body condition and observed damage',1,'vehicle',array['weekly'],18),
      ('Disinfection / Cleaning','Wipe down and disinfect all hard surfaces',1,'vehicle',array['weekly'],1),
      ('Disinfection / Cleaning','Sweep and mop rear of ambulance and front cab footwells',1,'vehicle',array['weekly'],2),
      ('Disinfection / Cleaning','Disinfect stretcher and stair chair',1,'vehicle',array['weekly'],3),
      ('Disinfection / Cleaning','Computer and printer operating correctly',1,'vehicle',array['weekly'],4),
      ('Disinfection / Cleaning','On-board suction functioning correctly',1,'vehicle',array['weekly'],5),
      ('Disinfection / Cleaning','Inspect all hand tools; clean and oil as needed',1,'vehicle',array['weekly'],6),
      ('Front Tires','Front left PSI',1,'vehicle',array['weekly'],1),
      ('Front Tires','Front right PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Rear left inner PSI',1,'vehicle',array['weekly'],1),
      ('Rear Tires','Rear left outer PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Rear right inner PSI',1,'vehicle',array['weekly'],3),
      ('Rear Tires','Rear right outer PSI',1,'vehicle',array['weekly'],4),
      ('Cab','Run sheets',10,'equipment',array['inventory'],1),
      ('Cab','Billing authorization / HIPAA forms',10,'equipment',array['inventory'],2),
      ('Cab','Refusal forms',10,'equipment',array['inventory'],3),
      ('Cab','Multi-patient refusal forms',10,'equipment',array['inventory'],4),
      ('Cab','Spanish / English refusal forms',10,'equipment',array['inventory'],5),
      ('Cab','Polish / English refusal forms',10,'equipment',array['inventory'],6),
      ('Cab','Arabic / English refusal forms',10,'equipment',array['inventory'],7),
      ('Cab','Petitions for involuntary admission',10,'equipment',array['inventory'],8),
      ('Cab','Safe Haven information sheet',1,'equipment',array['inventory'],9),
      ('Cab','File for Life',1,'equipment',array['inventory'],10),
      ('Cab','COVID-19 non-transport forms',10,'equipment',array['inventory'],11),
      ('Cab','List of vacant properties',1,'equipment',array['inventory'],12),
      ('Cab','Residential Knox Box locations',1,'equipment',array['inventory'],13),
      ('Cab','Commercial Knox Box locations',1,'equipment',array['inventory'],14),
      ('Cab','Mobile radio',1,'equipment',array['inventory'],15),
      ('Cab','Portable radios',2,'equipment',array['inventory'],16),
      ('Cab','Knox Box keys',1,'equipment',array['inventory'],17),
      ('Cab','Door opener',1,'equipment',array['inventory'],18),
      ('Cab','I-PASS',1,'equipment',array['inventory'],19),
      ('Cab','Emergency Response Guidebook',1,'equipment',array['inventory'],20),
      ('Cab','Region 7 SMO book',1,'equipment',array['inventory'],21),
      ('Cab','Preplan book',1,'equipment',array['inventory'],22),
      ('Cab','Terrorism book',1,'equipment',array['inventory'],23),
      ('Cab','Seat belt cutter',1,'equipment',array['inventory'],24),
      ('Cab','Bell Fuels gas card',1,'equipment',array['inventory'],25),
      ('Cab','Life hammer',1,'equipment',array['inventory'],26),
      ('Cab','Insurance card',1,'equipment',array['inventory'],27),
      ('Cab','Registration',1,'equipment',array['inventory'],28),
      ('Cab','Antidote kit (yellow Pelican case)',1,'equipment',array['inventory'],29),
      ('Cab','Gloves (all sizes)',1,'equipment',array['inventory'],30),
      ('Cab','Fire extinguisher',1,'equipment',array['inventory'],31),
      ('Cab','PPE kits with surgical mask, N95 and gown',2,'equipment',array['inventory'],32),
      ('Cab','Toughbook',1,'equipment',array['inventory'],33),
      ('Cab','Safety vests',2,'equipment',array['inventory'],34),
      ('Driver''s Side Front','Onboard O2 PSI (replace at 500 PSI)',1,'equipment',array['inventory'],1),
      ('Driver''s Side Front','Ice melt containers',2,'equipment',array['inventory'],2),
      ('Driver''s Side Front','Soap bottle',1,'equipment',array['inventory'],3),
      ('Driver''s Side Front','Shovel',1,'equipment',array['inventory'],4),
      ('Driver''s Side Front','Opticide',1,'equipment',array['inventory'],5),
      ('Driver''s Side Front','DeWalt sprayer appliance',1,'equipment',array['inventory'],6),
      ('Driver''s Side Front','Animal snare',1,'equipment',array['inventory'],7),
      ('Driver''s Side Front','Spare SCBA cylinder',1,'air_pack',array['air_pack'],1),
      ('Driver''s Side Front','Decontamination SCBA at 4500 PSI',1,'air_pack',array['air_pack'],2),
      ('Driver''s Side Middle','Car seat',1,'equipment',array['inventory'],1),
      ('Driver''s Side Middle','SKED / Oregon spine splint',1,'equipment',array['inventory'],2),
      ('Driver''s Side Middle','Traction splint (adult and pediatric)',1,'equipment',array['inventory'],3),
      ('Driver''s Side Middle','Extrication tools',1,'equipment',array['inventory'],4),
      ('Driver''s Side Middle','Caution tape',1,'equipment',array['inventory'],5),
      ('Driver''s Side Middle','Flares',1,'equipment',array['inventory'],6),
      ('Driver''s Side Middle','Utility rope',1,'equipment',array['inventory'],7),
      ('Driver''s Side Middle','Hydrant wrench',1,'equipment',array['inventory'],8),
      ('Driver''s Side Middle','Pick head axe',1,'equipment',array['inventory'],9),
      ('Driver''s Side Middle','Sledgehammer',1,'equipment',array['inventory'],10),
      ('Driver''s Side Middle','Loyola LifeStar landing kit',1,'equipment',array['inventory'],11),
      ('Driver''s Side Middle','Road triangles',1,'equipment',array['inventory'],12),
      ('Driver''s Side Rear','Driver SCBA pack at 4500 PSI',1,'air_pack',array['air_pack'],1),
      ('Driver''s Side Rear','Passenger SCBA pack at 4500 PSI',1,'air_pack',array['air_pack'],2),
      ('Passenger Side Rear','Backboards',2,'equipment',array['inventory'],1),
      ('Passenger Side Rear','Scoop stretcher',1,'equipment',array['inventory'],2),
      ('Passenger Side Rear','Stair chair',1,'equipment',array['inventory'],3),
      ('Passenger Side Rear','CPR / short board',1,'equipment',array['inventory'],4),
      ('Passenger Side Rear','Spider straps',1,'equipment',array['inventory'],5),
      ('Passenger Side Rear','Water rope / water disk',1,'equipment',array['inventory'],6),
      ('Passenger Side Rear','KED',1,'equipment',array['inventory'],7),
      ('Passenger Side Rear','Splints',6,'equipment',array['inventory'],8),
      ('Passenger Side Rear','Head beds',3,'equipment',array['inventory'],9),
      ('Passenger Side Rear','Adult C-collars',3,'equipment',array['inventory'],10),
      ('Jump Bag - Main Compartment','Stethoscope',1,'equipment',array['inventory'],1),
      ('Jump Bag - Main Compartment','Adult BP cuff',1,'equipment',array['inventory'],2),
      ('Jump Bag - Main Compartment','Pulse oximeter',1,'equipment',array['inventory'],3),
      ('Jump Bag - Main Compartment','CPR mask',1,'equipment',array['inventory'],4),
      ('Jump Bag - Main Compartment','Glucometer with lancets, test strips, alcohol pads and bandages',1,'equipment',array['inventory'],5),
      ('Jump Bag - Main Compartment','Trauma shears',1,'equipment',array['inventory'],6),
      ('Jump Bag - Main Compartment','Handheld suction',1,'equipment',array['inventory'],7),
      ('Jump Bag - Main Compartment','Bite stick',1,'equipment',array['inventory'],8),
      ('Jump Bag - Main Compartment','Tube holder',1,'equipment',array['inventory'],9),
      ('Jump Bag - Main Compartment','Bacterial / viral filter',1,'equipment',array['inventory'],10),
      ('Jump Bag - Main Compartment','Nebulizer with albuterol and Atrovent (check date)',1,'equipment',array['inventory'],11),
      ('Jump Bag - Main Compartment','i-gel sizes 3, 4 and 5',1,'equipment',array['inventory'],12),
      ('Jump Bag - Main Compartment','Adult BVM',1,'equipment',array['inventory'],13),
      ('Jump Bag - Main Compartment','EtCO2 detector',1,'equipment',array['inventory'],14),
      ('Jump Bag - Main Compartment','Pen light',1,'equipment',array['inventory'],15),
      ('Jump Bag - Top Mesh Pouch','Oral airways',1,'equipment',array['inventory'],1),
      ('Jump Bag - Top Mesh Pouch','Nasal airways sizes 12Fr-34Fr (one each)',1,'equipment',array['inventory'],2),
      ('Jump Bag - Top Mesh Pouch','Lubricating jelly',10,'equipment',array['inventory'],3),
      ('Jump Bag - Top Mesh Pouch','Hot pack',1,'equipment',array['inventory'],4),
      ('Jump Bag - Top Mesh Pouch','Cold pack',1,'equipment',array['inventory'],5),
      ('Jump Bag - Large Side Pouch 1','Adult C-collars',2,'equipment',array['inventory'],1),
      ('Jump Bag - Large Side Pouch 1','Pediatric C-collar',1,'equipment',array['inventory'],2),
      ('Jump Bag - Large Side Pouch 1','Infant C-collar',1,'equipment',array['inventory'],3),
      ('Jump Bag - Large Side Pouch 1','Short board splint',1,'equipment',array['inventory'],4),
      ('Jump Bag - Large Side Pouch 1','Long board splint',1,'equipment',array['inventory'],5),
      ('Jump Bag - Large Side Pouch 2','Multi-trauma dressing',1,'equipment',array['inventory'],1),
      ('Jump Bag - Large Side Pouch 2','Burn sheet',1,'equipment',array['inventory'],2),
      ('Jump Bag - Large Side Pouch 2','Occlusive dressings',2,'equipment',array['inventory'],3),
      ('Jump Bag - Large Side Pouch 2','Abdominal pads',2,'equipment',array['inventory'],4),
      ('Jump Bag - Large Side Pouch 2','Kerlix',4,'equipment',array['inventory'],5),
      ('Jump Bag - Large Side Pouch 2','4x4 gauze',10,'equipment',array['inventory'],6),
      ('Jump Bag - Large Side Pouch 2','Hemostatic dressings',2,'equipment',array['inventory'],7),
      ('Jump Bag - Large Side Pouch 2','Arm slings',2,'equipment',array['inventory'],8),
      ('Jump Bag - Large Side Pouch 2','Woundstop',1,'equipment',array['inventory'],9),
      ('Jump Bag - Large Side Pouch 2','Elastic bandages',2,'equipment',array['inventory'],10),
      ('Jump Bag - Large Side Pouch 2','SAM splint',1,'equipment',array['inventory'],11),
      ('Jump Bag - Large Side Pouch 2','Sterile water 500cc',1,'equipment',array['inventory'],12),
      ('Jump Bag - Large Side Pouch 2','Hydrogen peroxide',1,'equipment',array['inventory'],13),
      ('Jump Bag - Large Side Pouch 2','Medical tape (assorted)',1,'equipment',array['inventory'],14),
      ('Jump Bag - Large Side Pouch 2','Tourniquet',1,'equipment',array['inventory'],15),
      ('Jump Bag - Small Side Pouch','Spare gloves (pairs, L and XL)',2,'equipment',array['inventory'],1),
      ('Jump Bag - Small Side Pouch','Eye protection',2,'equipment',array['inventory'],2),
      ('Jump Bag - Small Side Pouch','Surgical masks',4,'equipment',array['inventory'],3),
      ('Jump Bag - Small Side Pouch','N95 masks',4,'equipment',array['inventory'],4),
      ('Jump Bag - Small Side Pouch','Biohazard bags',2,'equipment',array['inventory'],5),
      ('Medication Boxes','Aspirin bottle',1,'equipment',array['inventory'],1),
      ('Medication Boxes','Epinephrine kits',2,'equipment',array['inventory'],2),
      ('Medication Boxes','Glucagon',1,'equipment',array['inventory'],3),
      ('Medication Boxes','Narcan',2,'equipment',array['inventory'],4),
      ('Medication Boxes','Nasal atomizer / MADD device',1,'equipment',array['inventory'],5),
      ('Medication Boxes','Oral glucose',2,'equipment',array['inventory'],6),
      ('Medication Boxes','Zofran ODT',1,'equipment',array['inventory'],7),
      ('Medication Boxes','1cc syringe',1,'equipment',array['inventory'],8),
      ('Medication Boxes','3cc syringe',1,'equipment',array['inventory'],9),
      ('Medication Boxes','21g needle',1,'equipment',array['inventory'],10),
      ('Oxygen Bag','Portable O2 PSI (replace at 500 PSI)',1,'equipment',array['inventory'],1),
      ('Oxygen Bag','Adult NRB masks',2,'equipment',array['inventory'],2),
      ('Oxygen Bag','Adult nasal cannula',1,'equipment',array['inventory'],3),
      ('Action Area','Tablet (charged / charging)',1,'equipment',array['inventory'],1),
      ('Action Area','Cell phone (charged / charging)',1,'equipment',array['inventory'],2),
      ('Action Area','BP cuff',1,'equipment',array['inventory'],3),
      ('Action Area','Stethoscope (adult / child)',1,'equipment',array['inventory'],4),
      ('Action Area','Glucometer with lancets, test strips, alcohol pads and bandages',1,'equipment',array['inventory'],5),
      ('Action Area','Region 7 SMO book',1,'equipment',array['inventory'],6),
      ('Action Area','Spanish book',1,'equipment',array['inventory'],7),
      ('Action Area','Pharmacopeia book',1,'equipment',array['inventory'],8),
      ('Action Area','Pediatric chart',1,'equipment',array['inventory'],9),
      ('Action Area','Thermometer',1,'equipment',array['inventory'],10),
      ('Action Area','Pen light',1,'equipment',array['inventory'],11),
      ('Action Area','Trauma shears',1,'equipment',array['inventory'],12),
      ('Action Area','Ring cutter',1,'equipment',array['inventory'],13),
      ('Action Area','Handcuff key',1,'equipment',array['inventory'],14),
      ('Action Area','Hand sanitizer',1,'equipment',array['inventory'],15),
      ('Cabinet 1 - Above Action Area','PPE kits with surgical mask, N95 and gown',10,'equipment',array['inventory'],1),
      ('Cabinet 1 - Above Action Area','Face shields',4,'equipment',array['inventory'],2),
      ('Cabinet 1 - Above Action Area','Accident kits',2,'equipment',array['inventory'],3),
      ('Cabinet 1 - Above Action Area','Exposure kits',4,'equipment',array['inventory'],4),
      ('Cabinet 1 - Above Action Area','Printed EMS run reports',10,'equipment',array['inventory'],5),
      ('Cabinet 1 - Above Action Area','Pediatric BVM',1,'equipment',array['inventory'],6),
      ('Cabinet 1 - Above Action Area','Infant BVM',1,'equipment',array['inventory'],7),
      ('Cabinet 1 - Above Action Area','Child BP cuff',1,'equipment',array['inventory'],8),
      ('Cabinet 1 - Above Action Area','Suction canister with lid',1,'equipment',array['inventory'],9),
      ('Cabinet 1 - Above Action Area','Adult BVMs',2,'equipment',array['inventory'],10),
      ('Cabinet 2','Adult NRB masks',5,'equipment',array['inventory'],1),
      ('Cabinet 2','Adult nasal cannulas',5,'equipment',array['inventory'],2),
      ('Cabinet 2','Oxygen tubing',3,'equipment',array['inventory'],3),
      ('Cabinet 2','Nebulizer',1,'equipment',array['inventory'],4),
      ('Cabinet 2','Albuterol',1,'equipment',array['inventory'],5),
      ('Cabinet 2','Atrovent',1,'equipment',array['inventory'],6),
      ('Cabinet 2','Safety glasses',5,'equipment',array['inventory'],7),
      ('Cabinet 2','Suction tubing',2,'equipment',array['inventory'],8),
      ('Cabinet 2','Suction catheters sizes 6, 8, 10, 12, 14, 16 and 18Fr (each size)',2,'equipment',array['inventory'],9),
      ('Cabinet 2','Yankauer / flange suction tips',5,'equipment',array['inventory'],10),
      ('Cabinet 2','Oral airways (assorted)',1,'equipment',array['inventory'],11),
      ('Cabinet 2','Nasal airways sizes 12Fr-34Fr (one each)',1,'equipment',array['inventory'],12),
      ('Cabinet 2','Lubricating jelly',5,'equipment',array['inventory'],13),
      ('Cabinet 2','CPR masks',2,'equipment',array['inventory'],14),
      ('Cabinet 2','Bacterial / viral filters',2,'equipment',array['inventory'],15),
      ('Cabinet 2','Tube holders',2,'equipment',array['inventory'],16),
      ('Cabinet 2','EtCO2 detectors',2,'equipment',array['inventory'],17),
      ('Cabinet 2','i-gel sizes 3, 4 and 5 (each size)',2,'equipment',array['inventory'],18),
      ('Cabinet 2','Pediatric nebulizer mask',1,'equipment',array['inventory'],19),
      ('Cabinet 2','Pediatric nasal cannulas',3,'equipment',array['inventory'],20),
      ('Cabinet 2','Infant nasal cannulas',3,'equipment',array['inventory'],21),
      ('Cabinet 2','Pediatric NRB masks',3,'equipment',array['inventory'],22),
      ('Cabinet 2','Infant NRB masks',3,'equipment',array['inventory'],23),
      ('Cabinet 3 - Beneath Action Area','Emesis basins',3,'equipment',array['inventory'],1),
      ('Cabinet 3 - Beneath Action Area','Cavicide wipes',1,'equipment',array['inventory'],2),
      ('Cabinet 3 - Beneath Action Area','Opticide',1,'equipment',array['inventory'],3),
      ('Cabinet 3 - Beneath Action Area','Biohazard bags',20,'equipment',array['inventory'],4),
      ('Cabinet 3 - Beneath Action Area','Dustpan and broom',1,'equipment',array['inventory'],5),
      ('Cabinet 4 - Corner Shelf','OB kits',2,'equipment',array['inventory'],1),
      ('Cabinet 4 - Corner Shelf','Infant hats',2,'equipment',array['inventory'],2),
      ('Cabinet 4 - Corner Shelf','Baby bottle',1,'equipment',array['inventory'],3),
      ('Cabinet 4 - Corner Shelf','Gowns',4,'equipment',array['inventory'],4),
      ('Cabinet 4 - Corner Shelf','Glucometer supplies with lancets, test strips, alcohol pads and bandages',1,'equipment',array['inventory'],5),
      ('Cabinet 4 - Corner Shelf','Sterile gloves',2,'equipment',array['inventory'],6),
      ('Cabinet 4 - Corner Shelf','Latex-free kit',1,'equipment',array['inventory'],7),
      ('Cabinet 5','Kerlix',10,'equipment',array['inventory'],1),
      ('Cabinet 5','4x4 gauze',20,'equipment',array['inventory'],2),
      ('Cabinet 5','Abdominal pads',2,'equipment',array['inventory'],3),
      ('Cabinet 5','Occlusive dressings',2,'equipment',array['inventory'],4),
      ('Cabinet 5','Hemostatic dressings',4,'equipment',array['inventory'],5),
      ('Cabinet 5','Woundstop',1,'equipment',array['inventory'],6),
      ('Cabinet 5','Tape (assorted)',1,'equipment',array['inventory'],7),
      ('Cabinet 5','Elastic bandages',4,'equipment',array['inventory'],8),
      ('Cabinet 5','Triangle bandages',4,'equipment',array['inventory'],9),
      ('Cabinet 6','Arm sling sizes S, M, L and XL',1,'equipment',array['inventory'],1),
      ('Cabinet 6','Clavicle splint',1,'equipment',array['inventory'],2),
      ('Cabinet 6','SAM splint',1,'equipment',array['inventory'],3),
      ('Cabinet 6','Long board splints',3,'equipment',array['inventory'],4),
      ('Cabinet 6','Short board splints',3,'equipment',array['inventory'],5),
      ('Cabinet 6','Soft restraints',1,'equipment',array['inventory'],6),
      ('Cabinet 6','Red / blue Velcro restraint',1,'equipment',array['inventory'],7),
      ('Cabinet 6','Aluminum foil',1,'equipment',array['inventory'],8),
      ('Cabinet 6','Cups',10,'equipment',array['inventory'],9),
      ('Cabinet 6','Box of baggies',1,'equipment',array['inventory'],10),
      ('Cabinet 6','Cold packs',5,'equipment',array['inventory'],11),
      ('Cabinet 6','Hot packs',5,'equipment',array['inventory'],12),
      ('Cabinet 7 - Overhead Bench Seat','Sterile water 2000cc',2,'equipment',array['inventory'],1),
      ('Cabinet 7 - Overhead Bench Seat','Normal saline 2000cc',2,'equipment',array['inventory'],2),
      ('Cabinet 7 - Overhead Bench Seat','Hydrogen peroxide',2,'equipment',array['inventory'],3),
      ('Cabinet 7 - Overhead Bench Seat','Multi-trauma dressings',5,'equipment',array['inventory'],4),
      ('Cabinet 7 - Overhead Bench Seat','Burn sheets',4,'equipment',array['inventory'],5),
      ('Under Bench Seat','Pillows with pillow cases',2,'equipment',array['inventory'],1),
      ('Under Bench Seat','Triage tag kit',1,'equipment',array['inventory'],2),
      ('Under Bench Seat','Body bags',2,'equipment',array['inventory'],3),
      ('Under Bench Seat','Stuffed animals',1,'equipment',array['inventory'],4),
      ('Under Bench Seat','Duct tape',1,'equipment',array['inventory'],5),
      ('Under Bench Seat','Emergency / disposable blankets',2,'equipment',array['inventory'],6),
      ('Under Bench Seat','Seat belt extension straps',2,'equipment',array['inventory'],7),
      ('Under Bench Seat','Bed pans',2,'equipment',array['inventory'],8),
      ('Under Bench Seat','Urinals',2,'equipment',array['inventory'],9),
      ('Roll-up Cabinet Top Shelf','BP cuffs (assorted kit)',1,'equipment',array['inventory'],1),
      ('Roll-up Cabinet Top Shelf','Portable suction unit',1,'equipment',array['inventory'],2),
      ('Roll-up Cabinet Top Shelf','Catheter bag sizes 6Fr-18Fr',1,'equipment',array['inventory'],3),
      ('Roll-up Cabinet Top Shelf','Spare stretcher battery',1,'equipment',array['inventory'],4),
      ('Roll-up Cabinet Second Shelf','C-collar bag with 4 adult, 4 pediatric and 4 infant collars',1,'equipment',array['inventory'],1),
      ('Roll-up Cabinet Third Shelf','AED',1,'equipment',array['inventory'],1),
      ('Roll-up Cabinet Third Shelf','Defibrillator pads',2,'equipment',array['inventory'],2),
      ('Roll-up Cabinet Third Shelf','Pediatric key',1,'equipment',array['inventory'],3),
      ('Roll-up Cabinet Third Shelf','Razor',1,'equipment',array['inventory'],4),
      ('Roll-up Cabinet Third Shelf','AED battery',1,'equipment',array['inventory'],5),
      ('Pediatric Jump Bag','BP cuff with stethoscope',1,'equipment',array['inventory'],1),
      ('Pediatric Jump Bag','Bulb syringes',2,'equipment',array['inventory'],2),
      ('Pediatric Jump Bag','Oral airways',4,'equipment',array['inventory'],3),
      ('Pediatric Jump Bag','Broselow tape',1,'equipment',array['inventory'],4),
      ('Pediatric Jump Bag','Pedi-Wheel',1,'equipment',array['inventory'],5),
      ('Pediatric Jump Bag','Pediatric BVM',1,'equipment',array['inventory'],6),
      ('Pediatric Jump Bag','Pediatric NRB mask',1,'equipment',array['inventory'],7),
      ('Pediatric Jump Bag','Pediatric nasal cannula',1,'equipment',array['inventory'],8),
      ('Pediatric Jump Bag','Infant BVM',1,'equipment',array['inventory'],9),
      ('Pediatric Jump Bag','Infant NRB masks',3,'equipment',array['inventory'],10),
      ('Pediatric Jump Bag','Infant nasal cannulas',3,'equipment',array['inventory'],11),
      ('Drawer','Epinephrine kits',2,'equipment',array['inventory'],1),
      ('Drawer','Glucagon',1,'equipment',array['inventory'],2),
      ('Drawer','Narcan',2,'equipment',array['inventory'],3),
      ('Drawer','Nasal atomizer / MADD devices',2,'equipment',array['inventory'],4),
      ('Drawer','Oral glucose',2,'equipment',array['inventory'],5),
      ('Drawer','Zofran ODT',1,'equipment',array['inventory'],6),
      ('Drawer','Aspirin bottle',1,'equipment',array['inventory'],7),
      ('Drawer','1cc syringe',1,'equipment',array['inventory'],8),
      ('Drawer','3cc syringe',1,'equipment',array['inventory'],9),
      ('Drawer','21g needle',1,'equipment',array['inventory'],10),
      ('Drawer','King tubes sizes 3, 4 and 5',1,'equipment',array['inventory'],11),
      ('Drawer','EtCO2 detectors',2,'equipment',array['inventory'],12),
      ('Drawer','Tube holder',1,'equipment',array['inventory'],13),
      ('Fourth Shelf','Jump bag',1,'equipment',array['inventory'],1),
      ('Fourth Shelf','O2 bag',1,'equipment',array['inventory'],2),
      ('Bottom Shelf','Plastic bin with 2 Scott P100 filters, 2 Scott CBRN canisters and 2 adapters',1,'equipment',array['inventory'],1),
      ('Bottom Shelf','Mega Mover',1,'equipment',array['inventory'],2),
      ('Bottom Shelf','Bottle jack',1,'equipment',array['inventory'],3),
      ('Linen Cabinet','Sheets',5,'equipment',array['inventory'],1),
      ('Linen Cabinet','Blankets',5,'equipment',array['inventory'],2),
      ('Linen Cabinet','Towels',10,'equipment',array['inventory'],3),
      ('Linen Cabinet','Spare box of gloves',1,'equipment',array['inventory'],4),
      ('Misc. Interior','Powercot stretcher and load system charged and operating properly',1,'equipment',array['inventory'],1),
      ('Misc. Interior','Gloves sizes S, M, L and XL',1,'equipment',array['inventory'],2),
      ('Misc. Interior','Sharps bin',1,'equipment',array['inventory'],3),
      ('Misc. Interior','Fire extinguisher',1,'equipment',array['inventory'],4),
      ('Misc. Interior','Spare O2 cylinders',2,'equipment',array['inventory'],5)
  ), ranked_items as (
    select
      source_items.*,
      c.id as compartment_id,
      'form-272-' || lpad(row_number() over (
        order by c.sort_order, source_items.item_order, source_items.item_name
      )::text, 3, '0') as source_key
    from source_items
    join public.inventory_compartments c
      on c.department_id = stickney_id
     and c.apparatus_id = ambulance_1205_id
     and c.label = source_items.section_label
  )
  insert into public.inventory_equipment
    (department_id, apparatus_id, compartment_id, name, quantity_required,
     equipment_category, check_types, source_key, source_form, item_order)
  select
    stickney_id,
    ambulance_1205_id,
    ranked_items.compartment_id,
    ranked_items.item_name,
    ranked_items.quantity_required,
    ranked_items.equipment_category,
    ranked_items.check_types,
    ranked_items.source_key,
    '1205 Weekly Check form 272',
    ranked_items.item_order
  from ranked_items
  on conflict (department_id, apparatus_id, source_key) where source_key is not null
  do update set
    compartment_id = excluded.compartment_id,
    name = excluded.name,
    quantity_required = excluded.quantity_required,
    equipment_category = excluded.equipment_category,
    check_types = excluded.check_types,
    source_form = excluded.source_form,
    item_order = excluded.item_order,
    retired_at = null;
end $$;
