do $$
declare
  stickney_id uuid;
  truck_1204_id uuid;
begin
  select id into stickney_id
  from public.departments
  where name = 'Stickney Fire Department'
  limit 1;

  select id into truck_1204_id
  from public.inventory_apparatus_profiles
  where department_id = stickney_id and name = '1204'
  limit 1;

  if stickney_id is null or truck_1204_id is null then
    raise exception 'Stickney Fire Department apparatus 1204 must exist before loading form 439';
  end if;

  insert into public.inventory_compartments
    (department_id, apparatus_id, label, side, sort_order)
  values
    (stickney_id, truck_1204_id, 'Vehicle', 'cab', 100),
    (stickney_id, truck_1204_id, 'Front Tires', 'front', 110),
    (stickney_id, truck_1204_id, 'Rear Tires', 'rear', 120),
    (stickney_id, truck_1204_id, 'Cab', 'cab', 130),
    (stickney_id, truck_1204_id, 'Pump / Booster Tank', 'pump', 140),
    (stickney_id, truck_1204_id, 'SCBA', 'cab', 150),
    (stickney_id, truck_1204_id, 'Tools & Equipment', 'interior', 160),
    (stickney_id, truck_1204_id, 'Compartment 1 (EMS)', 'driver', 170),
    (stickney_id, truck_1204_id, 'Compartment 2', 'driver', 180),
    (stickney_id, truck_1204_id, 'Engineer''s Panel (Compartment 3)', 'pump', 190),
    (stickney_id, truck_1204_id, 'Compartment 4', 'driver', 200),
    (stickney_id, truck_1204_id, 'Compartment 5', 'driver', 210),
    (stickney_id, truck_1204_id, 'Compartment 6', 'driver', 220),
    (stickney_id, truck_1204_id, 'Compartment 7 (Rear)', 'rear', 230),
    (stickney_id, truck_1204_id, 'Compartment 8 (Rear)', 'rear', 240),
    (stickney_id, truck_1204_id, 'Compartment 9 (Rear)', 'rear', 250),
    (stickney_id, truck_1204_id, 'Rear Hose', 'rear', 260),
    (stickney_id, truck_1204_id, 'Compartment 10', 'officer', 270),
    (stickney_id, truck_1204_id, 'Compartment 11', 'officer', 280),
    (stickney_id, truck_1204_id, 'Compartment 12', 'officer', 290),
    (stickney_id, truck_1204_id, 'Compartment 13', 'officer', 300)
  on conflict (apparatus_id, label) do update
  set side = excluded.side,
      sort_order = excluded.sort_order;

  with source_items(section_label, item_name, quantity_required, equipment_category, check_types, item_order) as (
    values
      ('Vehicle','Record mileage',1,'vehicle',array['weekly'],1),
      ('Vehicle','Record engine hours',1,'vehicle',array['weekly'],2),
      ('Vehicle','Fuel (must be 3/4)',1,'vehicle',array['weekly'],3),
      ('Vehicle','DEF (refill at 1/2)',1,'vehicle',array['weekly'],4),
      ('Vehicle','Airhorn operational',1,'vehicle',array['weekly'],5),
      ('Vehicle','Vehicle horn operational',1,'vehicle',array['weekly'],6),
      ('Vehicle','Siren operational',1,'vehicle',array['weekly'],7),
      ('Vehicle','Head lights / brake lights / turn signals operational',1,'vehicle',array['weekly'],8),
      ('Vehicle','Outrigger stabilizers and aerial operational',1,'vehicle',array['weekly'],9),
      ('Vehicle','Parking brake operational',1,'vehicle',array['weekly'],10),
      ('Vehicle','Emergency lights operational',1,'vehicle',array['weekly'],11),
      ('Vehicle','Transmission fluid (engine must be running)',1,'vehicle',array['weekly'],12),
      ('Vehicle','Engine oil',1,'vehicle',array['weekly'],13),
      ('Vehicle','Wheel and tire condition',1,'vehicle',array['weekly'],14),
      ('Front Tires','Left PSI',1,'vehicle',array['weekly'],1),
      ('Front Tires','Right PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Left inner PSI',1,'vehicle',array['weekly'],1),
      ('Rear Tires','Left outer PSI',1,'vehicle',array['weekly'],2),
      ('Rear Tires','Right inner PSI',1,'vehicle',array['weekly'],3),
      ('Rear Tires','Right outer PSI',1,'vehicle',array['weekly'],4),
      ('Cab','Door opener',1,'equipment',array['weekly','inventory'],1),
      ('Cab','Knox Box keys',1,'equipment',array['weekly','inventory'],2),
      ('Cab','5 gas meter (fully charged)',1,'equipment',array['weekly','inventory'],3),
      ('Cab','Portable radios (charged and on channel 1)',4,'equipment',array['weekly','inventory'],4),
      ('Cab','Thermal imaging camera (TIC), charged',1,'equipment',array['weekly','inventory'],5),
      ('Cab','R.I.T. bag cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],6),
      ('Cab','Nitrile / latex gloves',1,'equipment',array['weekly','inventory'],7),
      ('Cab','Cooler with water and ice',1,'equipment',array['weekly','inventory'],8),
      ('Cab','Fuel card and PIN',1,'equipment',array['weekly','inventory'],9),
      ('Cab','Box lights',3,'equipment',array['weekly','inventory'],10),
      ('Cab','Hi-vis safety vests',4,'equipment',array['weekly','inventory'],11),
      ('Cab','SCBA harness',4,'air_pack',array['weekly','inventory','air_pack'],12),
      ('Cab','Officer''s clipboard (stocked)',1,'equipment',array['weekly','inventory'],13),
      ('Pump / Booster Tank','Water level full',1,'vehicle',array['weekly'],1),
      ('Pump / Booster Tank','Record pump hours',1,'vehicle',array['weekly'],2),
      ('Pump / Booster Tank','Exercise primer, pressure governor and circulate water',1,'vehicle',array['weekly'],3),
      ('Pump / Booster Tank','Vehicle goes into pump and recirculates water',1,'vehicle',array['weekly'],4),
      ('SCBA','Officer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],1),
      ('SCBA','Engineer SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],2),
      ('SCBA','Rear 1 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],3),
      ('SCBA','Rear 2 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],4),
      ('SCBA','Rear 3 SCBA harness and cylinder at 4500 PSI',1,'air_pack',array['weekly','inventory','air_pack'],5),
      ('SCBA','Driver side torpedo cylinder 1',1,'air_pack',array['weekly','inventory','air_pack'],6),
      ('SCBA','Driver side torpedo cylinder 2',1,'air_pack',array['weekly','inventory','air_pack'],7),
      ('SCBA','Officer side torpedo cylinder 1',1,'air_pack',array['weekly','inventory','air_pack'],8),
      ('SCBA','Officer side torpedo cylinder 2',1,'air_pack',array['weekly','inventory','air_pack'],9),
      ('SCBA','Officer side torpedo cylinder 3',1,'air_pack',array['weekly','inventory','air_pack'],10),
      ('SCBA','Officer side torpedo cylinder 4',1,'air_pack',array['weekly','inventory','air_pack'],11),
      ('Tools & Equipment','Run and operate all power tools / E-Tools',1,'equipment',array['weekly'],1),
      ('Tools & Equipment','Visually check all other hose, tools and equipment',1,'equipment',array['weekly'],2),
      ('Compartment 1 (EMS)','Scene tape (yellow)',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 1 (EMS)','Scene tape (red)',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 1 (EMS)','Jump bag - O2',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 1 (EMS)','Jump bag - blood pressure cuff with stethoscope',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 1 (EMS)','Jump bag - pulse oximeter',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 1 (EMS)','Jump bag - BVM (adult)',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 1 (EMS)','Jump bag - non-rebreather mask',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 1 (EMS)','Jump bag - nasal cannulas',1,'equipment',array['weekly','inventory'],8),
      ('Compartment 1 (EMS)','AED pads',2,'equipment',array['weekly','inventory'],9),
      ('Compartment 1 (EMS)','AED spare battery',1,'equipment',array['weekly','inventory'],10),
      ('Compartment 1 (EMS)','AED pediatric key',1,'equipment',array['weekly','inventory'],11),
      ('Compartment 2','A-Frame ladder with foot extension and tray attachment',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 2','Preconnected crosslay - 2.5 inch with nozzle',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 2','Preconnected crosslay - 1.75 inch fog',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 2','Preconnected crosslay - 1.75 inch smooth bore',1,'equipment',array['weekly','inventory'],4),
      ('Engineer''s Panel (Compartment 3)','Exercise all levers and drains',1,'vehicle',array['weekly'],1),
      ('Engineer''s Panel (Compartment 3)','Exercise primer',1,'vehicle',array['weekly'],2),
      ('Engineer''s Panel (Compartment 3)','Hydrant wrench',1,'equipment',array['weekly','inventory'],3),
      ('Engineer''s Panel (Compartment 3)','Spanners',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 4','Cellar nozzle',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 4','Foam eductor',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 4','2.5 inch to 1.5 inch wye',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 4','4 inch female to Storz',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 4','5 inch female to Storz',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 4','5 inch female to 4 inch male',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 4','Blitz Force gun',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 4','Master fog nozzle',1,'equipment',array['weekly','inventory'],8),
      ('Compartment 4','2.5 inch double female',2,'equipment',array['weekly','inventory'],9),
      ('Compartment 4','2.5 inch double male',2,'equipment',array['weekly','inventory'],10),
      ('Compartment 4','2.5 inch to 1.5 inch reducers',2,'equipment',array['weekly','inventory'],11),
      ('Compartment 4','2.5 inch female to Storz elbow',1,'equipment',array['weekly','inventory'],12),
      ('Compartment 4','4 inch Storz to 2.5 inch male',1,'equipment',array['weekly','inventory'],13),
      ('Compartment 4','Hydrant bag - hydrant wrench',1,'equipment',array['weekly','inventory'],14),
      ('Compartment 4','Hydrant bag - spanners',2,'equipment',array['weekly','inventory'],15),
      ('Compartment 4','Hydrant bag - 2.5 inch to 1.5 inch reducer',1,'equipment',array['weekly','inventory'],16),
      ('Compartment 4','Hydrant bag - gate valve',1,'equipment',array['weekly','inventory'],17),
      ('Compartment 4','Hydra-Shield hydrant wrench (silver)',1,'equipment',array['weekly','inventory'],18),
      ('Compartment 4','Custodian hydrant wrench (red)',1,'equipment',array['weekly','inventory'],19),
      ('Compartment 4','Electric PPV fan',1,'equipment',array['weekly','inventory'],20),
      ('Compartment 4','Wheel chocks',3,'equipment',array['weekly','inventory'],21),
      ('Compartment 4','50 foot 2.5 inch hose',1,'equipment',array['weekly','inventory'],22),
      ('Compartment 5','High rise pack - 100 foot 2.5 inch hose',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 5','High rise pack - 100 foot 1.75 inch hose',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 5','High rise pack - 2.5 inch smooth bore',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 5','High rise pack - orange straps',6,'equipment',array['weekly','inventory'],4),
      ('Compartment 5','High rise bag - 2.5 inch to 1.5 inch reducer',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 5','High rise bag - spanner wrenches',2,'equipment',array['weekly','inventory'],6),
      ('Compartment 5','High rise bag - in-line pressure gauge',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 5','High rise bag - pipe wrench',1,'equipment',array['weekly','inventory'],8),
      ('Compartment 5','High rise bag - rope hose tool',1,'equipment',array['weekly','inventory'],9),
      ('Compartment 5','High rise bag - 2.5 inch gate valve',1,'equipment',array['weekly','inventory'],10),
      ('Compartment 5','High rise bag - 1.75 inch smooth bore',1,'equipment',array['weekly','inventory'],11),
      ('Compartment 5','R.I.T. bag - 60 minute cylinder',1,'air_pack',array['weekly','inventory','air_pack'],12),
      ('Compartment 5','R.I.T. bag - facepiece (medium)',1,'air_pack',array['weekly','inventory','air_pack'],13),
      ('Compartment 5','R.I.T. bag - webbing',1,'equipment',array['weekly','inventory'],14),
      ('Compartment 5','R.A.S.P. bag',1,'equipment',array['weekly','inventory'],15),
      ('Compartment 6','Cans of 50:1 fuel',2,'equipment',array['weekly','inventory'],1),
      ('Compartment 6','Metal blade Partner saw',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 6','Wood (Warthog) Partner saw',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 6','Stihl utility saw',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 6','Truckman vent saw',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 6','Saw tool box - spare belts',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 6','Saw tool box - wrench',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 6','Check bar chain oil in chainsaws',1,'equipment',array['weekly'],8),
      ('Compartment 6','Check fuel level in all saws',1,'equipment',array['weekly'],9),
      ('Compartment 7 (Rear)','16 foot roof ladders',2,'equipment',array['weekly','inventory'],1),
      ('Compartment 7 (Rear)','24 foot extension ladder',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 7 (Rear)','8 foot New York multi hooks',2,'equipment',array['weekly','inventory'],3),
      ('Compartment 8 (Rear)','Rope rescue bags',2,'equipment',array['weekly','inventory'],1),
      ('Compartment 8 (Rear)','300 foot life safety rope',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 8 (Rear)','Bag of webbing',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 8 (Rear)','Harnesses',2,'equipment',array['weekly','inventory'],4),
      ('Compartment 9 (Rear)','35 foot extension ladder',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 9 (Rear)','Attic / scuttle hole ladder',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 9 (Rear)','10 foot pike pole',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 9 (Rear)','12 foot pike pole',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 9 (Rear)','7 foot pike pole',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 9 (Rear)','6 foot Eck hook',1,'equipment',array['weekly','inventory'],6),
      ('Rear Hose','2.5 inch skid load with rope hose tools and playpipe',1,'equipment',array['weekly','inventory'],1),
      ('Rear Hose','4 inch L.D.H.',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 10','3-bank Milwaukee battery charger with batteries',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 10','Grinder / cutter with spare battery',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 10','Bag with glass cutter and Sawzall with spare battery',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 10','Box of electrical whips / pigtails',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 10','Ratcheting straps',2,'equipment',array['weekly','inventory'],5),
      ('Compartment 10','Ram brace',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 10','Hardwire battery adapter for Genesis E-Tools',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 10','Case of E-Tool tips',1,'equipment',array['weekly','inventory'],8),
      ('Compartment 10','Spreaders',1,'equipment',array['weekly','inventory'],9),
      ('Compartment 10','Cutters',1,'equipment',array['weekly','inventory'],10),
      ('Compartment 10','Ram',1,'equipment',array['weekly','inventory'],11),
      ('Compartment 11','8 pound pick head axe',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 11','Maul',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 11','Sledge hammer',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 11','Large bolt cutters',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 11','Small bolt cutters',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 11','Halligan bar',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 11','K-Tool bag - K-Tool',1,'equipment',array['weekly','inventory'],7),
      ('Compartment 11','K-Tool bag - wedge',1,'equipment',array['weekly','inventory'],8),
      ('Compartment 11','K-Tool bag - elevator key',1,'equipment',array['weekly','inventory'],9),
      ('Compartment 11','K-Tool bag - needle nose pliers',1,'equipment',array['weekly','inventory'],10),
      ('Compartment 11','K-Tool bag - screwdriver',1,'equipment',array['weekly','inventory'],11),
      ('Compartment 11','K-Tool bag - keys',1,'equipment',array['weekly','inventory'],12),
      ('Compartment 11','K-Tool bag - electrical fuse puller',1,'equipment',array['weekly','inventory'],13),
      ('Compartment 12','Dry chemical extinguisher',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 12','CO2 extinguisher',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 12','Class K extinguisher',1,'equipment',array['weekly','inventory'],3),
      ('Compartment 12','Kodiak rescue struts',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 12','Rabbit Tool with rubber mallet',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 12','Ratchet straps',1,'equipment',array['weekly','inventory'],6),
      ('Compartment 13','Wood cribbing',1,'equipment',array['weekly','inventory'],1),
      ('Compartment 13','Wedges',1,'equipment',array['weekly','inventory'],2),
      ('Compartment 13','Step chocks',2,'equipment',array['weekly','inventory'],3),
      ('Compartment 13','Airbag control unit in case',1,'equipment',array['weekly','inventory'],4),
      ('Compartment 13','Protective pad for airbags',1,'equipment',array['weekly','inventory'],5),
      ('Compartment 13','Airbags',5,'equipment',array['weekly','inventory'],6)
  ), ranked_items as (
    select
      source_items.*,
      c.id as compartment_id,
      'form-439-' || lpad(row_number() over (
        order by c.sort_order, source_items.item_order, source_items.item_name
      )::text, 3, '0') as source_key
    from source_items
    join public.inventory_compartments c
      on c.department_id = stickney_id
     and c.apparatus_id = truck_1204_id
     and c.label = source_items.section_label
  )
  insert into public.inventory_equipment
    (department_id, apparatus_id, compartment_id, name, quantity_required,
     equipment_category, check_types, source_key, source_form, item_order)
  select
    stickney_id,
    truck_1204_id,
    ranked_items.compartment_id,
    ranked_items.item_name,
    ranked_items.quantity_required,
    ranked_items.equipment_category,
    ranked_items.check_types,
    ranked_items.source_key,
    '1204 Weekly Check form 439',
    ranked_items.item_order
  from ranked_items
  on conflict (department_id, apparatus_id, source_key) where source_key is not null
  do update set
    compartment_id = excluded.compartment_id,
    name = excluded.name,
    quantity_required = excluded.quantity_required,
    equipment_category = excluded.equipment_category,
    check_types = excluded.check_types,
    source_form = excluded.source_form,
    item_order = excluded.item_order,
    retired_at = null;
end $$;
