'use client';
import { useState } from 'react';
import { categories,emptyTrainingData,normalizeTrainingData,validateTraining,todayChicago,safeLink,type TrainingRecord,type TrainingSnapshot,type TrainingData,type TrainingField } from './model';
import { useUnsavedWork } from '../use-unsaved-work';
import { certificationCatalog } from './osfm-catalog';
import books from './osfm-books.json';

export const kindNames={activity:'activity',completion:'training record',assignment:'assignment',credential:'credential',proficiency:'task-book entry',group:'member group',resource:'resource'};
type Props={initial:TrainingRecord;snapshot:TrainingSnapshot;onSave:(record:TrainingRecord)=>Promise<void>;onCancel:()=>void};
export default function TrainingEditor({initial,snapshot,onSave,onCancel}:Props) {
  const [data,setData]=useState<TrainingData>(initial.data),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
  const dirty=JSON.stringify(data)!==JSON.stringify(initial.data),kind=initial.kind;
  useUnsavedWork(dirty,busy);
  const set=<K extends keyof TrainingData>(key:K,value:TrainingData[K])=>setData(d=>({...d,[key]:value}));
  const activities=snapshot.records.filter(r=>r.kind==='activity'&&!r.archived&&r.data.status!=='draft');
  const credentials=snapshot.records.filter(r=>r.kind==='credential'&&!r.archived);
  const groups=snapshot.records.filter(r=>r.kind==='group'&&!r.archived);
  const isPeople=['completion','assignment','credential','proficiency','group'].includes(kind);
  const steps=isPeople?['Details','People','Review']:['Details','Review'];
  const cert=certificationCatalog.find(c=>c.id===data.certificationId);
  const book=books.find(b=>b.certificationId===data.certificationId&&b.kind===(data.method==='Initial certification'?'initialBook':'recertificationBook'));
  const field=(key:keyof TrainingData,label:string,type='text',hint='')=><label className="tr-field" key={key}>{label}<input type={type} value={String(data[key]??'')} onChange={e=>set(key,(type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value) as never)} onInput={type==='date'?e=>set(key,e.currentTarget.value as never):undefined} step={type==='number'?'0.25':undefined} min={type==='number'?0:undefined}/>{hint&&<small>{hint}</small>}</label>;
  const select=(key:keyof TrainingData,label:string,options:string[])=><label className="tr-field">{label}<select value={String(data[key])} onChange={e=>set(key,e.target.value as never)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
  function chooseActivity(id:string) {const activity=activities.find(r=>r.id===id);setData(d=>({...d,activityId:id,...(activity?{title:activity.data.title,category:activity.data.category,hours:activity.data.hours,description:activity.data.description,delivery:activity.data.delivery,certificationId:activity.data.certificationId,sourceUrl:activity.data.sourceUrl,sourceEdition:activity.data.sourceEdition,fields:activity.data.fields,test:activity.data.test,answers:{}}:{})}));}
  async function save(draft:boolean) {
    setError('');
    try {const next=normalizeTrainingData({...data,status:draft?'draft':kind==='completion'?'completed':'saved'});validateTraining(kind,next,snapshot.records,snapshot.members);setBusy(true);await onSave({...initial,data:next});}
    catch(e){setError(e instanceof Error?e.message:'Save failed. Your entries remain here.');}finally{setBusy(false);}
  }
  function cancel(){if(!dirty||window.confirm('Leave this editor without saving these changes?'))onCancel();}
  function customField(f:TrainingField) {return <label className="tr-field" key={f.id}>{f.label}{f.required?' *':''}{f.type==='choice'||f.type==='yes-no'?<select value={data.answers[f.id]??''} onChange={e=>set('answers',{...data.answers,[f.id]:e.target.value})}><option value="">Select…</option>{(f.type==='yes-no'?['Yes','No','Not applicable']:f.options).map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type} value={data.answers[f.id]??''} onChange={e=>set('answers',{...data.answers,[f.id]:e.target.value})}/>}</label>;}
  const selectedMembers=snapshot.members.filter(m=>data.employeeIds.includes(m.id));
  return <section className="tr-editor">
    <button type="button" className="tr-back" onClick={cancel} disabled={busy}>← Back to Training</button>
    <div className="tr-heading"><div><p className="tr-eyebrow">{initial.version?'Edit saved record':'New '+kindNames[kind]}</p><h2>{data.title||'Choose the details'}</h2></div><span className="tr-badge">{dirty||!initial.version?'Changes not saved':'Saved version '+initial.version}</span></div>
    <ol className="tr-steps" aria-label="Training steps">{steps.map((s,i)=><li key={s} aria-current={step===i?'step':undefined}><button type="button" disabled={busy} onClick={()=>setStep(i)}>{i+1}. {s}</button></li>)}</ol>
    {error&&<div className="tr-error" role="alert">{error}</div>}
    <form onSubmit={e=>{e.preventDefault();if(step<steps.length-1)setStep(step+1);else void save(false);}}>
    <fieldset disabled={busy} className="tr-form-body">
    {step===0&&<>
      <p className="tr-muted">Add what you know. Extra detail is optional; a draft can be finished later.</p>
      {(kind==='completion'||kind==='assignment')&&<label className="tr-field">Start with an activity<select value={data.activityId} onChange={e=>chooseActivity(e.target.value)}><option value="">Enter training directly</option>{activities.map(a=><option key={a.id} value={a.id}>{a.data.title}</option>)}</select></label>}
      {field('title',kind==='activity'?'Activity name *':'Name *')}
      <label className="tr-checkbox"><input type="checkbox" checked={data.test} onChange={e=>setData(d=>({...d,test:e.target.checked,title:e.target.checked?'test/training':d.title}))}/>Test only — excluded from credit and official exports</label>
      {['activity','completion','assignment'].includes(kind)&&<div className="tr-grid">{select('category','Category',categories)}{select('delivery','Method',['Hands-on','Classroom','Online','Blended','Incident experience','External course','Other'])}{field('hours',kind==='completion'?'Training duration (hours) *':'Suggested duration (hours)','number')}</div>}
      {['completion','assignment'].includes(kind)&&<div className="tr-grid">{field('date',kind==='completion'?'Completed on *':'Starts on','date')}{field('startTime','Start time (24-hour)','text','Example: 08:30 or 18:00')}{kind==='assignment'&&field('dueDate','Due date *','date')}{field('instructor',kind==='completion'?'Instructor / provider *':'Instructor / provider')}{field('location','Location')}</div>}
      {kind==='credential'&&<>
        <label className="tr-field">Credential / certification *<select value={data.certificationId} onChange={e=>{const c=certificationCatalog.find(x=>x.id===e.target.value);setData(d=>({...d,certificationId:e.target.value,title:d.test?'test/training':c?.title??d.title,requiredJprs:[],sourceUrl:'',sourceEdition:'',method:e.target.value==='custom'?'Department requirement':d.method}));}}><option value="">Choose certification…</option><option value="custom">Other credential / department task book</option>{certificationCatalog.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>
        <div className="tr-grid">{select('method','Tracking',['Recertification','Initial certification','Department requirement','External credential'])}{field('credentialNumber','Certificate number')}{field('externalId','OSFM firefighter / external ID')}{field('issuedDate','Original certification date','date')}{field('cycleStart','Verified cycle start *','date')}{field('dueDate','Official renewal / not-current date','date','Use the date in the official record. A reminder is not an OSFM decision.')}</div>
        {data.certificationId==='custom'&&<p className="tr-note">Use this for EMS, CPR, department qualifications, or another verified requirement. Enter the issuer’s actual dates and task list; no OSFM renewal rule is assumed.</p>}{cert&&<div className="tr-note">{cert.recertification==='not-listed'?'This certification is not listed for recurring renewal in current Section 141.390. Do not assume an expiration date.':cert.recertification==='points'?'Fire Investigator uses the official 100-point tally over four years. Keep supporting documentation.':'Recertification requires level-specific JPR evidence from the applicable cycle.'} <a href={cert.ruleUrl} target="_blank" rel="noreferrer">Read certification rule ↗</a></div>}
        {book&&<div className="tr-note"><a href={book.url} target="_blank" rel="noreferrer">Open official {data.method==='Initial certification'?'practical':'recertification'} book ↗</a><p>{book.edition} · {book.bookDate||'Edition shown in book'}</p>{book.jprs.length>0?<button type="button" onClick={()=>setData(d=>({...d,requiredJprs:book.jprs.map(j=>j.id),sourceUrl:book.url,sourceEdition:book.edition}))}>Use this book’s JPR index</button>:<button type="button" onClick={()=>setData(d=>({...d,sourceUrl:book.url,sourceEdition:book.edition==='Check the official book edition'?'OSFM '+book.title+' official form':book.edition}))}>Use this official form</button>}<small>Review the official book for your course/cycle. Different editions must not be mixed.</small></div>}
        <details><summary>Task list and OSFM receipt</summary><label className="tr-field">Required JPR / skill IDs (one per line)<textarea rows={5} value={data.requiredJprs.join('\n')} onChange={e=>set('requiredJprs',e.target.value.split('\n'))}/></label>{field('sourceUrl','Task-book source link','url')}{field('sourceEdition','Standard and edition')}{field('submissionDate','Date manually submitted to OSFM','date')}{field('receipt','OSFM receipt / reference (if received)')}{field('reviewNote','Review note')}</details>
      </>}
      {kind==='proficiency'&&<>
        {safeLink(data.sourceUrl)&&<p><a href={data.sourceUrl.split('#')[0]+(/^\d+$/.test(data.sourcePage)?'#page='+data.sourcePage:'')} target="_blank" rel="noreferrer">Read the official task sheet ↗</a></p>}
        <label className="tr-field">Credential / task book *<select value={data.credentialId} onChange={e=>{const c=credentials.find(r=>r.id===e.target.value);setData(d=>({...d,credentialId:e.target.value,employeeIds:c?.data.employeeIds??[],certificationId:c?.data.certificationId??'',test:c?.data.test??d.test,title:c?.data.test?'test/training':d.title,sourceUrl:c?.data.sourceUrl??'',sourceEdition:c?.data.sourceEdition??''}));}}><option value="">Choose a saved credential…</option>{credentials.map(c=><option key={c.id} value={c.id}>{snapshot.members.find(m=>m.id===c.data.employeeIds[0])?.name} — {c.data.title}</option>)}</select></label>
        <label className="tr-field">{data.certificationId==='il-334'?'JPR / official tally category *':'JPR / skill ID *'}<input list="training-jprs" value={data.jpr} onChange={e=>{const id=e.target.value,b=books.find(b=>b.url===data.sourceUrl),j=b?.jprs.find(j=>j.id===id);setData(d=>({...d,jpr:id,sourcePage:j?String(j.page):d.sourcePage}));}}/><datalist id="training-jprs">{credentials.find(c=>c.id===data.credentialId)?.data.requiredJprs.map(id=><option key={id} value={id}/>)}</datalist></label>
        <div className="tr-grid">{field('date','Performed on *','date')}{select('method','Evidence from',['Training','Incident experience','Practical exam','Investigator tally'])}{select('result','Result',['Practiced','Needs more practice','Proficient'])}{field('evaluator','Evaluator’s name')}{field('location','Location / incident reference')}{field('sourcePage','Official book PDF page *')}{field('sourceEdition','Standard and edition *')}{field('sourceUrl','Official task-book link *','url')}</div>
        <label className="tr-checkbox"><input type="checkbox" checked={data.verified} onChange={e=>set('verified',e.target.checked)}/>I reviewed the evaluator’s evidence. This records my review, not someone else’s signature.</label>
        <p className="tr-muted">Attach the signed proficiency sheet after saving. Practiced tasks do not count as proficient.</p>
        {data.certificationId==='il-334'&&<div className="tr-grid">{field('points','Documented investigator points','number')}{field('pointsBasis','Official tally category / calculation basis *')}</div>}
      </>}
      {kind==='resource'&&<div className="tr-grid">{field('sourceUrl','Resource link','url')}{select('category','Category',categories)}</div>}
      <label className="tr-field">{kind==='completion'?'What was covered / objectives':'Description / instructions'}<textarea rows={4} value={data.description} onChange={e=>set('description',e.target.value)}/></label>
      {kind==='activity'&&<details open={data.fields.length>0}><summary>Build your form · {data.fields.length} custom fields</summary><p>Make selections easy. Only mark a field required if your department needs it.</p>{data.fields.map((f,i)=><div className="tr-custom-field" key={f.id}><label className="tr-field">Field {i+1} label<input value={f.label} onChange={e=>set('fields',data.fields.map(x=>x.id===f.id?{...x,label:e.target.value}:x))}/></label><label className="tr-field">Answer type<select value={f.type} onChange={e=>set('fields',data.fields.map(x=>x.id===f.id?{...x,type:e.target.value as TrainingField['type']}:x))}>{['text','number','date','choice','yes-no'].map(t=><option key={t}>{t}</option>)}</select></label>{f.type==='choice'&&<label className="tr-field">Choices (one per line)<textarea value={f.options.join('\n')} onChange={e=>set('fields',data.fields.map(x=>x.id===f.id?{...x,options:e.target.value.split('\n')}:x))}/></label>}<label className="tr-checkbox"><input type="checkbox" checked={f.required} onChange={e=>set('fields',data.fields.map(x=>x.id===f.id?{...x,required:e.target.checked}:x))}/>Required</label><button type="button" onClick={()=>set('fields',data.fields.filter(x=>x.id!==f.id))}>Remove field</button></div>)}<button type="button" onClick={()=>set('fields',[...data.fields,{id:crypto.randomUUID(),label:'',type:'choice',options:[],required:false}])}>+ Add a field</button></details>}
      {kind==='completion'&&(activities.find(a=>a.id===data.activityId)?.data.fields??data.fields).map(customField)}
      {['activity','completion','assignment'].includes(kind)&&<details><summary>Reference links and additional tracking</summary>{field('sourceUrl','Reference link','url')}{field('sourceEdition','Standard / edition')}{field('externalId','External course / transcript ID')}<p>Keep OSFM skill evidence in Credentials & task books. Hours alone do not verify a JPR.</p></details>}
    </>}
    {isPeople&&step===1&&<>
      <h3>{kind==='group'?'Choose group members':'Who is this for?'}</h3><p>{['credential','proficiency'].includes(kind)?'Choose one member.':'Tap names or choose a saved group. Enter actual attendance hours for each member when needed.'}</p>
      {groups.length>0&&!['credential','proficiency'].includes(kind)&&<label className="tr-field">Add a group<select value="" onChange={e=>{const g=groups.find(g=>g.id===e.target.value);if(g)set('employeeIds',[...new Set([...data.employeeIds,...g.data.employeeIds])]);}}><option value="">Choose group…</option>{groups.map(g=><option key={g.id} value={g.id}>{g.data.title}</option>)}</select></label>}
      <label className="tr-field">Find a member<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or rank"/></label>
      <p>{data.employeeIds.length} selected <button type="button" onClick={()=>set('employeeIds',[])}>Clear selections</button></p>
      <div className="tr-member-list">{snapshot.members.filter(m=>(m.active||data.employeeIds.includes(m.id))&&`${m.name} ${m.rank}`.toLowerCase().includes(query.toLowerCase())).map(m=><label className="tr-member" key={m.id}><input type={['credential','proficiency'].includes(kind)?'radio':'checkbox'} name="member" checked={data.employeeIds.includes(m.id)} onChange={e=>set('employeeIds',['credential','proficiency'].includes(kind)?[m.id]:e.target.checked?[...data.employeeIds,m.id]:data.employeeIds.filter(id=>id!==m.id))}/><span><strong>{m.name}</strong><small>{m.rank}{!m.active?' · Inactive':''}</small></span></label>)}</div>
      {kind==='completion'&&selectedMembers.length>0&&<details><summary>Adjust individual attendance</summary><p>Defaults to {data.hours??0} hours per selected member. Enter 0 for an absence.</p>{selectedMembers.map(m=><label className="tr-field" key={m.id}>{m.name} · hours<input type="number" min="0" max={data.hours??24} step="0.25" value={data.attendance[m.id]??data.hours??''} onChange={e=>set('attendance',{...data.attendance,[m.id]:Number(e.target.value)})}/></label>)}</details>}
    </>}
    {step===steps.length-1&&<>
      <h3>Review before saving</h3><dl className="tr-review"><dt>Name</dt><dd>{data.title||'Name needed'}</dd><dt>Record type</dt><dd>{kindNames[kind]}{data.test?' · TEST ONLY':''}</dd>{data.date&&<><dt>Date</dt><dd>{data.date} {data.startTime}</dd></>}{data.cycleStart&&<><dt>Cycle starts</dt><dd>{data.cycleStart}</dd></>}{data.dueDate&&<><dt>Due</dt><dd>{data.dueDate}</dd></>}{data.hours!==null&&<><dt>Duration</dt><dd>{data.hours} hours</dd></>}{isPeople&&<><dt>People</dt><dd>{selectedMembers.map(m=>m.name).join('; ')||'No one selected'}</dd></>}{data.instructor&&<><dt>Instructor</dt><dd>{data.instructor}</dd></>}{kind==='completion'&&<><dt>Actual attendance</dt><dd>{selectedMembers.map(m=><div key={m.id}>{m.name} — {data.attendance[m.id]??data.hours??0} hours</div>)}</dd></>}{kind==='proficiency'&&<><dt>Task / result</dt><dd>{data.jpr} · {data.result}</dd><dt>Evaluator</dt><dd>{data.evaluator||'Not recorded'}</dd></>}<dt>Notes</dt><dd>{data.description||'None added'}</dd></dl>
      <div className="tr-note">{kind==='completion'?'Save completed training records the actual attendance shown above. Save draft gives no credit.':'Saving creates a private pilot record.'} No member notifications or OSFM submissions are sent.</div>
    </>}
    </fieldset>
    <div className="tr-editor-actions"><button type="button" onClick={step?()=>setStep(step-1):cancel} disabled={busy}>{step?'← Back':'Cancel'}</button><button type="button" onClick={()=>void save(true)} disabled={busy}>Save draft</button><button className="tr-primary" type="submit" disabled={busy}>{busy?'Saving…':step<steps.length-1?'Next →':kind==='completion'?'Save completed training':'Save '+kindNames[kind]}</button></div>
    </form>
  </section>;
}
export function newTrainingRecord(kind:TrainingRecord['kind'],data:Partial<TrainingData>={}):TrainingRecord {
 return {id:crypto.randomUUID(),kind,version:0,archived:false,createdAt:'',updatedAt:'',updatedBy:'',data:{...emptyTrainingData(),...(['completion','proficiency'].includes(kind)?{date:todayChicago()}:{}),...(kind==='credential'?{method:'Recertification'}:{}),...data}};
}
