'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import TrainingEditor,{newTrainingRecord,kindNames} from './editor';
import { categories,creditedHours,assignmentProgress,deadlineLabel,todayChicago,trainingCsv,type TrainingRecord,type TrainingSnapshot,type TrainingData,type TrainingKind } from './model';
import { certificationCatalog,OSFM_FORMS_URL,OSFM_RULE_URL,OSFM_PORTAL_URL,OSFM_PROPOSED_URL } from './osfm-catalog';
import {osfmBooks as books} from './osfm-selection';
import OsfmTaskBrowser,{SelectedOsfmTasks} from './osfm-task-browser';
import {taskReference} from './osfm-selection';
import { credentialEvidence,credentialTimeline,osfmHandoff } from './osfm';
import './training.css';

const tabs=['Overview','Assignments','History & reports','Credentials & task books','OSFM task books','Activity library','Calendar','Files & groups','OSFM guide'] as const;
type Tab=typeof tabs[number];
async function fetchTraining(signal?:AbortSignal):Promise<TrainingSnapshot>{const r=await fetch('/api/training',{cache:'no-store',signal});const j=await r.json();if(!r.ok)throw new Error(j.error||'Training could not load.');return j;}
const blank:TrainingSnapshot={records:[],members:[],attachments:[]};
function download(name:string,value:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function External({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>;}
export default function TrainingWorkspace() {
  const [snapshot,setSnapshot]=useState<TrainingSnapshot>(blank),[loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [tab,setTab]=useState<Tab>('Overview'),[editing,setEditing]=useState<TrainingRecord|null>(null),[selectedId,setSelectedId]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<{version:number;actor:string;createdAt:string;payload:string;archived:number}[]|null>(null);
  const [osfmSelection,setOsfmSelection]=useState<string[]>([]);
  const [query,setQuery]=useState(''),[member,setMember]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[showArchived,setShowArchived]=useState(false),[month,setMonth]=useState(todayChicago().slice(0,7)),[fileRecord,setFileRecord]=useState('');
  const receive=useCallback((j:TrainingSnapshot)=>{setSnapshot(j);setLoaded(true);setLoading(false);setError('');const p=new URLSearchParams(window.location.search),record=p.get('trainingRecord'),section=p.get('trainingTab');if(record)setSelectedId(record);if(tabs.includes(section as Tab))setTab(section as Tab);},[]);
  const fail=useCallback((e:unknown)=>{setError(e instanceof Error?e.message:'Training could not load.');setLoading(false);setLoaded(false);},[]);
  const load=useCallback(()=>fetchTraining().then(receive).catch(fail),[receive,fail]);
  useEffect(()=>{const c=new AbortController();void fetchTraining(c.signal).then(j=>{if(!c.signal.aborted)receive(j);}).catch(e=>{if(!c.signal.aborted)fail(e);});return()=>c.abort();},[receive,fail]);
  const visible=useMemo(()=>snapshot.records.filter(r=>showArchived||!r.archived),[snapshot.records,showArchived]);
  const selected=snapshot.records.find(r=>r.id===selectedId);
  const active=snapshot.records.filter(r=>!r.archived&&r.data.status!=='draft'&&!r.data.test);
  const assignments=active.filter(r=>r.kind==='assignment');
  const credentials=active.filter(r=>r.kind==='credential');
  const pending=assignments.filter(r=>assignmentProgress(r,snapshot.records).completed<r.data.employeeIds.length);
  const dueCredentials=credentials.filter(r=>r.data.dueDate&&deadlineLabel(r.data.dueDate)!=='Upcoming');
  const memberName=(id:string)=>snapshot.members.find(m=>m.id===id)?.name??'Unknown member';
  function route(next:Tab,record=''){setTab(next);setSelectedId(record);setEditing(null);setHistory(null);setQuery('');setNotice('');setError('');const url=new URL(window.location.href);url.searchParams.set('trainingTab',next);if(record)url.searchParams.set('trainingRecord',record);else url.searchParams.delete('trainingRecord');window.history.replaceState(window.history.state,'',url);}
  function create(kind:TrainingKind,data:Partial<TrainingData>={}){setEditing(newTrainingRecord(kind,data));setSelectedId('');setError('');setNotice('');}
  async function save(record:TrainingRecord) {
    const response=await fetch('/api/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:record.id,kind:record.kind,version:record.version,archived:record.archived,data:record.data})});
    const result=await response.json();if(!response.ok||!result.record)throw new Error(result.error||'The save was not confirmed. Retry with this screen open.');
    setSnapshot(s=>({...s,records:[result.record,...s.records.filter(r=>r.id!==record.id)]}));setEditing(null);setSelectedId(record.id);setHistory(null);const url=new URL(window.location.href);url.searchParams.set('trainingRecord',record.id);window.history.replaceState(window.history.state,'',url);setNotice(`Saved ${kindNames[record.kind]} · version ${result.record.version}.`);
  }
  async function archive(r:TrainingRecord){if(!window.confirm(`${r.archived?'Restore':'Archive'} ${r.data.title}? ${r.archived?'It will return to active lists.':'It will leave active lists and totals; history and files remain available.'}`))return;setBusy(true);try{await save({...r,archived:!r.archived});}catch(e){setError(e instanceof Error?e.message:'Change not saved.');}finally{setBusy(false);}}
  async function audit(r:TrainingRecord){setBusy(true);try{const response=await fetch(`/api/training?history=${encodeURIComponent(r.id)}`,{cache:'no-store'}),j=await response.json();if(!response.ok)throw new Error(j.error);setHistory(j.history);}catch{setError('History could not load. Retry.');}finally{setBusy(false);}}
  async function upload(file:File|undefined,recordId:string){if(!file)return;if(!recordId){setError('Choose the saved record this file belongs to.');return;}if(file.size>4194304){setError('Choose a file up to 4 MB.');return;}setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('recordId',recordId);const response=await fetch('/api/training/files',{method:'POST',body:form}),j=await response.json();if(!response.ok)throw new Error(j.error);setSnapshot(s=>({...s,attachments:[j.attachment,...s.attachments]}));setNotice('File saved privately.');}catch(e){setError(e instanceof Error?e.message:'File not saved.');}finally{setBusy(false);}}
  const recordsOf=(kind:TrainingKind)=>visible.filter(r=>r.kind===kind&&`${r.data.title} ${r.data.category} ${r.data.description} ${r.data.employeeIds.map(memberName).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const recordList=(records:TrainingRecord[],emptyText:string)=><div className="tr-list">{records.length?records.map(r=><button className="tr-record" key={r.id} onClick={()=>route(tab,r.id)}><span><strong>{r.data.title}</strong><small>{r.data.employeeIds.map(memberName).join(' · ')||r.data.category} {r.data.date?'· '+r.data.date:''}{r.data.dueDate?' · Due '+r.data.dueDate:''}</small></span><span className="tr-badge">{r.archived?'Archived':r.data.test?'Test only':r.data.status==='draft'?'Draft':r.kind==='assignment'?`${assignmentProgress(r,snapshot.records).completed}/${r.data.employeeIds.length} complete`:r.kind==='credential'?deadlineLabel(r.data.dueDate):r.data.status==='completed'?'Completed':'Saved'} →</span></button>):<div className="tr-empty">{emptyText}</div>}</div>;
  const search=<div className="tr-toolbar"><label className="tr-field">Find training<input type="search" placeholder="Name, topic, or member" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="tr-checkbox"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Include archived</label></div>;
  const completionReport=recordsOf('completion').filter(r=>(!member||r.data.employeeIds.includes(member))&&(!category||r.data.category===category)&&(!from||r.data.date>=from)&&(!to||r.data.date<=to));
  const uploadControl=(recordId:string)=><label className="tr-upload">+ Attach PDF or photo<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files?.[0],recordId);e.target.value='';}}/><small>Private · up to 4 MB per file</small></label>;
  const attachments=(recordId?:string)=>snapshot.attachments.filter(f=>!recordId||f.recordId===recordId).map(f=><a className="tr-file" href={`/api/training/files/${f.id}`} key={f.id}>{f.filename}<small>{(f.size/1024).toFixed(0)} KB · {snapshot.records.find(r=>r.id===f.recordId)?.data.title} · Download</small></a>);
  if(editing)return <div className="training-workspace"><TrainingEditor key={editing.id+':'+editing.version} initial={editing} snapshot={snapshot} onSave={save} onCancel={()=>{setEditing(null);setSelectedId(editing.version?editing.id:'');}}/></div>;
  return <section className="training-workspace">
    <header className="tr-heading"><div><p className="tr-eyebrow">Stickney · Private pilot</p><h1>Training</h1><p>Record what you did. See what’s due. Keep proof together.</p></div><span className="tr-badge">Only bobff353@gmail.com</span></header>
    <nav className="tr-tabs" aria-label="Training sections">{tabs.map(t=><button key={t} className={tab===t?'active':''} aria-current={tab===t?'page':undefined} onClick={()=>route(t)}>{t}</button>)}</nav>
    {notice&&<div className="tr-success" role="status">{notice}</div>}{error&&<div className="tr-error" role="alert">{error} <button onClick={()=>void load()}>Reload saved records</button></div>}
    {loading?<p role="status">Loading your private training workspace…</p>:!loaded?<p>Training is unavailable until the saved records can be loaded.</p>:selected?<>
      <button className="tr-back" onClick={()=>route(tab)}>← Back to {tab}</button>
      <div className="tr-heading"><div><p className="tr-eyebrow">{kindNames[selected.kind]} · Version {selected.version}</p><h2>{selected.data.title}</h2><p>{selected.data.test?'Test only · excluded from credit and exports':selected.data.status==='draft'?'Draft · not completed':selected.archived?'Archived':'Saved'} · {new Date(selected.updatedAt).toLocaleString()}</p></div><div className="tr-inline-actions"><button className="tr-primary" onClick={()=>setEditing(selected)}>Edit {kindNames[selected.kind]}</button><button disabled={busy} onClick={()=>void archive(selected)}>{selected.archived?'Restore':'Archive'}</button></div></div>
      <div className="tr-panel"><dl className="tr-review"><dt>People</dt><dd>{selected.data.employeeIds.map(memberName).join('; ')||'No people assigned'}</dd><dt>Category</dt><dd>{selected.data.category||'Not entered'}</dd>{selected.data.date&&<><dt>Date</dt><dd>{selected.data.date} {selected.data.startTime}</dd></>}{selected.data.dueDate&&<><dt>Due</dt><dd>{selected.data.dueDate}</dd></>}{selected.data.hours!==null&&<><dt>Duration</dt><dd>{selected.data.hours} hours</dd></>}{selected.data.instructor&&<><dt>Instructor</dt><dd>{selected.data.instructor}</dd></>}{selected.data.location&&<><dt>Location</dt><dd>{selected.data.location}</dd></>}<dt>Notes / objectives</dt><dd className="tr-preserve">{selected.data.description||'None added'}</dd></dl>{selected.data.sourceUrl&&<External href={selected.data.sourceUrl}>Open reference</External>}
      <SelectedOsfmTasks ids={selected.data.osfmTaskIds}/>
      {selected.kind==='activity'&&<><div className="tr-inline-actions"><button className="tr-primary" onClick={()=>create('completion',{...selected.data,activityId:selected.id,status:'draft',date:todayChicago(),employeeIds:[]})}>Record completion</button><button onClick={()=>create('assignment',{...selected.data,activityId:selected.id,status:'draft',date:'',employeeIds:[]})}>Assign activity</button></div><h3>Form preview</h3>{selected.data.fields.length?selected.data.fields.map(f=><p key={f.id}><strong>{f.label}</strong> · {f.type} · {f.required?'Required':'Optional'}{f.type==='choice'?' · '+f.options.join(' / '):''}</p>):<p>Uses the standard date, duration, instructor, location, notes, and attendance form.</p>}</>}
      {selected.kind==='assignment'&&<><p>{assignmentProgress(selected,snapshot.records).completed} of {selected.data.employeeIds.length} members have a linked completion.</p><button className="tr-primary" onClick={()=>create('completion',{...selected.data,assignmentId:selected.id,status:'draft',date:todayChicago(),dueDate:''})}>Record attendance & completion</button><p className="tr-muted">This pilot assignment is visible here only. No employee notices were sent.</p></>}
      {selected.kind==='completion'&&<><h3>Actual attendance</h3>{selected.data.employeeIds.map(id=><p key={id}>{memberName(id)} — {selected.data.attendance[id]??selected.data.hours??0} hours</p>)}{Object.entries(selected.data.answers).map(([id,value])=><p key={id}><strong>{selected.data.fields.find(f=>f.id===id)?.label??id}:</strong> {value}</p>)}</>}
      {selected.kind==='proficiency'&&<dl className="tr-review"><dt>JPR</dt><dd>{selected.data.jpr}</dd><dt>Result</dt><dd>{selected.data.result}</dd><dt>Performed</dt><dd>{selected.data.date}</dd><dt>Evaluator</dt><dd>{selected.data.evaluator||'Not recorded'}</dd><dt>Evidence review</dt><dd>{selected.data.verified?'Reviewed by '+selected.updatedBy:'Not reviewed'}</dd><dt>Edition / PDF page</dt><dd>{selected.data.sourceEdition} · {selected.data.sourcePage}</dd>{selected.data.points!==null&&<><dt>Investigator points</dt><dd>{selected.data.points} · {selected.data.pointsBasis}</dd></>}</dl>}
      </div>
      {selected.kind==='credential'&&<CredentialDetail record={selected} snapshot={snapshot} onTask={data=>create('proficiency',data)} onOpen={id=>route(tab,id)} onExport={()=>{try{download(`osfm-handoff-${selected.id}.json`,JSON.stringify(osfmHandoff(selected,snapshot),null,2));setNotice('Review package downloaded. Nothing was sent to OSFM.');}catch(e){setError(e instanceof Error?e.message:'Unable to export.');}}}/>}
      <section className="tr-panel"><h3>Files & evidence</h3>{attachments(selected.id)}{!selected.archived&&uploadControl(selected.id)}<p className="tr-muted">Use signed task sheets, course certificates, rosters, and supporting photos. Originals remain separate from your notes.</p></section>
      <section className="tr-panel"><button disabled={busy} onClick={()=>void audit(selected)}>View revision history</button>{history&&history.map(h=><details key={h.version}><summary>Version {h.version} · {new Date(h.createdAt).toLocaleString()} · {h.actor}{h.archived?' · Archived':''}</summary><pre className="tr-json">{JSON.stringify(JSON.parse(h.payload),null,2)}</pre></details>)}</section>
    </>:selectedId?<div className="tr-empty">That training record was not found. <button onClick={()=>route('Overview')}>Back to Training</button></div>:<>
    {tab==='Overview'&&<>
      <div className="tr-start"><button onClick={()=>create('completion')}><span>01</span><strong>Record training</strong><small>Log a drill, class, or outside course →</small></button><button onClick={()=>create('assignment')}><span>02</span><strong>Assign training</strong><small>Choose people and a due date →</small></button><button onClick={()=>route('Credentials & task books')}><span>03</span><strong>Check credentials</strong><small>See renewals, task books, and evidence →</small></button></div>
      <div className="tr-inline-actions"><button onClick={()=>route('OSFM task books')}>Browse OSFM numbers & prebuilt task books →</button></div>
      <div className="tr-stats"><button onClick={()=>route('Assignments')}><strong>{pending.length}</strong>Open assignments</button><button onClick={()=>route('Credentials & task books')}><strong>{dueCredentials.length}</strong>Credential dates needing attention</button><button onClick={()=>route('History & reports')}><strong>{active.filter(r=>r.kind==='completion'&&r.data.status==='completed').length}</strong>Completed training records</button></div>
      <section className="tr-panel"><div className="tr-heading"><h2>What needs attention</h2><button onClick={()=>void load()}>Refresh</button></div>{recordList([...pending,...dueCredentials], 'Nothing due has been recorded yet. Add assignments or verified credential dates to begin.')}</section>
      <section className="tr-panel"><h2>Continue a draft</h2>{recordList(snapshot.records.filter(r=>!r.archived&&r.data.status==='draft'),'No unfinished drafts.')}</section>
      <details className="tr-panel"><summary>Coming from Vector / TargetSolutions?</summary><p><strong>Record Completions</strong> → Record training. <strong>Create Assignments</strong> → Assign training. <strong>My History</strong> → History & reports. <strong>My Credentials</strong> → Credentials & task books. <strong>Activities Builder</strong> → Activity library. <strong>File Center</strong> → Files & groups.</p><p>This private pilot stores your records separately. Licensed Vector course content and its OSFM connection are not copied.</p></details>
    </>}
    {tab==='Assignments'&&<>{search}<div className="tr-heading"><div><h2>Assignments</h2><p>Choose who needs training and when. Completion is recorded separately.</p></div><button className="tr-primary" onClick={()=>create('assignment')}>+ Assign training</button></div>{recordList(recordsOf('assignment'),'No assignments yet. Assign training to create the first one.')}</>}
    {tab==='History & reports'&&<>{search}<div className="tr-heading"><h2>Training history</h2><button className="tr-primary" onClick={()=>create('completion')}>+ Record training</button></div><div className="tr-grid"><label className="tr-field">Member<select value={member} onChange={e=>setMember(e.target.value)}><option value="">All members</option>{snapshot.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="tr-field">Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="tr-field">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="tr-field">Through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="tr-toolbar"><p><strong>{completionReport.reduce((s,r)=>s+creditedHours(r,member||undefined),0).toFixed(2)}</strong> credited member-hours · excludes drafts, tests, and archived records</p><button onClick={()=>download('training-attendance.csv',trainingCsv(completionReport.map(r=>member?{...r,data:{...r.data,employeeIds:[member]}}:r),snapshot.members),'text/csv;charset=utf-8')}>Export filtered CSV</button><button onClick={()=>window.print()}>Print / Save PDF</button></div>{recordList(completionReport,'No training matches these filters.')}<div className="tr-print-report"><h2>Training attendance report</h2><p>{from||'All dates'} through {to||'today'} · {member?memberName(member):'All members'} · {category||'All categories'}</p><table><thead><tr><th>Member</th><th>Training / date</th><th>Actual hours</th><th>Instructor</th></tr></thead><tbody>{completionReport.filter(r=>!r.archived&&!r.data.test&&r.data.status==='completed').flatMap(r=>r.data.employeeIds.filter(id=>!member||id===member).map(id=><tr key={r.id+id}><td>{memberName(id)}</td><td>{r.data.title}<br/>{r.data.date}</td><td>{creditedHours(r,id)}</td><td>{r.data.instructor}</td></tr>))}</tbody></table></div></>}
    {tab==='Credentials & task books'&&<>{search}<div className="tr-heading"><div><h2>Credentials & task books</h2><p>Track official dates and documented proficiency. The app does not award certifications.</p><button onClick={()=>route('OSFM task books')}>Browse prebuilt OSFM task books</button></div><button className="tr-primary" onClick={()=>create('credential')}>+ Add credential</button></div>{recordList(recordsOf('credential'),'No credentials recorded. Add a member’s verified certificate or initial-certification task book.')}</>}
    {tab==='OSFM task books'&&<OsfmTaskBrowser selected={osfmSelection} onChange={setOsfmSelection} onUseBook={b=>create('credential',{title:b.title,certificationId:b.certificationId,method:b.kind==='initialBook'?'Initial certification':'Recertification',requiredJprs:b.jprs.map(j=>j.id),sourceUrl:b.url,sourceEdition:b.edition})} onTraining={(kind,ids)=>create(kind,{title:taskReference(ids[0])?.book.title??'OSFM training',osfmTaskIds:ids})}/>}
    {tab==='Activity library'&&<>{search}<div className="tr-heading"><div><h2>Activity library</h2><p>Build reusable forms once, then record or assign with a few taps.</p></div><button className="tr-primary" onClick={()=>create('activity')}>+ Build activity</button></div>{recordList(recordsOf('activity'),'No department activities saved yet. Choose a starting category or build your own.')}<h3>Start with a department topic</h3><div className="tr-chips">{categories.filter(c=>c.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c} onClick={()=>create('activity',{title:c,category:c})}>{c} +</button>)}</div><h3>Illinois certification catalog · {certificationCatalog.length} levels</h3><p>These are sourced references, not purchased courses or completed training.</p><div className="tr-catalog">{certificationCatalog.filter(c=>`${c.title} ${c.section}`.toLowerCase().includes(query.toLowerCase())).map(c=><article className="tr-panel" key={c.id}><small>Illinois OSFM · §{c.section}</small><h3>{c.title}</h3><p>{c.recertification==='points'?'Four-year investigator tally':c.recertification==='jpr'?'Four-year JPR recertification':'Not in the recurring list under §141.390'}</p><div className="tr-link-list"><External href={c.ruleUrl}>Requirements</External>{c.initialBook&&<External href={c.initialBook}>Initial practical book</External>}{c.recertificationBook&&<External href={c.recertificationBook}>{c.id==='il-334'?'Investigator tally':'Recertification book'}</External>}{!c.initialBook&&!c.recertificationBook&&<External href={OSFM_FORMS_URL}>Check available official forms</External>}</div><button onClick={()=>create('credential',{title:c.title,certificationId:c.id})}>Track this credential</button></article>)}</div></>}
    {tab==='Calendar'&&<><div className="tr-heading"><div><h2>Training calendar</h2><p>Click a record to reschedule or edit it. Dates use the department’s calendar.</p></div><button className="tr-primary" onClick={()=>create('assignment')}>+ Schedule training</button></div><label className="tr-field">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{Array.from(new Set(visible.flatMap(r=>[r.data.date,r.data.dueDate]).filter(d=>d.startsWith(month)))).sort().map(day=><section className="tr-panel" key={day}><h3>{new Date(day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h3>{recordList(visible.filter(r=>r.data.date===day||r.data.dueDate===day),'')}</section>)}{!visible.some(r=>r.data.date.startsWith(month)||r.data.dueDate.startsWith(month))&&<div className="tr-empty">No training dates in this month. Schedule training to add a dated assignment.</div>}</>}
    {tab==='Files & groups'&&<><div className="tr-heading"><div><h2>Files & groups</h2><p>Keep evidence with its record. Save groups for quicker assignments.</p></div><button onClick={()=>create('group')}>+ Create member group</button><button onClick={()=>create('resource')}>+ Add resource link</button></div><h3>Member groups</h3>{recordList(recordsOf('group'),'No groups yet.')}<h3>Resource links</h3>{recordList(recordsOf('resource'),'No resource links saved.')}<section className="tr-panel"><h3>Upload evidence</h3><label className="tr-field">Attach to<select value={fileRecord} onChange={e=>setFileRecord(e.target.value)}><option value="">Choose a saved record…</option>{snapshot.records.filter(r=>!r.archived).map(r=><option key={r.id} value={r.id}>{r.data.title} · {kindNames[r.kind]}</option>)}</select></label>{uploadControl(fileRecord)}{attachments()}{!snapshot.attachments.length&&<p>No files uploaded.</p>}</section></>}
    {tab==='OSFM guide'&&<OsfmGuide/>}
    </>}
  </section>;
}

function CredentialDetail({record,snapshot,onTask,onOpen,onExport}:{record:TrainingRecord;snapshot:TrainingSnapshot;onTask:(d:Partial<TrainingData>)=>void;onOpen:(id:string)=>void;onExport:()=>void}) {
  const evidence=credentialEvidence(record,snapshot.records),timeline=credentialTimeline(record),catalog=certificationCatalog.find(c=>c.id===record.data.certificationId),book=books.find(b=>b.url===record.data.sourceUrl);
  function task(jpr=''){onTask({title:record.data.test?'test/training':`${record.data.title} · ${jpr||'Proficiency'}`,credentialId:record.id,certificationId:record.data.certificationId,employeeIds:record.data.employeeIds,jpr,sourceUrl:record.data.sourceUrl,sourceEdition:record.data.sourceEdition,sourcePage:String(book?.jprs.find(j=>j.id===jpr)?.taskPage??book?.jprs.find(j=>j.id===jpr)?.page??''),test:record.data.test});}
  return <section className="tr-panel"><div className="tr-heading"><h3>Task-book evidence</h3><button className="tr-primary" onClick={()=>task()}>+ Record a task</button></div>{timeline&&<div className="tr-note"><strong>{timeline.status}</strong><p>Application window: {timeline.opens} · official due date: {timeline.due} · 90-day grace ends: {timeline.graceEnds}.</p><small>Current §141.390 rule, effective November 24, 2025. Verify eligibility and dates with OSFM. Proposed 2026 changes are not applied.</small></div>}
    {catalog?.recertification==='points'&&record.data.method!=='Initial certification'?<p><strong>{evidence.points} / 100</strong> documented points · validate every tally category and supporting record.</p>:<p><strong>{evidence.documented.length} / {record.data.requiredJprs.length}</strong> selected JPRs have reviewed proficiency evidence. {record.data.requiredJprs.length?'Chief review and official acceptance remain separate.':'Edit the credential to choose and verify a task-book index.'}</p>}
    <div className="tr-chips">{record.data.requiredJprs.map(j=><button key={j} className={evidence.documented.includes(j)?'tr-done':''} onClick={()=>task(j)}>{evidence.documented.includes(j)?'✓':'○'} {j}</button>)}</div>
    {evidence.entries.map(e=><button className="tr-record" key={e.id} onClick={()=>onOpen(e.id)}><span>{e.data.jpr} · {e.data.date} · {e.data.evaluator||'Evaluator not recorded'}</span><span>{e.data.result} →</span></button>)}
    <div className="tr-inline-actions">{catalog&&<button onClick={onExport}>Download OSFM review package</button>}<External href={OSFM_PORTAL_URL}>Open OSFM portal</External></div><p className="tr-muted">Export is a versioned JSON handoff for review and future integration. It is not an approved upload file or a submission. Upload signed official sheets or enter records in the OSFM portal as directed.</p>{record.data.receipt&&<p>Manually recorded OSFM reference: {record.data.receipt} · {record.data.submissionDate||'Date not recorded'}</p>}
  </section>;
}
function OsfmGuide(){return <>
  <div className="tr-heading"><div><h2>Illinois OSFM guide</h2><p>Official sources checked September 24, 2026. Open the source before making a certification decision.</p></div><span className="tr-badge">Direct connection: not connected</span></div>
  <div className="tr-panel"><h3>Current recertification rule</h3><p>Section 141.390 lists 28 certification levels requiring renewal. Listed credentials generally use four-year cycles; Fire Investigator requires 100 documented points. Other listed levels use applicable JPR evidence.</p><p>Applications may be submitted within 12 months of the official not-current date. OSFM sends department notices at one year and 90 days. The current rule provides a 90-day grace period; after it, the rule calls for an approved level-specific course to restore current status. Confirm individual dates and any OSFM-approved extension.</p><p>Chief attestation and retained department records are required. Training from one cycle cannot be reused for another. Highest-level recertification can cover lower levels within a discipline through OSFM; this app does not assume or grant that approval.</p><External href={OSFM_RULE_URL}>Current §141.390</External></div>
  <div className="tr-note"><h3>Proposed changes are separate</h3><p>OSFM’s September 2026 proposal includes changing the grace-period rule and adding Community Risk Reduction Practitioner. It is a proposal with a comment period through October 26, 2026, not an active certification rule in this pilot.</p><External href={OSFM_PROPOSED_URL}>Read the proposal and current status</External></div>
  <div className="tr-panel"><h3>What belongs in a complete training record</h3><ul><li>Member, date, actual attendance, instructor/provider, topic, location, and objectives.</li><li>For task books: correct standard/edition, specific JPR/skill ID, performed date, evaluator, outcome, supporting evidence, and signed official sheets.</li><li>For credentials: verified certificate number, OSFM ID, cycle dates, applicable task list, chief review, and the eventual OSFM receipt/certificate.</li><li>For initial courses: prerequisites, approved course/facility, written and practical examinations, course roster, and the current official task book.</li></ul><p>State-approved courses have separate course-approval and public-calendar requirements. A department drill is not automatically an approved certification course.</p><div className="tr-link-list"><External href="https://sfm.illinois.gov/about/divisions/personnel-standards/certification-exam-information.html">Course approval, calendar & FD Mail</External><External href={OSFM_FORMS_URL}>Official task books and forms</External><External href="https://sfm.illinois.gov/about/divisions/personnel-standards/course-reference.html">Approved reference material</External></div></div>
  <div className="tr-panel"><h3>Future OSFM integration</h3><p>Records retain stable member/record IDs, external IDs, dates, versions, source references, evaluator evidence, and private attachments. The review package keeps these fields together for a future approved connector.</p><p>No public submission API or acceptance contract has been verified. This build does not send records, promise recertification, or treat a download as receipt. The private pilot also sends no employee push/email notices.</p><div className="tr-link-list"><External href={OSFM_PORTAL_URL}>DPSE WebAccess</External><External href="https://sfm.illinois.gov/iam/firedepartment/ilfftrainingtrackingtool.html">Official Illinois training-tracking program</External><External href="https://webapps.sfm.illinois.gov/PSEPortal/HelpDocs/PSEFirefighter.pdf">Firefighter portal guide</External></div></div>
</>;}
